        IMPLICIT INTEGER (A-Z)
        DOUBLE PRECISION FILRPT,LUDF,ACTF,LUDSF,ACTSF,FLDIF,TODAY
        INTEGER BLOCK(128),LUDUN(3),ACTUN(3),LUDKEY(4),ACTKEY(4)
        INTEGER UNAME(3),MSG1(6),MSG2(6),MSG3(6),MSG4(6),MSG5(6)
        DATA LUDKEY,ACTKEY/'/KUXA1.12/R24',0,'/KUXA1.12/R30',0/
        DATA MSG1/'IN ACTG AND LUD BUT NOT IN MUD'/
        DATA MSG2/'IN ACTG AND MUD BUT NOT IN LUD'/
        DATA MSG3/'IN ACTG BUT NOT IN LUD AND MUD'/
        DATA MSG4/'IN LUD AND MUD BUT NOT IN ACTG'/
        DATA MSG5/'IN LUD BUT NOT IN MUD AND ACTG'/
        DATA A,L,M,UUN,GAN/'ACTG: LUD: MUD:UUN  GAN'/
        DATA ZERO,TWO,FOUR/0,2,4/
C       
C       INITIALIZATION SECTION
C
        CALL SYSNO(SYSN)
        IF (SYSN.LT.0) STOP 'Cannot get the system no.'
        CALL MAKNAM(LUDF,SYSN,'LUD.DAT')
        CALL MAKNAM(ACTF,SYSN,'ACT.DAT')
        CALL MAKNAM(LUDSF,SYSN,'LUD.SRT')
        CALL MAKNAM(ACTSF,SYSN,'ACT.SRT')
        CALL MAKNAM(FLDIF,SYSN,'DIF.DAT')
        CALL MAKNAM(FILRPT,SYSN,'OUT.RPT')
C
C       CREATE THE LUD FILE
C       INPUT FILE IS (SYS)DUL.SYS
C       OUTPUT FILE XXXLUD.DAT (WHERE XXX IS 3-DIGIT SYSTEM NO.)
C
        CALL STROUT('Openning the Lud file$',-1,1,1)
        OPEN (UNIT=20,FILE='(SYS)DUL.SYS',MODE='IMAGE',ERR=120)
        OPEN (UNIT=21,FILE=LUDF)
        TOTLUD= 0
100     READ(20,END=130)BLOCK
        DO 110I= 1,126,3
          IF (BLOCK(I).LE.0) GO TO 100
          TOTLUD= TOTLUD + 1
          CALL SIXASC(BLOCK(I+1),LUDUN,12)
          WRITE(21,140)LUDUN,BLOCK(I)
110     CONTINUE
        GO TO 100
120     CALL STROUT('Cannot open (SYS)DUL.SYS$',-1,1,1)
        CALL NEXIT
130     CLOSE (UNIT=20,UNIT=21)
        CALL STROUT(LUDF,10,1,0)
        CALL STROUT(' file created$',-1,0,1)
140     FORMAT(2A5,A2,O12)
C
C       CREATE THE ACCOUNTING FILE
C       INPUT DATA FROM AUX CIRCUIT
C       OUTPUT FILE XXXACT.DAT (WHERE XXX IS 3-DIGIT SYSTEM NO.)
C
        CALL STROUT('Building Circuit to Accounting System.$',-1,1,1)
        CALL BLDCIR('CUD10:74;','UPDLUD',ACTPRT,HOSTER,SUPER)
        IF ((HOSTER.NE.0).OR.(SUPER.NE.0)) GO TO 210
        CALL HSHAKE(ACTPRT,FLAG)
        IF (FLAG.NE.0) GO TO 220
        CALL STACT(ACTPRT,SYSN,FLAG)
        IF (FLAG.NE.0) GO TO 230
        OPEN (UNIT=22,FILE=ACTF)
        TOTACT= 0
        CALL STROUT('Circuit Established.$',-1,0,1)
200     CALL GETACT(ACTUN,CID,ACTGAN,ACTUUN,ACTPRT,FLAG)
        IF (FLAG.EQ.255) GO TO 280
        IF (FLAG.NE.0) GO TO 240
        TOTACT= TOTACT + 1
        WRITE(22,290)ACTUN,ACTGAN,ACTUUN,CID
        GO TO 200
210     CALL CIRERR(HOSTER,SUPER)
        GO TO 999
220     CALL STROUT('Handshake timeout$',-1,1,1)
        GO TO 270
230     CALL STROUT('Error in starting up Accounting System.$',-1,1,1)
        GO TO 270
240     IF (FLAG.EQ.5) GO TO 250
        CALL STROUT('Input Accounting port error$',-1,1,1)
        GO TO 260
250     CALL STROUT('Accounting error - Code: 5$',-1,1,1)
260     CLOSE (UNIT=22)
270     CALL ZAPC(ACTPRT)
        GO TO 999
280     CALL STROUT(ACTF,10,1,0)
        CALL STROUT(' file created$',-1,0,1)
        CLOSE (UNIT=22)
        CALL ZAPC(ACTPRT)
290     FORMAT(2A5,A2,3O6)
C
C       SORT THE LUD FILE
C       UNSORT FILE: XXXLUD.DAT
C       SORT FILE:   XXXLUD.SRT
C       XXX IS 3-DIGIT SYSTEM NO.
C
        CALL STROUT(LUDF,10,1,0)
        CALL STROUT(' ',1,0,0)
        CALL SORT(LUDF,LUDSF,LUDKEY,MERR,PERR)
        IF ((MERR.NE.0).OR.(PERR.NE.0)) CALL SRTERR(MERR,PERR)
C
C       SORT THE ACCOUNTING FILE
C       UNSORT FILE: XXXACT.DAT
C       SORT FILE:   XXXACT.SRT
C
        CALL STROUT(ACTF,10,1,0)
        CALL STROUT(' ',1,0,0)
        CALL SORT(ACTF,ACTSF,ACTKEY,MERR,PERR)
        IF ((MERR.NE.0).OR.(PERR.NE.0)) CALL SRTERR(MERR,PERR)
        CALL DELET(LUDF,FLAG)
        CALL DELET(ACTF,FLAG)
C
C       COMPARE ALL USERS IN LUD AND ACCOUNTING FILES
C       INPUT FILES: XXXLUD.SRT & XXXACT.SRT
C       OUTPUT FILE: XXXDIF.DAT
C       
        OPEN(UNIT=20,FILE=LUDSF,DISPOSE='DELETE')
        OPEN(UNIT=21,FILE=ACTSF,DISPOSE='DELETE')
        OPEN(UNIT=22,FILE=FLDIF)
400     READ(20,480,END=450)LUDUN,LUDGAN,LUDUUN
        READ(21,490,END=460)ACTUN,ACTGAN,ACTUUN,CID
410     IF(ICMP(ACTUN,LUDUN))420,440,430
420     WRITE(22,500)ACTUN,ACTGAN,ACTUUN,ZERO,ZERO,CID,TWO
        READ(21,490,END=460)ACTUN,ACTGAN,ACTUUN,CID
        GO TO 410
430     WRITE(22,500)LUDUN,ZERO,ZERO,LUDGAN,LUDUUN,ZERO,FOUR
        READ(20,480,END=450)LUDUN,LUDGAN,LUDUUN
        GO TO 410
440     WRITE(22,500)LUDUN,ACTGAN,ACTUUN,LUDGAN,LUDUUN,CID,ZERO
        GO TO 400
450     READ(21,490,END=470)ACTUN,ACTGAN,ACTUUN,CID
        WRITE(22,500)ACTUN,ACTGAN,ACTUUN,ZERO,ZERO,CID,TWO
        GO TO 450
460     READ(20,480,END=470)LUDUN,LUDGAN,LUDUUN
        WRITE(22,500)LUDUN,ZERO,ZERO,LUDGAN,LUDUUN,ZERO,FOUR
        GO TO 460
470     CLOSE (UNIT=20,UNIT=21)
        END FILE 22
        REWIND 22
480     FORMAT(2A5,A2,2O6)
490     FORMAT(2A5,A2,3O6)
500     FORMAT(2A5,A2,5O6,O3)
C
C       CHECK ALL USERS IN XXXDIF.DAT AGAINST THE MUD
C
        OPEN(UNIT=20,FILE=FILRPT)
        CALL STROUT('Building Circuit to the MUD.$',-1,1,1)
        CALL BLDCIR('NCUD1:1;',0,MUDPRT,HOSTER,SUPER)
        IF((HOSTER.EQ.0).AND.(SUPER.EQ.0)) GO TO 510
        CALL CIRERR(HOSTER,SUPER)
        GO TO 900
510     CALL HSHAKE(MUDPRT,FLAG)
        IF(FLAG.EQ.0) GO TO 515
        CALL STROUT('Handshake timeout from MUD circuit$',-1,1,1)
        GO TO 900
C
C       INPUT A RECORD FROM XXXDIF.DAT FILE AND SEND TO THE MUD
C
515     CALL DATE(TODAY)
        CALL TIME(ITIME)
        WRITE(20,520)TODAY,ITIME
520     FORMAT(/'DATE: ',A10,T67,'TIME: ',A5,//
     +  'PDP10 LUD ACTG BASE CHECK VERSION 1.00',//
     +  'USERNAME',9X,'GAN',7X,'UUN',7X,'CID',10X,'ERROR MESSAGES',/)
        CALL STROUT('Circuit Established.$',-1,0,1)
525     READ(22,500,END=800)UNAME,ACTGAN,ACTUUN,LUDGAN,LUDUUN,CID,FLAG
        CALL GETMUD(UNAME,MUDPRT,MUDGAN,MUDUUN,RCODE)
        IF (RCODE) 530,540,550
530     CALL STROUT('MUD error - Input port$',-1,1,1)
        GO TO 900
540     CALL STROUT('MUD error - An answer from MUD is not 40$',-1,1,1)
        GO TO 900
550     IF (RCODE.LT.3) GO TO 560
        CALL STROUT('MUD error code: $',-1,1,0)
        CALL TYPDEC(RCODE)
        GO TO 900
560     IF (RCODE.EQ.2) FLAG = FLAG + 1
        IF (FLAG.EQ.0) GO TO 620
        GO TO (570,580,590,600,610) FLAG
570     WRITE(20,700)UNAME,ACTGAN,ACTUUN,CID,MSG1
        IF (LUDGAN.NE.ACTGAN) WRITE(20,720)A,ACTGAN,L,LUDGAN,GAN
        IF (LUDUUN.NE.ACTUUN) WRITE(20,720)A,ACTUUN,L,LUDUUN,UUN
        GO TO 525
580     WRITE(20,700)UNAME,ACTGAN,ACTUUN,CID,MSG2
        IF (MUDGAN.NE.ACTGAN) WRITE(20,720)A,ACTGAN,M,MUDGAN,GAN
        IF (MUDUUN.NE.ACTUUN) WRITE(20,720)A,ACTUUN,M,MUDUUN,UUN
        GO TO 525
590     WRITE(20,700)UNAME,ACTGAN,ACTUUN,CID,MSG3
        GO TO 525
600     WRITE(20,710)UNAME,LUDGAN,LUDUUN,MSG4
        IF (LUDGAN.NE.MUDGAN) WRITE(20,720)M,MUDGAN,L,LUDGAN,GAN
        IF (LUDUUN.NE.MUDUUN) WRITE(20,720)M,MUDUUN,L,LUDUUN,UUN
        GO TO 525
610     WRITE(20,710)UNAME,LUDGAN,LUDUUN,MSG5
        GO TO 525
620     USERSW= .TRUE.
        IF (ACTGAN.EQ.LUDGAN) GO TO 630
        USERSW= .FALSE.
        WRITE(20,730)UNAME,ACTGAN,ACTUUN,CID
        WRITE(20,720)A,ACTGAN,L,LUDGAN,GAN
        IF (ACTGAN.NE.MUDGAN) WRITE(20,720)A,ACTGAN,M,MUDGAN,GAN
630     IF (LUDGAN.EQ.MUDGAN) GO TO 650
        IF (.NOT.USERSW) GO TO 640
        USERSW= .FALSE.
        WRITE(20,730)UNAME,ACTGAN,ACTUUN,CID
640     WRITE(20,720)M,MUDGAN,L,LUDGAN,GAN
650     IF (ACTUUN.EQ.LUDUUN) GO TO 670
        IF (.NOT.USERSW) GO TO 660
        USERSW= .FALSE.
        WRITE(20,730)UNAME,ACTGAN,ACTUUN,CID
660     WRITE(20,720)A,ACTUUN,L,LUDUUN,UUN
        IF (ACTUUN.NE.MUDUUN) WRITE(20,720)A,ACTUUN,M,MUDUUN,UUN
670     IF (LUDUUN.EQ.MUDUUN) GO TO 525
        IF (.NOT.USERSW) GO TO 680
        USERSW= .FALSE.
        WRITE(20,730)UNAME,ACTGAN,ACTUUN,CID
680     WRITE(20,720)M,MUDUUN,L,LUDUUN,UUN
        GO TO 525
700     FORMAT(2A5,A2,3(3X,O6),3X,6A5)
710     FORMAT(2A5,A2,2(3X,O6),12X,6A5)
720     FORMAT(7X,A5,3X,O6,4X,A5,3X,O6,3X,'MISMATCH ',A3)
730     FORMAT(2A5,A2,3(3X,O6))
800     WRITE(20,810)TOTACT,TOTLUD
810     FORMAT(/'TOTAL USERS IN ACTG:',I6,/T17,'LUD:',I6,//'EOJ')
900     CLOSE(UNIT=20)
        CALL ZAPC(MUDPRT)
999     CALL NEXIT
        END
 