C
C LUD update program
C Date: 5/23/86      - Khanh nguyen
C
C 10/07/86  1.1  Changed ACTCOD.HST file to (KHANHQN)ACTCOD.HST.
C                Used sort program in KHANHQN instead of login's
C                directory.
C                Armed for interrupt on receipt of a WAKE.
C 03/02/89  2.0  Read LUDUPD.DEL and LUDUPD.CHG in VALDEV:34 instead
C                of building the circuit to VALDEV:35.
C
      PROGRAM LUDUPD
      IMPLICIT INTEGER (A-Z)
      LOGICAL LUDDWN,ACTDWN
      DOUBLE PRECISION FILEID,PROFIL,SRTFIL,TTFIL,IBMFIL,HSTDWN,
     *LOGUN,PRGRUN,PRGTBL(2),LNMTBL(2),ERRFIL,TOUTFL,CUD10,RUPD(2),
     *FILEX,LFILID,VAL370
      INTEGER LOGSTR(5),ACTCMD(3),KEY(4),WHONAM(3),UUNARR(6),UUNTEM(6)
      COMMON /TOUTBL/TOUT,TOUTFL/RECBLK/CODE,UNAME(3),NEWNAM(3),UUN/
     *TTFBLK/TTFIL/ASTBLK/ASTTBL(2,100),NSYS
      DATA PRGTBL,LNMTBL/'R UPDLUD$','GO UPDLUD$','CUD10','USEVAL'/
      DATA CUD10,RUPD/'CUD10:74;','R (VALDEV)UPDLUD$'/
      DATA VAL370,KEY/'VAL370','/KUNA3.4/R36',0/
      DATA ONE,THREE,ACTCMD/1,3,"76,0,"62/
      TYPE 100
100   FORMAT(/T2,'LUD update program - Version 1.1')
C
C Initialize variables and accounting system type table.
C
      CALL GDATE(FILEID)
      CALL GUSERN(WHONAM)
      CALL MAKFIL(FILEID,FILEID,'.A   ')
      CALL MAKFIL(FILEID,TTFIL,'.TTT')
      CALL MAKFIL(FILEID,IBMFIL,'.IBM')
      CALL MAKFIL(FILEID,ERRFIL,'.ERR')
      OPEN (UNIT=20,FILE='(SSVAL)ACTCOD.HST',ACCESS='SEQIN',ERR=1020)
      NSYS= 1
C   Read ACTCOD.HST into a table
110   READ(20,120,END=130)ASTTBL(1,NSYS),ASTTBL(2,NSYS)
120   FORMAT(2I4)
      NSYS= NSYS+1
      GO TO 110
130   NSYS= NSYS-1
      CLOSE (UNIT=20)
      LUDDWN= .FALSE.
      ACTDWN= .FALSE.
      TIMINT= 1800 ! time interval = 1800 seconds
      ETIME= 61200 ! time to stop = 17:00
      IBMTIM = 86400 ! time to stop IBM system = 24:00
      CALL WAKEUP        ! set WAKE interrupt
      CALL DETACH(JOBNO) ! detach the job
      TOUT= 5
      ENCODE(10,140,TOUTFL) FILEID,JOBNO
140   FORMAT(A6,'.',A3)
C
C   Write heading to outfile
C
      OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,100)
      WRITE(TOUT,150) WHONAM,CTIME,JOBNO
150   FORMAT(/,' Logged into: ',3A5,/,' Time: ',A5,/,' Frame ID: ',A3)
      CLOSE (UNIT=TOUT)
C
C To get all transactions from LUD update system.
C
160   CALL MTIME(STIME)
      CALL NXTAVF(FILEID) ! get the next available filename
      OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,170)CTIME
170   FORMAT(/T2,A5,' - Building circuit to Lud Update System.')
      CLOSE (UNIT=TOUT)
      IF (.NOT.ACTDWN) GO TO 210
      CALL RENAM(LFILID,FILEID,IERR)
      ACTDWN= .FALSE.
210   CALL OPNFIL(20,FILEID,'APPEND',$210)
200   OPEN (UNIT=21,FILE='(VALDEV)LUDUPD.DEL',ACCESS='SEQIN',ERR=300)
220   READ(21,230,END=280)UNAME,UUNTEM      
230   FORMAT(2A5,A2,6A1)
      DO 235 I = 1,6
      IF (UUNTEM(I) .NE. ' ') GOTO 238
      JJ = 7 - I
      MM = 1
      DO 231 IR = 1,6
      UUNARR(IR) = '0'
231   CONTINUE
      DO 233 KK = JJ+1,6
      UUNARR(KK) = UUNTEM(MM)
      MM = MM + 1
233   CONTINUE
      GOTO 239
238   UUNARR(I) = UUNTEM(I)
235   CONTINUE
239   WRITE(20,240) UNAME,UUNARR
240   FORMAT(' 1',2A5,A2,6A1,12X)
      GO TO 220
280   CLOSE(UNIT=21,DISPOSE='DELETE')
300   OPEN(UNIT=21,FILE='(VALDEV)LUDUPD.CHG',ACCESS='SEQIN',ERR=400)
310   READ(21,315,END=390)UNAME,NEWNAM,UUNTEM
315   FORMAT(2A5,A2,2A5,A2,6A1)
      DO 318 I = 1,6
      IF (UUNTEM(I) .NE. ' ') GOTO 314
      JJ = 7 - I
      MM = 1
      DO 316 IR = 1,6
      UUNARR(IR) = '0'
316   CONTINUE
      DO 317 KK = JJ+1,6
      UUNARR(KK) = UUNTEM(MM)
      MM = MM + 1
317   CONTINUE
      GOTO 319
314   UUNARR(I) = UUNTEM(I)
318   CONTINUE
319   WRITE(20,320) UNAME,UUNARR,NEWNAM
320   FORMAT(' 3',2A5,A2,6A1,2A5,A2)
      GO TO 310
390   CLOSE(UNIT=21,DISPOSE='DELETE') ! finish copying from VALDEV
400   CLOSE (UNIT=20)
410   NREC= 0
      CALL OPNFIL(20,FILEID,'SEQIN',$440)
420   READ(20,430,END=440) CODE,UNAME,UUN,NEWNAM
430   FORMAT(I2,2A5,A2,O6,2A5,A2)
      NREC= NREC+1
      GO TO 420
440   IF (NREC.GT.0) GO TO 500
      CLOSE (UNIT=20,DISPOSE='DELETE')
445   OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      WRITE(TOUT,450)
450   FORMAT(T10,'No updates this visit.')
      CLOSE (UNIT=TOUT)
      IF (ACTDWN) GO TO 460
      IF (LUDDWN) GO TO 470
      GO TO 990
460   ACTDWN = .FALSE.
      CALL RENAM(LFILID,FILEID,IERR)
      GOTO 410
470   LUDDWN =.FALSE.
      CALL RENAM(HSTDWN,SRTFIL,IERR)
      GOTO 850
500   CLOSE (UNIT=20)
      OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      WRITE(TOUT,510) NREC,FILEID
510   FORMAT(' Created ',I3,' records in ',A10)
      CALL TIME(CTIME)
      WRITE(TOUT,520) CTIME
520   FORMAT(/T2,A5,' - Building circuit to Accounting system.')
      CLOSE (UNIT=TOUT)
      CALL BLDCIR(CUD10,RUPD,PORT,ERRCOD)
      IF (ERRCOD.EQ.0) GO TO 550
      CALL CIRERR(ERRCOD)
      CALL MAKFIL(FILEID,LFILID,'. XX')
      CALL RENAM(FILEID,LFILID,IERR)
      IF (IERR.EQ.0) ACTDWN= .TRUE.
      GO TO 990
550   CALL HSTART(0)
      CALL MAKFIL(FILEID,PROFIL,'. PP')
      IF (.NOT.LUDDWN) GO TO 560
      CALL RENAM(HSTDWN,PROFIL,IERR)
      LUDDWN= .FALSE.
560   CALL MAKFIL(FILEID,FILEX,'. XX') ! Acct host is down
      CALL OPNFIL(20,FILEID,'SEQIN',$560)
      NERRS= 0
C
C     Get username from YYMMDD.# (#:A,B,...,Z)
570   READ(20,430,END=780) CODE,UNAME,UUN,NEWNAM
580   CALL S1BYTE(PORT,"105) ! list hosts for a user
      CALL S3BYTE(PORT,UUN) ! send uun
      CALL G1BYTE(PORT,RTNCOD,$590) ! get an answer from accounting
      IF (RTNCOD.EQ.1) GO TO 650   ! success
      IF (RTNCOD.EQ."14) GO TO 580 ! accounting system busy, try again
      CODE= CODE+1
      CALL WERROR(RTNCOD,0)
      NERRS= NERRS+1
      GO TO 570
590   OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,600) CTIME
600   FORMAT(X,A5,' - Accounting circuit zapped during list hosts')
      WRITE(TOUT,610) UNAME,UUN
610   FORMAT(' Username: ',2A5,A2,' - ',O6)
      CLOSE (UNIT=TOUT)
620   CALL OPNFIL(21,FILEX,'SEQOUT',$780)
630   WRITE(21,430) CODE,UNAME,UUN,NEWNAM
      READ(20,430,END=640) CODE,UNAME,UUN,NEWNAM
      GO TO 630
640   LFILID= FILEX
      ACTDWN= .TRUE.
      CLOSE (UNIT=21)
      GO TO 780
650   CALL G2BYTE(PORT,HOST,$590)
      IF (HOST.EQ."177777) GO TO 680
C Host 39 is not IPC host anymore
      IF (HOST.EQ.39) GOTO 650 
      ASYST= FNDAST(HOST)
      GO TO (660,660,670) ASYST
      CALL FWRITE(ERRFIL,HOST,$650) ! YYMMDD.ERR
660   CALL FWRITE(PROFIL,HOST,$650) ! YYMMDD.#PP
670   CALL FWRITE(IBMFIL,HOST,$650) ! YYMMDD.IBM
C
C Update accounting database
C
680   CALL S1BYTE(PORT,ACTCMD(CODE)) ! delete or change username
      CALL S3BYTE(PORT,UUN) ! send uun
      IF (CODE.EQ.3) GO TO 690
      CALL S2BYTE(PORT,1) ! send a dummy host
      GO TO 700
690   CALL SUNAME(PORT,NEWNAM,12) ! send new name for change username
700   CALL G1BYTE(PORT,RTNCOD,$720) ! get an answer from accounting
      IF (RTNCOD.EQ.1) GO TO 710
      IF (RTNCOD.EQ."14) GO TO 690 ! file busy, try again
      CALL WERROR(RTNCOD,0)
      NERRS= NERRS+1
710   CALL WTTFIL(RTNCOD,0)
      GO TO 570
720   OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      IF (CODE.EQ.3) GO TO 740
      WRITE(TOUT,730) CTIME
730   FORMAT(X,A5,' - Accounting circuit zapped during delete user.')
      WRITE(TOUT,610) UNAME,UUN
      GO TO 770
740   WRITE(TOUT,750) CTIME
750   FORMAT(X,A5,' - Accounting circuit zapped during change name.')
      WRITE(TOUT,610) UNAME,UUN
      WRITE(TOUT,760) NEWNAM
760   FORMAT(' New name: ',2A5,A2)
770   CLOSE (UNIT=TOUT)
      GO TO 620
780   CLOSE (UNIT=20)
      CALL ZAPC(PORT)
      CALL HSTEND(0,NERRS)
      OPEN (UNIT=20,FILE=PROFIL,ACCESS='SEQIN',ERR=990)
      NREC= 0
790   READ(20,870,END=795) CODE,HOST,UNAME,NEWNAM,UUN
      NREC= NREC+1
      GO TO 790
795   CALL MAKFIL(FILEID,SRTFIL,'. SS')
      CALL SORT(PROFIL,SRTFIL,KEY,MERR,PERR) ! sort the profile according hosts
      IF ((MERR.NE.0).OR.(PERR.NE.0)) GO TO 1000
      OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      WRITE(TOUT,800) NREC
800   FORMAT(X,'Sorted ',I4,' records.')
      GO TO 830
810   WRITE(TOUT,820) NREC
820   FORMAT(' Sorted ',I4,' records.')
830   CLOSE (UNIT=TOUT)
C
C Update all transactions in the LUD.
C
850   PHOST= 0
      CALL MAKFIL(FILEID,HSTDWN,'. DD') ! host down
      CALL OPNFIL(20,SRTFIL,'SEQIN',$850) ! sort file
860   READ(20,870,END=980) CODE,HOST,UNAME,NEWNAM,UUN
870   FORMAT(I2,I4,2(2A5,A2),O6)
      IF (PHOST.EQ.HOST) GO TO 940
880   IF (PHOST.NE.0) CALL HSTEND(PHOST,NERRS)
      PHOST= HOST
      NERRS= 0
      CALL ZAPC(PORT)
      ASYST= FNDAST(HOST)
      LOGUN= LNMTBL(ASYST)
      PRGRUN= PRGTBL(ASYST)
      CALL MKLGST(LOGUN,HOST,LOGSTR)
      CALL HSTART(HOST)
      CALL BLDCIR(LOGSTR,PRGRUN,PORT,ERRCOD)
      IF (ERRCOD.EQ.0) GO TO 940
      CALL CIRERR(ERRCOD)
920   CALL OPNFIL(21,HSTDWN,'APPEND',$920)
930   WRITE(21,870) CODE,HOST,UNAME,NEWNAM,UUN
      READ(20,870,END=970) CODE,HOST,UNAME,NEWNAM,UUN
      IF (PHOST.EQ.HOST) GO TO 930
      CLOSE (UNIT=21)
      LUDDWN= .TRUE.
      GO TO 880
940   CALL S1BYTE(PORT,CODE) ! delete or change name in the LUD
      IF (ASYST.EQ.2) CALL S3BYTE(PORT,0) ! send a dummy request #
      CALL SUNAME(PORT,UNAME,12)
      IF (CODE.EQ.3) CALL SUNAME(PORT,NEWNAM,12)
      IF (ASYST.EQ.2) CALL S3BYTE(PORT,"44444444)
      CALL G1BYTE(PORT,RTNCOD,$950)
      IF (RTNCOD.EQ.1) GO TO 945
      IF (RTNCOD.EQ."14) GO TO 940
      CALL WERROR(RTNCOD,HOST)
      NERRS= NERRS+1
945   CALL WTTFIL(RTNCOD,HOST)
      IF ((RTNCOD.NE.1).OR.(ASYST.NE.1).OR.(CODE.NE.1)) GO TO 860
      CALL G3BYTE(PORT,IGAN,$950)
      CALL G3BYTE(PORT,IUUN,$950)
      GO TO 860
950   OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,960) CTIME,HOST
960   FORMAT(X,A5,' Circuit zapped during process host ',I3)
      CLOSE (UNIT=TOUT)
      GO TO 920
970   CLOSE (UNIT=21)
      LUDDWN= .TRUE.
980   CLOSE (UNIT=20,DISPOSE='DELETE')
      CALL HSTEND(HOST,NERRS)
      CALL ZAPC(PORT)
990   CALL ZAPC(-1) ! zap all circuits
      CALL MTIME(CTIME)
      IF (CTIME.GE.ETIME) GO TO 2000
      TRUN= CTIME-STIME
      IF (TRUN.GT.TIMINT) GO TO 160
      TS= TIMINT-MOD(CTIME,TIMINT)
      TSM= TS/60
      IF (MOD(TS,60).GT.0) TSM= TSM+1
      OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      WRITE(TOUT,995) TSM
995   FORMAT(/T2,'Dismissing for ',I2,' minutes.')
      CLOSE (UNIT=TOUT)
      CALL SLEEPY(TS)
      GO TO 160
1000  OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,1010) CTIME,PROFIL,MERR,PERR
1010  FORMAT(X,A5,' - ',A10,' file sorted error. Error codes',2I6)
      CLOSE (UNIT=TOUT)
      GO TO 990
1020  TYPE 1030
1030  FORMAT(' ACTCOD.HST - file not found.')
      CALL NEXIT
C
C Process 370 records
C
2000  CALL MAKFIL(FILEID,PROFIL,'.370')
      CALL MAKFIL(FILEID,HSTDWN,'.DWN')
      OPEN (UNIT=20,FILE=IBMFIL,ACCESS='SEQIN',ERR=2300)
      NREC= 0
2010  READ(20,870,END=2020) CODE,HOST,UNAME,NEWNAM,UUN
      NREC= NREC+1
      GO TO 2010
2020  CLOSE (UNIT=20)
      CALL SORT(IBMFIL,PROFIL,KEY,MERR,PERR)
      IF ((MERR.NE.0).OR.(PERR.NE.0)) GO TO 2250
      TIMINT= 900
      OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,2030) CTIME,NREC,IBMFIL
2030  FORMAT(/T2,A5,' - Sorted ',I4,' records (',A10,').')
      CLOSE (UNIT=TOUT)
      LUDDWN= .FALSE.
2040  CALL MTIME(STIME)
      PHOST= 0
      CALL OPNFIL(20,PROFIL,'SEQIN',$2500)
2100  READ(20,870,END=2200) CODE,HOST,UNAME,NEWNAM,UUN
      IF (PHOST.EQ.HOST) GO TO 2150
2110  IF (PHOST.NE.0) CALL HSTEND(PHOST,NERRS)
      PHOST= HOST
      NERRS= 0
      CALL ZAPC(PORT)
      CALL HSTART(HOST)
      CALL MKLGST(VAL370,HOST,LOGSTR) ! make the login string
      CALL BLDCIR(LOGSTR,'1POINT$',PORT,ERRCOD)
      IF (ERRCOD.EQ.0) GO TO 2150
      IF (ERRCOD.EQ.17) ERRCOD= 23
      CALL CIRERR(ERRCOD)
2120  CALL OPNFIL(21,HSTDWN,'APPEND',$2120)
2130  WRITE(21,870) CODE,HOST,UNAME,NEWNAM,UUN
      READ(20,870,END=2190) CODE,HOST,UNAME,NEWNAM,UUN
      IF (HOST.EQ.PHOST) GO TO 2130
      CLOSE (UNIT=21)
      LUDDWN= .TRUE.
      GO TO 2110
2150  CALL S1BYTE(PORT,CODE) ! delete or change name in the LUD
      CALL SUNAME(PORT,UNAME,8) ! send 8-byte username
      IF (CODE.EQ.3) CALL SUNAME(PORT,NEWNAM,8)
2160  CALL G1BYTE(PORT,RTNCOD,$2170)
      IF (RTNCOD.EQ.1) GO TO 2165
      IF ((RTNCOD.EQ."223).OR.(RTNCOD.EQ."21)) GO TO 2160
      CALL WERROR(RTNCOD,HOST)
      NERRS= NERRS+1
2165  CALL WTTFIL(RTNCOD,HOST)
      GO TO 2100
2170  OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,960) CTIME,HOST
      CLOSE (UNIT=TOUT)
      GO TO 2120
2190  CLOSE (UNIT=21)
      LUDDWN= .TRUE.
2200  CLOSE (UNIT=20,DISPOSE='DELETE')
      CALL ZAPC(PORT)
      CALL HSTEND(HOST,NERRS)
      IF (.NOT.LUDDWN) GO TO 2500
      LUDDWN= .FALSE.
      CALL RENAM(HSTDWN,PROFIL,IERR)
      IF (IERR.NE.0) GO TO 2400
      CALL MTIME(CTIME)
      IF (CTIME.GE.IBMTIM) GOTO 2500
      TRUN= CTIME-STIME
      IF (TRUN.GT.TIMINT) GO TO 2040
      TS= TIMINT-MOD(CTIME,TIMINT)
      TSM= TS/60
      IF (MOD(TS,60).GT.0) TSM= TSM+1
      OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      WRITE(TOUT,995) TSM
      CLOSE (UNIT=TOUT)
      CALL SLEEPY(TS)
      GO TO 2040
2250  OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,1010) CTIME,IBMFIL,MERR,PERR
      CLOSE (UNIT=TOUT)
      GO TO 2500
2300  OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,2310) CTIME
2310  FORMAT(/T2,A5,' - No 370 updates.')
      CLOSE (UNIT=TOUT)
      GO TO 2500
2400  OPEN (UNIT=TOUT,FILE=TOUTFL,ACCESS='APPEND')
      CALL TIME(CTIME)
      WRITE(TOUT,2410) CTIME,HSTDWN,PROFIL,IERR
2410  FORMAT(/T2,A5,' - Cannot rename ',A10,' to ',A10,'. - ',I5)
      CLOSE (UNIT=TOUT)
2500  CALL BYE
      END
   