        IMPLICIT INTEGER (A-Z)
        INTEGER UNAME(3),NNAME(3)
        CALL STROUT('BUILDING CIRCUIT TO LUD$',-1,1,1)
        CALL BLDCIR('USEVAL:1;','UPDLUD',PORT,HOSTER,SUPER)
        IF ((HOSTER.NE.0).OR.(SUPER.NE.0)) GO TO 999
        CALL HSHAKE(PORT,FLAG)
        IF (FLAG.NE.0) GO TO 998
        CALL STROUT('CIRCUIT ESTABLISHED$',-1,1,1)
        I= 0
5       READ (20,10,END=900)UNAME,DISTNO
10      FORMAT(2A5,A2,X,I3)
        TYPE 1,UNAME,DISTNO
1       FORMAT(T5,2A5,A2,I3)
        CALL S1BYTE(PORT,8)
        CALL S3BYTE(PORT,I)
        CALL SUNAME(PORT,UNAME)
        CALL S1BYTE(PORT,DISTNO)
        CALL S3BYTE(PORT,9586980)
        CALL G1BYTE(PORT,CODE)
        TYPE 30,CODE
30      FORMAT(' RETURN CODE: ',I5)
        GO TO 5
900     CLOSE (UNIT=20)
        CALL ZAPC(PORT)
        STOP
998     TYPE 100
100     FORMAT(' FAIL HAND SHAKE')
        STOP
999     TYPE 110
110     FORMAT(' CANNOT BUILD CIRCUIT')
        STOP    
        END
