From: Ali Ozer <ALI@Score.Stanford.EDU>
Date: Wed 20 Jan 88 19:59:29-PST
Subject: BADGE Meeting


Reminder that the January BADGE meeting is Thursday, January 20th,
at 8pm. The meeting is at Turing Auditorium (as always) and open
to everyone interested in programming the Amiga.

I don't know who the speaker is this month, but I'll post it if I find
out before the meeting. (Last month we saw Dale showing off the 1Kx800x2
monitor, X (running under AmigaDOS, *not* Unix), and the fast file
system... Very neat stuff!)

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 21 Jan 88 0:03:06 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 21 Jan 88 00:01:22 PST
Received: from rocky.stanford.edu by Sushi.Stanford.EDU with TCP; Wed 20 Jan 88
	23:51:29-PST
Received: by rocky.stanford.edu; Wed, 20 Jan 88 23:50:49 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ali@rocky.stanford.edu>
From: Ali Ozer <ali@rocky.stanford.edu>
Date: Wed, 20 Jan 88 23:50:49 PST
To: amiga@sushi.stanford.edu
Subject: January BADGE


I messed up in my previous message --- I said ``Th Jan 20,'' I meant to
say ``Th Jan 21.'' Sorry about that!

Also, info about the meeting just appeared on Usenet, so here it is:


Featured speakers for the January 1988 meeting are:

 *  Matt Dillon, who will discuss Amiga Device I/O
 *  Jim Mackraz of Amiga, who will present a short talk (subject unknown)
 *  Dave Comstock, who will talk about the virus programs.

Hope to see you all there!

Ali
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 21 Jan 88 20:04:00 PST
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 21 Jan 88 20:04:51 PST
Return-path: <@OFFICE-1.ARPA:ALI@Score.Stanford.EDU>
From: Ali Ozer <ALI@Score.Stanford.EDU>
Date: Thu 21 Jan 88 19:07:56-PST
To: JMS%F29.TYMNET@OFFICE-1.ARPA
Message-id: <12368512419.11.ALI@Score.Stanford.EDU>
Subject: Re: $90 for Amiga C compiler?
In-Reply-To: Message from "Joe Smith <JMS%F29.TYMNET@OFFICE-1.ARPA> " of Thu 21
	Jan 88 16:38:09-PST


I don't know much about Lattice C (I use Manx), but $90 doesn't sound
bad. But make sure it is version 4.0 --- Lattice 3.03 is supposed to be
very slow, and 3.10 is a bit better. But 4.0 includes a lot of optimizing
code and such.

In any case, make sure you get some extra memory (1.5 Megs or more!) if you
want to do serious development. I and my girlfriend did some programming
on a 512K machine, and then on a 1 Meg machine, and currently on a 2.5 Meg
machine, and believe me with lots of memory everything is so much
smoother and faster... Even GURUs aren't so bothersome anymore!

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Sun, 24 Jan 88 23:12:08 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 24 Jan 88 23:10:40 PST
Received: from MACBETH.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Sun 24 Jan
	88 23:01:20-PST
Return-path: <@OFFICE-1.ARPA,
	@Sushi.Stanford.EDU:F.FALTOR@MACBETH.STANFORD.EDU>
From: HENRY GREEN <F.FALTOR@MACBETH.STANFORD.EDU>
Date: Sun 24 Jan 88 23:05:08-PST
To: amiga@SUSHI.STANFORD.EDU
Message-id: <12369342032.306.F.FALTOR@MACBETH.STANFORD.EDU>
Subject: Disassembler for the amiga

Does anyone know of a way to disassemble code for the Amiga via public
domain or the Manx C package?


-Henry Green
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 26 Jan 88 12:17:04 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 26 Jan 88 12:14:26 PST
Received: from russell.stanford.edu by Sushi.Stanford.EDU with TCP; Tue 26 Jan
	88 12:02:30-PST
Received: by russell.stanford.edu (3.2/4.7); Tue, 26 Jan 88 12:10:13 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@russell.stanford.edu>
From: kasper@russell.stanford.edu (Kasper Osterbye)
Date: Tue, 26 Jan 88 12:10:13 PST
To: amiga@sushi
Subject: My amiga stays with me :-)

Hi,

As some of you might know, I have an A500, and have long wondered
how I get that machine to run when I go back to Denmark where we
run a 220/50hz PAL world.

I asked here and there and got different answers until yesterday
reading the usenet amiga group, I suddenly realized that commodore
amiga group was on the net - so I asked a guy there directly, and here
is what I got:

>The A500 should work fine with an 110V 50hz supply. As the 2080 is getting
>RGB + sync info from the computer, it too will work. To change to a PAL
>system you would need to replace the hi-order clock crystal and the AGNUS
>chip. The 2080 monitor is capable of being tweaked to a PAL screen by adjusting
>the Vertical Heigth. You might want to purchase a replacement power supply
>to better match the 220V 50HZ as the standard supply may overheat at 110V
>50Hz.

I thought someone might be tempted to buy a new Agnus and clock crystal,
as that seems to turn your machine into a 256 line machine.
(a super-morerows gimmic)

Anyway - I am happy I can look forward to living with my Amiga for more
than a year ahead.

/Kasper

Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 26 Jan 88 22:22:38 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 26 Jan 88 22:18:52 PST
Received: from russell.stanford.edu by Sushi.Stanford.EDU with TCP; Tue 26 Jan
	88 22:09:04-PST
Received: by russell.stanford.edu (3.2/4.7); Tue, 26 Jan 88 22:16:48 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@russell.stanford.edu>
From: kasper@russell.stanford.edu (Kasper Osterbye)
Date: Tue, 26 Jan 88 22:16:48 PST
To: amiga@sushi
Subject: Fish Disk's contens?


Ali used to have a file called whereis on sushi, but I was not able
to find it. DO anyone have a complete index to the Fish library somewhere?

/Kasper
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 27 Jan 88 19:45:39 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 27 Jan 88 19:43:18 PST
Received: from OFFICE-1.ARPA by Sushi.Stanford.EDU with TCP; Wed 27 Jan 88
	19:33:03-PST
Received: from F29.Tymnet by OFFICE-1.ARPA; 27 Jan 88 19:37:02 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU,
	@OFFICE-1.ARPA:JMS@F29.TYMNET>
From: Joe Smith <JMS%F29.TYMNET@OFFICE-1.ARPA>
Date: Wed, 27 Jan 88 19:35:23 PST
To: Amiga@Sushi.Stanford.EDU
Subject: Amiga on Microtimes.

The latest issue of Microtimes has Max Toy and an Amiga 2000 on the front cover.
Get them while they're hot!
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 28 Jan 88 10:13:29 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 28 Jan 88 10:07:16 PST
Received: from russell.stanford.edu by Sushi.Stanford.EDU with TCP; Thu 28 Jan
	88 09:57:49-PST
Received: by russell.stanford.edu (3.2/4.7); Thu, 28 Jan 88 10:05:37 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@russell.stanford.edu>
From: kasper@russell.stanford.edu (Kasper Osterbye)
Date: Thu, 28 Jan 88 10:05:37 PST
To: amiga@sushi
Subject: Printing IFF pictures.


When I make a picture in DpaintII using black on white background, And
then prints this picture out - DPaint in its superior wisdom thinks I
want the the same aspect as on the screen - which makes characters look
somewhat strange.

Does anyone know of a dump printprogram that prints a black pixel when
there is a black pixel, a white for white, and do not do any aspect stuff?

/Kasper

kasper@russell
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 2 Feb 88 11:31:36 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 2 Feb 88 11:28:32 PST
Received: from Score.Stanford.EDU by Sushi.Stanford.EDU with TCP; Tue 2 Feb 88
	11:20:21-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ALI@Score.Stanford.EDU>
From: Ali Ozer <ALI@Score.Stanford.EDU>
Date: Tue 2 Feb 88 11:18:19-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12371572656.47.ALI@Score.Stanford.EDU>
Subject: FAUG, UW


Reminder to all that FAUG (First Amiga User's Group) meeting is tonight...
It's at Palo Alto Hyatt, at 7:30pm.

I finally got the chance to look at and install UW (Unix Windows). UW
gives you terminal emulation over the serial line, but lets you have up to
seven windows at once. You just have to be connected to some Unix
host on which you are running the UW server. On the Amiga you run the
UW client (a rather tiny program). Then you can telnet from your Unix host
to other machines and be connected to different machines in different
windows.

Installation was painless; one problem is that UW only provides ANSI
emulation (no VT100 or H19). On Rocky Emacs works fine, but under TOPS-20
Emacs has problems. Being as much of a TOPS-20 person as Unix person,
I need Emacs to run under TOPS-20, so I need some reasonable terminal
emulation. But, if your main domain is Unix, then this program can serve
you well. It runs on a 512K machine without any problems, and you do not
need to be a superuser to install the Unix side.

Anyway, let me know if you are interested in getting copies of UW.

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 4 Feb 88 0:44:01 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 4 Feb 88 00:43:21 PST
Return-path: <@OFFICE-1.ARPA:ALI@Sushi.Stanford.EDU>
From: Ali Ozer <ALI@Sushi.Stanford.EDU>
Date: Wed 3 Feb 88 23:17:54-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12371965797.8.ALI@Sushi.Stanford.EDU>
Subject: Fish disk info


The files in <ali.amiga.fish> have been updated to reflect the current
status of Fred Fish's Freely Distributable Software Library...

The files 1, 2, 3, ... 127, 128 contain the contents of the 128 disks in
the library.

The file WHEREIS contains a full index of the 128 disks. WHEREIS is
larger than 50K and contains 800 entries. If you're looking for a specific
program, or you just like to browse through the list of programs, make sure
you get a hold of WHEREIS.

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 4 Feb 88 10:01:03 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 4 Feb 88 09:59:06 PST
Received: from HAMLET.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Thu 4 Feb 88
	09:49:05-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:R.RACER@HAMLET.STANFORD.EDU>
From: ARTHUR WALKER <R.RACER@HAMLET.STANFORD.EDU>
Date: Thu 4 Feb 88 09:52:59-PST
To: amiga@SUSHI.STANFORD.EDU
Message-id: <12372081410.119.R.RACER@HAMLET.STANFORD.EDU>
Subject: Mach 1.5

I have uploaded an amiga archive, Mach15.arc, to my directory
USER:<r.racer> on the tragedies.  It is an integrated screen
saver/popcli/mouse accelerator/clicktofront/keyboard macro server/etc
and its characteristics can changed via KB hotkeys or through the command
line.  It seems to live in harmony with ConMan and the rest of my
environment.  So check it out, and tell me whether Kermit handled the
binary file transfer propoerly.

Art Walker
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 4 Feb 88 10:07:17 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 4 Feb 88 10:06:25 PST
Received: from HAMLET.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Thu 4 Feb 88
	09:53:45-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:R.RACER@HAMLET.STANFORD.EDU>
From: ARTHUR WALKER <R.RACER@HAMLET.STANFORD.EDU>
Date: Thu 4 Feb 88 09:57:22-PST
To: amiga@SUSHI.STANFORD.EDU
Message-id: <12372082209.119.R.RACER@HAMLET.STANFORD.EDU>
Subject: PLCC puller

The people servicing my amiga 2000 claim to be unable to find an 84 pin
PLCC chip puller for fat agnus anywhere in the bay area (sold out at Fry's).

So which EE can crack a lab drawer and loan me this chip puller.  Or, does
anyone have a pointer?  If you know an AT owner who has upgraded via the
Intel inboard 386 AT, the installation kit includes such a puller.  I will
post to su-computers and micro as well.  HELPPLEASETHANKS.

Art
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 11 Feb 88 9:10:46 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 11 Feb 88 08:08:26 PST
Received: from LEAR.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Wed 10 Feb 88
	09:28:15-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:R.RACER@LEAR.STANFORD.EDU>
From: ARTHUR WALKER <R.RACER@LEAR.STANFORD.EDU>
Date: Wed 10 Feb 88 09:28:41-PST
To: amiga@SUSHI.STANFORD.EDU
Message-id: <12373649850.307.R.RACER@LEAR.STANFORD.EDU>
Subject: DNET network protocol

Has anyone FTPed Matt Dillon's DNET with intent to build the host side for
a UNIX machine on campus?  What is DNET, you ask?  Umm, hereis some less
oblique information:


Message-ID: <8802070403.AA14080@cory.Berkeley.EDU>
Date: 7 Feb 88 04:03:46 GMT
Sender: daemon@ucbvax.BERKELEY.EDU
Lines: 39


	I am trying to find people interested in testing and writing servers
for DNET.  I currently have DNET working between an Amiga and a UNIX 4.3
machine.  DNET is a windowed protocol which supports up to 65535 independant
server-client connections in both directions over your dialup (tty) line.

	For large transfers, DNET has tested out to about 94% the raw line
speed.  As DNET has an underlying protocol, data is essentially guarenteed
(no noise).

	DNET uses a server-client/port scheme similar to the internet scheme.
It is relatively trivial to write servers and applications for it.  I have
already written a file transfer server and terminal-rlogin (though it currently
cannot handle window-resizing automatically.  I also was able to hack up a
server on the Amiga end to allow remote logins to the Amiga (you get a shell).

	DNET is not on the internet, but it would be relatively trivial to
write a glue server listening both on the internet and on DNET's AF_UNIX
sockets.  DNET *does* use UNIX domain sockets which allows users to have
completely independant DNET's running.  As I type this, I have two other
terminal windows open and a very large file transfer running (unread
comp.sys.amiga news).

	At the moment I only want people who either have two Amigas (connect
serial ports together with Tx/Rx and a few other lines flipped), or have
an Amiga and a UNIX BSD 4.3 account (4.2 should work also).  After we get it
debugged I'll post a cleaned up version to the net.  You can also ask me
to send it to you for the hell of it.  Those of you who might want to port
it to other mini's or mainframes should wait until the cleaned-up debugged
version is sent to the net.

	Those people on the ARPA net should make my life easy and FTP
into pub/amiga on ucbvax.berkeley.edu (dnet.arc) ... it's not on there yet...
mail me so I know when I have to start putting on ucbvax.

					-Matt

	..!ihnp4!ucbvax!dillon		usenet
	dillon@ucbvax.berkeley.edu	arpanet


Message-ID: <8802080203.AA04530@cory.Berkeley.EDU>
Date: 8 Feb 88 02:03:08 GMT
Sender: daemon@ucbvax.BERKELEY.EDU
Lines: 20


	I'm gratified by the number of responses I've gotten on DNET.  The
alpha is now available for ARPAnet users via anonymous ftp to
ucbvax.berkeley.edu.  Hopefully this will mean some good things in a couple
of months for those of you who do not have arpa access.

	The alpha is nearly 380K.. somewhat difficult to send to USENET
sites, but those of you on the USENET who want it should mail me and
include the fastest route you know of to get from me to you.  If you are
too many hops away from a major node I probably will have problems getting
it to you, in which case you can send me EMail and I'll send you the
stuff (but if you can send me EMail asking for my address,and then send me
a disk, that would be MUCH more preferable).

	One of things that will get written soon (has yet to be written)
will be an NFS using DNET... although the current version has a client/server
to send files/directories there is something very special about being
able to CD into DNET: and onto a remote host.

				-Matt

Message-ID: <1122@louie.udel.EDU>
Date: 8 Feb 88 22:15:29 GMT
Reply-To: rminnich@udel.EDU (Ron Minnich)
Organization: University of Delaware
Lines: 23

First impressions of DNET.

      *****    GEE, THIS IS GREAT!    *****
hmm, i blew all that time on internet.device and then matt
comes out with this thing ... it just isn't fair.

   First off, it works. Second off, it requires no kernel hacks,
yet also appears to be pretty efficient. Although there does seem
to be a slightly longer echo loop it is not real bad even at 9600,
at least i don't think. But the real amazing thing is how well file transfer
works. Beautifully. and fast, as fast as tcp/ip over SLIP. I am
impressed.
   There is only one slight caveat. In moving from TCP to DNET
you are moving from a very standard protocol which runs on lots
of different OSs to one which is 4.xbsd specific. On the other
hand you could probably move dnet to many different machines.
I think i may drop internet.device and move over to dnet (but am
not sure yet). No matter what, DNET is quite a piece of work.
Makes me wonder why i bought a C compiler!
   Highly recommended for a test-drive at least!
ron
--
ron (rminnich@udel.edu)

Well, who's up for it now?   -Art
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 11 Feb 88 9:10:17 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 11 Feb 88 08:09:34 PST
Received: from Score.Stanford.EDU by Sushi.Stanford.EDU with TCP; Wed 10 Feb 88
	10:25:32-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ALI@Score.Stanford.EDU>
From: Ali Ozer <ALI@Score.Stanford.EDU>
Date: Wed 10 Feb 88 10:24:28-PST
To: R.RACER@Lear.Stanford.EDU
Cc: amiga@Sushi.Stanford.EDU
Message-id: <12373660007.15.ALI@Score.Stanford.EDU>
Subject: Re: DNET network protocol
In-Reply-To: <12373649850.307.R.RACER@LEAR.STANFORD.EDU>


I have dnet running on Rocky. A problem is, I haven't gotten the "term"
program to work properly. Might be the tip, but I'll let people know how it
goes. If it works, be assured that it'll blow UW (which I sent you
a message about a week ago) out of the water...

Ali

ps. If anyone is interested in getting dnet, let me know and I'll tell
you where it is on Rocky...

-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 11 Feb 88 9:43:29 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 11 Feb 88 08:43:03 PST
Return-path: <@OFFICE-1.ARPA:ROKICKI@Sushi.Stanford.EDU>
From: Tomas G. Rokicki <ROKICKI@Sushi.Stanford.EDU>
Date: Thu 11 Feb 88 01:23:16-PST
To: amiga@Sushi.Stanford.EDU
Messa: <12373823629.9.ROKICKI@Sushi.Stanford.EDU>
Subject: DFC (A new disk copier and formatter)

I've just `finished' a new program, a disk copier and formatter.  It
replaces both diskcopy and format, but is smaller than either.  In
addition, it has a number of additional features and a nice Intuition
interface.  Please try it out, and report any bugs, misfeatures,
misspellings in the C source, complaints, or anything to me.  All
documentation is at the very top of the source file.  The files are in
SUSHI:<ROKICKI>DFC.C and SUSHI:<ROKICKI>DFC.UU, both available by
anonymous FTP.

I've tested it out fairly thoroughly, but you might want to write-protect
your disks just to be on the safe side.

Enjoy!  And report back your findings, even if it works flawlessly!
Thanks.

-tom
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 12 Feb 88 15:54:41 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 12 Feb 88 15:52:35 PST
Return-path: <@OFFICE-1.ARPA:ALI@Sushi.Stanford.EDU>
From: Ali Ozer <ALI@Sushi.Stanford.EDU>
Date: Fri 12 Feb 88 15:45:20-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12374242706.43.ALI@Sushi.Stanford.EDU>
Subject: BBS List

The file <ALI.AMIGA.MISC>BBS-LIST.TXT, fresh off Usenet, lists more than
600 BBS'es (phone numbers, protocols, locations) with Amiga-related
stuff... I think list contains BBS'es from every state and from some
foreign countries, so next time you're away from California you can still
find some BBS to dial up to... 8-)

Oh, and in other news, Commodore apparently did reach its goal of
selling half million Amigas by end of 1987. And the number is growing
wildly! Commodore also posted profits of $20.7 million for second quarter
of 1987, profits mostly due to the Amiga.

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Sat, 13 Feb 88 19:11:43 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 13 Feb 88 19:08:52 PST
Return-path: <@OFFICE-1.ARPA:ROKICKI@Sushi.Stanford.EDU>
From: Tomas G. Rokicki <ROKICKI@Sushi.Stanford.EDU>
Date: Sat 13 Feb 88 19:01:48-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12374540616.12.ROKICKI@Sushi.Stanford.EDU>
Subject: vt100

Has anyone hacked vt100 to give a nice, bordered window?  This borderless
stuff has got to go.  (Yes, I've morerowed my Amiga, so 640x400 is no sweat.)
Thanks for any help!

-tom
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Sun, 14 Feb 88 18:04:30 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 14 Feb 88 18:01:49 PST
Received: from rocky.stanford.edu by Sushi.Stanford.EDU with TCP; Sun 14 Feb 88
	17:54:39-PST
Received: by rocky.stanford.edu; Sun, 14 Feb 88 17:54:27 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ali@rocky.stanford.edu>
From: Ali Ozer <ali@rocky.stanford.edu>
Date: Sun, 14 Feb 88 17:54:27 PST
To: amiga@sushi.stanford.edu, micro@lear.stanford.edu,
	su-events@score.stanford.edu
Subject: February BADGE meeting: Thursday the 18th, 8:15PM, Turing Aud

The February 1988 BADGE (Bay Area Amiga Developers' GroupE) meeting will be
held this Thursday, February 18, 1988, in the Turing Auditorium at Stanford.

The featured speaker for the February 1988 meeting is Jim Goodnow, creator
of Manx C. He will be discussing an exciting new public domain program of
his creation. The backup speaker will be Brian (De?)Witt, who will
discuss semaphores.

The BADGE meeting is scheduled to begin at 8:15 PM.

Admission is free and open to anyone interested in programming the Amiga
computer.

Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 19 Feb 88 12:57:14 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 19 Feb 88 12:55:50 PST
Received: from MACBETH.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Fri 19 Feb
	88 12:46:17-PST
Return-path: <@OFFICE-1.ARPA,
	@Sushi.Stanford.EDU:J.JIGALO@MACBETH.STANFORD.EDU>
From: Michael Frank <J.JIGALO@MACBETH.STANFORD.EDU>
Date: Fri 19 Feb 88 12:45:31-PST
To: amiga@SUSHI.STANFORD.EDU
Cc: j.jigalo@MACBETH.STANFORD.EDU
Message-id: <12376044979.123.J.JIGALO@MACBETH.STANFORD.EDU>
Subject: recoverable ram disk

I've had a lot of trouble getting the asdg recoverable ram disk to work.
I got the device both from a bulletin board and from the Draco SYS disk
(Fred Fish 76); neither version seems to work. I've made sure the mountlist
for VD0: has the correct buffer size and type for my 2 megs of fast ram
(I've also tried variations), and I've made sure that the MountList and
the asdg.vdisk.device file both reside in DEVS: where they belong. But
no amount of resetting or cold-booting gets the system to even recognize
that VD0: exists.  If anyone knows about subtle quirks of the MountList
file or knows some other reason for the problem, I seriously need help.
(By the way, I also tested the normal RAM: device to see if VD0 was somehow
hidden under that name, but it didn't keep its files thru reset)

Michael Frank  (=8
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 26 Feb 88 12:05:51 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 26 Feb 88 12:04:26 PST
Received: from csli.stanford.edu by Sushi.Stanford.EDU with TCP; Fri 26 Feb 88
	11:55:34-PST
Received: by csli.stanford.edu (3.2/4.7); Fri, 26 Feb 88 12:02:47 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Fri, 26 Feb 88 12:02:47 PST
To: amiga@sushi
Subject: Address...


Does anyone here know the mailing address of the person who made dnet at
berkeley? I finally got fed up with the editor "med". I tried "dme" and
I know that he (I think he is called Matt?) has a copy in /pub/amiga
at ucbvax. However there seems to be a checksum error in his file, so
I would like to get hold of him.

Any other editors around? I am really not that critical but the following
are the rules:
* It must be able to produce european letters - that rules out uedit, and
  a number of emacs (as the use the ALT key for their own purpose)
* I want just a little user friendlyness. I do not want to memorize 50 commands
  by strange shift key escape sequences.

Any suggestions?

/Kasper
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 26 Feb 88 15:33:48 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 26 Feb 88 15:31:53 PST
Received: from miracles by Sushi.Stanford.EDU with TCP; Fri 26 Feb 88
	15:22:45-PST
Received: by miracles ; Fri, 26 Feb 88 15:24:45 pst
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:dmr@miracles.STANFORD.EDU>
From: Daniel M. Rosenberg <dmr@miracles.STANFORD.EDU>
Date: Fri, 26 Feb 88 15:24:45 pst
To: OPUS@Sushi.Stanford.EDU, amiga@Sushi.Stanford.EDU
Message-id: <8802262324.AA10443@miracles>
Subject: Re: Vi

If you buy Manx C, you get the 'Z' editor, which is a lot like
vi (it's just missing some features, and has improved with the 3.6
release of the compiler).

Or, you could run PC/VI on the PC side of a 2000, I suppose.

Dan
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 26 Feb 88 16:45:47 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 26 Feb 88 16:44:29 PST
Return-path: <@OFFICE-1.ARPA:OPUS@Sushi.Stanford.EDU>
From: Robin Kim <OPUS@Sushi.Stanford.EDU>
Date: Fri 26 Feb 88 15:16:48-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12377907527.16.OPUS@Sushi.Stanford.EDU>
Subject: Vi


Does anyone know of an implementation of or emulator for the vi editor
for the Amiga?  I've modified dme so that it comes close, but it cannot
do many of the best features of vi.

Robin
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 26 Feb 88 17:04:52 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 26 Feb 88 17:01:05 PST
Return-path: <@OFFICE-1.ARPA:ROKICKI@Sushi.Stanford.EDU>
From: Tomas G. Rokicki <ROKICKI@Sushi.Stanford.EDU>
Date: Fri 26 Feb 88 16:52:49-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12377925008.19.ROKICKI@Sushi.Stanford.EDU>
Subject: Amiga in the news!

Breaking every copyright law in existence, but from the Times Tribune
(Palo Alto) on the top of page one, we find:

New system could be the ultimate in backseat driving!

SAN FRANCISCO--The California Department of Transportation and Radar
Control Systems Corp. on Thursday unveiled a prototype computer
attachment for vehicles that officials said could alleviate traffic
congestion and may even save lives.

The device consists of a radar antenna attached to the front of the
car that senses motion and an internally mounted computer that
``speaks'' to the driver and activates braking if necessary.

The system, known as LOOKOUT, will allow motorists to drive closer
together and allow for increased traffic flow, Caltrans interim
Director Donald L. Watson said during a news conference.

Caltrans heard about Radar Control Systems while searching for
solutions to traffic congestion and was impressed with the radar
device, Watson said.

``People can drive faster and closer, and we don't have to build
new freewyas . . . We can't build our way out of this situation,''
he explained.

``We know that there's a lot of space between cars.  Moving faster
at a closer distance is still safe, with this technology,'' Watson
said.

The Bay Area is facing one of the highest annual traffic increases
in the state at 27 percent, Watson said.  The Los Angelos area is
experiencing `only' a 15 percent increase, he added.

The radar system serves as a detection device for frontal traffic,
and if the driver doesn't respond in the usual 0.7 seconds, the
device will apply the brakes within 0.2 seconds, if necessary, John
Davis, the radar system's inventor, said.

The prototype displayed at the press conference was mounted in a
1977 Dodge Sportsman van.  inside, an Amiga computer terminal
displayed a video image of what was in front of the van through a
camera that was mounted on the dash.

When the vehicle came too close to another vehicle, building or
sign post, an automated voice would issue such commands as
``Watch it'' and ``Slow down.''

``The roads are nice, the cars are nice, but the driver needs help,''
Davis said.  ``This allows him to maintain a safety margin'' at
higher speeds.

The radar is capable of scanning 20,000 feet ahead of the car, but
will only emit a command or activate the brakes if it senses any
immediate danger, Davis said.

Davis estimated that the device could halve the number of traffic
accidents in California.

Davis has worked on the device full time for about five years at
Radar Control Systems.

Davis said he expects the system will be available for production
in about two years.  Current cost estimates range between $500 and
$1000 per car, depending on model and driver programming requests,
Davis said.

(Pictured is your basic two-drive 1000 with a 1080 monitor, strapped
down inside the van.)

-tom
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 29 Feb 88 14:27:50 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 29 Feb 88 14:26:28 PST
Received: from csli.stanford.edu by Sushi.Stanford.EDU with TCP; Mon 29 Feb 88
	14:04:06-PST
Received: by csli.stanford.edu (3.2/4.7); Mon, 29 Feb 88 14:11:26 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Mon, 29 Feb 88 14:11:26 PST
To: amiga@sushi
Subject: Amiga Show..


Hi,

Is anyone going to the Amiga show at Oakland the weekend of 12/13? I
would be intersted in sharing the ride..

/Kasper
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 2 Mar 88 12:24:03 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 2 Mar 88 12:22:07 PST
Received: from LEAR.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Wed 2 Mar 88
	11:46:37-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:R.RACER@LEAR.STANFORD.EDU>
From: ARTHUR WALKER <R.RACER@LEAR.STANFORD.EDU>
Date: Wed 2 Mar 88 11:49:37-PST
To: AMIGA@SUSHI.STANFORD.EDU
Message-id: <12379180531.20.R.RACER@LEAR.STANFORD.EDU>
Subject: PAK-68 68020/881 board


Last night at FAUG Bryce Nesbitt patched KS1.2 so that my german 68020 kit board would work under 1.2 without an 881.  Shortly thereafter, Dale Luck told me
what that section of code expects if there's no 881, and this morning I did a
one minute reversible hardware hack to produce the desired result.

So I now have a 68020 board that works in a 500, 2000 or 1000 which costs
about $60 plus a couple of hours to build, plus the price of the 68020.

I have also found today a source of 16 mhz 881s for $145.  I will buy today
or tomorrow and let you all know how it comes out.

I'll make up a nice little set of text files for dissemination to anyone
who wants to take this project on.  I guess the only thing you will find
harder than I did is finding a dirt-cheap 68020.  This same chip source will
do no better than $75 for the 12 mhz 68020.  Nonetheless, you can have the
equivalent of the CSA piggyback with 881 (faster, since it's a 16 mhz 881
instead of a 12 mhz) for about $280 instead of $700 mail order or about
$1000 list.

Benchmarks also to come.

Art
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 2 Mar 88 22:06:00 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 2 Mar 88 22:04:50 PST
Received: from MACBETH.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Wed 2 Mar
	88 17:55:09-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:K.KCHAN@MACBETH.STANFORD.EDU>
	
From: Ken Min Chan <K.KCHAN@MACBETH.STANFORD.EDU>
Date: Wed 2 Mar 88 17:58:12-PST
To: amiga@SUSHI.STANFORD.EDU
Message-id: <12379247629.310.K.KCHAN@MACBETH.STANFORD.EDU>
Subject: NY Times

Recently, (Monday or Tuesday) the New York Times had a column on the
AMIGA 500 in their computer section.  They also said they will cover
some AMIGA software, etc. sometime next week.  Should be interesting.
At least we're being noticed and hey, this is free advertising in a
major newspaper.
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 2 Mar 88 22:12:28 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 2 Mar 88 22:10:39 PST
Received: from Portia.STANFORD.EDU by Sushi.Stanford.EDU with TCP; Wed 2 Mar 88
	20:26:23-PST
Received: by Portia.STANFORD.EDU (1.2/Ultrix2.0-B) id AA03262; Wed, 2 Mar 88
	20:31:06 pst
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:colvin@Portia.STANFORD.EDU>
From: colvin@Portia.STANFORD.EDU (Michael Colvin)
Date: Wed, 2 Mar 88 20:31:06 pst
To: amiga@sushi
Message-id: <8803030431.AA03262@Portia.STANFORD.EDU>
Subject: LA50 printer driver


I am trying to connect a DEC LA50 printer to an Amiga 1000.  Is there a printer
driver specifically for it?  If not, can anyone give pointers on the interface
between the two (serial connection).

Mike Colvin

Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 3 Mar 88 5:02:54 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 3 Mar 88 05:00:44 PST
Received: from csli.stanford.edu by Sushi.Stanford.EDU with TCP; Thu 3 Mar 88
	04:53:33-PST
Received: by csli.stanford.edu (3.2/4.7); Thu, 3 Mar 88 00:01:44 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Thu, 3 Mar 88 00:01:44 PST
To: amiga@sushi
Subject: Prolog.


I have just gotten hold of the port of Stony brook prolog from David Roch.

When I have downloaded the 1.2MB of uuencoded zoo files over my 1200baud
line, I will let you know if I can fit it unto my 1meg machine, or if I
finally have found an excuse to go out to shop for more memory.

Now lets do some estimated 3 hours of kermiting...
/Kasper
From: Joe Smith <JMS@F29.TYMNET>
Date: Thu, 3 Mar 88 21:30:27 PST
To: Colvin@Portia.STANFORD.EDU
Subject: LA50 requires null modem.

I have an LA50 connected to my A2000.  It requires a null modem, at minimum a
cable with 2, 3, and 7 wired with 2 and 3 crossed.  It works at 4800 baud, I
have Preferences set to "Generic" printer.  If you print from NotePad, be
sure to click on "Draft" in the "Print As" menu before selecting "Print".
I too have been looking for a device driver.  I'll post another request on
the Amiga BBOARD.		/Joe
From: Joe Smith <JMS@F29.TYMNET>
Date: Thu, 3 Mar 88 21:34:37 PST
To: Amiga@Sushi.Stanford.EDU
Subject: Who has LA50 printer driver

On page 70 of Volume 2, #7 of Amazing Computing, Richard Bielak mentions that
he has seen an LA-50 printer driver on Compuserve.  Has anyone got a copy of
this?  Could it be put in an accessable place, such as Ali's directory?
Many thanks if this could be done.

		/Joe Smith
From: Joe Smith <JMS@F29.TYMNET>
Date: Sat, 5 Mar 88 12:38:12 PST
To: <@OFFICE-1.ARPA:colvin@portia.Stanford.EDU>
Cc: colvin%portia@Sushi.Stanford.EDU
Subject: Re: LA50 requires null modem.
In-reply-to: <8803040725.AA03004@Portia.STANFORD.EDU> of Thu, 3 Mar 88 23:25:41
	pst

On the LA50: SW1 has all switches open.  SW2 has all open execpt #7.
In Preferences: Baud=4800, Buffer=512, Read Bits=8, Write Bits=8,
  Stop bits=1, Parity=None, Handshake=XON/XOFF.

I have an LA50 Installation Guide and an LA50 Programmer's Manual at work
if you have any questions.
			/Joe
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 7 Mar 88 11:51:39 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 7 Mar 88 11:51:22 PST
Return-path: <@OFFICE-1.ARPA:ROKICKI@Sushi.Stanford.EDU>
From: Tomas G. Rokicki <ROKICKI@Sushi.Stanford.EDU>
Date: Mon 7 Mar 88 11:32:59-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12380488223.15.ROKICKI@Sushi.Stanford.EDU>
Subject: File system redundancy

Boy am I glad the Amiga file system is redundant.  Let me relate a
story . . .

Saturday morning I was doing some complicated macro hacking in
micrognuemacs, when, unbeknownst to me, I accidentally overwrote
a very important file on one of my floppies.  Let me say that this
file was extremely important, that I had been building it over
the past two years, and no monetary value could be placed on it.

That afternoon I went back to add something to the file, when I
noticed the catastrophe.  Shit, said I.  And then some other
choice swear words.  Then I went to a movie to think about my
life without that file.

But the hacker in me would not give up.  So, I write protected and
made several copies of the diskette, and then tried to recover
the file with some of the many disk editor programs on the Fish
disks.  I couldn't get the file back with any of them.  Disksalv
failed because the disk was hunky-dory, and the file was so large
that I couldn't patch the pieces back together with a disk editor.

So, I wrote a small program which simply dumped to an ASCII file
the contents of every block on that disk that didn't have the
contents of a freshly formatted disk.  I then wrote another program
which pieced as many fragments of each file together as it could,
and wrote them all out to disk.  These programs took about an hour
to write.

Well, I ran them, and after a little debugging, I had about eight
`files' in my RAM disk.  I examined them one by one, and wallah
:-) one of them was my original file, completely intact.  This was
only possible because of all the redundancy; pointers to the next
block in each block, pointers back to the original file block, and
sequence numbers.

So my life goes on, all hunky-dory, and I continue to work.  And
once again I learn the importance of backups, by not having one.

-tom
-------
From: Joe Smith <JMS@F29.TYMNET>
Date: Mon, 7 Mar 88 11:49:40 PST
To: colvin%portia@sushi.stanford.edu
Subject: Info on LA50 switch settings.

SW1-1 thru SW1-4 define the character set.  All 4 open means U.S. ASCII.
SW1-5 is graphics aspect ratio.  Open is 144 dpi, closed is 180 dpi.
SW1-6 and SW1-7 define protocol.  Both open means to use XON/XOFF.
SW1-8 is right margin.  Open means stay at column 80, closed starts new line.
The factory setting is all SW1 switches open.

SW2-1 thru SW2-3 define the baud rate. OOO=4800, OOC=3600, OCO=2400,
  OCC=1200, COO=600, COC=300, CCO=200, CCC=110.  Fastest when all open.
SW2-4 thru SW2-6 define data bits and parity.  OCC=7O, CCC=7E, OOC=7M, COO=7S,
  OCO=8O, CCO=8E, OOO=8N (8 data bits, no parity, 1 stop bit).
SW2-6 and SW2-7 are not documented.  SW2-6 is closed and SW2-7 is open.
The factory setting is all SW2 switches open except for SW2-7.

The LA50 is usually set up for 4800 baud, 8 data bits, no parity, 1 stop bit,
XON/XOFF flow control, US ASCII character set.
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 9 Mar 88 0:25:34 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 9 Mar 88 00:19:50 PST
Received: from csli.stanford.edu by Sushi.Stanford.EDU with TCP; Wed 9 Mar 88
	00:09:57-PST
Received: by csli.stanford.edu (3.2/4.7); Wed, 9 Mar 88 00:17:28 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Wed, 9 Mar 88 00:17:28 PST
To: amiga@sushi
Subject: Prolog.


Hi,

If anyone are interested in getting the Stony brook prolog that
was ported by David Roch, I got all the floppies (3). I have not
yet tried any real heavy duty stuff. It comes with all sources and
documentation. It takes a bit more than one MB (peanuts ;-) to run.

/Kasper


Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 9 Mar 88 0:31:34 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 9 Mar 88 00:25:39 PST
Received: from csli.stanford.edu by Sushi.Stanford.EDU with TCP; Wed 9 Mar 88
	00:18:17-PST
Received: by csli.stanford.edu (3.2/4.7); Wed, 9 Mar 88 00:25:48 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Wed, 9 Mar 88 00:25:48 PST
To: amiga@sushi
Subject: Northern California Amiga Show.


Hi,

As I said last week, I am trying to set up a car-pool for the Northern
California Amiga Show this weekend the 12th/13th march in Oakland. Anyone
interested should mail me when they would like to go, and a phoneno.
I will try to put out a message latest thursday night.

/Kasper

ps. I got your messages, Tom and Stuart.
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 9 Mar 88 0:41:46 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 9 Mar 88 00:36:20 PST
Received: from csli.stanford.edu by Sushi.Stanford.EDU with TCP; Wed 9 Mar 88
	00:03:10-PST
Received: by csli.stanford.edu (3.2/4.7); Wed, 9 Mar 88 00:10:39 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Wed, 9 Mar 88 00:10:39 PST
To: amiga@sushi
Subject: Yeah yeah yeah.


Hi,

I guess I can not really keep my mouth shut. I got myself convinced that
I really could not live in only one MB anymore (my excuse was that
Prolog (see other msg), Latex, and some big Icon stuff could not run in
a 1MB machine) . So I have went down to HT, and got the subsystem for my
a500, and put in a 2MB Micron board. When I decided to get it, I did
not realize what it would do to my amiga. The whole C: in ram, together
with editor and a collection of other utils. Having space to run wiconify.
My shiny new 3MB a500 flies. I can barely release the left-amiga/escape
key before popcli puts a new window up. Now this is fun.

Oh well, but it really made a much greater difference than I expected.

/Kasper

Life in the fast lane..........
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 11 Mar 88 15:57:30 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 11 Mar 88 15:54:28 PST
Received: from csli.stanford.edu by Sushi.Stanford.EDU with TCP; Fri 11 Mar 88
	15:47:26-PST
Received: by csli.stanford.edu (3.2/4.7); Fri, 11 Mar 88 15:55:05 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Fri, 11 Mar 88 15:55:05 PST
To: amiga@sushi
Cc: kasper@csli.stanford.edu
Subject: Help - how do I print a "g"?

Hi,

I kow that I have asked before, but I find it har to beleive that I
am the only one who have come across this problem.
If I print pictures from DPAINT, some fancy aspect calculations are
done, so that the picture on the paper looks a lot like that on the
screen (if I had a colour printer) - this is really fine for art.

However, I sometimes want to make a generic computer science illustration
(Boxes, circles, arcs, and some text). This I do in only black/white
hires. But when I print such a picture, this is what happens: text
get messed up because some pixels are not square (in order to get the
right aspect) The following showed what happend to a `g':

printed `g', and expected `g'


   *** ***         *** **
  **  ***         **  **
  **  ***         **  **
  **  ***         **  **
  **  ***          ****
   ****          **   **
***   ***         *****
  *****
  *****

and a small box comes out messed up too:
printed:         expected:
******               *****
**   *               *   *
**   *               *   *
**   *               *   *
******               *****
******


There seems to be three solutions to this problem:
1) Someone has a program that prints `uniform' pixels
2) I make a program that prints uniform pixels.
3) I ask someone if I can borrow their Mac :-(

Hope someone can help me with 1)

/Kasper
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 14 Mar 88 16:33:09 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 14 Mar 88 16:28:43 PST
Received: from polya.stanford.edu by Sushi.Stanford.EDU with TCP; Mon 14 Mar 88
	16:21:56-PST
Received: by polya.stanford.edu (5.54/inc-1.2) id AA07464; Mon, 14 Mar 88
	16:26:54 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ali@polya.stanford.edu>
From: ali@polya.stanford.edu (Ali Ozer)
Date: Mon, 14 Mar 88 16:26:54 PST
To: amiga@sushi.stanford.edu
Message-id: <8803150026.AA07464@polya.stanford.edu>
Subject: March 1988 BADGE info

March 1988 BADGE (Bay Area Amiga Developers' Group) meeting will be held
in Turing Auditorium at Stanford campus.  The meeting is scheduled to
begin at 8:15pm.

The featured speaker for the March 1988 meeting is Jim Mackraz, who will
present the "Beta Version" of the talk he will be giving at the Developers'
Conference in April.

-----------------------------------------------------------------------------
SPECIAL NOTE: there is a possibility of a SECOND MEETING during the last
week of March featuring Rich Miner from the University of Lowell.  Meeting
times will be posted. Following is an excerpt from Rich's letter:

-- From Rich Miner --
"I will be heading out west in late March for NCGA and the Electronic
Imaging Show.  ...  We have built a 35-MIPS Parallel Coprocessor for
the Amiga and are also working on a Hi-Res graphics card that I could
talk about.  In fact I will be giving talks at the Electronic Imaging
show and at Lawrence Livermore Labs on the Amiga as a
High-Performance, low cost, parallel imaging workstation.  I would
also be willing to talk about this and give a presentation ... I would
focus on the design of our co-processor and its integration with the
Amiga environment as a powerful parallel coprocessor, none of this
8086 coprocessor bull :-) I could bring out a board and give a live
Demo.  For a brief write-up look in the January Amiga World in one of
the news sections toward the front.  I could also give a preview-talk
on the 1024x800x10 TMS-34010-50 based graphics card we have designed
and are building for the A2000."

Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 14 Mar 88 16:33:44 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 14 Mar 88 16:31:30 PST
Received: from Score.Stanford.EDU by Sushi.Stanford.EDU with TCP; Mon 14 Mar 88
	16:24:54-PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ALI@Score.Stanford.EDU>
From: Ali Ozer <ALI@Score.Stanford.EDU>
Date: Mon 14 Mar 88 16:24:50-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12382376360.10.ALI@Score.Stanford.EDU>
Subject: Prev message

That was silly of me, I forgot to mention the date of the meeting. I guess
you all know by now: Third Thursday of every month... That would make
this month's BADGE this Thursday, March 17th.
Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 18 Mar 88 6:18:27 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 18 Mar 88 06:15:56 PST
Received: from polya.stanford.edu by Sushi.Stanford.EDU with TCP; Fri 18 Mar 88
	06:09:13-PST
Received: by polya.stanford.edu (5.54/inc-1.2) id AA04207; Fri, 18 Mar 88
	06:13:49 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ali@polya.stanford.edu>
From: ali@polya.stanford.edu (Ali Ozer)
Date: Fri, 18 Mar 88 06:13:49 PST
To: amiga@sushi.stanford.edu
Message-id: <8803181413.AA04207@polya.stanford.edu>
Subject: Commodore announcements, from USENET...


TITLE: 1988 CEBIT Show Announcements

With over 500 members of the press in attendance, Commodore held a
press conference the first day of CEBIT (3/16/88). Chairman Irving Gould
took this opportunity to announce the continuation of the company's
successful financial picture. For the 6 month period ending 12/31/87,
net income rose to $34 million, up from $25.5 million in the same period
one year ago.  This represents an increase of 33%.  Mr. Gould stated that
80% of the net income came from products not present in the Commodore
line 2 years ago.

Mr. Gould announced the redesign of the PC line, and the further develop-
ment of the Amiga computer family. Plans for the Amiga 2500 and Amiga 3000
were discussed. Mr. Gould STRESSED "the A2000 will remain compatible with
all new attributes of new Amiga products".

Details of new products are:

AMIGA 2500AT will have the following specifications:

		68020/68881
		286 Bridgeboard
		40 MG Autoboot harddrive

AMIGA 2500UX will be equipped with

		68020/68881
		Autoboot Hardrive (with option of 100 MG harddrive)
		Unix 5.3 compatible operating system

The Unix included with the A2500UX is a proprietary high performance
windowing user shell. Also optional for the A2500UX will be a tapestream
storage device.

It was also announced that Commodore is continuing work on the Amiga 3000,
which will be based on Motorola's 68030 chip. Some of the attributes of
this machine include networking capabilities and multiple mass storage
devices of up to 2.2 gigabytes.  Release of the A3000 is slated for
calendar year 1989.

Other new products also shown at the Commodore booth include:

	A2620		68020/68881/68851 coprocessor for the A2000
	 		                    with 2-4 MG RAM
	A2024		High Resolution Gray Scale Amiga Monitor
	A2300		Amiga 2000 Genlock
	A2286 		80286 based Amiga bridgeboard
			Transputer project

In other news from the press conference:

Commodore announced a cooperative effort with a large scale research
group to develop a high performance workstation.  The West German Society
for Biotechnological Research and Commodore are working together to
develop the workstation which will be based on the Amiga 2000 with
Transputer. The workstation is aimed at the chemical, pharmaceutical
and food industries, and is considered ideal conditions for graphics
applications and display of molecular structures.

Chairman Gould announced no plans for Commodore to increase prices due
to DRAM  price increases. We will continue to supply our market at prices
levels now in effect.

It was also announced that enchanced graphics chips with non-interlace
mode will be available for the Amiga 500 and Amiga 2000.

Commodore is the leader in the West German microcomputer industry, with
a market share of over 50%. With professional systems, Commodore ranks
in 2nd place in Germany, and is unchallenged in the home market.

European press reaction to the conference has been very positive. Some
of the headlines from the show include: "Commodore and Nixdorf Grow,
Grow, Grow" and "Commodore Attacks the Professional and Business Market".

Commodore and, more especially, CATS, want to thank you as developers for
your ongoing support.  It is this support which has made the advancements
possible.

Hoping to see all of you in Washington -

			Lauren

Received: from OFFICE-1.ARPA by F29.Tymnet; Sat, 26 Mar 88 23:12:17 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 26 Mar 88 23:10:16 PST
Return-path: <@OFFICE-1.ARPA:SHENK@Sushi.Stanford.EDU>
From: Eric E. Shenk <SHENK@Sushi.Stanford.EDU>
Date: Sat 26 Mar 88 23:03:36-PST
To: amiga@Sushi.Stanford.EDU
Message-id: <12385594681.13.SHENK@Sushi.Stanford.EDU>
Subject: help! kermit problems


With the impending demise of sushi, I thought it wise to offload everything
of use onto floppies, but whenever I try to use kermit, I get nowhere.
The symptoms are that my local kermit times out whenever I try to get a
file.  Furthermore, when I tell the remote to FINISH, it just hangs up
(I presume that eventually it would time out, but I get impatient and
reboot).  Is this a problem with kermit on the dec-20, with my copy of
kermit, or with the user?  Help!  (and fast, too).  Much thanks.  -eric
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 28 Mar 88 10:23:26 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 28 Mar 88 10:21:43 PST
Received: from polya.stanford.edu by Sushi.Stanford.EDU with TCP; Mon 28 Mar 88
	07:51:22-PST
Received: by polya.stanford.edu (5.54/inc-1.2) id AA24373; Mon, 28 Mar 88
	07:56:05 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU:ali@polya.stanford.edu>
From: ali@polya.stanford.edu (Ali T. Ozer)
Date: Mon, 28 Mar 88 07:56:05 PST
To: amiga@sushi.stanford.edu
Message-id: <8803281556.AA24373@polya.stanford.edu>
Subject: Second BADGE meeting for March


Accoring to a posting from USENET, the second BADGE meeting for March
is going to happen this Thursday (3/31), at the regular time & place
(Turing Auditorium, 8:15pm). Rich Miner from the Univ of Lowell CPE
Imaging Research Lab will be talking about the 35 MIPS parallel
coprocessor built for the Amiga. (He might even give a demo!) See you all
there!

Ali

ps. Because sushi is going away, this newsgroup will move over to
Score, probably starting later today or tomorrow... You can post to
AMIGA@Sushi for another few days, but because Sushi is going away for
good, your postings will go to the bit bucket after this week... Starting
tomorrow, please post to AMIGA@Score. Thank you for your support.
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 30 Mar 88 22:03:23 PST
Received: from Sushi.Stanford.EDU by OFFICE-1.ARPA; 30 Mar 88 22:02:29 PST
Received: from Score.Stanford.EDU by Sushi.Stanford.EDU with TCP; Wed 30 Mar 88
	21:54:45-PST
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Wed 30 Mar 88
	21:54:41-PST
Received: by csli.stanford.edu (3.2/4.7); Wed, 30 Mar 88 20:21:56 PST
Return-path: <@OFFICE-1.ARPA, @Sushi.Stanford.EDU,
	@Score.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Wed, 30 Mar 88 20:21:56 PST
To: amiga@score
Subject: Printing problems solved!!!




After seaching around I have finally found a printing program that
will not mix up my pictures, but prints it just the way I want it to.

If anyone is intersted in this ultimate printing program, I can mail
you a copy. It asks for a modest $5 shareware fee.

--Kasper

: from Score.Stanford.EDU by OFFICE-1.ARPA; 1 Apr 88 10:40:43 PST
Return-path: <@OFFICE-1.ARPA:ALI@Score.Stanford.EDU>
From: Ali Ozer <ALI@Score.Stanford.EDU>
Date: Fri 1 Apr 88 10:30:51-PST
To: amiga@Score.Stanford.EDU
Message-id: <12387030513.36.ALI@Score.Stanford.EDU>
Subject: testing...


As of today, the AMIGA mailing list is on SCORE. Please send mail to
AMIGA@Score rather than AMIGA@Sushi.

Some email addresses had to be changed from Sushi to Polya in the
switchover... So, as they say:

"If you don't get this, please contact us."

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Sun, 3 Apr 88 0:01:13 PST
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 3 Apr 88 00:01:36 PST
Return-path: <@OFFICE-1.ARPA:DAMON@Score.Stanford.EDU>
From: Daemon Koronakos <DAMON@Score.Stanford.EDU>
Date: Sat 2 Apr 88 23:45:59-PST
To: amiga@Score.Stanford.EDU
Message-id: <12387437406.9.DAMON@Score.Stanford.EDU>
Subject: Question from a Novice

Hi folks,

I'm trying to fool around with the Amiga's multitasking.  I have a
bunch of tasks running which finish their jobs before their time slices
are used up, so they sit busy-waiting (bad).  I want to have each task
check to see if it has done as much useful work as it can, then put itself
to sleep so other tasks can have a crack at the cpu.

I just want the tasks to sleep until the scheduler decides it's time to
run the task again.  I don't want to wake up the task with a message
or anything like that.

So far as I can tell from the documentation I have, I would want to
put a Wait(mask) in my task code, where <mask> is 32 bits, the 16 hi
bits being used by the system and the lo 16 bits being used by moi.
Since I don't want to do anything fancy I don't need to worry about
the lower 16, but I can't find any description of the upper 16.  Can I
just give Wait a mask with all 16 hi bits set to 1, and all 16 lo bits set
to 0s?  I assume one of those upper 16 is the signal bit for "wake up
task because it's your turn again".

Will this work?  Also where can I find out what these upper 16 bits are
used for, exactly?

Damon
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 4 Apr 88 11:17:56 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 4 Apr 88 11:14:52 PDT
Received: from Sushi.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Mon 4 Apr 88
	09:15:05-PST
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ROKICKI@Sushi.Stanford.EDU>
From: Tomas G. Rokicki <ROKICKI@Sushi.Stanford.EDU>
Date: Mon 4 Apr 88 10:14:52-PDT
To: amiga@Score.Stanford.EDU
Message-id: <12387803113.17.ROKICKI@Sushi.Stanford.EDU>
Subject: Looking for

an empty 2-meg card for a 2000, an 80 meg hard disk, and a A2090
controller.  Anyone have pointers for a good place to get these
things, or hard disk recommendations?  Thanks!  (No, I don't have
my 2000 yet, but supposedly I will get it soon . ..)

-tom
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 4 Apr 88 11:17:57 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 4 Apr 88 11:13:56 PDT
Received: from Sushi.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Mon 4 Apr 88
	09:13:54-PST
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ROKICKI@Sushi.Stanford.EDU>
From: Tomas G. Rokicki <ROKICKI@Sushi.Stanford.EDU>
Date: Mon 4 Apr 88 10:13:45-PDT
To: amiga@Score.Stanford.EDU
Message-id: <12387802908.17.ROKICKI@Sushi.Stanford.EDU>
Subject: Turing

Well, folks, I messed up again; apparently ventilating fans and
audio were left on in Turing last Thursday after BADGE.  (Does
anyone know where the ventilating fans are?)  I need someone who
is willing to stay at Turing after BADGE until everyone is gone,
and verify that *everything* is turned off.  Apparently I can't
handle it, as this is the third time this has happened, and I think
the Turing people might be getting just a little angry with us.
Volunteers?

-tom
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 4 Apr 88 11:17:59 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 4 Apr 88 11:16:35 PDT
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Mon 4 Apr 88
	10:37:50-PDT
Received: by csli.stanford.edu (3.2/4.7); Mon, 4 Apr 88 10:47:02 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Mon, 4 Apr 88 10:47:02 PDT
To: amiga@score
Subject: Smooooth scrolling? - how to?

Hi,

I wanted to write a little game. In that little game I wanted a background
to scroll smoothly to the left. It prooved to be more difficult than I
hoped for. Here is what I did, but it is utterly slow.

I make an off-screen rasterport to draw into, so that I should not have to
scroll the rasterport on the screen (I use a HIRES 16 color screen - to big?)

My scroll loop looks like this
	Scroll of screen rasterport 1 to the left
		Using the build in rasterscroll.
	Draw one vertical line of new background.
	Copy the off-screen raster to the Screen raster
		Using the BltBitMapRasterPort procedure.


This came out hopelessly slow, so what do I do?
- Take a low res low color screen
- Use bltbitmap directly (is there any win here)
- Apply amiga-guro trick #71.4 for smooth scrolling backgrounds, only I
  do not know that trick.

-- Kasper

Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 4 Apr 88 18:13:18 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 4 Apr 88 18:11:37 PDT
Received: from OFFICE-1.ARPA by SCORE.STANFORD.EDU with TCP; Mon 4 Apr 88
	17:46:57-PDT
Received: from F29.Tymnet by OFFICE-1.ARPA; 4 Apr 88 17:51:35 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU,
	@OFFICE-1.ARPA:JMS@F29.TYMNET>
From: Joe Smith <JMS%F29.TYMNET@OFFICE-1.ARPA>
Date: Mon, 4 Apr 88 17:48:55 PDT
To: Amiga@SCORE.Stanford.EDU
Subject: Max Toy at FAUG Tuesday.

The following came from the San Jose Mercury News:
  "First Amiga Users Group will meet at 7 p.m. at the Hyatt Palo Alto.
Max Toy, president of Commodore Business Machines, will be the featured
speaker.  Other presenters will demonstrate new and soon-to-be released
Amiga software.  There is a small charge for non-members.  For further
information, call (415)595-5452 or (408)996-0528."
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 5 Apr 88 11:24:19 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 5 Apr 88 11:23:28 PDT
Received: from Portia.stanford.edu by SCORE.STANFORD.EDU with TCP; Tue 5 Apr 88
	11:15:01-PDT
Received: by Portia.stanford.edu (5.54/inc-1.2) id AA22332; Tue, 5 Apr 88
	11:19:21 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:rgkim@Portia.stanford.edu>
From: rgkim@Portia.stanford.edu (Robin Kim)
Date: Tue, 5 Apr 88 11:19:21 PDT
To: amiga@score.stanford.edu
Message-id: <8804051819.AA22332@Portia.stanford.edu>
Subject: Access! termcap


Does anyone have a termcap for Access! which is compatible with vi?

Robin
rgkim@portia
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 5 Apr 88 21:31:20 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 5 Apr 88 21:30:21 PDT
Received: from Portia.stanford.edu by SCORE.STANFORD.EDU with TCP; Tue 5 Apr 88
	21:15:34-PDT
Received: by Portia.stanford.edu (5.54/inc-1.2) id AA15758; Tue, 5 Apr 88
	21:19:44 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:rgkim@Portia.stanford.edu>
From: rgkim@Portia.stanford.edu (Robin Kim)
Date: Tue, 5 Apr 88 21:19:44 PDT
To: amiga@score.stanford.edu
Message-id: <8804060419.AA15758@Portia.stanford.edu>
Subject: Access!


Does anyone have a termcap for Access! that will make it work with vi?

Robin
rgkim@portia
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 6 Apr 88 7:36:45 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 6 Apr 88 07:35:02 PDT
Return-path: <@OFFICE-1.ARPA:ALI@Score.Stanford.EDU>
From: Ali Ozer <ALI@Score.Stanford.EDU>
Date: Wed 6 Apr 88 07:26:18-PDT
To: amiga@Score.Stanford.EDU
Message-id: <12388296714.10.ALI@Score.Stanford.EDU>
Subject: Fish lists


The Fish disk lists have been moved from <ali.amiga.fish> on Sushi to
<ali.amiga.fish> on Score. There you'll find files named 1, 2, 3, ... 138
that contain info about the contents of each disk and a large file named
WHEREIS that is a master index (sorted by program name). You can freely
FTP these files and print them out...

[Actually the lists don't go up to disk 138 yet --- the newest batch (129..138)
 still needs to be added to the list. As Max Toy said last night at FAUG, this
 will happen "soon."]

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 15 Apr 88 15:08:18 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 15 Apr 88 15:05:52 PDT
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Fri 15 Apr 88
	14:57:14-PDT
Received: by csli.stanford.edu (3.2/4.7); Fri, 15 Apr 88 15:07:14 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:kasper@csli.stanford.edu>
From: kasper@csli.stanford.edu (Kasper Osterbye)
Date: Fri, 15 Apr 88 15:07:14 PDT
To: amiga@score
Subject: Faug bboard


For some odd reason, I just "discovered" the Faug bboard the other day.
I just have not figured out how to download ny files yet. I normally
use the kermit build into the vt100 program. But the files on FAUG is not
uuencoded, so I dont get them down right. I have tried to set XFER-MODE
to image, but that did not help.

How do you get things down from faug?

--Kasper
kasper@csli.stanford.edu

Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 20 Apr 88 1:07:59 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 19 Apr 88 20:13:12 PDT
Received: from polya.stanford.edu by SCORE.STANFORD.EDU with TCP; Tue 19 Apr 88
	20:05:04-PDT
Received: by polya.stanford.edu (5.54/inc-1.2) id AA15100; Tue, 19 Apr 88
	20:05:24 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.stanford.edu>
From: ali@polya.stanford.edu (Ali T. Ozer)
Date: Tue, 19 Apr 88 20:05:24 PDT
To: amiga@score.stanford.edu
Message-id: <8804200305.AA15100@polya.stanford.edu>
Subject: April BADGE


The April 1988 BADGE will be held Thursday, April 21, 1988, in Turing
Auditorium. There will be two speakers:

  Brian Witt discussing "Semaphores and Signals", and

  Thad Floryan demonstrating "Cobble-It-Yourself SCSI Add-Ons" including
  multi-media peripherals, 190MB tape units, and the latest 3.5" embedded
  SCSI hard disk drives.

As always, the meeting will start no later than 8:15PM.
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 20 Apr 88 12:18:58 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 20 Apr 88 12:18:11 PDT
Return-path: <@OFFICE-1.ARPA:ISKAN@Score.Stanford.EDU>
From: Waleed Iskandar <ISKAN@Score.Stanford.EDU>
Date: Wed 20 Apr 88 12:09:14-PDT
To: amiga@Score.Stanford.EDU
Message-id: <12392018236.17.ISKAN@Score.Stanford.EDU>
Subject: Inexpensive Computer Products



I hope people won't mind that this message is an advertisement, but it
is also a great opportunity for you to get Amiga accessories safe and
cheap (check end of message on incredible 3.5" floppy offer).

I just started a small company called ISKAN which takes orders from anyone
for computer hardware and software accessories, then will purchase the
product from a manufacturer or distributor and charge whoever ordered it
a fee which will cover cost, expenses (shipping, phone), tax and a
very modest profit margin.

These prices will be less expensive than or at least the same as
mail-order prices.  In addition, you get free delivery within the Stanford,
Palo Alto, Menlo Park, Mountain View areas.  The company will also take
care of all warranty repairs.  The company will handle non-warranty repairs,
but it will probably be slower than taking it to an authorized service
center.

The company takes orders for all accessories and even some computers.  An
example of the inexpensive price is the STARBOARD2 2 meg expansion for
299 dollars.  Also as an introductory offer, you can get 3.5" floppy
disks for 1 dollar each.

To order from ISKAN or just for general information, call 854-1461.
Leave your name, number and product you're interested in if you get
an answering machine.  Someone will get back to you within 24 hours.

Waleed ---
-------
eceived: from OFFICE-1.ARPA by F29.Tymnet; Sat, 23 Apr 88 23:27:08 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 23 Apr 88 23:26:09 PDT
Return-path: <@OFFICE-1.ARPA:ALI@Score.Stanford.EDU> 
From: Ali Ozer <ALI@Score.Stanford.EDU> 
Date: Sat 23 Apr 88 23:17:00-PDT 
To: amiga@Score.Stanford.EDU 
Message-id: <12392926231.10.ALI@Score.Stanford.EDU> 
Subject: Digitizing, anyone? 


Computer Science Dept just purchased Perfect Vision, the real-time
digitizer. The software has some problems (and will crash under certain
predictable situations), but other than that the product is pretty nice.
You can digitize 16-gray pictures in 1/60th of a second, and you can
digitize images from a VCR! (It'll also do color from VCR, apparently, when
a color seperator box becomes available to in between the digitizer and
the VCR.)

Anyway, at Tresidder with the digitizer we have a pretty nice VCR/camcorder
(capable of zooming into less than an inch). If any of you would like to
get anything digitized, let me know and we can arrange to meet at
Tresidder. You can even digitize stuff off a VHS video tape.

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Sat, 30 Apr 88 18:42:15 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 30 Apr 88 18:40:13 PDT
Return-path: <@OFFICE-1.ARPA:ALI@Score.Stanford.EDU> 
From: Ali Ozer <ALI@Score.Stanford.EDU> 
Date: Sat 30 Apr 88 18:32:38-PDT 
To: amiga@Score.Stanford.EDU 
Message-id: <12394709470.10.ALI@Score.Stanford.EDU> 
Subject: Fashion Island "World Class Expo 1988" 


At Fashion Island the Computer Spectrum of Burlingame is holding an
Amiga/Atari "World Class Expo." Not a big expo by most standards, but the
admission is free, and there are stuff on sale... Most prices are average,
except for the Amiga 500 price: The Amiga 500 is $500, which is below
local dealer averages... The 512K expansion is $149, the monitor is $299,
and the external floppy is $219 --- For a total full system price
of under $1200... Not bad in my opinion. So if you're thinking of buying
a 500 or know anyone who is, send them over there. Tomorrow (May 1st) is
the last day.

They also have the 2000 for $1449. Extra 2 Megs for $349. Not too bad!

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Sat, 30 Apr 88 22:01:15 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 30 Apr 88 21:59:59 PDT
Received: from lindy.stanford.edu by SCORE.STANFORD.EDU with TCP; Sat 30 Apr 88
	21:52:43-PDT
Received: by lindy.stanford.edu; Sat, 30 Apr 88 21:58:43 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:GG.MPD@forsythe.stanford.edu>
	
From: Michael Durket <GG.MPD@forsythe.stanford.edu> 
Date: Sat, 30 Apr 88 21:55:59 PDT 
To: amiga@score.stanford.edu 
Subject: "I swear there's a ThinkJet driver"... 

I swear there's a ThinkJet driver for the amiga. Does anyone
know what BBS systems might have it?

   Thanks,

      Mike
From: Joe Smith <JMS@F29.TYMNET> 
Date: Fri, 6 May 88 19:18:06 PDT 
To: ROKICKI@Score.Stanford.EDU 
Subject: Got a guru from DFC. 

Hi!  I was using DFC from a recent Fish disk and it got guru number
81000005.00C3844A (Exec: corrupted memory list).  All I did was to use
it to copy 3 disks from DF0 to DF2, then toggle 'verify' off and back on,
then toggle 'memory' on and back off.  Sorry, I was unable to reproduce
the problem.  I'm running an A2000 with 1 meg (and approx 100K in RAM:).

Just thought you'd want to know.

		/Joe
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 6 May 88 21:01:56 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 6 May 88 20:59:43 PDT
Return-path: <@OFFICE-1.ARPA:ROKICKI@Score.Stanford.EDU> 
From: Tomas Rokicki <ROKICKI@Score.Stanford.EDU> 
Date: Fri 6 May 88 20:54:14-PDT 
To: JMS%F29.TYMNET@OFFICE-1.ARPA 
Message-id: <12396308113.11.ROKICKI@Score.Stanford.EDU> 
Subject: Re: Got a guru from DFC. 
In-Reply-To: Message from "Joe Smith <JMS%F29.TYMNET@OFFICE-1.ARPA> " of Fri 6
	May 88 19:19:35-PDT

Thanks for the bug report.  If you get it again, let me know.

-tom
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 10 May 88 17:01:56 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 10 May 88 16:59:31 PDT
Received: from polya.stanford.edu by SCORE.STANFORD.EDU with TCP; Tue 10 May 88
	15:31:52-PDT
Received: by polya.stanford.edu (5.54/inc-1.2) id AA21262; Tue, 10 May 88
	15:37:23 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:rokicki@polya.stanford.edu> 
From: Tomas G. Rokicki <rokicki@polya.stanford.edu> 
Date: Tue, 10 May 88 15:37:23 PDT 
To: amiga@score.stanford.edu 
Message-id: <8805102237.AA21262@polya.stanford.edu> 
Subject: Monitor 

I want a cheap monochrome NTSC monitor to use on my Amiga in my office.
(If it is not cheap enough, I may just go the full nine yards and get
another good monitor, but you always hear bout these $100 b/w monitors.)
Anyone got any pointers?  High persistence would be a major win.
Thanks!

-tom
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 10 May 88 21:40:56 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 10 May 88 21:38:21 PDT
Return-path: <@OFFICE-1.ARPA:ROKICKI@Score.Stanford.EDU> 
From: Tomas Rokicki <ROKICKI@Score.Stanford.EDU> 
Date: Tue 10 May 88 21:36:38-PDT 
To: amiga@Score.Stanford.EDU 
Message-id: <12397364408.17.ROKICKI@Score.Stanford.EDU> 
Subject: Monitor 

Alternatively, if anyone has an old 1080 they'd be willing to sell, let
me know.  Thanks!

-tom
-------
From: Joe Smith <JMS@F29.TYMNET> 
Date: Tue, 10 May 88 18:58:56 PDT 
To: Amiga@SCORE.Stanford.EDU 
Subject: Sending CLI output to the printer. 

On my Amiga, I need to do something just like typing Control-P to CP/M or
MS-DOS.  That is, everything I type has to be output to both the screen and
the printer, and the output from programs go to both the screen and the
printer.  Using redirection doesn't cut it since input from the keyboard
does not show up on the redirected output.

Is there a console handler out there that can do this?

		/Joe Smith
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 18 May 88 22:17:15 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 18 May 88 22:14:53 PDT
Received: from polya.stanford.edu by SCORE.STANFORD.EDU with TCP; Wed 18 May 88
	22:13:38-PDT
Received: by polya.stanford.edu (5.54/inc-1.2) id AA26302; Wed, 18 May 88
	22:13:55 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.stanford.edu> 
From: Ali T. Ozer <ali@polya.stanford.edu> 
Date: Wed, 18 May 88 22:13:55 PDT 
To: amiga@score.stanford.edu 
Message-id: <8805190513.AA26302@polya.stanford.edu> 
Subject: dmouse, virusx, badge 


Two new things in <ali.amiga.misc> on Score: dmouse & virusx 1.21

Dmouse, Matt Dillon's latest creation, provides mouse acceleration, 
mouse blanking, single-click window ordering, and screen blanking.
Work with acceleration factor of 3 or 5 for a while and any other mouse
seems terribly sloooow. And all you need is 2x2 inches of desk space!

Dmouse is in three files --- dmouse.uu, dmouse-handler.uu, and dmouse.doc.
Get them to you Amiga, uudecode them, and put dmouse-handler in the l:
directory. 

Virusx.uu has the "arc" version of the latest and apparently greatest
virus checker. I didn't test it myself, but it might be useful at some
point... This is version 1.21.

And, it's Wednesday night before the third Thursday of the month, and
no news of BADGE! This of course does not mean there won't be a meeting,
but be prepared for a no-speaker type gathering. Of course, this might
be the greatest chance to start up the discussions on the next 
BADGE Killer Demo Contest.

Ali
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 19 May 88 7:19:21 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 19 May 88 07:16:09 PDT
Received: from polya.stanford.edu by SCORE.STANFORD.EDU with TCP; Thu 19 May 88
	07:16:02-PDT
Received: by polya.stanford.edu (5.54/inc-1.2) id AA04018; Thu, 19 May 88
	07:16:22 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.stanford.edu> 
From: Ali T. Ozer <ali@polya.stanford.edu> 
Date: Thu, 19 May 88 07:16:22 PDT 
To: amiga@score.stanford.edu 
Message-id: <8805191416.AA04018@polya.stanford.edu> 
Subject: Finally, BADGE info. (They're cutting it close, like Tom used to! 8-) 


The May 1988 BADGE (Bay Area Amiga Developers' GroupE) meeting will be held
Thursday, May 19, 1988, in Turing Auditorium. 

The Double Header agenda features:

  Chuck McManis and "IntuiTrix" (or "How to Coerce Intuition to Do What I
  Mean and Not What I Say!" :-)

  Kevin Clague detailing and demonstrating his latest Super Mandelbrot, with
  hi-res, lo-res, variable bit-planes, 68020/68881 support, spawing of
  multiple child processes, dynamic color palette alteration, etc.

As always, the meeting will begin by 8:15pm. For those people new to
the Amiga & BADGE:

  The Bay Area Amiga Developers' GroupE (BADGE) is an organization of
  hardware and software developers for the Amiga computer.  Admission to
  BADGE is free and open to anyone interested in developing on the Amiga
  computer.  BADGE meets the third Thursday every month at Turing
  Auditorium in the Jordan Quad at Stanford University.

Hope to see you all there!
Received: from OFFICE-1.ARPA by F29.Tymnet; Sun, 22 May 88 17:49:38 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 22 May 88 17:51:28 PDT
Received: from polya.stanford.edu by SCORE.STANFORD.EDU with TCP; Sun 22 May 88
	17:45:31-PDT
Received: by polya.stanford.edu (5.54/inc-1.2) id AA23155; Sun, 22 May 88
	17:45:51 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.stanford.edu> 
From: Ali T. Ozer <ali@polya.stanford.edu> 
Date: Sun, 22 May 88 17:45:51 PDT 
To: amiga@score.stanford.edu, su-events@score.stanford.edu 
Message-id: <8805230045.AA23155@polya.stanford.edu> 
Subject: 1988 BADGE Killer Demo Contest Rules Committee Meeting --- Th, May 26 

BADGE (Bay area Amiga Developers' GroupE) will host the first Rules' Committee
meeting for the 1988 BADGE Killer Demo Contest at 8pm, on Thursday, May 26,
in Turing Auditorium at Stanford University.

Randy Spencer (of Infinity Software) volunteered to be the Coordinator and,
from a show of hands, it appears the attendance will be large. Everyone
interested in contributing to the discussion is welcome. Bring your
suggestions regarding categories, "special equipment needed", etc.

The goal of the contest is to collect exciting demos for the Amiga
computer and give them wide distribution throughout the Amiga
community.  Last year's Zeroth BADGE Killer Demo Contest, held in
October 1987, was a huge success --- The winning demos were displayed
at Amiga dealer windows everywhere, and the authors won various prizes
and worldwide fame among Amiga owners.
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 25 May 88 21:47:43 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 25 May 88 21:49:21 PDT
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Wed 25 May 88
	21:41:55-PDT
Received: by csli.stanford.edu (3.2/4.7); Wed, 25 May 88 21:42:26 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:bratt@csli.stanford.edu> 
From: Harry Bratt <BRATT@CSLI.Stanford.EDU> 
Date: Wed 25 May 88 21:42:25-PDT 
To: amiga@SCORE.STANFORD.EDU 
Message-id: <580624945.0.BRATT@CSLI.Stanford.EDU> 
Subject: Workbench question 
Mail-System-Version: <SUN-MM(242)+TOPSLIB(128)@CSLI.Stanford.EDU>

Hello there - I was wondering if someone would have an answer to
a problem I just came across.  It goes like this:
I opened a window for a disk and a window for one of the drawers
in the first window.  I removed an icon from inside the drawer's
window and placed it on the workbench screen.  I then closed all
windows and double-clicked the icon to run the program.
After finishing with the program I thought - is there going to be
a problem with this icon being here?  Will it have been removed
from the disk if I power down now?  That seemed unlikely, but anyway
I opened the disk's window and dragged it on top of its drawer
to see what would happen.  It disappeared and I heard no disk access.
Today I opened this drawers window again and the icon was gone.
I did a dir in CLI and it as well as its .icon are there in the
right directory, but don't show up in the wb window.  The window's
scroll bars are full size, so it's not in a different place in
the window it's just gone.
It runs fine from CLI.
What happened?
Thanks,
 -Harry
  (bratt@csli)
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 26 May 88 14:21:37 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 26 May 88 14:23:25 PDT
Received: from LEAR.STANFORD.EDU by SCORE.STANFORD.EDU with TCP; Thu 26 May 88
	14:08:31-PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:J.JIGALO@LEAR.STANFORD.EDU> 
From: Michael Frank <J.JIGALO@LEAR.STANFORD.EDU> 
Date: Thu 26 May 88 14:00:32-PDT 
To: amiga@SCORE.STANFORD.EDU 
Message-id: <12401475680.306.J.JIGALO@LEAR.STANFORD.EDU> 
Subject: v1.3 

I want 1.3!

Does anyone know, from the nets or something, WHEN version 1.3 will be
available for us plebians (non-developers)? A couple months ago, Max Toy
said "May", and that's the last I've heard. And when it is available, how
do we get it cheapest? Send off to C-A? Any reassurances would be
appreciated.

Thx, Mike Frank. 8->
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 26 May 88 16:07:37 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 26 May 88 16:09:55 PDT
Return-path: <@OFFICE-1.ARPA:ROKICKI@Score.Stanford.EDU> 
From: Tomas Rokicki <ROKICKI@Score.Stanford.EDU> 
Date: Thu 26 May 88 15:22:14-PDT 
To: J.JIGALO@Lear.Stanford.EDU 
Cc: amiga@Score.Stanford.EDU 
Message-id: <12401490555.39.ROKICKI@Score.Stanford.EDU> 
Subject: Re: v1.3 
In-Reply-To: <12401475680.306.J.JIGALO@LEAR.STANFORD.EDU>

1.3 will be available when the people developing it and the Commodore
QA people are satisfied that it is essentially bug free.  At the
moment, this is not the case (although it's real close!)  It will be
available from your local dealers and will probably be cheap.  If I
*had* to guess when it would be available, I'd say sometime in July.

And it will be worth many times what they will charge . . .

-tom
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 26 May 88 16:30:37 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 26 May 88 16:31:29 PDT
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Thu 26 May 88
	16:20:04-PDT
Received: by csli.stanford.edu (3.2/4.7); Thu, 26 May 88 16:20:27 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:bratt@csli.stanford.edu> 
From: Harry Bratt <BRATT@CSLI.Stanford.EDU> 
Date: Thu 26 May 88 16:20:24-PDT 
To: amiga@SCORE.STANFORD.EDU 
Message-id: <580692024.0.BRATT@CSLI.Stanford.EDU> 
Subject: Re: Workbench question 
Mail-System-Version: <SUN-MM(242)+TOPSLIB(128)@CSLI.Stanford.EDU>

Thanks everyone who responded to my question about why my icon
disappeared from its wb drawer.
Michael Frank gave me some suggestions to try, but half way through
his first suggestion, -poof- the icon was back.
Now I'm _really_ puzzled.
What I did was list the directory to see the .info was there and was
reasonably long (it was).  Load it into IconEd to see that it looked
ok (it did).  Make a copy of it using CLI copy to a.info.  Then, I
opened the drawer from the wb to see if "a" was there - and it was...
on top of the original icon.  I don't know what brought the original
back, but I just deleted a.info and everything's normal now.
Try as I may I just cannot duplicate this problem.
So I'd still be quite interested if anyone has any ideas what could
have happened.  Thanks again,
 -Harry
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Sat, 28 May 88 18:05:48 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 28 May 88 18:06:55 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Fri 27 May 88
	22:57:59-PDT
Received: by polya.Stanford.EDU (5.59/inc-1.2) id AA01255; Fri, 27 May 88
	22:58:35 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.Stanford.EDU> 
From: Ali T. Ozer <ali@polya.Stanford.EDU> 
Date: Fri, 27 May 88 22:58:35 PDT 
To: amiga@score.Stanford.EDU, su-computers@lear.Stanford.EDU 
Message-id: <8805280558.AA01255@polya.Stanford.EDU> 
Subject: Announcing the 1988 BADGE Killer Demo Contest... 


	  Announcing the First Annual BADGE Killer Demo Contest

The Bay Area Amiga Developers GroupE is sponsoring, for the second time,
a competition designed to provide some impetus to the creative
and sometimes demented developers and users of the Amiga to create
some killer demos.  The rewards consist of cold hard cash, recognition
throughout the Amiga community, and some neat toys.

Last years winners included Joel Hagen, Ken Offer, Robert Wilt,
Leo Schwab, and Mark Riley.  Some of the prizes from last year
included an Amiga 2000, ASDG 8 Meg Memory board, Microbotics Starboard II,
Manx C compiler, and 3 year subscriptions to Info magazine.

Last years winning demos were distributed to dealers and in the 
Fred Fish Freely Distributable Library disks 112 - 127.

This year we are doing it again...

Two catagories:   Custom Programs / Tool Based demos

Environment:   1 meg machine, 2 floppies, WorkBench 1.3 running

Technical Qualifications:
	Runs from Workbench or CLI
	Runs from within a drawer on any device
	Runs on all Kickstart supported processors (68000, 010, 020)
	If no obvious close gadget, input causes exit
	Returns all memory and resources, doesn't write to disk

Entry:  Letter of Intent   September 15, 1988
        Final Submission   September 29, 1988

Judging: October 20, 1988 meeting of Bay Area Developers GroupE
	 All attending are eligible to vote
	 Spelling doesn't count

Send a letter of intent or inquiries for more information to:

Randy Spencer P.O. Box 4542, Berkeley CA 94704

Include your name, address, and phone number; and an SASE for a
complete listing of the rules and suggestions

Phone number (415) 222-7595   ----    BBS number (415) 222-9416


Received: from OFFICE-1.ARPA by F29.Tymnet; Sat, 28 May 88 18:07:02 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 28 May 88 18:08:23 PDT
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Sat 28 May 88
	12:18:10-PDT
Received: by csli.stanford.edu (3.2/4.7); Sat, 28 May 88 12:18:40 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:kasper@csli.stanford.edu> 
From: kasper@csli.stanford.edu (Kasper Osterbye) 
Date: Sat, 28 May 88 12:18:40 PDT 
To: amiga@score 
Subject: what is ".fastdir" files? 


I have encountered them here and there, and the name indicates some
kind of wishthinking - anyone kow what they are?

--kasper
From: Joe Smith <JMS@F29.TYMNET> 
Date: Sun, 29 May 88 22:55:14 PDT 
To: <@OFFICE-1.ARPA, @Score.Stanford.EDU:kasper@csli.stanford.edu> 
Subject: Re: what is ".fastdir" files? 
In-reply-to: your message of Sat, 28 May 88 12:18:40 PDT

The .fastdir files are created by CLImate.  If you only use CLImate's gadgets
to do CLI type activities and don't use the CLI, then the .fastdir files
are supposed to match the disk directory, therefore CLImate does not have
to read the header block of every file in the directory.  I tend to destroy
them wherever they are.     /Joe
From: Joe Smith <JMS@F29.TYMNET> 
Date: Mon, 30 May 88 1:22:28 PDT 
To: Amiga@SCORE.Stanford.EDU 
Subject: INFO-AMIGA.DIGEST? 

I saw something on USENET that refered to INFO-AMIGA on BITNET.
Has the INFO-AMIGA.DIGEST been revived?  If so, where does one send the
request to sign up.

/Joe
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 1 Jun 88 13:14:32 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 1 Jun 88 13:14:36 PDT
Received: from OFFICE-1.ARPA ([26.6.0.128].#Internet) by SCORE.STANFORD.EDU
	with TCP; Mon 30 May 88 01:26:26-PDT
Received: from F29.Tymnet by OFFICE-1.ARPA; 30 May 88 01:28:18 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU,
	@OFFICE-1.ARPA:JMS@F29.TYMNET> 
From: Joe Smith <JMS%F29.TYMNET@OFFICE-1.ARPA> 
Date: Mon, 30 May 88 1:22:28 PDT 
To: Amiga@SCORE.Stanford.EDU 
Subject: INFO-AMIGA.DIGEST? 

I saw something on USENET that refered to INFO-AMIGA on BITNET.
Has the INFO-AMIGA.DIGEST been revived?  If so, where does one send the
request to sign up.

/Joe
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 3 Jun 88 11:21:00 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 3 Jun 88 11:21:11 PDT
Received: from jaguar.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Fri 3 Jun 88
	11:16:37-PDT
Received: by jaguar.Stanford.EDU (5.51/inc-1.01) id AA26246; Fri, 3 Jun 88
	11:09:09 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:jwilson@jaguar.Stanford.EDU> 
From: James Wilson <jwilson@jaguar.Stanford.EDU> 
Date: Fri, 3 Jun 88 11:09:09 PDT 
To: amiga@score.stanford.edu 
Message-id: <8806031809.AA26246@jaguar.Stanford.EDU> 
Subject: modems 

I want to get a modem that works for my Amiga 500.  I planned on
buying a Supra 2400 for $139 from the company mentioned on
comp.sys.amiga. Unfortunately, they now charge $155 instead of $139
and charge $2.50 for shipping. Is this still a good deal?

Can you recommend a lower price 1200 or 2400 baud modem?

Thanks in advance,
James

Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 7 Jun 88 8:31:04 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 7 Jun 88 08:26:00 PDT
Return-path: <@OFFICE-1.ARPA:ALI@Score.Stanford.EDU> 
From: Ali Ozer <ALI@Score.Stanford.EDU> 
Date: Tue 7 Jun 88 08:24:39-PDT 
To: amiga@Score.Stanford.EDU 
Message-id: <12404560263.22.ALI@Score.Stanford.EDU> 
Subject: New Fish disks, FAUG 


Fish disks 139-146 are out; the list of what's on them can be found in
<ali.amiga.fish>139-146 on Score. (Soon to be broken up into files
named 139, 140, 141, etc.) Looks like there are some good stuff on there;
two-disk Stony Brook Prolog distribution, a Small-C (subset of C) compiler,
and "RIM," a relational information manager...

Also reminder: FAUG meeting is tonight (first Tuesday of the month) at
7:00pm, at Palo Alto Hyatt.

Ali
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 8 Jun 88 18:17:31 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 8 Jun 88 18:14:31 PDT
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Wed 8 Jun 88
	18:11:17-PDT
Received: by csli.stanford.edu (3.2/4.7); Wed, 8 Jun 88 18:11:59 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:kasper@csli.stanford.edu> 
From: kasper@csli.stanford.edu (Kasper Osterbye) 
Date: Wed, 8 Jun 88 18:11:59 PDT 
To: amiga@score 
Subject: Printer drivers? 


What is actually you set when you go into the preferences and set the
printer parameters. If I set a leftmargin of 5, only some programs
starts to print with a left margin of 5. Is it left for the programmer
to check the preferences in order to read margins and pitch etc.? If
that is the case why was such parameters put ito the preferences anyway?

--Kasper.
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 15 Jun 88 7:37:52 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 15 Jun 88 07:36:27 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Wed 15 Jun 88
	07:26:17-PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA08217; Wed, 15 Jun 88
	07:26:31 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.Stanford.EDU> 
From: Ali T. Ozer <ali@polya.Stanford.EDU> 
Date: Wed, 15 Jun 88 07:26:31 PDT 
To: amiga@score 
Message-id: <8806151426.AA08217@polya.Stanford.EDU> 
Subject: June BADGE --- Th, June 16 


The June 1988 BADGE (Bay Area Amiga Developers' GroupE) meeting will be held
Thursday, June 16, 1988, in the Turing Auditorium of the Jordan Quad on the
Stanford University campus. 

The agenda features Marvin W. of SLAC (Stanford Linear Accelerator) and
Pete Goodeve discussing IPC (Inter Process Communication), Clients and Servers.

As always, the meeting will begin at 8:15pm and will be followed (~11pm) by 
the traditional post-meeting meeting at the Oasis in Menlo Park.

Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 20 Jun 88 13:53:54 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 20 Jun 88 13:48:30 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Mon 20 Jun 88
	13:32:28-PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA03316; Mon, 20 Jun 88
	13:36:56 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:rokicki@polya.Stanford.EDU> 
From: Tomas G. Rokicki <rokicki@polya.Stanford.EDU> 
Date: Mon, 20 Jun 88 13:36:56 PDT 
To: amiga@sushi 
Message-id: <8806202036.AA03316@polya.Stanford.EDU> 
Subject: Scheme Amiga! 

Ed Puckett has put together a pretty nice little Scheme system
for the Amiga!  It's not even commercial.  Write me for details.
After I play with it some, I'll probably be setting it up for ftp . . .

-tom
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 21 Jun 88 12:30:52 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 21 Jun 88 12:28:42 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Tue 21 Jun 88
	12:25:56-PDT
Received: from solar.Stanford.EDU by polya.Stanford.EDU (5.59/25-eef) id
	AA17523; Tue, 21 Jun 88 12:22:23 PDT
Received: by solar.stanford.edu; Tue, 21 Jun 88 12:25:59 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU,
	@polya.Stanford.EDU:shf@solar.stanford.edu> 
From: Stuart Ferguson <shf@solar.stanford.edu> 
Date: Tue, 21 Jun 88 12:25:59 PDT 
To: amiga@Polya.Stanford.EDU 
Message-id: <8806211922.AA17523@polya.Stanford.EDU> 
Subject: 020 and 32-bit memory 

I've already asked this on USEnet, but I really need an answer fast ...

Is there any reason why a program that works on an Amiga with an '020 
would not work on an Amiga with an '020 *and* 32-bit memory?

I've gotten some vague reports from beta-testers along these lines and 
I'd like to know if there are any differences as far as software should 
be concerned.  My understanding was that this type of change to the 
hardware is completely transparent to the programmer.  Thanx in advance.

	Stuart Ferguson
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 21 Jun 88 12:51:51 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 21 Jun 88 12:50:43 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Tue 21 Jun 88
	12:47:01-PDT
Received: from solar.Stanford.EDU by polya.Stanford.EDU (5.59/25-eef) id
	AA17423; Tue, 21 Jun 88 12:21:15 PDT
Received: by solar.stanford.edu; Tue, 21 Jun 88 12:24:51 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU,
	@polya.Stanford.EDU:shf@solar.stanford.edu> 
From: Stuart Ferguson <shf@solar.stanford.edu> 
Date: Tue, 21 Jun 88 12:24:51 PDT 
To: amiga@Polya.Stanford.EDU 
Message-id: <8806211921.AA17423@polya.Stanford.EDU> 
Subject: Library Source 

Hi.

I'm looking for examples of how to create a run-time library using Manx 3.6a
C compiler.  If there are sources I can get on-line here that's great, but
pointers like Fish disk #X would also be Ok.  Also, has anyone implemented
a library base locking protocol, or seen the source to LockIBase() in
Intuition?  While source examples for a library are essential, it would also
help to know the general rules involved as well.  Many of the basic rules I
can take an educated guess at, but I imagine that there are some tricky things
that only someone who has actually done it would know.  Any help would be
appreciated.  Thanx in advance.

	Stuart Ferguson
Received: from OFFICE-1.ARPA by F29.Tymnet; Sun, 26 Jun 88 14:21:59 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 26 Jun 88 14:19:59 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Sun 26 Jun 88
	14:19:35-PDT
Received: from solar.Stanford.EDU by polya.Stanford.EDU (5.59/25-eef) id
	AA13349; Sun, 26 Jun 88 14:17:39 PDT
Received: by solar.stanford.edu; Sun, 26 Jun 88 14:17:17 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU,
	@polya.Stanford.EDU:shf@solar.stanford.edu> 
From: Stuart Ferguson <shf@solar.stanford.edu> 
Date: Sun, 26 Jun 88 14:17:17 PDT 
To: amiga@Polya.Stanford.EDU 
Message-id: <8806262117.AA13349@polya.Stanford.EDU> 
Subject: Fish index 

There used to be information about Fish disks on <ali.amiga.fish> on
sushi.  I tried to ftp these recently with no sucess.  What happened
to this stuff?  Thanx.

	Stuart
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 6 Jul 88 9:17:09 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 6 Jul 88 09:15:43 PDT
Received: from csli.stanford.edu by SCORE.STANFORD.EDU with TCP; Tue 5 Jul 88
	22:58:13-PDT
Received: by csli.stanford.edu (3.2/4.7); Tue, 5 Jul 88 16:46:10 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:kasper@csli.stanford.edu> 
From: kasper@csli.stanford.edu (Kasper Osterbye) 
Date: Tue, 5 Jul 88 16:46:10 PDT 
To: amiga@score 
Subject: Memory test programs? 


Hi,
The memory of my a500 or the internal 1/2 MB expansion is suspect for
giving me guru 00003.xxxxx (not sure about the number of zero's and x's).
Do anyone know of a diagnostics program?

--Kasper
   Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 6 Jul 88 11:13:11 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 6 Jul 88 11:12:25 PDT
Return-path: <@OFFICE-1.ARPA:ISKAN@Score.Stanford.EDU> 
From: Waleed Iskandar <ISKAN@Score.Stanford.EDU> 
Date: Wed 6 Jul 88 11:05:18-PDT 
To: amiga@Score.Stanford.EDU 
Message-id: <12412191685.41.ISKAN@Score.Stanford.EDU> 
Subject: Amiga 1000 cheap 


I have an Amiga 1000 with monitor and half meg for sale.
The price is 450 dollars or Best Offer (so make me one).

Included with the hardware is a lot of software (public domain mostly
plus some games and other stuff), a mouse pad and a monitor swivel
stand.  The machine is 1.5 years old and works perfectly.  A couple
of manuals are also available with it.

Send mail to ISKAN@SCORE, or call me at 323-9706.

Waleed Iskandar
-------
From: Joe Smith <JMS@F29.TYMNET> 
Date: Sun, 17 Jul 88 21:28:38 PDT 
To: rokiki@polya.stanford.edu 
Subject: Hodgepodge from August Sci-Am 

Have you seen "Computer Recretions" in the August Scientific American?
For simulations with N=63, all states would show up on an extra-halfbrite
screen.  Is it difficult to get the Amiga's blitter to do integer division?
I'd love to see an Amiga version of HODGEPODGE running at blitter speeds.

		/Joe Smith
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 18 Jul 88 3:12:01 PDT
Received: from polya.Stanford.EDU by OFFICE-1.ARPA; 18 Jul 88 02:24:10 PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA02584; Mon, 18 Jul 88
	02:24:21 PDT
Return-path: <@OFFICE-1.ARPA:rokicki@polya.Stanford.EDU> 
From: Tomas G. Rokicki <rokicki@polya.Stanford.EDU> 
Date: Mon, 18 Jul 88 02:24:21 PDT 
To: JMS%F29.TYMNET@OFFICE-1.ARPA 
Message-id: <8807180924.AA02584@polya.Stanford.EDU> 
Subject: Re: Hodgepodge from August Sci-Am 

Hmm, to get the blitter to do integer division would be very difficult;
getting it to do addition is hard enough.  I'll have to pick up a copy of
that magazine . . .

-tom
Received: from OFFICE-1.ARPA by F29.Tymnet; Thu, 21 Jul 88 20:40:42 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 21 Jul 88 20:21:27 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Thu 21 Jul 88
	20:19:10-PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA22146; Thu, 21 Jul 88
	20:19:29 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.Stanford.EDU> 
From: Ali T. Ozer <ali@polya.Stanford.EDU> 
Date: Thu, 21 Jul 88 20:19:29 PDT 
To: amiga@score 
Message-id: <8807220319.AA22146@polya.Stanford.EDU> 
Subject: info-amiga on the Tragedies 


Lee and I were away during the last month, and because I forgot to
set up some cron jobs or tell anyone about it, the forwarding of
comp.sys.amiga mail from Polya to info-amiga bboard on the Tragedies
was interrupted... Sorry about that! I started up the mailing again,
from about 4-5 days ago, so the bboard should be full and ready for your
reading pleasure. 

Ali
From: Joe Smith <JMS@F29.TYMNET> 
Date: Fri, 22 Jul 88 12:20:29 PDT 
To: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.Stanford.EDU> 
Subject: Re: info-amiga on the Tragedies 
In-reply-to: <8807220319.AA22146@polya.Stanford.EDU> of Thu, 21 Jul 88 20:19:29
	PDT

What happened to the INFO-AMIGA digest?  I've heard two stories: one says the
moderator of the digest gave up and INFO-AMIGA died, the other says that
INFO-AMIGA is just a reposting of comp.sys.amiga from USENET.  Are either or
both statements true?  I would want to get on the INFO-AMIGA mailing list
if it is different from comp.sys.amiga.

		/Joe
+-----------------------------------------------------------------------------+
|  TYMNET:   JMS@F29            UUCP: {ames|pyramid}oliveb!tymix!antares!jms  |
|  INTERNET: JMS%F29.Tymnet@Office-1.ARPA   PHONE: Joe Smith @ (408)922-6220  |
+-----------------------------------------------------------------------------+
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 22 Jul 88 18:05:53 PDT
Received: from polya.Stanford.EDU by OFFICE-1.ARPA; 22 Jul 88 17:33:52 PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA23217; Fri, 22 Jul 88
	17:33:50 PDT
Return-path: <@OFFICE-1.ARPA:ali@polya.Stanford.EDU> 
From: Ali T. Ozer <ali@polya.Stanford.EDU> 
Date: Fri, 22 Jul 88 17:33:50 PDT 
To: JMS%F29.TYMNET@OFFICE-1.ARPA, ali@polya.Stanford.EDU 
Message-id: <8807230033.AA23217@polya.Stanford.EDU> 
Subject: Re: info-amiga on the Tragedies 

info-amiga did indeed die. It used to be a diest, but the moderator gave
up because of the heavy workload. About six months ago I started
dumping comp.sys.amiga from polya to the tragedies, into the "info-amiga" bboard.
Other than the name, the info-amiga bboard on lots has nothing to do with the
original digest...
Ali
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 12 Jul 88 18:04:41 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 12 Jul 88 17:34:58 PDT
Return-path: <@OFFICE-1.ARPA:HITT@Score.Stanford.EDU> 
From: Daniel Hitt <HITT@Score.Stanford.EDU> 
Date: Tue 12 Jul 88 17:31:57-PDT 
To: amiga@Score.Stanford.EDU 
Message-id: <12413834936.9.HITT@Score.Stanford.EDU> 
Subject: producing drawings 


I need some software to make some architectural drawings (residential
floor plans).

Does anybody know of a program, either commercial or in the public domain,
that can be used to produce such drawings?

Also, where would one go to get access to a plotter or other device
to produce the drawings?

Thanks.

(All of this on the Amiga, of course.)
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 22 Aug 88 22:30:22 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 22 Aug 88 22:26:38 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Mon 22 Aug 88
	22:27:46-PDT
Received: from Lear.Stanford.EDU by polya.Stanford.EDU (5.59/25-eef) id
	AA09710; Mon, 22 Aug 88 22:25:09 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU,
	@polya.Stanford.EDU:M.MIKEW@LEAR.STANFORD.EDU> 
From: Mike Wolfe <M.MIKEW@LEAR.STANFORD.EDU> 
Date: Mon 22 Aug 88 22:22:08-PDT 
To: amiga@POLYA.STANFORD.EDU 
Message-id: <12424635667.172.M.MIKEW@LEAR.STANFORD.EDU> 
Subject: sell out... 



   I'm considering selling my Amiga (1000 with 512K, color monitor, extra drive
cheap printer, lots o' software).  Does anybody have any idea of:

       o  A price I can expect/ask for it
       o  The best way to advertise (club newsletters, classified?)
       o  Any friends who want one?

Thanks, 
 Mike
-------
   Received: from OFFICE-1.ARPA by F29.Tymnet; Mon, 22 Aug 88 22:30:22 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 22 Aug 88 22:26:38 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Mon 22 Aug 88
	22:27:46-PDT
Received: from Lear.Stanford.EDU by polya.Stanford.EDU (5.59/25-eef) id
	AA09710; Mon, 22 Aug 88 22:25:09 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU,
	@polya.Stanford.EDU:M.MIKEW@LEAR.STANFORD.EDU> 
From: Mike Wolfe <M.MIKEW@LEAR.STANFORD.EDU> 
Date: Mon 22 Aug 88 22:22:08-PDT 
To: amiga@POLYA.STANFORD.EDU 
Message-id: <12424635667.172.M.MIKEW@LEAR.STANFORD.EDU> 
Subject: sell out... 



   I'm considering selling my Amiga (1000 with 512K, color monitor, extra drive
cheap printer, lots o' software).  Does anybody have any idea of:

       o  A price I can expect/ask for it
       o  The best way to advertise (club newsletters, classified?)
       o  Any friends who want one?

Thanks, 
 Mike
-------
Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 13 Sep 88 7:21:43 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 13 Sep 88 07:20:36 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Tue 13 Sep 88
	07:19:11-PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA04913; Tue, 13 Sep 88
	07:19:05 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.Stanford.EDU> 
From: Ali T. Ozer <ali@polya.Stanford.EDU> 
Date: Tue, 13 Sep 88 07:19:05 PDT 
To: amiga@score, su-events@score 
Message-id: <8809131419.AA04913@polya.Stanford.EDU> 
Subject: September BADGE --- Th, Sept 15, 8:15pm at Turing Aud 


The September 1988 BADGE (Bay Area Amiga Developers' GroupE) meeting will be
held Thursday, September 15, 1988, in the Turing Auditorium of the Jordan Quad
on the Stanford University campus. 

The agenda features Jay Miner on "Amiga Hardware."
Also speaking be Dave Needle (subject unknown).

October will be the BADGE Killer Demo Contest, and November will feature
Dale Luck on "Amiga X-Windows".

BADGE begins at 8:15 PM. Admission is free and open to everyone interested in
developing on the Amiga computer.

Following the meeting (~11PM) will be the traditional post-meeting meeting
at the Oasis in Menlo Park (the local "watering-hole", 19th tee, etc. :-).


Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 16 Sep 88 15:36:25 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 16 Sep 88 15:31:03 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Fri 16 Sep 88
	15:27:34-PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA14737; Fri, 16 Sep 88
	15:27:48 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:rokicki@polya.Stanford.EDU> 
From: Tomas G. Rokicki <rokicki@polya.Stanford.EDU> 
Date: Fri, 16 Sep 88 15:27:48 PDT 
To: amiga@polya.Stanford.EDU 
Message-id: <8809162227.AA14737@polya.Stanford.EDU> 
Subject: VSO 

It's that time of the year again, when we need all of the Amiga
type Stanford students to come forward and be counted!  We need
another few signatures to be eligible for VSO privileges this
year again, so if you are a student with an Amiga, or just
interested in the Amiga, please give me a call at 326-5312 so we
can get this form filled out.  Or simply stop by 072 CIS (on the
second floor).  If I'm not there, the form will be in some obvious
place; simply sign your name and student ID number in the
appropriate slots.

-tom
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 16 Sep 88 18:53:24 PDT
Received: from chpc.brc.utexas.edu by OFFICE-1.ARPA; 16 Sep 88 18:48:14 PDT
Return-path: <@OFFICE-1.ARPA:c072erh%utarlg.decnet@chpc.brc.utexas.edu> 
From: "UTARLG::C072ERH" <c072erh%utarlg.decnet@chpc.brc.utexas.edu> 
Date: 16 Sep 88 20:48:00 CDT 
To: "jms%f29.tymnet" <jms%f29.tymnet@OFFICE-1.ARPA> 
Subject: Re: Console logging 


	The program you want is called HardCopy.  It is found on 
	Fish Disk #75 with the source in C so that you can change it
	to do what you want.  It currently does what the PHOTO did on
	the old Decsystem-20's,  logging all terminal I/O to a file to
	print later, while still letting you see the prompts.


			Ray.  (It is also on the GoldFish Disk #3)

     \-----------------------------------------------------------/
     \ Ray Howard                      Bitnet: C072ERH@UTARLG    /
     \                                         C072ERH@UTARLVM1  /
     \ "IBM s*cks silicon" --- Banana JR. PC from Bloom County   /
     \      Internet: c072erh%utarlg.decnet@chpc.brc.utexas.edu  /
     \===========================================================/

From: Joe Smith <JMS@F29.TYMNET> 
Date: Wed, 21 Sep 88 0:00:37 PDT 
To: rokicki@polya.stanford.edu 
Subject: Got BlitLab 

Thanks for sending me BlitLab - it arrived Tuesday morning.

The manual was well written, but there are a few things you might
want to add.

  1) On page Blitter-6, "...+A~A~B+..." should be "...+A~B~C+...".
  2) Same page, near "A+B", add "The quickest way to clear out that
     big long formula is to select anywhere within the function
     string gadjet, then hold the right Amiga key and press the 'X' key."
  3) On page Blitter-9, just before the heading "Copying Arbitrary Regions",
     add "Be sure to toggle 'DESC' back to '(desc)' before proceeding."

Again, thanks for the wonderful examples.

+-----------------------------------------------------------------------------+
| TYMNET: JMS@F29  CA:"POPJ P,"  UUCP: {ames|pyramid}oliveb!tymix!antares!jms |
| INTERNET: JMS%F29.Tymnet@Office-1.ARPA   PHONE: Joe Smith @ (408)922-6220   |
+-----------------------------------------------------------------------------+
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 21 Sep 88 0:53:51 PDT
Received: from polya.Stanford.EDU by OFFICE-1.ARPA; 21 Sep 88 00:52:09 PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA09534; Wed, 21 Sep 88
	00:51:45 PDT
Return-path: <@OFFICE-1.ARPA:rokicki@polya.Stanford.EDU> 
From: Tomas G. Rokicki <rokicki@polya.Stanford.EDU> 
Date: Wed, 21 Sep 88 00:51:45 PDT 
To: JMS%F29.TYMNET@OFFICE-1.ARPA 
Message-id: <8809210751.AA09534@polya.Stanford.EDU> 
Subject: Re: Got BlitLab 

Thanks for the comments on the manual!  Glad you liked it.  Now to fix
up dfc some more . . .

Received: from OFFICE-1.ARPA by F29.Tymnet; Sat, 24 Sep 88 10:47:20 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 24 Sep 88 10:43:54 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Sat 24 Sep 88
	10:42:47-PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA11535; Sat, 24 Sep 88
	08:55:22 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:ali@polya.Stanford.EDU> 
From: Ali T. Ozer <ali@polya.Stanford.EDU> 
Date: Sat, 24 Sep 88 08:55:22 PDT 
To: amiga@score 
Message-id: <8809241555.AA11535@polya.Stanford.EDU> 
Subject: 1.3 


Here's a message about 1.3 from Carolyn Scheppner (of Commodore)... 
amiga.dev/main #4248, from cscheppner, 758 chars, Fri Sep 16 11:11:28 1988
Comment(s).
----------

TITLE:	>>>  1.3 Released to Production   <<<

   I have been asked to make the announcement that 1.3 Workbench and Extras
have been released to Production.  I can't supply a date on when Enhancer
kits will be in the stores or available through CATS, but the manuals are
being printed right now, so you should be seeing them quite soon.

   I will be uploading the few files which changed between Omega 9 and
Release to amiga.com and amiga.update listings areas as soon as I get myself
a copy of Release.

   We would like to thank all of our developers who participated in the
Beta/Gamma/Omega-testing of 1.3, especially those who provided quick and
valuable feedback by downloading and using each version as it was posted to
the closed listings areas.

Received: from OFFICE-1.ARPA by F29.Tymnet; Tue, 27 Sep 88 11:37:47 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 27 Sep 88 11:33:58 PDT
Received: from polya.Stanford.EDU by SCORE.STANFORD.EDU with TCP; Tue 27 Sep 88
	11:31:48-PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA16873; Tue, 27 Sep 88
	11:32:38 PDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:rokicki@polya.Stanford.EDU> 
From: Tomas G. Rokicki <rokicki@polya.Stanford.EDU> 
Date: Tue, 27 Sep 88 11:32:38 PDT 
To: amiga@score 
Message-id: <8809271832.AA16873@polya.Stanford.EDU> 
Subject: VSO application 

We still need one more student signature for the Voluntary Student
Organization, or we won't have BADGE this year.  Anyone back on
campus yet?  Stop by CIS 072 (second floor) and sign the application
on my desk.  Thanks!                                         -tom
Received: from OFFICE-1.ARPA by F29.Tymnet; Fri, 30 Sep 88 14:33:50 PDT
Received: from polya.Stanford.EDU by OFFICE-1.ARPA; 30 Sep 88 14:29:49 PDT
Received: by polya.Stanford.EDU (5.59/25-eef) id AA14865; Fri, 30 Sep 88
	14:30:43 PDT
Return-path: <@OFFICE-1.ARPA:rokicki@polya.Stanford.EDU> 
From: Tomas G. Rokicki <rokicki@polya.Stanford.EDU> 
Date: Fri, 30 Sep 88 14:30:43 PDT 
To: JMS%F29.TYMNET@OFFICE-1.ARPA 
Message-id: <8809302130.AA14865@polya.Stanford.EDU> 
Subject: Re: Change in mailing address. 

Okay, I'll try and get the UUCP address to work . . .

-tom
Received: from OFFICE-1.ARPA by F29.Tymnet; Wed, 28 Sep 88 12:09:58 PDT
Received: from Score.Stanford.EDU by OFFICE-1.ARPA; 28 Sep 88 12:06:05 PDT
Received: from ATHENA by SCORE.STANFORD.EDU with TCP; Wed 28 Sep 88
	12:04:47-PDT
Received: by ATHENA.MIT.EDU (5.45/4.7) id AA16007; Wed, 28 Sep 88 15:05:22 EDT
Received: by M4-167-1.MIT.EDU (5.45/4.7) id AA20843; Wed, 28 Sep 88 15:05:15
	EDT
Return-path: <@OFFICE-1.ARPA, @Score.Stanford.EDU:willus@ATHENA.MIT.EDU> 
From: <willus@ATHENA.MIT.EDU> 
Date: Wed, 28 Sep 88 15:05:12 EDT 
To: amiga@score.stanford.edu 
Message-id: <8809281905.AA20843@M4-167-1.MIT.EDU> 
Subject: "Hi there. I was wondering if anybody"... 

Hi there.
	I was wondering if anybody knew where I could get some
source code that acts as a template for adding a task to the
system when a diskette is inserted or ejected.  Can someone
help me out?  Thanks.
-Will Menninger, willus@portia
  From: Joe Smith <JMS@F29.TYMNET> 
Date: Fri, 30 Sep 88 0:55:07 PDT 
To: amiga-request@score.stanford.edu 
Cc: rokicki@polya.stanford.edu 
Subject: Change in mailing address. 

I will no longer be able to receive the Amiga mailing list at
JMS%F29.Tymnet@Office-1.ARPA because Office-1 will be shut down 1-Oct-88.
My uucp address is:
+-----------------------------------------------------------------------------+
| TYMNET: JMS@F29  CA:"POPJ P,"  UUCP: {ames|pyramid}oliveb!tymix!antares!jms |
| INTERNET: closed for renovations         PHONE: Joe Smith @ (408)922-6220   |
+-----------------------------------------------------------------------------+
    )Sy\½