Received: from F26.Tymnet.COM by F74.Tymnet.COM; Mon, 5 Feb 90 20:02:24 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Tue, 6 Feb 90 4:00:22 UT
Return-path: <NSC.L/HANSON@EMSTXS.Ontyme.Tymnet> 
From: NSC.L/HANSON@EMSTXS.Ontyme.Tymnet 
Date: 06 FEB 90 00:20:42 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M11461@Ontyme.Tymnet 
Subject: "BT TYMNET INC. INTEROFFICE MEMORANDUM"... 

                              BT TYMNET INC.

                          INTEROFFICE MEMORANDUM



     MEMO NO:      RDS-014

     DATE:         February 5, 1990

     TO:           All Employees

     FROM:         Payroll

     SUBJECT:      Automatic Deposits

     -----------------------------------------------------------------


     It is expected that input for automatic deposits will be
     completed week ending 2/9/90.  It will be two to three weeks
     from that date before the actual deposit to your account begins.

     If automatic deposit does not begin by March 2nd, call Payroll
     at (408) 922-6216, (408) 922-6369 or (408) 922-6415 and we will
     follow up on it for you.

     bw
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Tue, 13 Feb 90 20:03:09 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Wed, 14 Feb 90 4:00:22
	UT
From: NSCMS.B/BURDICK@EMSTXS.Ontyme.Tymnet 
Date: 14 FEB 90 00:28:01 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I33502@Ontyme.Tymnet 
Subject: EXECUTIVE ROAD TOUR 
Resent-from: Joe Smith <JMS@F74.Tymnet.COM> (NSC.J/SMITH@Ontyme) 
Resent-date: Tue, 13 Feb 90 20:12:06 PST 
Resent-to: Monitor Group <JMS>, Carl, Osman, Craig Fletcher <Fletcher@gemini> 
Resent-cc: Harry Matthews <NSC.H/Matthews@Ontyme> 
ExecutiveRoadTour: 

PR INFO...PR INFO...PR INFO...PR INFO...PR INFO...PR INFO...PR INFO...




TO:		All BT Tymnet Employees

FROM:	Corporate Communications

DATE:		February 14, 1990

RE:		Executive Road Tour


Dear Colleagues,

The challenges facing us, both individually and collectively, have never been
greater.  From only three short months ago, weUve completely reorganized the
structure of the company, faced a significant reduction in our staffing, and are
now refocusing this company to become a world leader in communications services.

Each of you has been affected by these changes, where through working on aspects
of the integration with British Telecom, identifying synergies in our
operations, or working on constructing the world wide network infrastructure.  I
would like the opportunity to discuss these challenges with you and therefore
invite you to attend one of the following sessions.


		LOCATION				DATE

		Switzerland				Feb. 20th
		France				Feb. 21st
		Germany				Feb. 22nd
		Sweden				Feb. 23rd
		U.K.					Feb. 24th
		New York				Feb. 27th
		Rockville				Feb. 28th
		Chicago				Mar. 1st
		Irvine					Mar. 2nd
		San Jose				Mar. 5th
		Hong Kong				Mar. 12th
		Australia				Mar. 15th		



I look forward to seeing you there.

Best Regards,


							
Mark Baker
President and CEO
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Thu, 5 Apr 90 15:20:33
	PDT
From: NSCMS.B/BURDICK@EMSTXS.Ontyme.Tymnet 
Date: 05 APR 90 23:00:01 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I52203@Ontyme.Tymnet 
Subject: Human Resources - Organization Change 
HumanResources-OrganizationChange: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      05 APR 90  14:53                            MARKETING

TO>        All Employees

COPIES>    

FROM>      Mark Baker


SUBJECT>   Human Resources - Organization Change


-----------------------------------------------------------------------


In line with our long standing intentions, Ian Waterhouse returns to his
duties in the UK effective June 1st.  I am pleased to confirm that Kay
Childs is appointed Vice President Human Resources, effective April 1st.
In addition, following Chris Hickley's intended departure, Mary Jane Wheble
is appointed HR Manager-East, also effective April 1st.

I would like to take this opportunity to congratulate Kay and Mary Jane
on their new appointments and also to thank Ian for his tremendous contribution
to BT Tymnet during this important period and to express our best wishes
for his future.


Mark Baker
President and CEO
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 13 Apr 90 2:01:24
	PDT
From: BTE.MKTG@EMSTXS.Ontyme.Tymnet 
Date: 13 APR 90 09:19:17 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: S36298@Ontyme.Tymnet 
Subject: BT TYMNET NEW ADDRESS IN FRANCE 

 
 
 
       II   M   M  PPP    OO   RRR  TTTTT   A    N   N  TTTTT
       II   MM MM  P  P  O  O  R  R   T    A A   NN  N    T
       II   M M M  PPP   O  O  RRR    T   AAAAA  N N N    T
       II   M   M  P      OO   R  R   T   A   A  N  NN    T
                                    
 
                            !!!!!!!!!!!!!!!
                               !!!!!!!!!
                                 !!!!!!
                                   !!
 
                           AS OF MAY 2, 1990
 
               BT TYMNET EUROPE, BRITISH TELECOM FRANCE &
 
                         BRITISH TELECOM INT'L
 
                       WILL CHARED NEW PREMISES:
 
                                    
 
                            35 rue de Paris
 
                             92100 BOULOGNE
 
                                 FRANCE
 
                                    
 
                         TEL # 331 47 12 57 00
 
                         FAX # 331 47 12 08 22
 
                            TELEX # 633 286
 
                                    
 
            EMPLOYEES' PHONE EXTENSIONS WILL BE NOTICED SOON
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Thu, 19 Apr 90 16:31:29
	PDT
From: NSCMS.B/BURDICK@EMSTXS.Ontyme.Tymnet 
Date: 20 APR 90 00:29:35 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I57240@Ontyme.Tymnet 
Subject: PLEASE FORWARD TO ALL EMPLOYEES - FINANCIAL ORGANIZATION 
FinancialOrganization: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      19 APR 90  16:17                            MARKETING

TO>        All Employees

COPIES>    Kay Childs
            Mark Baker

FROM>      Lawrence Foulds
            Chief Financial Officer


SUBJECT>   Financial Organization


-----------------------------------------------------------------------


I am delighted to announce the Financial Organization effective April 1, 
1990. Reporting to me are John Elbert, Vice President of Finance; Carlos
Servera, Director of Financial Services; Linda Smith, Senior Section Manager
Export/Import Compliance; Richard Hungerford, Manager, MIS Development;
Michelle Camillo, Manager, MIS and Fred Canning, Manager, MIS Production.

In John Elbert's organization continuing to report to him are Jim Johnson,
Director, Financial Planning; Lynne Hanson, Director, Accounting; Ellen
Martino, Manager, Asset Accounting, and Virginia Diraison, Executive Secretary
and an open position for Manager Real Estate and Network Facilities. New
appointments are Mike Tipton, Director of Facilities and Procurement Services
and Mark Lauver, Executive Staff. John will act for me in any absence from
the office.

Reporting to Carlos Servera in Financial Services are Cami Ashton, Manager,
Contracts Administration, Credit, Collections & Accounts Receivables; Debbie
Mullin, Manager of Billing & Commissions; and Allan Gainey, Manager of 
ACS/EDI/Card Services Finance.

I am confident that the new organization will provide strong support for 
BT Tymnet in reaching it's goals and objectives in the coming year.

Lawrence Foulds
Chief Financial Officer
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 20 Apr 90 11:30:10
	PDT
From: NSCMS.B/BURDICK@EMSTXS.Ontyme.Tymnet 
Date: 20 APR 90 18:42:16 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I57446@Ontyme.Tymnet 
Subject: NORTH AMERICAN ORGANISATION - DISTRIBUTE IMMEDIATELY 
NorthAmericanOrganisation: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      20 APR 90  10:40                            MARKETING

TO>        All BT Tymnet Employees

COPIES>    

FROM>      Public Relations


SUBJECT>   North American Organisation


-----------------------------------------------------------------------


NORTH AMERICAN ORGANISATION



The following announcement was made today by David Dey, Managing Director,
Communications Systems Division, in London via a videoconference link to the New
York Office:

"On the successful completion of his assignment to British Telecom Inc, Mike
Ford is returning to the United Kingdom on 30 April to take up an appointment as
Director Special Projects, reporting to David Dey. Mike will be involved in the
development of the new organisation through Project Sovereign. He will also
retain line management responsibility for CTG Canada and remain on the Board of
Mitel. As a result of Mike's move, the following appointment is announced.

Mark Baker is appointed President, British Telecom Inc, effective 1 May 1990, in
addition to his responsibilities as President and CEO of BT Tymnet."

In his remards to the company's senior managers who were present, David Dey
stressed that British Telecom Inc will continue as a business unit and will
grow, and he emphasised the strategic importance of a strong BT presence in New
York. He also stressed that the change in President did not mean that BT Inc was
to be folded into Tymnet. 

During the course of the year, plans will be developed to bring together BT
Tymnet and BT Inc into a single British Telecom trading company in USA under
Mark Baker, with the aim of providing the best possible interface with our US
customers for all BT services and products. This new company has the working
title of "British Telecom USA Inc". This coming together would run parallel to
the organisational changes in the UK. In the meantime, joint teams will be
established to ensure coordination of particular activities, eg Human Resources
and Treasury activities, where this is already in effect.

He also stated that a new Executive Vice President, British Telecom Inc will be
appointed very shortly, based in New York, to manage the day to day activities
of the company, reporting to Mark Baker. All those currently reporting to Mike
Ford  will report to the EVP.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 20 Apr 90 12:28:19
	PDT
From: NSCMS.B/BURDICK@EMSTXS.Ontyme.Tymnet 
Date: 20 APR 90 20:09:08 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I57495@Ontyme.Tymnet 
Subject: URGENT - HOLD ON DISTRIBUTION OF NORTH AMERICAN ORGANISATION 
URGENT-HOLDONNORTHAMERICANORGANISATIONMESSAGE: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      20 APR 90  12:06                            MARKETING

TO>        ALL *** Supervisors

COPIES>    Mark Baker

FROM>      Public Relations - Internal Communications


SUBJECT>   URGENT - HOLD ON NORTH AMERICAN ORGANISATION MESSAGE


-----------------------------------------------------------------------


PLEASE DO NOT DISTRIBUTE TO EMPLOYEES THE MESSAGE REGARDING THE NORTH
AMERICAN ORGANISATION!!!!

DO NOT DISTRIBUTE UNTIL FURTHER NOTICE!!!

THANK YOU.

BARBARA BURDICK, NSCMS.B/BURDICK
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 23 Apr 90 8:41:38
	PDT
From: NSCMS.S/VOTH@EMSTXS.Ontyme.Tymnet 
Date: 23 APR 90 16:15:17 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I57802@Ontyme.Tymnet 
Subject: Please send to all your account users - Thanks 
Arbor/EarthDay: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      23 APR 90  08:14                            MARKETING

TO>        supervisors

COPIES>    

FROM>      Corporate Communications


SUBJECT>   Arbor/Earth Day


-----------------------------------------------------------------------




In an effort to support our local community and broaden public awareness of
Earth Day, BT Tymnet's Public Relations Dept. has contributed a small gift of
five European Birch Trees to the San Jose Beautiful Parks and Recreation
Department for the 1990 Earth/International Arbor Day celebration on Sunday,
April 22nd.  As the city is currently experiencing a drought alert, these trees
will be stored and cared for at the City's greenhouse on 6th and Empire until
November when they will then be planted in the Civic Center area.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Thu, 26 Apr 90 18:27:59
	PDT
From: NSCMS.B/BURDICK@EMSTXS.Ontyme.Tymnet 
Date: 27 APR 90 02:16:11 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I59575@Ontyme.Tymnet 
Subject: Performance Sharing Program 
PerformanceSharingProgram: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      26 APR 90  18:13                            MARKETING

TO>        All BT Tymnet Employees

COPIES>    Kay Childs

FROM>      Internal Communications


SUBJECT>   Performance Sharing Program


-----------------------------------------------------------------------


Watch your mail for the announcement of the new Performance Sharing Program!!
This important package will tell you all about "Being the Best Through Team
Work"!! Climb the ladder of success, being the best together!
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 4 May 90 20:47:23
	PDT
From: NSCMS.B/BEACHLE@EMSTXS.Ontyme.Tymnet 
Date: 04 MAY 90 23:57:34 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I62510@Ontyme.Tymnet 
Subject: PLEASE DISTRIBUTE TO ALL EMPLOYEES 
BritishTelecomExecutiveVPnamed: 

Date:	May 4, 1990

To:	All BT Tymnet Employees

From:	Internal Communications

Subject:        British Telecom Executive VP named


British Telecom today announced the appointment of Lawrence "Laurie" Huntley  as
the Executive Vice President of British Telecom Inc. to manage the day-to-day
activities of the company.  Huntley was the former Director of Sales for British
Telecom International in the UK.  He reports to Mark Baker, who recently added
the position of President of British Telecom Inc to his responsibilities as
President of BT Tymnet. 

The appointment follows the departure of Michael L. Ford, former President of
British Telecom Inc., who will be returning to the U.K. to take up an
appointment as Director of Special Projects, reporting to David Dey, Managing
Director of BT's Communications Systems Division. Ford has headed up BT's New
York offices and its North American international services operation since
1986.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 4 May 90 20:47:31
	PDT
From: NSCMS.B/BEACHLE@EMSTXS.Ontyme.Tymnet 
Date: 05 MAY 90 00:02:43 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I62512@Ontyme.Tymnet 
Subject: PLEASE DISTRIBUTE TO ALL EMPLOYEES 
BTINC.MARKCOMMMERGER: 

DATE:	MAY 4, 1990

TO:	ALL BT TYMNET EMPLOYEES

FROM:	INTERNAL COMMUNICATIONS

SUBJECT:	BT INC.MARK COMM MERGER

	
MARK BAKER, PRESIDENT OF BT TYMNET & BT INC., IS PLEASED TO ANNOUNCE THE MERGER
OF THE MARKETING COMMUNICATIONS AREAS OF BRITISH TELECOM INC. AND BT TYMNET.
THIS MOVE WILL HELP TO STRENGTHEN THE CORPORATE COMMUNICATIONS DEPARTMENT AND TO
PRESENT A COORDINATED APPROACH TO THE MARKETPLACE.

EFFECTIVE IMMEDIATELY, JONATHAN OGILVIE, DIRECTOR OF MARKETING COMMUNICATIONS IN
NEW YORK, WILL REPORT TO JUDI SASSALI, DIRECTOR OF CORPORATE COMMUNICATIONS.
THIS POSITIVE STEP MOVES THE TWO COMPANIES CLOSER TO A UNIFIED APPROACH TO OUR
CUSTOMERS.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 7 May 90 18:19:54
	PDT
From: NSCMS.B/BURDICK@EMSTXS.Ontyme.Tymnet 
Date: 08 MAY 90 01:47:51 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I63166@Ontyme.Tymnet 
Subject: Please Distribute To All employees 
InternalCommunications: 

Date: 	May 4, 1990

To:       	All BT Tymnet Employees

From:    	Barbara Burdick, Public Relations Manager

Subject:   	Internal Communications

I am pleased to announce the appointment of Bea Baechle, Internal Communications
Specialist, effective April 23.   Within BT Tymnet's Corporate Communications
department, Bea is responsible for communi-cating company news and employee
accomplishments worldwide in this newly created position.   Bea is interested in
your story ideas, editorial inputs, employee recognition letters, and ANY
newsworthy information to broaden the scope of employee communications around
the world.  

She joins BT Tymnet after six years of employee communications and community
relations with General Electric. Her communications background is augmented by
two years of experience as sales manager coordinating the telemarketing and
corporate sales efforts of the San Jose Symphony.  Please join me in welcoming
Bea in her new appointment.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 11 May 90 12:01:01
	PDT
From: NSCMS.B/BAECHLE@EMSTXS.Ontyme.Tymnet 
Date: 11 MAY 90 19:38:37 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I65006@Ontyme.Tymnet 
Subject: PLEASE DISTRIBUTE TO ALL EMPLOYEES 
BENEFITSQUESTIONS: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      11 MAY 90  11:37                            MARKETING

TO>        ALL BT TYMNET EMPLOYEES

COPIES>    KAY CHILDS

FROM>      INTERNAL COMMUNICATIONS


SUBJECT>   BENEFITS QUESTIONS


-----------------------------------------------------------------------


If you've called the Bts Group lately, you've probably encountered a
frustrating phenomena -- "full" voice mailboxes!

The Benefits Group is currently receiving over 80 calls each day. During the
transition to new, more "your-choice" oriented benefits programs and a brand new
HRIS/Payroll System, they have encountered both technical problems and more
employee questions than anticipated.

To allow the Benefits Group to complete implementation and answer employee
questions, specific hours have been designated to respond to your questions in
the Benefits Office:  10 a.m. - Noon and 1 - 3 p.m.(PST), Monday through
Friday.

While the Benefits Group wants to address your questions personally, they
suggest that you first try calling the appropriate Benefit Provider at the 800
number listed below with basic questions.  This will enable the Benefits Group
to be more available to quickly research and resolve more difficult problems for
you.  

Benefit forms are available in the Building "F" lobby.  You may also drop off
completed forms with the receptionist in Bldg. "F".

Your Benefits Group is working diligently to complete implementation of our
plans, including:  Debbie Metcalf, responsible for all plans; Mary Kaverman,
responsible for insured plan enrollment and billing; and their most recent
addition, Lourie Campos, who is responsible for the Savings Plan and Flex
Spending Plan.

Your support and patience are appreciated.  The Benefits Group believes the new
plans are worth both!


MetLife Basic  - (800)338-4187

MetLife HMO    - (800)334-4638

T. Rowe Price  - (800)922-7526
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 21 May 90 19:44:12
	PDT
From: NSCMS.B/BAECHLE@EMSTXS.Ontyme.Tymnet 
Date: 22 MAY 90 03:15:52 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I68653@Ontyme.Tymnet 
Subject: General Manager Pacific Named 
GeneralManagerPacificNamed: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      21 MAY 90  19:14                            MARKETING

TO>        All BT Tymnet Employees

COPIES>    Kay Childs

FROM>      Internal Communications


SUBJECT>   General Manager Pacific Named


-----------------------------------------------------------------------


Art Parsons, Senior Vice President of Sales and Marketing, is pleased
to announce the appointment of Thomas "Tommy" Arnett as the General Manager of
the Pacific Rim, effective immediately.  The Pacific Rim territory will include
the growing markets of Asia, Australia and the Middle East.

Tommy brings 10 years of Tymnet experience to the job, three of which were spent
in the Pacific Rim.  His strong international sales experience will be an asset
in this position, which reports to Jim Patty, Vice President of International
Sales and Support.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 4 Jun 90 10:34:46
	PDT
From: NSCMS.B/BAECHLE@EMSTXS.Ontyme.Tymnet 
Date: 04 JUN 90 18:17:53 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I73286@Ontyme.Tymnet 
Subject: Please distribute to all employees, s. (As usual with org
	announcements) 
NewQualityDirectorNamed: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      04 JUN 90  10:15                            MARKETING

TO>        All BT Tymnet Employees

COPIES>    Kay Childs

FROM>      Internal Communications


SUBJECT>   New Quality Director Named


-----------------------------------------------------------------------


Mark Baker, President of BT Tymnet, Inc., is very pleased to announce the
appointment of Steve Poppe as Director of Quality, reporting directly to him as
of today, June 4.

Steve brings eight years of Tymnet experience to the job.  Prior to his most
recent position as the Executive Advisor reporting to Al Fenn, Steve has served
as the Manager of Management Sciences, Manager of Network Analysis & Design,
Manager of Communication Services, and Technical Book Boss on the V.A.
proposal.

"I plan to set BT Tymnet firmly on the track of perpetually improving quality
and reducing the cost of quality," said Steve.  Please join Mark in
congratulating Steve on his new appointment.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Tue, 12 Jun 90 20:58:05
	PDT
From: NSCMS.A/FORSYTHE@EMSTXS.Ontyme.Tymnet 
Date: 12 JUN 90 23:41:00 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I76791@Ontyme.Tymnet 
Subject: ARTICLE DEADLINE 
DEADLINEFORCUSTOMERNEWSLETTER: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      12 JUN 90  15:40                            MARKETING

TO>        THE WORLD

COPIES>    

FROM>      ANNE FORSYTHE


SUBJECT>   DEADLINE FOR CUSTOMER NEWSLETTER


-----------------------------------------------------------------------


THE DEADLINE APPROACHETH . . .


The deadline for articles for the Fall issue of the customer newsletter is
drawing nigh.  June 25th is just around the corner and I'm on the lookout for
articles of interest to our customers (remember them?). 

I'd like to get a variety of articles so anyone from Payment Systems, EDI or
Dialcom who's interested in informing our customers of these areas, please feel
free to call me at (408) 922-7558.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 20 Jul 90 16:13:24
	PDT
From: NSCMS.B/BAECHLE@EMSTXS.Ontyme.Tymnet 
Date: 20 JUL 90 23:53:30 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I89885@Ontyme.Tymnet 
Subject: Please forward the message to all employees. 
VoicesforInternalVideo: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      20 JUL 90  15:51                            MARKETING

TO>        THE WORLD

COPIES>    Judie Sassali

FROM>      Bea Baechle


SUBJECT>   Voices for Internal Video


-----------------------------------------------------------------------



A T T E N T I O N  all talented employees who speak a second language
fluently!!!  (Or the co-workers who might volunteer the shy ones!)

BT Tymnet is producing an internal video that will kick off the training to our
Global Network Services (GNS).  We are looking for employees who either work in
or who will be visiting San Jose in August to do a quick VOICE-OVER of, "I've
got a latitude attitude," in their second language. While the voices are
speaking the slogan, a map will be shown lighting up the different places on the
globe.

The video will convey that we are all working as one global team. If you or
anyone you know can join the fun, please call Bea Baechle, (408) 922-6763 ASAP!
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Wed, 25 Jul 90 15:48:16
	PDT
From: NSCMS.B/BAECHLE@EMSTXS.Ontyme.Tymnet 
Date: 25 JUL 90 23:16:19 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I91413@Ontyme.Tymnet 
Subject: Please distribute to all employees - ASAP - hard copies didn't make
	it! 
ProductManagement: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      25 JUL 90  15:15                            MARKETING

TO>        All Employees

COPIES>    Kay Childs

FROM>      Internal Communications


SUBJECT>   Product Management


-----------------------------------------------------------------------


The following announcement describes the structure of the Product Management
Organization under Ron Bamberg, who is temporarily filling the position of Vice
President of Product Management, reporting to Mark Baker.  Ron continues as Vice
President of Business Development & Planning.

Product Management

Reporting to Ron in this capacity are:
	
Rick Sprenkel - Manager of Applications Product Support
Scott Cary - Manager of Messaging Products
Rand Walker - Manager of EDI Products
Tom Welsh - Acting Manager of Card Services Products
Lana Vaysburd - Director of Network Product Management

Network Product Management

Areas of responsibility under Lana are:

Mike Rebmann - Program Management
Bob Barbour - Network Product Technical Support
Kurt Bauer -  Network Management & Hardware Platforms
Karen Slater -  Special Projects
Lana Vaysburd - Transport Services & Communication Interfaces
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Thu, 2 Aug 90 10:51:12
	PDT
From: NSCMS.JUDIES@EMSTXS.Ontyme.Tymnet 
Date: 02 AUG 90 18:23:58 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I94267@Ontyme.Tymnet 
Subject: Please forward to all users in your respective accounts 
BTTymnetTRADEMARKPROCEDURES: 

TO:  All Employees

FROM:  Judie Sassali

DATE:  August 2, 1990

SUBJECT:  BT Tymnet TRADEMARK PROCEDURES



Following are the procedures that must be exercised within BT Tymnet for any
requested BT Tymnet trademark search.  Effective immediately, all requests must
be submitted to Janet Spinks in the Corporate Communications Department, where
they will be formulated and submitted in the correct format to Carol Scribner in
the BT Tymnet Law Department.  Carol will then folow British Telelcom procedure
and work with an outside firm and the trademark department within British
Telecom plc.  BT Tymnet's Law Department has been informed that no requests will
be submitted unless processed through the Corporate Commuications Department
first.  Please feel free to call Janet Spinks, Promotional Services Manager,
with any questions or concerns regarding trademark procedures for BT Tymnet Inc.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 6 Aug 90 10:51:03
	PDT
From: NSCMS.S/VOTH@EMSTXS.Ontyme.Tymnet 
Date: 06 AUG 90 18:12:26 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I95187@Ontyme.Tymnet 
Subject: Please send to all your account. Thanks 
NewVicePresidentProductManagement: 

________________________________________ INTERNAL COMMUNICATIONS MEMORANDUM

Date    :        August 6, 1990
To      :        All Employees
From    :        Mark Baker
Re      :        New Vice President Product Management
__________________________________________________________________________

        I am pleased to announce Michael Charles as the new Vice President
Product Management, effective August 6, reporting directly to me.

        Mike brings 20 years of IBM experience to the position, with a 
demonstrated record of accomplishment directing marketing, planning, sales,
finance, general administration and MIS functions for major divisions of 
IBM both domestically and internationally.
        
        The following functions report to Mike:
        
        Director of Network Product Management  -       Lana Vaysburd
        Applications Product Management         -       Rick Sprenkel
        Messaging Products                      -       Scott Carey
        EDI Products                            -       Rand Walker
        Card Services Products                  -       Tom Welsh

        I am sure you will join me in welcoming Mike to BT Tymnet and 
give him every support in his task.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Wed, 15 Aug 90 9:16:07
	PDT
From: NSCMS.L/FRANCHINO@EMSTXS.Ontyme.Tymnet 
Date: 15 AUG 90 16:32:08 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I98725@Ontyme.Tymnet 
Subject: NEW PHONE NUMBERS FOR NEW JERSEY OFFICE 
NEWPHONENUMBERSFORNEWJERSEYOFFICE: 

                             B T   T Y M N E T
                                     
                            M E M O R A N D U M
                                     
                                                                 MARKETING
                                                                 AND SALES
DATE>     15 AUG 90
 
TO>       THE WORLD
 
COPIES>   
          
FROM>     LARAINE FRANCHINO
 
SUBJECT>  NEW PHONE NUMBERS FOR NEW JERSEY OFFICE
 
---------------------------------------------------------------------------
 
THE NEW JERSEY OFFICE IS HAVING A NEW PHONE SYSTEM INSTALLED ON FRIDAY,
AUGUST 17TH.  CUTOVER TO NEW NUMBERS WILL BE AFTER 5:00 P.M.
 
THE FOLLOWING IS A LIST OF NEW NUMBERS, EFFECTIVE MONDAY, AUGUST 20TH:
 
          201/438-2300   MAIN NUMBER
          201/438-7520   FAX  NUMBER
          
          SALES
          -----
          
          201/438-7516   GREG TOOMBS
          201/438-7515   CESAR NERYS
          201/438-7512   LOREN WASSERMAN
          201/438-7513   JIM COYLE
          201/438-7510   LEAH SETZER
          201/438-7511   MARIA KULNIS
          
          
          TECHNICAL
          ----------
          
          201/438-7509   RALPH SETZER
          201/438-7507   TOM SAMPSON
          201/438-7508   LEN PARCHMENT
          201/438-7504   MARY ANNE STEINIS
          201/438-7506   SHEK SETO
          201/438-7503   ELIZABETH IANIERI
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Fri, 17 Aug 90 13:58:37
	PDT
From: NSCMS.L/FRANCHINO@EMSTXS.Ontyme.Tymnet 
Date: 17 AUG 90 21:16:05 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I99980@Ontyme.Tymnet 
Subject: CORRECTION TO LYNDHURST, NEW JERSEY PHONE NUMBERS 
CORRECTIONTONEWPHONENUMBERSFORLYNDHURST, NEWJERSEYOFFICE: 

                             B T   T Y M N E T
                                     
                            M E M O R A N D U M
                                     
                                                                 MARKETING
                                                                 AND SALES
DATE>     17 AUG 90
 
TO>       THE WORLD
 
COPIES>   
          
FROM>     LARAINE FRANCHINO
 
SUBJECT>  CORRECTION TO NEW PHONE NUMBERS FOR LYNDHURST, NEW JERSEY OFFICE
 
---------------------------------------------------------------------------
 
THERE IS A CORRECTION TO PREVIOUS ONTYME.  MAIN NUMBER BEGINS WITH THE 438
PREFIX, HOWEVER, THE DIRECT DIAL NUMBERS AND FAX NUMBER WILL BEGIN WITH THE
804 PREFIX.  THIS IS EFFECTIVE MONDAY, AUGUST 20TH.
 
PLEASE NOTE THE FOLLOWING CORRECTIONS:
 
          201/438-2300   MAIN NUMBER
          201/804-7520   FAX  NUMBER
          
          SALES
          -----
          
          201/804-7516   GREG TOOMBS
          201/804-7515   CESAR NERYS
          201/804-7512   LOREN WASSERMAN
          201/804-7513   JIM COYLE
          201/804-7510   LEAH SETZER
          201/804-7511   MARIA KULNIS
          
          
          TECHNICAL
          ----------
          
          201/804-7509   RALPH SETZER
          201/804-7507   TOM SAMPSON
          201/804-7508   LEN PARCHMENT
          201/804-7504   MARY ANNE STEINIS
          201/804-7506   SHEK SETO
          201/804-7503   ELIZABETH IANIERI
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Tue, 21 Aug 90 17:02:54
	PDT
From: NSCMS.B/BAECHLE@EMSTXS.Ontyme.Tymnet 
Date: 22 AUG 90 00:40:25 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I01195@Ontyme.Tymnet 
Subject: Please send to "The World." Thanks!!!!! 
GLOBALLINKDEBUT: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      21 AUG 90  16:39                            MARKETING

TO>        THE WORLD

COPIES>    Barbara Burdick

FROM>      Bea Baechle


SUBJECT>   GLOBAL LINK DEBUT


-----------------------------------------------------------------------


 
NEWS FLASH!!!      
INTERNAL NEWSLETTER EVOLVES INTO THE GLOBAL LINK!!!


A new name, a new look!  The BT Tymnet internal employee newsletter has changed
names and design to reflect our expanding horizons around the world, including
coverage of BT Inc., based in New York. The Networking News has become THE
GLOBAL LINK.

Look for The Global Link in your mailbox. If you do not receive one this week,
please contact me via electronic mail.

What has not changed, is the reason why the newsletter is printed:  to inform
you, to recognize individual and group efforts, and to broaden your awareness of
the many facets of the company.  I rely on YOUR news tips and YOUR expertise in
the area where you work.  Thanks in advance for your ideas and contributions!
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 20 Aug 90 16:13:52
	PDT
From: NSCMS.B/BAECHLE@EMSTXS.Ontyme.Tymnet 
Date: 20 AUG 90 23:39:28 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I00677@Ontyme.Tymnet 
Subject: Organization 
Organization: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      20 AUG 90  15:38                            MARKETING

TO>        All Employees

COPIES>    Kay Childs

FROM>      R.C.M. Baker


SUBJECT>   Organization


-----------------------------------------------------------------------


     Al Fenn has accepted a position with the BT Business Development Unit based
in London, reporting to Colin Williams, Director of Business Development,
effective, August 20, 1990.  Al will be moving to the U.K. initially, with
future location to be confirmed in due course.

   I know that you will all join me in congratulating Al on his new appointment,
which is an important step in developing the global capability of British
Telecom.    

   Our thanks to Al for his great contribution to the Tymnet business, and we
wish him all the success in the future.

   Until further notice the following organizational changes become effective:

1)  Bill Euske - Vice President, Network Technology Development,
will report directly to me.

2)  Bob Tomasi - Vice President, Operations, will report directly to me.

3)  Terry Donaher has accepted the position of Vice President, 
Information Services, reporting to Lawrence Foulds. This will include MIS
activities and management of the BT Tymnet Data Centers in Fremont, Rockville
and Irvine.

4) The Applications Development organizations reporting to Terry Donaher will be
integrated as appropriate into NTD. Terry will project manage this transition
during the next few weeks.

5) B.J. Chang will report to Bill Euske.


R.C.M. Baker
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Thu, 13 Sep 90 7:41:12
	PDT
From: NSCMS.L/FRANCHINO@EMSTXS.Ontyme.Tymnet 
Date: 13 SEP 90 15:02:31 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I08942@Ontyme.Tymnet 
Subject: NEW PHONE NUMBERS FOR LYNDHURST, NEW JERSEY OFFICE 
NEWPHONENUMBERSFORLYNDHURST, NEWJERSEYOFFICE: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      13 SEP 90  09:51                            MARKETING

TO>        NSC.SUPS

COPIES>    

FROM>      LARAINE FRANCHINO


SUBJECT>   NEW PHONE NUMBERS FOR LYNDHURST, NEW JERSEY OFFICE


-----------------------------------------------------------------------


ON AUGUST 17TH, I SENT A CORRECTED ONTYME REGARDING THE NEW PHONE NUMBERS
FOR THE LYNDHURST, NEW JERSEY OFFICE.  APPARENTLY, NOT ALL ACCOUNT USERS
ARE AWARE OF THIS CORRECTION.  

McDONNELL DOUGLAS RECEPTIONIST IS KEEPING A DAILY LOG OF ALL CALLS FOR
TYMNET COMING IN ON THE OLD NUMBER.  MANY OF THESE CALLS ARE FROM
CORPORATE HEADQUARTERS.

COULD YOU PLEASE RESEND THE FOLLOWING INFORMATION TO ALL ACCOUNT USERS.

THANK YOU!




LARAINE FRANCHINO

************************************************************************

                            -B T   T Y M N E T
                                     
                            M E M O R A N D U M
                                     
                                                                 MARKETING
                                                                 AND SALES
DATE>     17 AUG 90
 
TO>       THE WORLD
 
COPIES>   
          
FROM>     LARAINE FRANCHINO
 
SUBJECT>  CORRECTION TO NEW PHONE NUMBERS FOR LYNDHURST, NEW JERSEY OFFICE
 
---------------------------------------------------------------------------
 
THERE IS A CORRECTION TO PREVIOUS ONTYME.  MAIN NUMBER BEGINS WITH THE 438
PREFIX, HOWEVER, THE DIRECT DIAL NUMBERS AND FAX NUMBER WILL BEGIN WITH THE
804 PREFIX.  THIS IS EFFECTIVE MONDAY, AUGUST 20TH.
 
PLEASE NOTE THE FOLLOWING CORRECTIONS:
 
          201/438-2300   MAIN NUMBER
          201/804-7520   FAX  NUMBER
          
          SALES
          -----
          
          201/804-7516   GREG TOOMBS
          201/804-7515   CESAR NERYS
          201/804-7512   LOREN WASSERMAN
          201/804-7513   JIM COYLE
          201/804-7510   LEAH SETZER
          201/804-7511   MARIA KULNIS
          
          
          TECHNICAL
          ----------
          
          201/804-7509   RALPH SETZER
          201/804-7507   TOM SAMPSON
          201/804-7508   LEN PARCHMENT
          201/804-7504   MARY ANNE STEINIS
          201/804-7506   SHEK SETO
          201/804-7503   ELIZABETH IANIERI
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Tue, 25 Sep 90 16:55:59
	PDT
From: NSCMS.A/FORSYTHE@EMSTXS.Ontyme.Tymnet 
Date: 25 SEP 90 23:18:18 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I12964@Ontyme.Tymnet 
Subject: PLEASE SEND TO ALL EMPLOYEES 
DEADLINEFORARTICLESANDNEWNAMEFORCUSTOMERNEWSLETTER: 

                              BT TYMNET

                         M E M O R A N D U M

                                                       SALES AND
DATE>      25 SEP 90  15:17                            MARKETING

TO>        THE WORLD

COPIES>    

FROM>      ANNE FORSYTHE - EDITOR
            ABOUT NETWORKING


SUBJECT>   DEADLINE FOR ARTICLES AND NEW NAME FOR CUSTOMER NEWSLETTER


-----------------------------------------------------------------------


The deadline for articles for BT Tymnet's new customer newsletter is TUESDAY,
OCTOBER 16TH.  Dubbed "About Networking", the newsletter covers all products and
services of networking, electronic transaction services, EDI, Dialcom and
British Telecom, Inc. (Did I forget anyone?  There are so many areas these days
. . .)

The purpose of the customer newsletter is, obviously, to keep our customers
informed of BT Tymnet's latest and greatest services and products.  But we
discuss other pertinent issues as well in the newsletter, such as regulatory
issues, market research results, management programs that directly affect
customers, executive changes, new offerings, user group meetings and results,
industry standards, product progress, new management strategies, contract wins,
technical training, etc.  We want to give our customers a well-rounded view of
BT Tymnet.

That's where you come in.  I always need fresh ideas from employees, especially
now since we're one, big, happy family.  The scope of About Networking has
broadened considerably and I know there are talented employees out there just
panting to have an article published.  And listen, you don't have to be an ace
writer.  I can interview you and get the story or you can write the article and
I'll edit it.  I'll try to make it easy for you!  

So if you're working on something you think customers should know or would be
interested in, OR, if you know someone else who is, please give me a call at
(408) 922-7558 or send me a message via OnTyme at NSCMS.A/FORSYTHE.  REMEMBER,
THE DEADLINE IS OCTOBER 16TH.
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Wed, 12 Dec 90 4:21:05
	PST
From: BTE.SUP@EMSTXS.Ontyme.Tymnet 
Date: 12 DEC 90 11:47:11 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: (64 names) 
Message-id: S62220@Ontyme.Tymnet 
Subject: ENOPS MOVE 
ENOPSMOVE: 

================================ MEMORANDUM =================================

                         BRITISH TELECOM TYMNET  EUROPE

DATE>      12 DEC 90  10:17

TO>        TO WHOM IT MAY CONCERN

COPIES>    

FROM>      ENOPS


SUBJECT>   ENOPS MOVE


-----------------------------------------------------------------------





PLEASE NOTE THE EUROPEAN NETWORK OPERATIONS  (ENOPS)  WILL MOVE

FROM MONDAY 17TH DECEMBER 1990 AT 8:00 GMT.



NEW TELEPHONE NUMBER IS :     (331) 47 28 92 60

NEW FAX NUMBER IS        :    (331) 47 28 49 45

NEW TELEX NUMBER IS      :    613750F   BTYSAV


================================ MEMORANDUM =================================

                         BRITISH TELECOM TYMNET  EUROPE

DATE>      12 DEC 90  10:17

TO>        TO WHOM IT MAY CONCERN

COPIES>    

FROM>      ENOPS


SUBJECT>   ENOPS MOVE


-----------------------------------------------------------------------





PLEASE NOTE THE EUROPEAN NETWORK OPERATIONS  (ENOPS)  WILL MOVE

FROM MONDAY 17TH DECEMBER 1990 AT 8:00 GMT.



NEW TELEPHONE NUMBER IS :     (331) 47 28 92 60

NEW FAX NUMBER IS        :    (331) 47 28 49 45

NEW TELEX NUMBER IS      :    613750F   BTYSAV
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 6 May 91 3:25:07
	PDT
From: BTE.SUP@EMSTXS.Ontyme.Tymnet 
Date: 06 MAY 91 11:13:17 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: (114 names) 
Message-id: S73407@Ontyme.Tymnet 
Subject: NMC (ENOPS) - 8 TO 10 MAY 
NMC(ENOPS)-8TO10MAY: 

================================ MEMORANDUM =================================

                         BRITISH TELECOM TYMNET  EUROPE

DATE>      06 MAY 91  12:05

TO>        THE WORLD

COPIES>    

FROM>      ENOPS


SUBJECT>   NMC (ENOPS) -8 TO 10 MAY


-----------------------------------------------------------------------


IN RESPECT OF COOPERATION FOR THE MILAN RELOCATION OF NODES; NMC (ENOPS)
WILL BE OPEN FROM 8 TO 10 MAY.

BEST REGARDS,

ENOPS ( JEAN-MICHEL, FRANCK ).
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Thu, 16 May 91 6:16:29
	PDT
From: BTE.SUP@EMSTXS.Ontyme.Tymnet 
Date: 16 MAY 91 13:56:57 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: S74161@Ontyme.Tymnet 
Subject: BANK HOLIDAY 
BANKHOLLIDAYONMAYTHE20TH.: 

================================ MEMORANDUM =================================

                         BRITISH TELECOM TYMNET  EUROPE

DATE>      16 MAY 91  14:49

TO>        THE WORLD

COPIES>    

FROM>      ENOPS


SUBJECT>   BANK HOLLIDAY ON MAY THE 20TH.


-----------------------------------------------------------------------


PLEASE, BE INFORMED THAT ENOPS WILL BE CLOSED ON NEXT MONDAY
(MAY THE 20TH) DUE TO A BANK HOLLIDAY.

BEST REGARDS,

ENOPS ( arturo, jean-michel, franck ).
   D g