Received: from D35.Tymnet by F29.Tymnet; Fri, 23 Sep 88 14:07:47 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 23 Sep 88 14:00:27 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 22 SEP 88 22:09:24 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A49839@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 22 Sep 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 09/22/88     1900     Tp           Forward accounting records
 Thursday                           from secondary collection
                                    to primary collection
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 09/23/88   0000-0330  Bellopatrick ASP dump                    F30
 Friday                Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Fri, 23 Sep 88 14:07:56 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 23 Sep 88 14:00:44 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 23 SEP 88 21:56:13 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A50289@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 23 Sep 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
                           N   O   T   I   C   E   S
===============================================================================
   Attn: All....Andy Yee will be out of town from Sunday 9/25 thru Friday
   9/30.  All CICS problems should be directed to St. Louis CICS contact.
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 09/23/88   2230       Tp           EDCSTOP for early batch     EDC
 Friday                Scheduler    processing
 
           ___________ ____________ ___________________________ __________ _____
            2300-0500  Bellopatrick ASP dump                    F33
                       Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 09/24/88   0000-0100  Bellopatrick ASP dump                    X32
 Saturday              Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            0100-0500  Cromwell     1) Install 3380's           F45
                       IBM          2) Update UCW for 3033      F87
                                    3) IPL system with new GEN
                                       and test 3380's
           ___________ ____________ ___________________________ __________ _____
            0100-0500  Cromwell     Verify UCW for VM System
                       IBM
           ___________ ____________ ___________________________ __________ _____
            0200       Cromwell     Initiate all file backups
                       Ortiz
           ___________ ____________ ___________________________ __________ _____
            1600-2100  Bellopatrick ASP dump                    F74
 
 
            ** NOTE...(ACCOUNTING BEFORE SYSTEM COMES DOWN)
 
           ___________ ____________ ___________________________ __________ _____
            1800-2130  Bellopatrick ASP dump                    F26
 
 
            ** NOTE...(BACKUP STARTS AT 1500)
                      (ACCOUNTING BEFORE SYSTEM COMES DOWN)
 
           ___________ ____________ ___________________________ __________ _____
            2230       Tp           EDCSTOP for early batch     EDC
                       Scheduler    processing
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 09/25/88   0100-0500  Cromwell     1) Install 3350's           F45
 Sunday                Richardson   2) IPL System and test      F87
                                       3350's
 
           ___________ ____________ ___________________________ __________ _____
            0200       Cromwell     Initiate all msg backups
                       Ortiz
           ___________ ____________ ___________________________ __________ _____
            2300-0130  Bellopatrick Asp dump                    F58
                       Cromwell
 
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 09/26/88   0000-0330  Bellopatrick ASP dump                    F22
 Monday                Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            Process of batch request for payroll tape(s) and
            deliver to MVS/VM Console operator
           ___________ ____________ ___________________________ __________ _____
            Payroll tape transmission - prior to 2200 each Monday
 _______________________________________________________________________________
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Wed, 28 Sep 88 14:08:53 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 28 Sep 88 14:00:27 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 27 SEP 88 22:16:14 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A51609@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 27 Sep 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 09/27/88   2100-0230  Bellopatrick ASP dump                    F38
 Tuesday               Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 09/28/88   0200-0400  Cromwell     PM on Node 5513             ND5513
 Wednesday             Richardson
 
           ___________ ____________ ___________________________ __________ _____
            0800-0900  Marcotte     IPL system to install       F45
                       Lira         updated version of INVOKE
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Thu, 29 Sep 88 14:04:31 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Thu, 29 Sep 88 14:00:29 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 28 SEP 88 23:08:33 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A52182@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 28 Sep 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 09/28/88   1800-2000  Bellopatrick PM on Node 7173             ND7173
 Thursday              Richardson   (Backup for NETVAL)
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 09/29/88   0200-0400  Cromwell     PM on Node 3067             ND3067
 Thursday              Richardson   (Payment Systems Collector)
 
           ___________ ____________ ___________________________ __________ _____
            0230-0330  Scheduler    To Split EDC control files  EDC
                       Barton
 
           ___________ ____________ ___________________________ __________ _____
            0300-0500  Cromwell     PM on Node 2324             ND2324
                       Richardson
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Fri, 30 Sep 88 14:06:52 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 30 Sep 88 14:00:28 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 30 SEP 88 00:30:02 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A52662@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 29 Sep 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 09/29/88   1800-2300  Bellopatrick Ops to copy out packs       F26
 Thursday              Cromwell     260000 (unit 301) B1
                       Richardson   260008 (unit 341) B1
                                           to
                                    disk drive A1
           ___________ ____________ ___________________________ __________ _____
            1800-?     Bellopatrick Start full dump on F1087
                       Cromwell     using set #8
                       Fischer
 
            ** Note..Final backup to be taken on the 30th after shutting the
               System at 2400 **
           ___________ ____________ ___________________________ __________ _____
            1800-?     Bellopatrick Start full dump on F1088
                       Cromwell     using set #5
                       Fischer
 
            ** Note..Final backup to be taken on the 30th after shutting the
               System at 2400 **
           ___________ ____________ ___________________________ __________ _____
            1800-?     Bellopatrick Start full dump on F1643
                       Cromwell     using set #6
                       Fischer
 
            ** Note..Final backup to be taken on the 30th after shutting the
               System at 2400 **
           ___________ ____________ ___________________________ __________ _____
            2000-2100  Bellopatrick Move to 1St backup          HS1304
                       Le-ngo
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 09/30/88   0000-0200  Cromwell     PM on node 6162             ND6162
 Friday                Richardson
 
           ___________ ____________ ___________________________ __________ _____
            0000-0330  Bellopatrick ASP dump                    F30
                       Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            Midshift   Cromwell     Change Oper Password
 
 
           ___________ ____________ ___________________________ __________ _____
            0200-0400  Cromwell     PM on Node 7274             ND7274
                       Richardson
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Sat, 1 Oct 88 14:04:10 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 1 Oct 88 14:00:32 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 30 SEP 88 22:08:21 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A52996@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 30 Sep 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 09/30/88   1600-2100  Bellopatrick FSC to check out DASD A1    F74
 Friday                Richardson
 
             ** NOTE:  BACKUP BEFORE SYSTEM GOES DOWN **
 
           ___________ ____________ ___________________________ __________ _____
            1800-2300  Bellopatrick Ops to copy out packs       F26
                       Cromwell     260000 (unit 301) B1
                       Richardson   260008 (unit 341) B1
                                           to
                                    disk drive A1
           ___________ ____________ ___________________________ __________ _____
              1900     Tp           Forward accounting records
                                    from secondary collection
                                    to primary collection
           ___________ ____________ ___________________________ __________ _____
            2300-0500  Bellopatrick ASP dump                    F33
                       Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/01/88   0000-0100  Bellopatrick ASP dump                    X32
 Saturday              Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            0200       Cromwell     Initiate all file backups
                       Le-ngo
           ___________ ____________ ___________________________ __________ _____
            1600-2100  Bellopatrick ASP dump                    F74
 
 
            ** NOTE...(ACCOUNTING BEFORE SYSTEM COMES DOWN)
                      (BACKUP BEFORE SYSTEM GOES DOWN)
 
           ___________ ____________ ___________________________ __________ _____
            1800-2130  Bellopatrick ASP dump                    F26
 
 
            ** NOTE...(BACKUP STARTS AT 1500)
                      (ACCOUNTING BEFORE SYSTEM COMES DOWN)
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/02/88   0100-0200  Tp           1) Implementation of MIM 7  CONB2
 Sunday                Yee          2) COMTEN Reload (FTT007A)
 
           ** Note **
                     Make sure MIM 0 through 7 are switched onto the
                     COMTEN box before the reload.
           ______ ____________ ___________________________ __________ _____
            0200       Cromwell     Initiate all msg backups
                       Le-ngo
           ___________ ____________ ___________________________ __________ _____
            2300-0130  Bellopatrick Asp dump                    F58
                       Cromwell
 
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/03/88   0000-0330  Bellopatrick ASP dump                    F22
 Monday                Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            0200-0400  Cromwell     PM on Node 3111             ND3111
                       Richardson
 
           ___________ ____________ ___________________________ __________ _____
            0400-0630  Tp           BOS maintenance             BOS
                       Bolain
 
            ** NOte ** Terry will call TP to bring BOS down.  If he is
                       unable to work on 10/3, he will work on 10/4 from
                       0400-0630 **
           ___________ ____________ ___________________________ __________ _____
            Process of batch request for payroll tape(s) and
            deliver to MVS/VM Console operator
           ___________ ____________ ___________________________ __________ _____
            Payroll tape transmission - prior to 2200 each Monday
 _______________________________________________________________________________
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Mon, 3 Oct 88 14:04:54 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Mon, 3 Oct 88 14:00:24 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 03 OCT 88 21:55:25 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A53925@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 03 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/03/88   2300-0200  Bellopatrick ASP dump                    B39
 Monday                Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/04/88   0000-0230  Bellopatrick ASP dump                    F29
 Tuesday               Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            0100-0200  Cromwell     Swap Host 5514 from node    NETVAL
                                    "A" to node "B"
 
           ___________ ____________ ___________________________ __________ _____
            0400-0630  Tp           BOS maintenance             BOS
                       Bolain
 
            ** NOte ** Terry will call TP to bring BOS down.
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Wed, 5 Oct 88 14:03:45 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 5 Oct 88 14:00:23 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 04 OCT 88 23:42:28 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A54574@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 04 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/04/88   1800-2300  Bellopatrick FSC to check out DASD B1    F26
 Tuesday               Richardson
 
           ___________ ____________ ___________________________ __________ _____
            1900-2300  Terry        FSC to check out Fan in the B39
                       Richardson   CPU
 
           ___________ ____________ ___________________________ __________ _____
            2000-2100  Tp           Recycle TCICS170            TCICS170
 
           ___________ ____________ ___________________________ __________ _____
            2100-0230  Bellopatrick ASP dump                    F38
                       Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Thu, 6 Oct 88 14:04:48 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Thu, 6 Oct 88 14:00:24 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 05 OCT 88 22:55:03 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A55022@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 05 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/05/88   1800-2400  Terry        ALT PATH DASD 436           ALT PATH
 Wednesday             Cromwell
                       Richardson
 
               Insure: 1) That there is no valid data on 436
                       2) 436 is OFFLINE TO MVS/F87, MVS/F45 & VM/F40
                      THEN:
                       1) V PATH(420-43F,1),OFFLINE TO MVS/F87
                       2) V CH(4,1),OFFLINE TO MVS/F87
                       3) V CH(B),OFFLINE TO MVS/F45
                       4) DISABLE 'A & B' INTERFACES AT 3674 CU #2
                       5) NOTIFY FSC
                WHEN FSC RETURNS THE DRIVE.
                       1) ENABLE 'A & B' INTERFACES AT 3674 CU #2
                       2) V CH(4,1),ONLINE TO MVS/F87
                       3) V PATH(420-43F,1),ONLINE TO MVS/F87
                       4) V CH(B),ONLINE TO MVS/F45
               IMPACT:  ALT PATHS TO CH4 DASD ON MVS UNAVAILABLE
               ONSITE:  FSC CE
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Fri, 7 Oct 88 14:05:06 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 7 Oct 88 14:00:30 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 06 OCT 88 23:10:31 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A55575@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 06 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/06/88   1800-2300  Terry        1)  FSC to do more checking F26
 Thursday              Richardson       on DASD B1
                                    2) Copy out units 307/347
                                        from H1 ---> B1 if B1
                                        check out ok or to B2
 
            ** Note ** Have FSC check out B2 before coping out H1
 _________ ___________ ____________ ___________________________ __________ _____
            1800-2400  Terry        ALT PATH DASD 436 and 43D   ALT PATH
                       Cromwell
                       Richardson
 
               Insure: 1) That there is no valid data on 436 and 43D
                       2) 436 and 43D are OFFLINE TO MVS/F87, MVS/F45 & VM/F40
                      THEN:
                       1) V PATH(420-43F,1),OFFLINE TO MVS/F87
                       2) V CH(4,1),OFFLINE TO MVS/F87
                       3) V CH(B),OFFLINE TO MVS/F45
                       4) DISABLE 'A & B' INTERFACES AT 3674 CU #2
                       5) NOTIFY FSC
                WHEN FSC RETURNS THE DRIVE.
                       1) ENABLE 'A & B' INTERFACES AT 3674 CU #2
                       2) V CH(4,1),ONLINE TO MVS/F87
                       3) V PATH(420-43F,1),ONLINE TO MVS/F87
                       4) V CH(B),ONLINE TO MVS/F45
               IMPACT:  ALT PATHS TO CH4 DASD ON MVS UNAVAILABLE
               ONSITE:  FSC CE
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Fri, 7 Oct 88 14:05:24 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 7 Oct 88 14:01:03 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 07 OCT 88 21:41:25 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A55974@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 07 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/06/88   1800-2300  Terry        1)  FSC to check out DASD   F26
 Friday                Richardson       B1 and H1
                                    2)  Run full DSKCLN
 
           ___________ ____________ ___________________________ __________ _____
            2300-0500  Terry        ASP dump                    F33
                       Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/08/88   0000-0100  Terry        ASP dump                    X32
 Saturday              Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            0200       Cromwell     Initiate all file backups
                       Le-ngo
           ___________ ____________ ___________________________ __________ _____
            1600-2100  Terry        ASP dump                    F74
 
 
            ** NOTE...(ACCOUNTING BEFORE SYSTEM COMES DOWN)
                      (BACKUP BEFORE SYSTEM GOES DOWN)
 
           ___________ ____________ ___________________________ __________ _____
            1800-2130  Terry        ASP dump                    F26
 
 
            ** NOTE...(BACKUP STARTS AT 1500)
                      (ACCOUNTING BEFORE SYSTEM COMES DOWN)
 
           ___________ ____________ ___________________________ __________ _____
            2100-0100  Terry        VM DASD PM                  F40
                       Cromwell
                       Richardson
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/09/88   0100-0200  Tp           Comten Reload (FTT007B)     CONB2
 Sunday                Yee
 
            ** Note ** Remote access to MVS systems will be unavailable.
           ___________ ____________ ___________________________ __________ _____
            0200       Cromwell     Initiate all msg backups
                       Le-ngo
           ___________ ____________ ___________________________ __________ _____
            2300-0130  Terry        Asp dump                    F58
                       Cromwell
 
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/10/88   0000-0330  Terry        ASP dump                    F22
 Monday                Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            Process of batch request for payroll tape(s) and
            deliver to MVS/VM Console operator
           ___________ ____________ ___________________________ __________ _____
            Payroll tape transmission - prior to 2200 each Monday
 _______________________________________________________________________________
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Tue, 11 Oct 88 14:04:35 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Tue, 11 Oct 88 14:00:30 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 10 OCT 88 22:15:32 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A56760@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 10 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/10/88   1800-2400  Terry        ALT PATH DASD 436 and 43D   ALT PATH
 Monday                Richardson
 
               Insure: 1) That there is no valid data on 436 and 43D
                       2) 436 and 43D are OFFLINE TO MVS/F87, MVS/F45 & VM/F40
                      THEN:
                       1) V PATH(420-43F,1),OFFLINE TO MVS/F87
                       2) V CH(4,1),OFFLINE TO MVS/F87
                       3) V CH(B),OFFLINE TO MVS/F45
                       4) DISABLE 'A & B' INTERFACES AT 3674 CU #2
                       5) NOTIFY FSC
                WHEN FSC RETURNS THE DRIVE.
                       1) ENABLE 'A & B' INTERFACES AT 3674 CU #2
                       2) V CH(4,1),ONLINE TO MVS/F87
                       3) V PATH(420-43F,1),ONLINE TO MVS/F87
                       4) V CH(B),ONLINE TO MVS/F45
               IMPACT:  ALT PATHS TO CH4 DASD ON MVS UNAVAILABLE
               ONSITE:  FSC CE
           ___________ ____________ ___________________________ __________ _____
            2100       Tp           EDCSTOP for early batch     EDC            d
                       Scheduler    processing                                 h
 
           ___________ ____________ ___________________________ __________ _____
            2300-0200  Terry        ASP dump                    B39
                       Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/11/88   0000-0030  Carta        Switch System 'B' from      F45
 Tuesday                            MG2 to MG1
 
           ___________ ____________ ___________________________ __________ _____
            0000-0230  Terry        ASP dump                    F29
                       Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            0030-0400  Terry        MVS DASD PM                 F087
                       Cromwell                                 F45
                       Richardson
 
                                    Run UCC11MNT
 
                                    1) bring down F45MVS
                                    2) drain all initiators on F87
                                    3) run 'S ARTSINIT'
                                    4) reply '(ARTS)MP'
                                    5) run 'S UCC11MNT'
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Wed, 12 Oct 88 14:04:41 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 12 Oct 88 14:00:28 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 11 OCT 88 23:56:12 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A57224@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 11 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/11/88   1800-2300  Terry        FSC to do more checking on  F26
 Tuesday               Richardson   DASD B1 and H1
 
           ___________ ____________ ___________________________ __________ _____
            2100-0230  Terry        ASP dump                    F38
                       Cromwell
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Thu, 13 Oct 88 14:04:50 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Thu, 13 Oct 88 14:00:30 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 12 OCT 88 22:25:04 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A57653@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 12 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/12/88   2000-2100  Tp           Recycle CICS170             CICS170
 Wednesday             Yee
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from D35.Tymnet by F29.Tymnet; Fri, 14 Oct 88 14:05:01 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 14 Oct 88 14:00:30 PDT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 13 OCT 88 22:52:46 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A58035@Ontyme.Tymnet 
Subject: Special / Scheduled Events 

DATE> 13 Oct 88
 
FROM> Sue Pal
 
 
CC>   Computer Operations
      System Quality Control Office
      Technical Support
      Irvine Computer Operations
 
SUBJ> Special / Scheduled Events
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
===============================================================================
             S C H E D U L E D   /    S P E C I A L    E V E N T S
            ........................................................
 
  Date         Time/     Responsible        Description           System(s)
              Status     Person                                  Unavailable
 _________ ___________ ____________ ___________________________ __________ _____
 10/13/88   2000-2200  Terry        Move to 1St backup          HS7154
 Thursday              Ortiz
 
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
 10/14/88   0000-0330  Terry        ASP dump                    F30
 Friday                Cromwell
 
           ___________ ____________ ___________________________ __________ _____
            0000-0500  Terry        PM                          B39
                       Cromwell
                       Richardson
 _________ ___________ ____________ ___________________________ __________ _____
  Comments:
 
 
 _______________________________________________________________________________
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Fri, 1 Sep 89 20:05:37 PDT
Received: from EMSFSC.Ontyme.Tymnet by F26.Tymnet.COM; Sat, 2 Sep 89 3:04:50 UT
Return-path: <FSC.P/DWIGHT@EMSFSC.Ontyme.Tymnet> 
From: FSC.P/DWIGHT@EMSFSC.Ontyme.Tymnet 
Date: 01 SEP 89 15:51:25 
To: FSC.JM/SMITH@EMSFSC.Ontyme.Tymnet 
Message-id: P63223@Ontyme.Tymnet 
Subject: mon5 



     PLEASE POST ON ALL BULLETIN BOARDS:

     WEEK FIVE: - September 5, 1989

                            BERT NOVAK WEEKLY UPDATE


     Q:   I am very concerned about my retirement benefits, particularly in
          regard to the medical health care.  I want to work as long as I can
          and put in for retirement at the last possible moment before my
          business unit is actually taken over by another company.  At what
          point in time can I do that?

     A:   An employee who is eligible to retire (age 55 and 10 years of
          Credited service) can make his/her decision to retire on the last day
          prior to the divestiture.  A delay in making that decision may cause
          delay in the receipt of the first month's retirement check.  As with
          other divestitures, we will work with you to assure all items
          necessary to facilitate the retirements will be in order.

     Q:   I am concerned that the sale of the business unit will be announced
          and I will not be able to put in for retirement under the ERIP of
          MDISC.  Will there be a window of time from the time the sale is
          announced and the time I can still retire under MDISC?

     A:   See above response.

     Q:   If another company buys MDFSCO, how soon is the retirement package
          void?  If I am age 55+ and vested, will I have 30 days after
          announcement to make decision or must I apply now?

     A:   If you are vested you have a non-forfeitable right to receive the
          benefit you have earned under the Plan.  The "retirement package"
          cannot be voided.  To leave the payroll as a retiree you must apply
          for retirement prior to termination.

     Q:   If a person is age 54 now, but will be 55 and vested in 1990, can
          he/she write a letter of intent to retire now, with the company
          honoring it if sold within 12 months?

     A:   No.  The employee must be 55 and have at least 10 years of Credited
          Service as of the divestiture date to retire under the terms of the
          Pension Plan.

     Q:   I have been with the company seven years.  MDISC ERIP is going to 5
          year vesting on 11-17-89.  What happens if my business unit is sold
          in October?  Am I not vested on 11-17-89?  Do I begin again?

     A:   To clarify the question first, MDISC ERIP is going to 5-year cliff
          vesting on 27 November 1989, not 17 November.  In either case, the
          vesting of the ERIP will be a matter of discussion during
          negotiations between buyer and MDC.

                                    -more-

     Page 2

     Q:   What happens to my money in the Savings Plan when the business unit
          is sold?  Will my money in the 401K be distributed to me?

     A:   After the appropriate documentation has been filled out by the
          employee (regarding tax withholding), the money in the Savings Plan
          (401K and after-tax) will be distributed to the employee.

     Q:   If my Savings Plan monies are distributed to me, is this considered a
          lump sum distribution?  Can I therefore roll the taxable portion over
          into an IRA or other tax deferred vehicle?  What about paying taxes
          on it?

     A:   If your distribution is tied to the divestiture and you are an
          employee on that date, your distribution will be considered a lump
          sum distribution and eligible for rollover.  If you roll that
          distribution into a qualified tax deferred vehicle within 60 days of
          date of that distribution, you will not be taxed on that until it is
          distributed from that account.

     Q:   I read somewhere that when a company buys out another, the assets in
          the Savings  Plan can be taken over and the money used by the new
          owners for any expenditure.  Is that true?

     A:   We do not allow any Plan to Plan transfer in our Savings Plan.  At
          this time your money will be distributed to you.  Also, I am not
          aware of any case where another company can use your savings
          contributions for any expenditures.

     Q:   Will I receive the company matching funds in which I am vested?  What
          about the non-vest funds?  Due to the circumstances, will I be vested
          in those?

     A:   If you are an employee on the date of the divestiture and your
          termination is due to that divestiture or retirement, all company
          contributions will be vested and therefore distributed to you.

     Q:   Since the MDC Travel Company has provided poor corporate service and
          even worse personal service to employees, will we be contracting with
          a new travel agency after divestiture?

     A:   Yes.

          COMMENT:

          We will have a "firm" number by Tuesday, September 4, 1989 from
          Lodestar and we will then be working with our financial backers to
          respond to John McDonnell's offer.  Because of the confidentiality
          commitments, we cannot make the number public at this time.  Field
          Service has until mid-September to respond to McDonnell Douglas with
          an offer.



     Bert
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Thu, 2 Nov 89 20:05:49 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Fri, 3 Nov 89 4:00:30 UT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 02 NOV 89 22:39:57 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A85892@Ontyme.Tymnet 
Subject: ON CALL LIST ** PLEASE POST AT MVS CONSOLE AND IN SQC OFFICE 

DATE> 02 Nov 89
 
FROM> Sue Pal
 
TO>   MVS Computer Operations
      System Quality Control
 
CC>   Mike Bellopatrick
      Rick Daniels
      Bill Fischer
      Tech Support
      Ontyme Support
      Bonnie Terry
      Pete Acosta
 
SUBJ> ON CALL LIST ** PLEASE POST AT MVS CONSOLE AND IN SQC OFFICE
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
     O F F H O U R S    A N D    W E E K E N D    C O V E R A G E
 
            For the period of 11/03/89 through 11/10/89
 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 FSC - Field Service Company..NOTE NEW PAGER NUMBERS
 ----                         ======================
 Until - 11/05   Amritpal Johl   Home:   (408) 274-3319
                                 Pager:  (415) 727-7372
 11/06 - 11/12   Ali Mosaffa     Home:   (408) 374-9244
                                 Pager:  (415) 727-7371
 _______________________________________________________________________________
 TYMCOM X SUPPORT
 ----------------
 Primary Contact:   Joe SMITH       Pager: (408) 977-7962
                                    Home:  (415) 790-0608
 
 Secondary Contact: Carl BALTRUNAS  Pager: (408) 977-7960
                                    Home:  (408) 945-4314
 _______________________________________________________________________________
 SUN SYSTEM SUPPORT
 ------------------
 Primary Contact:   Craig FLETCHER  Pager: (   )          Office: 83-6250
                                    Home:  (415) 838-9002 Mail Stop: C41
 
 Secondary Contact: Carl BALTRUNAS  Pager: (408) 977-7960 Office: 83-6206
                                    Home:  (408) 945-4314 Mail Stop: C53
 
 Third Contact:     Joe SMITH       Pager: (408) 977-7962 Office: 83-6220
                                    Home:  (415) 790-0608 Mail Stop: D31
 -------------------------------------------------------------------------------
 Off hours Pager number for NETVAL:
 ----------------------------------
    (408) 289 - 6403
 -------------------------------------------------------------------------------
 IDMS Database oncall List:
 -------------------------
 Frank Mills     Work: (408)922-6252,  Pager:  (408) 994-6127
 -------------------------------------------------------------------------------
 MVS System Programming Support during off hours:
 ------------------------------------------------
 Primary Contact    -    Mike Lira       Pager:  (415) 498-9590
                                         Home :  (415) 794-8332
 Secondary Contact  -    Jim Callison    Pager:  (415) 498-9893
                                         Home :  (415) 952-8332
 _______________________________________________________________________________
 VM Support On-Call List:
 ------------------------
 Pager Number .................................. (314) 424-1288
 Until   -  11/06       Ralph Howard     Work :  (314) 233-3724
                                         Home :  (314) 481-3247
 11/07   -  11/13       Jim Schwegel     Work :  (314) 233-3728
                                         Home :  (618) 466-4208
  Note...If no response within an hour contack Mike Woolcott.
                        Mike Woolcott    Pager:  (314) 823-8749
                                         Work :  (314) 233-3631
                                         Home :  (314) 458-2720
 _______________________________________________________________________________
 Ontyme Support:
 ---------------
 Until   -   11/05      Huong Le-Ngo     Pager:  (408) 994-1956
                                         Home :  (408) 945-0810
 11/06   -   11/19      Brad Dong        Pager:  (415) 884-7460
                                         Home :  (408) 274-8744
--------------------------------------------------------------------------------
 TP Support for Payment Systems:
 ------------------------------
 Dan Miller - Primary Contact .......... Pager:  (415) 498-0150
                                         Home :  (408) 984-6939
 Scott Slade............................ Home :  (714) 998-7497
 Pat Bonnie ............................ Home :  (415) 449-7699
 Irvine Operations - Customer support...         (714) 851-9660
 Sonia Cartwright - Collector problems.. Home :  (415) 490-1315
 Neema Sundernath - Next day inquiry.... Home :  (415) 794-9139
 Naeem Raza       - EDC batch problems.. Home :  (408) 749-8017
                                         Pager:  (408) 291-9024
--------------------------------------------------------------------------------
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Mon, 6 Nov 89 12:02:36 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Mon, 6 Nov 89 20:00:22
	UT
Return-path: <OPERA.D/KEITH@EMSTXS.Ontyme.Tymnet> 
From: OPERA.D/KEITH@EMSTXS.Ontyme.Tymnet 
Date: 06 NOV 89 17:22:47 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A86791@Ontyme.Tymnet 
Subject: SCHEDULED POWER OUTAGE 

                            MCDONNELL DOUGLAS
                      INFORMATION PROCESSING COMPANY
                             4340 Solar Way
                         Fremont, California 94538
                             POWER SHUTDOWN

Time and Date Scheduled Down (PST or PDT)?  22:00 (PST) 11-NOV-89
Time and Date Scheduled Up (PST or PDT)..?  10:00 (PST) 12-NOV-89

All Systems Affected (Y or N)............?  N

Other Systems (Y or N)...................?  Y

ONTYME Hosts (Y or N)....................?  Y

The following ONTYME Hosts are affected:

515(B), 832(A), 1304(C), 2256(D), 2257(F), 2258(E),
2259(G), 2260(H), 2261(I), 7148(J), 7150(K), 7152(L),
7153(M), 7154(N), 2287(O), 2288(P) and 2289(Q).

The following RAILTRACK Hosts are affected:

114, 555

The following ONTYME Utility Nodes are affected:

5321

The following OUTDIAL Hosts are affected:

 834, 919

IBM Systems (Y or N).....................?  N

TYMCOM-10's (Y or N).....................?  Y

The following TYMCOM-10's are affected:

F23, F26, F30, F33, F38, F58, F74

RAM Systems (Y or N).....................?  Y

The following RAM Systems are affected:

6914 and 6915

NETVAL Systems (Y or N)..................?  Y

The following NETVAL System is affected:

5514

SUN Servers (Y or N).....................? N

Reason:  

>PG&E TO REPLACE FAULTY POWER EQUIPMENT.

Please adjust your processing schedule as necessary.

Thank You, 
Fremont Computer Operations  <MDCISG IPC>                              
(415)498-2588 or Ontyme OPERA.BATCH
Received: from D25.Tymnet.COM by F74.Tymnet.COM; Thu, 9 Nov 89 10:39:07 PST
Return-path: <JMS@F74.Tymnet.COM> 
From: Joe Smith <JMS@F74.Tymnet.COM> (TXS.J/SMITH@Ontyme) 
Date: Thu, 9 Nov 89 10:32:06 PST 
To: Ed Barens <IPC.E/Barens@Ontyme>, Jim English <IPC.J/English@Ontyme>, Leland
	Yarbrough <IPC.L/Yarbrough@Ontyme>, Jim Zone <IPC.J/Zone@Ontyme>, John
	Roddam <IPC.J/Roddam@Ontyme> 
Subject: D25 running P035/E-1. 

The regular monitor (SYS)SYSTEM.SAV on system 25 seems to have gotten a
subtle read error which prevented it from coming up Thursday morning.  I
had Ann load from NEWMON instead.  The only change between P035/E and
P035/E-1 is a patch to fix the way the monitor handled overflow blocks
in the LUD.  This patch was mandatory for system F74, and should
eventually be installed on all systems to avoid possible problems with
LUD.SYS in the future.

		/Joe
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Fri, 10 Nov 89 12:03:17 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Fri, 10 Nov 89 20:00:35
	UT
Return-path: <IPC.S/PAL@EMSTXS.Ontyme.Tymnet> 
From: IPC.S/PAL@EMSTXS.Ontyme.Tymnet 
Date: 10 NOV 89 17:16:20 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A88446@Ontyme.Tymnet 
Subject: ON CALL LIST ** PLEASE POST AT MVS CONSOLE AND IN SQC OFFICE 

DATE> 10 Nov 89
 
FROM> Sue Pal
 
TO>   MVS Computer Operations
      System Quality Control
 
CC>   Mike Bellopatrick
      Rick Daniels
      Bill Fischer
      Tech Support
      Ontyme Support
      Bonnie Terry
      Pete Acosta
 
SUBJ> ON CALL LIST ** PLEASE POST AT MVS CONSOLE AND IN SQC OFFICE
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
     O F F H O U R S    A N D    W E E K E N D    C O V E R A G E
 
            For the period of 11/10/89 through 11/17/89
 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 FSC - Field Service Company..NOTE NEW PAGER NUMBERS
 ----                         ======================
 Unitl - 11/12   Bill Richardson Home:   (408) 867-5575
                                 Pager:  (415) 727-7441
 11/13 - 11/19   Ali Mosaffa     Home:   (408) 374-9244
                                 Pager:  (415) 727-7371
 _______________________________________________________________________________
 TYMCOM X SUPPORT
 ----------------
 Primary Contact:   Joe SMITH       Pager: (408) 977-7962
                                    Home:  (415) 790-0608
 
 Secondary Contact: Carl BALTRUNAS  Pager: (408) 977-7960
                                    Home:  (408) 945-4314
 _______________________________________________________________________________
 SUN SYSTEM SUPPORT
 ------------------
 Primary Contact:   Craig FLETCHER  Pager: (   )          Office: 83-6250
                                    Home:  (415) 838-9002 Mail Stop: C41
 
 Secondary Contact: Carl BALTRUNAS  Pager: (408) 977-7960 Office: 83-6206
                                    Home:  (408) 945-4314 Mail Stop: C53
 
 Third Contact:     Joe SMITH       Pager: (408) 977-7962 Office: 83-6220
                                    Home:  (415) 790-0608 Mail Stop: D31
 -------------------------------------------------------------------------------
 Off hours Pager number for NETVAL:
 ----------------------------------
    (408) 289 - 6403
 -------------------------------------------------------------------------------
 IDMS Database oncall List:
 -------------------------
 Frank Mills     Work: (408)922-6252,  Pager:  (408) 994-6127
 -------------------------------------------------------------------------------
 MVS System Programming Support during off hours:
 ------------------------------------------------
 Primary Contact    -    Mike Lira       Pager:  (415) 498-9590
                                         Home :  (415) 794-8332
 Secondary Contact  -    Jim Callison    Pager:  (415) 498-9893
                                         Home :  (415) 952-8332
 _______________________________________________________________________________
 VM Support On-Call List:
 Pager Number .................................. (314) 424-1288
 ------------------------
 Until   -  11/12       Ralph Howard     Work :  (314) 233-3724
                                         Home :  (314) 481-3247
 11/13   -  11/19       Jim Schwegel     Work :  (314) 233-3728
                                         Home :  (618) 466-4208
  Note...If no response within an hour contack Mike Woolcott.
                        Mike Woolcott    Pager:  (314) 823-8749
                                         Work :  (314) 233-3631
                                         Home :  (314) 458-2720
 _______________________________________________________________________________
 Ontyme Support:
 ---------------
 Until   -   11/19      Brad Dong        Pager:  (415) 884-7460
                                         Home :  (408) 274-8744
 11/20   -   12/03      Huong Le-Ngo     Pager:  (408) 994-1956
                                         Home :  (408) 945-0810
--------------------------------------------------------------------------------
 TP Support for Payment Systems:
 ------------------------------
 Dan Miller - Primary Contact .......... Pager:  (415) 498-0150
                                         Home :  (408) 984-6939
 Scott Slade............................ Home :  (714) 998-7497
 Pat Bonnie ............................ Home :  (415) 449-7699
 Irvine Operations - Customer support...         (714) 851-9660
 Sonia Cartwright - Collector problems.. Home :  (415) 490-1315
 Neema Sundernath - Next day inquiry.... Home :  (415) 794-9139
 Naeem Raza       - EDC batch problems.. Home :  (408) 749-8017
                                         Pager:  (408) 291-9024
--------------------------------------------------------------------------------
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Mon, 13 Nov 89 20:03:53 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Tue, 14 Nov 89 4:00:22
	UT
Return-path: <IPC.SRAMAIL@EMSTXS.Ontyme.Tymnet> 
From: IPC.SRAMAIL@EMSTXS.Ontyme.Tymnet 
Date: 13 NOV 89 22:07:50 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: TXS.SUP@Ontyme.Tymnet, NSC.J/SNAVELY@Ontyme.Tymnet, NSC.MIS@Ontyme.Tymnet,
	FSC.B/RICHARDSON@Ontyme.Tymnet 
Message-id: A89296@Ontyme.Tymnet 
Subject: SPECIAL EVENTS TYMCOM-X/SUN 
SPECIALEVENTSTYMCOM-X/SUN: 

                        M E M O R A N D U M

           MC DONNELL-DOUGLAS INFORMATION SYSTEMS COMPANY




DATE>      13 NOV 89  14:04

TO>        Distribution

COPIES>    

FROM>      Debbie Burns
           RPM
           (415)498-2514


SUBJECT>   SPECIAL EVENTS TYMCOM-X/SUN


-----------------------------------------------------------------------



     
     
                        SPECIAL EVENTS TYMCOM-X/SUN    
     
date      time    sys   event                              person
---------------------------------------------------------------------------
11/14     2100-   F38   1. move F38 back to home hardware. Terry 
tuesday   0330          2. ASP dump.                       Acosta
                                                           Richardson 
     
     
11/16     1800-   F26   1. FSC to check disk drive H1.     Terry 
thursday  2300                                             Richardson 
     
***make sure systems D31 & D37 are up while F26 is down.    
     
*****NOTES*****
     
                                                                Page  2

We will also be discussing the following items in Tuesdays (11/14)    
meeting at 11:30 am.
     
     
1.  Necessary steps to upgrade system F58 to prepare it for 
    D34's customer load. 
     
2.  Schedules and necessary equipment needed to bring systems    
    D34 and D56 from Dallas to Fremont. 
     
3.  Adding additional disk to F23 to house part of F58's    
    customer load.
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Mon, 13 Nov 89 20:03:53 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Tue, 14 Nov 89 4:00:22
	UT
Return-path: <IPC.SRAMAIL@EMSTXS.Ontyme.Tymnet> 
From: IPC.SRAMAIL@EMSTXS.Ontyme.Tymnet 
Date: 13 NOV 89 22:07:50 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: TXS.SUP@Ontyme.Tymnet, NSC.J/SNAVELY@Ontyme.Tymnet, NSC.MIS@Ontyme.Tymnet,
	FSC.B/RICHARDSON@Ontyme.Tymnet 
Message-id: A89296@Ontyme.Tymnet 
Subject: SPECIAL EVENTS TYMCOM-X/SUN 
SPECIALEVENTSTYMCOM-X/SUN: 

                        M E M O R A N D U M

           MC DONNELL-DOUGLAS INFORMATION SYSTEMS COMPANY




DATE>      13 NOV 89  14:04

TO>        Distribution

COPIES>    

FROM>      Debbie Burns
           RPM
           (415)498-2514


SUBJECT>   SPECIAL EVENTS TYMCOM-X/SUN


-----------------------------------------------------------------------



     
     
                        SPECIAL EVENTS TYMCOM-X/SUN    
     
date      time    sys   event                              person
---------------------------------------------------------------------------
11/14     2100-   F38   1. move F38 back to home hardware. Terry 
tuesday   0330          2. ASP dump.                       Acosta
                                                           Richardson 
     
     
11/16     1800-   F26   1. FSC to check disk drive H1.     Terry 
thursday  2300                                             Richardson 
     
***make sure systems D31 & D37 are up while F26 is down.    
     
*****NOTES*****
     
                                                                Page  2

We will also be discussing the following items in Tuesdays (11/14)    
meeting at 11:30 am.
     
     
1.  Necessary steps to upgrade system F58 to prepare it for 
    D34's customer load. 
     
2.  Schedules and necessary equipment needed to bring systems    
    D34 and D56 from Dallas to Fremont. 
     
3.  Adding additional disk to F23 to house part of F58's    
    customer load.
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Wed, 15 Nov 89 20:02:16 PST
Received: from EMSTXS.Ontyme.Tymnet by F26.Tymnet.COM; Thu, 16 Nov 89 4:00:27
	UT
Return-path: <IPC.SRAMAIL@EMSTXS.Ontyme.Tymnet> 
From: IPC.SRAMAIL@EMSTXS.Ontyme.Tymnet 
Date: 15 NOV 89 21:14:12 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A90168@Ontyme.Tymnet 
Subject: SYSTEM D34 TRANSFER TO FREMONT 
TransferofsystemD34fromDallastoFremont: 

     
                       M E M O R A N D U M - MDIPC
     
Date : November 15, 1989 
     
To   : Ed Barens       Ed Roop
       Rick Daniels    Mike Bellopatrick
       Sam Quick       Leland Yarbrough 
       Alicia Williams Bill Fischer
     
CC   : Dallas Tape Librarian  
       Fremont Tape Librarian 
       Distribution 
     
From : Debbie Burns 
       Resource Planning & Management   
     
Subj : Transfer of system D34 from Dallas to Fremont   
-------------------------------------------------------------------------- 
     
During the week of December 9 thru 16, 1989, system D34 will be  
transfered from the Dallas Data Center to the Fremont Data Center.    
During this time the following events will occur; 
     
Dallas ops            - on Saturday 12/9, take ASP dump on D34   
                        and ship overnight courier to Fremont.   
                        Take a second ASP and keep on-site, also 
                        please send hardcopy of SAVE and VERIFY. 
     
Fremont ops           - on Sunday, 12/10, load ASP tape(s) from  
                        Dallas onto old F58. 
     
Dallas ops            - do daily backups on D34 during the week  
                        of 12/9 -> 12/15 and ship backup tapes   
                        to Fremont via overnight courier to 
                        arrive next day.  (i.e. do backup on
                        Sunday to arrive on Monday, etc.)   
     
Fremont ops           - continue to load daily tapes from Dallas 
                        to old system F58 all through to week.   
     
Dallas ops            - on Friday, 12/15 @ 1600 (cst), take system    
                        D34 down and bring up as system D22 or D29.   
                        Take final all-files and ship overnight  
                        courier to Fremont.  
     
Fremont ops           - on Saturday, 12/16, load last backup tapes    
                        as soon as they arrive onto F58 and bring
                        up F58 as new system F34. 
     
Dallas Tape lib       - Please box all tapes assigned to system  
                        D34 and send UPS ground service to Fremont.   
                        These tapes should arrive in Fremont no  
                        later than Monday, 12/18.  Please be sure
                        to include tape directories.   
     
Fremont Tape lib      - Please be prepared to house an estimated 
                        500 customer tapes from Dallas for system
                        F34.  
     
Dallas ops            - Please inform Fremont Operations about   
                        any special requests or projects you
                        currently do for system D34 customers.   
     
During this time period, no validations will be done for system D34,  
until Monday, December 18, 1989.  Tapes will not be accessible for    
3 to 4 days while in transit.  The downtime for system D34 will be    
from 1600 (cst) on Friday, 12/15, until noon Saturday, 12/16, (pst).  
     
Dallas operations, please use Federal Express next day service   
for all tapes except customer tapes which should be sent UPS.    
     
If you have any questions or concerns regarding this transition, 
please call me at (415)498-2514, or send an ontyme to IPC.SRAMAIL.    
     
Thank You,
Debbie Burns   
Resource Planning & Management
Received: from D37.Tymnet.COM by F74.Tymnet.COM; Thu, 16 Nov 89 0:36:57 PST
Return-path: <JMS@F74.Tymnet.COM> 
From: Joe Smith <JMS@F74.Tymnet.COM> (TXS.J/SMITH@Ontyme) 
Date: Thu, 16 Nov 89 0:26:41 PST 
To: Ed Barens <IPC.E/Barens@Ontyme>, Jim English <IPC.J/English@Ontyme>, Leland
	Yarbrough <IPC.L/Yarbrough@Ontyme>, Jim Zone <IPC.J/Zone@Ontyme>, John
	Roddam <IPC.J/Roddam@Ontyme> 
Subject: PDP-10 support pager numbers. 

The Fremont Data Center found that it is more expedient to page me directly
instead of going through Central Dispatch.  Use these numbers instead:

	(408)922-6220  Tymcom-X Support
	(415)498-3841  TXS pager (Joe and/or Carl)
	(408)977-7962  Joe Smith's pager
	(408)977-7960  Carl Baltrunas's pager
	(415)790-0608  Joe at home
	(408)945-4314  Carl at home


 bHQe