From: Joe Smith <JMS@F74.Tymnet.COM> (TXS.J/SMITH@Ontyme) 
Date: Wed, 15 Nov 89 17:29:53 PST 
To: harry@gemini 
Subject: KS2020 hardware maintenance 

Bill Sturm told me about version 2 of the memo of understanding.
The wording about the 2020 systems needs to be changed.
I need FSCO to provide hardware maintenance for those systems continuing
until 3 months after the last PDP-10 system is decomissioned.  The
phrase "PDP-10 system" includes TRW's 2020 and any other system running
the TYMCOM-X operating system.

		/Joe
From: harry@gemini
Date: Wed, 15 Nov 89 17:29:53 PST 
To: JMS@F74
Subject: KS2020 hardware maintenance 

		    MEMORANDUM OF UNDERSTANDING
			  14 November 1989

			    Version 3.0

Joe Smith has transferred from MDFSCO to MDNSC effective November 13, 1989.
The reasons for this transfer are stated on this memorandum.  Both undersigned
parties understand and agree to the following conditions of this transfer:

    A.   On the effective date of Joe Smith's transfer:

	 1.   MDNSC will assume the responsibility of providing software
	      support to TRW who is presently contracted with MDNSC for such
	      software support services on their DEC2020.  From November 18,
	      1989 and beyond, MDNSC will not be obligated to pay MDFSCO for
	      providing TRW's software support, as presently subcontracted to
	      MDFSCO for $1600 per month.
	      
	      In orderfor MDNSC to provide this support, MDFSCO agrees to
	      provide to nominated MDNSC personell, upon reasonable
	      notification, scheduled access to the DEC 2020 test bed system,
	      which is to be in a permanent state of fully functional working
	      order until three months after the last Tymnet KL10 is de-
	      commissioned. This access shall be both electronic and physical.
	      
	 2.   MDNSC will assume responsiblity for profiding software support
	      to MDSI (Walter Kass) on their two KL10's located in St. Louis
	      until 31 December 1989, after which time it is the
	      responsibility of MDFSCO to either provide contracted services
	      to MDSI from some support organization other than MDNSC or
	      cancel the service contract with MDSI.
	      
	 3.   MDNSC will assume responsibility for providing software support
	      on those KL10's located in the Fremont, California and Dallas,
	      Texas Datacenters which are operated for Tymnet's core business.
	      There are 14 of these systems which are numbered: 23, 25, 26,
	      30, 31, 32, 33, 34, 37, 38, 54, 56, 58 and 74.
	      
	 4.   MDFSCO agrees to an asset transfer to MDNSC and MDNSC agrees to
	      assume the present depreiciation schedule on the Sun workstation
	      used by Joe Smith.
	      
	 5.   Definition - the terms KL10, PDP10, or DEC 2020 used in the MOU
	      refers to those computers running the Tymcom X operating system.

Signed by W. H. Kersten, V.P. Tech Ops. on 11-16-89.
Signed by Harry Matthews, MGR, Technical Services on 11-17-89.
