Received: from tymix.Tymnet.COM by F74.Tymnet.COM; Fri, 10 Feb 89 11:30:48 PST
Received: from SUN.COM by tymix.Tymnet.COM (5.61/1.34) id AA14032; Thu, 9 Feb
	89 18:46:41 -0800
Received: from snail.Sun.COM by Sun.COM (4.1/SMI-4.0) id AA29854; Thu, 9 Feb 89
	18:00:25 PST
Received: from sunncal.sun.com by snail.Sun.COM (4.1/SMI-4.0) id AA11083; Thu,
	9 Feb 89 17:57:07 PST
Received: by sunncal.sun.com (3.2/SMI-3.2) id AA14961; Thu, 9 Feb 89 17:46:56
	PST
Received: from bambam by metaphor.UUCP (5.51/4.7) id AA02267; Thu, 9 Feb 89
	17:51:11 PST
Received: by bambam..com (4.0/SMI-3.2) id AA00944; Thu, 9 Feb 89 17:58:07 PST
Return-path: <bambam!metaphor!lgold@Sun.COM> 
From: bambam!metaphor!lgold@Sun.COM (Lynn Gold) 
Date: Thu, 9 Feb 89 17:58:07 PST 
To: sunncal!sun!F74.Tymnet.COM!JMS@Sun.COM 
Message-id: <8902100158.AA00944@bambam..com> 
Subject: Re: Test: Does TUMS mail get routed to Berkeley.EDU 

>If this message gets out, I expect it to go from F74 to tymix.Tymnet.COM and
>from there to Berkeley (via the connection in St. Louis).
>
>		Joe Smith  (415)790-0608
>

Step two:  Did you get my reply?

--Lynn

P.S.--DON'T try to directly reply to the return address the (brain-damaged)
mailer here composes.  The CORRECT return address IS

sunncal!metaphor!lgold@sun.com

You can figure out the rest of the path from Tymnet.

P.P.S.--How are you and Sally doing these days?  I've been busy (school
started up again, I've been S*I*C*K with the garbage that's been going
around, etc.
From: Joe Smith <JMS@F74.Tymnet.COM> 
Date: Fri, 10 Feb 89 11:52:01 PST 
To: sunncal!metaphor!lgold@sun.com 
Subject: Mail did arrive. 

The header says it came from metaphor to bambam to sunncal to snail to SUN.COM
and from there it went over the newly functional MILNET link from SUN.COM to
tymix.Tymnet.COM which sent it to JMS@F74.  I see what you mean about brain
damaged mailer, "bambam..com" stuck its name where metaphor belongs.
By the time the message arrived here it said that the "to:" address was
"sunncal!sun!F74.Tymnet.COM!JMS@Sun.COM"; aint mixed addresses wonderful?

I sent the original message to figmo@mica.Berkeley.EDU after seeing your
articles in rec.music.dementia.  Does that mean you work for Sun and play at
UCB?  I am still supporting the PDP-10's (we have 16 in use) and as a side
job I'm helping Tymnet do beta testing on the file server in the Turbo Engine.

M.D. Field Service Company bought us 2 Sun 3/50 workstations, we call them
Doctor and Tardis.  When we get a uucp link going between them and antares,
then Sally will have her own account for posting news about the Steven Cannell
Fan Club in rec.arts.tv.  (Look there under the subject WISEGUY, UNSUB, or
MIAMI VICE, I can be found in comp.sys.amiga)

Sally got A's in her music history class and American history class, and is
now taking Cultural Anthropology.  With Eclecticon in Sacramento this weekend
and ORAC next weekend, she says she can't afford to get sick.

--
Joe Smith (408)922-6220 | jms@antares.Tymnet.COM or jms@opus.Tymnet.COM
McDonnell Douglas FSCO  | UUCP: ...!{ames,pyramid}!oliveb!tymix!antares!jms
PO Box 49019, MS-D21    | PDP-10:JMS@F74.Tymnet.COM  CA license plate:"POPJ P,"
San Jose, CA 95161-9019 | narrator.device: "I didn't say that, my Amiga did!"
Received: from tymix.Tymnet.COM by F74.Tymnet.COM; Fri, 10 Feb 89 12:25:57 PST
Received: from SUN.COM by tymix.Tymnet.COM (5.61/1.34) id AA16087; Thu, 9 Feb
	89 23:06:06 -0800
Received: from snail.Sun.COM by Sun.COM (4.1/SMI-4.0) id AA29854; Thu, 9 Feb 89
	18:00:25 PST
Received: from sunncal.sun.com by snail.Sun.COM (4.1/SMI-4.0) id AA11083; Thu,
	9 Feb 89 17:57:07 PST
Received: by sunncal.sun.com (3.2/SMI-3.2) id AA14961; Thu, 9 Feb 89 17:46:56
	PST
Received: from bambam by metaphor.UUCP (5.51/4.7) id AA02267; Thu, 9 Feb 89
	17:51:11 PST
Received: by bambam..com (4.0/SMI-3.2) id AA00944; Thu, 9 Feb 89 17:58:07 PST
Return-path: <bambam!metaphor!lgold@Sun.COM> 
From: bambam!metaphor!lgold@Sun.COM (Lynn Gold) 
Date: Thu, 9 Feb 89 17:58:07 PST 
To: sunncal!sun!F74.Tymnet.COM!JMS@Sun.COM 
Message-id: <8902100158.AA00944@bambam..com> 
Subject: Re: Test: Does TUMS mail get routed to Berkeley.EDU 

>If this message gets out, I expect it to go from F74 to tymix.Tymnet.COM and
>from there to Berkeley (via the connection in St. Louis).
>
>		Joe Smith  (415)790-0608
>

Step two:  Did you get my reply?

--Lynn

P.S.--DON'T try to directly reply to the return address the (brain-damaged)
mailer here composes.  The CORRECT return address IS

sunncal!metaphor!lgold@sun.com

You can figure out the rest of the path from Tymnet.

P.P.S.--How are you and Sally doing these days?  I've been busy (school
started up again, I've been S*I*C*K with the garbage that's been going
around, etc.
Received: from tymix.Tymnet.COM by F74.Tymnet.COM; Fri, 10 Feb 89 23:09:28 PST
Received: from SUN.COM by tymix.Tymnet.COM (5.61/1.34) id AA23307; Fri, 10 Feb
	89 21:10:31 -0800
Received: from snail.Sun.COM by Sun.COM (4.1/SMI-4.0) id AA20291; Fri, 10 Feb
	89 15:36:46 PST
Received: from sunncal.sun.com by snail.Sun.COM (4.1/SMI-4.0) id AA12730; Fri,
	10 Feb 89 15:33:27 PST
Received: by sunncal.sun.com (3.2/SMI-3.2) id AA20168; Fri, 10 Feb 89 15:23:13
	PST
Received: from bambam by metaphor.UUCP (5.51/4.7) id AA04394; Fri, 10 Feb 89
	15:24:55 PST
Received: by bambam..com (4.0/SMI-3.2) id AA00542; Fri, 10 Feb 89 15:31:47 PST
Return-path: <bambam!metaphor!lgold@Sun.COM> 
From: bambam!metaphor!lgold@Sun.COM (Lynn Gold) 
Date: Fri, 10 Feb 89 15:31:47 PST 
To: sunncal!sun!F74.Tymnet.COM!JMS@Sun.COM 
Message-id: <8902102331.AA00542@bambam..com> 
Subject: Re: Mail did arrive. 

If you think the headers YOU get are weird, MY mailer says I got mail
from "sunncal!JMS%F74.Tymnet.COM."

To send mail to YOU, I have to send it to "sunncal!sun!F74.Tymnet.COM!JMS."

>I sent the original message to figmo@mica.Berkeley.EDU after seeing your
>articles in rec.music.dementia.  Does that mean you work for Sun and play at
>UCB?

Close.  I work at Metaphor; we're down the street from Sun.  I DO use a
Sun 3/50, though (that's what I'm typing at right now).

>Sally got A's in her music history class and American history class, and is
>now taking Cultural Anthropology.  With Eclecticon in Sacramento this weekend
>and ORAC next weekend, she says she can't afford to get sick.

ORAC?  Never heard of it.  My $$$ are saved up (well, not exactly saved,
BUT...) for Bayfilk, which takes place the 1st weekend in March.  I got an
"A" in my Broadcast Newswriting class (I'd have hung my teacher by his
toenails if I didn't :-) ), an "A" in KFJC, and a "C+" in my Information
Gathering and Research class (not bad for someone who didn't do 3 of the
assignments!).

This semester I'm taking Advanced Radio Reporting, Advanced TV Reporting,
and Reporting Public Opinion, along with KFJC; that comes to 12 units.
I'm taking it easy school-wise this semester because I was sick non-stop
from the beginning of November till now (I'm getting over a sinus infection;
they have me snorting steroids!), and would like to recover.

I finally bought the place I've been living in.  My first mortgage payment
is due Sunday (ouch).  Me, hyper?  Nah... :-)

Cheers,

--Lynn


From: Osman Guven <OSMAN@F74> 
Date: Wed, 15 Feb 89 22:35:10 PST 
To: Carl Baltrunas <Carl@F74>, jms 
Subject: FYI .. 

Here is copy of mail I sent to Bill Sturm.

===========================================
Bill ..

	My trip to Irvine last week was more productive than I expected.
I am glad we got to meet each other and had a chance to talk.  In the
future I hope to get acquainted with the people who work for you. I am
very much interested in learning more about what you do and your plans
for the M&E and SUN project.  See you here Wednesday.

-Osman-

P.S.	Here is the summary of our brainstorming session.

				-1-


							       10 February 1989

Brainstorming sesion:
	Bill  Sturm
	Craig Fletcher
	Osman Guven




		M A I N T E N A N C E   S T R A T E G Y 
		=======================================


F S C O
-------
	o  Changing technology requires it.
	o  We have to support it for FE anyway.
	o  Consistent with our horizontal service methodology.
	o  Sell the S/W at the same time with H/W sale, including
	   maintenance and warranty.  Service forever.
	o  Move the H/W and S/W dividing line out a layer.
	o  Expand focus from shrinking maintanence revenue to include
	   software offering.
	o  Offer different software option; installation, patching.
	o  MDFSCO can do it better than SUN.
	o  It fits our growth path.
	o  We support MDC products, better for all.

M D C
-----
	o  Make money internally.
	o  Single O/S support group.
	o  Customer money all goes to MDC.
	o  Maintenance margin goes up by riding MDC market potential.
	o  Control future System Integration.
	o  Reduce cost of sale for FSCO.
	o  May leverage our support for sale.
				-2-




S H O R T - T E R M - G O A L
-----------------------------
	o  Sell the H/W maintenance at the sale of hardware;
		a)  Service with warranty.
		b)  Install it.
		c)  Maintain it.
	o  Offer better service than SUN.

L O N G - T E R M - G O A L
---------------------------
	o  Sell the S/W(Bundled O/S) support once; at the same
	   time as H/W sale, including maintenance and warranty.
	o  Package options to suit customer`s need.
	o  Sole H/W and System S/W source service.
	o  H/W and S/W single coordinated source.
	o  Expand service offered to customer base.
				-3-




R E Q U I R E M E N T S
-----------------------
	o  Sell all the ISC components this idea.
	o  Mandatory sole source agreement with ISC components.
	o  Marketing agreement; commission, etc.
	o  Field Operation and Technical Operation.
	   must communicate better passing the knowledge.
	o  Single coordinated H/W and S/W support(same source).
	   Cooperative relationship with all parties.
	o  Remote serviceability = $$.
	o  Take adventage of "Laptop".
		a)  Online FE support.
		b)  Online symptom solution.
	o  Must have H/W and S/W resources available.
		a)  Update service and archive.
		b)  Past, present, future software version.
		c)  Documentation rights.
	o  Up to date training.
	o  Development for "Expert System".
	o  Look/Find a microcosm for a test bad.
	o  Do it right = Keep customer.
Received: from F33.Tymnet.COM by F74.Tymnet.COM; Sat, 18 Feb 89 19:58:04 PST
Return-path: <JMS@F74.Tymnet.COM> 
From: Joe Smith <JMS@F74.Tymnet.COM> 
Date: Sat, 18 Feb 89 19:49:27 PST 
To: Bill Fischer <IPC.B/Fischer@Ontyme>, Rick Daniels <IPC.R/Daniels@Ontyme>,
	Ed Roop <IPC.E/Roop@Ontyme>, Ed Barens <IPC.E/Barens@Ontyme>, Jim
	English <IPC.J/English@Ontyme>, Leland Yarbrough
	<IPC.L/Yarbrough@Ontyme>, Jim Zone <IPC.J/Zone@Ontyme>, John Roddam
	<IPC.J/Roddam@Ontyme> 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC 
Subject: The maximum size of DSKB is 3 million pages. 

When the Fremont Operations attempted to add a 26th pack to F33, it exposed
a previously unknown limitation on the size of DSKB.  The DSKCLN program
cannot run if DSKB is bigger than 3,000,000 pages is size.  The maximum
number of units are:

Memorex 3675 (200 Mb/spindle) = 39 units.
Memorex 3650 (300 Mb/spindle) = 25 units.
Memorex 3652 (600 Mb/spindle) = 12.5 drives = 25 logical units.

F33 is currently using only the BPA5 half of BPA5/BPC5; the BPC5 half is
marked as SPARE and is not part of DSKB.

			Joe Smith
			PDP-10 Support Group
From: Joe Smith <JMS@F74.TYMNET> 
Date: Thu, 12 Jan 89 12:27:09 PST 
To: julie@gleep 
Subject: MDFSCO is getting 2 standalone workstations. 

Field Service Company is getting two Sun 3/50 workstations with disks to be
installed on the second floor of Building D.  At this time, we have not
decided on their names or how they will be connected with the rest of the
network.  This is just a warning that we will need some host numbers assigned
in the near future.

		Joe Smith
Received: from D35.Tymnet by F74.Tymnet; Tue, 17 Jan 89 14:04:34 PST
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Tue, 17 Jan 89 14:01:17 PST
Received: from F74.Tymnet by EMSNSC.Ontyme.Tymnet; Mon, 16 Jan 89 23:01:15 PST
Received: from tymix.Tymnet.COM.Tymnet.COM by F74.Tymnet; Mon, 16 Jan 89
	23:00:57 PST
Received: by tymix.Tymnet.COM.Tymnet.COM (5.51/4.7) id AA27212; Mon, 16 Jan 89
	22:08:16 PST
Received: by gleep.Tymnet.com (3.2/SMI-3.2) id AA04530; Mon, 16 Jan 89 22:08:08
	PST
Return-path: <julies@gleep> 
From: julies@gleep (Julie Stier) 
Date: Mon, 16 Jan 89 22:08:08 PST 
To: TXS.J/SMITH@EMSNSC.Ontyme.Tymnet.com 
Cc: TXS.C/BATRUNAS@EMSNSC.Ontyme.Tymnet.com,
	TXS.O/GUVEN@EMSNSC.Ontyme.Tymnet.com 
Message-id: <8901170608.AA04530@gleep.Tymnet.com> 
Subject: Sun validations 


Joe,

The 3 validations requested for Carl, Osman and yourself have been completed
as follows:

usernames -
        carl
        osman
        jms

home - /usr/opus3/misc

default password - change me

Let me know if there are any problems with this.

julie
   