Received: from EMSFSC.Ontyme.Tymnet by F74.Tymnet.COM; Wed, 4 Jul 90 10:23:59
	PDT
From: FSC.A/HOFFMAN@EMSFSC.Ontyme.Tymnet 
Date: 03 JUL 90 15:41:40 
To: FSC.JM/SMITH@EMSFSC.Ontyme.Tymnet 
Message-id: P32785@Ontyme.Tymnet 
Subject: NOVADYNE NEWS 




         TO:      ALL MANAGERS
         FROM:    PAT DWIGHT
         SUBJECT: NOVADYNE NEWS
         DATE:    JULY 3, 1990

         WE DID IT!!!  NOVADYNE is real.  I have copied you on the press
         release that was sent out to the media on July 2, 1990.  Now you
         know what the "story" to the outside world is.

         Several questions have been raised about our new corporate
         address.  Yes, we did change it as follows:

                                 NOVADYNE COMPUTER SYSTEMS, INC.
                                 1775 E. St. Andrew Place
                                 Santa Ana, Ca.  92705-6560

         The corporate telephone numbers are the same, but callers should
         not be using the 714/566-4000, but rather 714/566-4800.

         More news to follow, watch your ONTYME mail.

         Regards,


         Pat




         CONTACT:      PAT DWIGHT
                       NOVADYNE COMPUTER SYSTEMS, INC.
                       714/566-4965

         DATE:         JULY 2, 1990


                    NOVADYNE(TM) COMPUTER SYSTEMS, INC. EMERGES 


                                FROM MCDONNELL DOUGLAS


                                

                  SANTA ANA, Calif., July 2, 1990 -- NOVADYNE Computer
         Systems, Inc, formerly  McDonnell Douglas Field Service Company,
         was founded today.  NOVADYNE Computer Systems, Inc. remains one
         of the largest independent field service and computer systems
         distribution organizations in North America, with over 1000
         professionals located in over 100 offices across the nation. 
                  The management buyout, headed by president and chief
         executive officer Bert Novak, began 11 months ago with McDonnell
         Douglas Corp.  Many financing alternatives were investigated,
         resulting in the selection of Menke Titolo Capital Corp. to lead
         the financial syndication.  "The same strong management team
         that was formed approximately three years ago and helped put
         this company together will now be running NOVADYNE," Novak said.
                                       -more-

         NOVADYNE
         2-2-2-2

                  NOVADYNE Computer Systems, Inc. products and services
         are marketed nationwide to companies in all facets of commerce
         including retailing, transportation, distribution,
         communications, health care, educational organizations and
         federal and local government agencies. 
                  NOVADYNE -- 'The Power of Many Combined as One' --
         represents the combined forces of the former Microdata(R),
         MCAUTO(R) and Tymshare(R) field service organizations.
                  NOVADYNE Computer Systems, Inc. is a single source for
         repair and maintenance service on mainframes, minis, CAD/CAM
         workstations, micros, peripherals and communications networks
         from manufacturers such as DEC(R), Tandem(R), Sun
         Microsystems(R), McDonnell Douglas(R), and many others.
                  Continuing its tradition of providing quality services
         to end-users, OEMs, VARs and dealers, NOVADYNE Computer Systems,
         Inc. delivers on-site services which are designed to meet
         specific user requirements with varying levels of response and
         coverage hours.  Depot repair services are customized for the
         self-maintainer, Reseller and other independent service
         companies and include repair, parts exchange and parts sales and
         leasing.
                  Service Management, specializing in business
         partnering, offers more flexible services and value-added
         service solutions to OEMs, VARs and VADs and their own
         customers.  This new service is provided directly to the 
                                     -more-

         NOVADYNE
         3-3-3-3
         customer on behalf of OEMs and Resellers, allowing them the
         freedom to concentrate on manufacturing and distribution of
         products.
                  NOVADYNE Computer Systems, Inc. recently assumed all
         sales and marketing responsibility for McDonnell Douglas
         Computer Systems products sold through dealers and VARs in North
         America.  "This sets our company apart, as we are the only
         nationwide non-manufacturing distributor capable of offering
         total software and hardware support to its Reseller network,"
         Novak said.
                  Distribution products are currently based on the
         McDonnell Douglas series of super mini computers, utilizing
         unique modular architecture to deliver faster CPU performance.
         These product offerings also include a broad range of software
         packages such as office automation, PC connectivity
         applications, and distribution management systems for general
         business which are marketed through its Reseller channel.
                  In the first quarter of 1990, the company announced the
         LX/2100 systems, the company's first entry into the UNIX(R)
         market.  LX/2100 systems are based on Sun Microsystems' SPARC(R)
         architecture, the most popular UNIX platform in the world.
                  "We will continue to expand our computer and network
         maintenance services to our Third and Fourth party markets.  We
         also intend to develop the distribution side of the business by
         attracting new OEMs and Resellers, and from this strong
         foundation, we will continue our heritage of continuous growth
         and expansion," Novak said.
                                      -more-

         NOVADYNE
         4-4-4-4

                  The company headquarters will remain at its present
         Santa Ana, Calif. location until nearby construction of its new
         facility is complete in mid-1991.  Revenues in 1989 exceeded
         $100 million.

                                         ###



                  DEC is a registered trademark of Digital Equipment
         Corp.
                  Tandem is a registered trademark of Tandem Computers
         Incorporated.
                  Sun, SPARC and Sun Microsystems are registered
         trademarks of Sun Microsystems, Inc.
                  REALITY and Tymshare are registered trademarks of
         McDonnell Douglas Corp.
                  UNIX is a registered trademark of AT&T.
                  NOVADYNE is a registered trademark of NOVADYNE Computer
         Systems, Inc.
