Received: from D35.Tymnet by F29.Tymnet; Sat, 17 Sep 88 14:04:20 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 17 Sep 88 14:00:29 PDT
Return-path: <ACS.E/GAGLIARDI@EMSTXS.Ontyme.Tymnet> 
From: ACS.E/GAGLIARDI@EMSTXS.Ontyme.Tymnet 
Date: 17 SEP 88 01:04:35 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A47437@Ontyme.Tymnet 
Subject: NSC ONTYME RESTRUCTURE 

                      ******************************
                      *                            *
                      *      Please Take Note!     *
                      *                            *  
                      ******************************

                          NETWORK SYSTEMS COMPANY

                            OnTyme Restructure
                            ******************

    NETWORK SYSTEMS COMPANY IS CONSOLIDATING THE MAJORITY OF THEIR ONTYME
    ACCOUNTS.  BELOW YOU WILL FIND THE DETAILS OF THE NEW ACCOUNTS YOU
    MUST USE TO COMMUNICATE WITH NETWORK SYSTEMS COMPANY, ALONG WITH THE
    EFFECTIVE DATES OF CHANGE.
                           

       ------------    
      /            \                                                      
     / NEW account  \                                                   
    /      NSC       \                                                 
   /                  \                                                
  |||||||||||||||||||||                                                
  |   OLD Accounts    |                                                
  |                   |                                                
  |   FIN     NSS     |           EFFECTIVE :  MONDAY, 9-26            
  |   HRD     TYMOPS  |                                                
  |   NSCHQ   NTD     |           BEGIN SENDING YOUR MESSAGES          
  |   TYMPLN  QSATS   |           TO THE NEW ACCOUNT, NSC.             
  |                   |                                                 
  |||||||||||||||||||||                                                 


       ------------    
      /            \                                               
     / NEW account  \                                                   
    /     NSCMS      \                                                 
   /                  \                                                
  |||||||||||||||||||||                                                
  |   OLD Accounts    |                                                
  |                   |                                                
  |   ENS     TYMHQ   |           EFFECTIVE :  MONDAY, 10-3            
  |   NETS    TYM     |                                                
  |   NSMS            |           BEGIN SENDING YOUR MESSAGES          
  |                   |           TO THE NEW ACCOUNT, NSCMS.           
  |                   |                                                 
  |||||||||||||||||||||                                                 

                     HOW DO I FIGURE OUT THE NEW IDS?
                     ********************************


              To figure out a new ID, merely change the OLD 
                   account name to the NEW account name




         For example, Dick Kovach's ID is FIN.R/KOVACH.  His new ID,
         starting 9-26, will be NSC.R/KOVACH.  

                     OLD ONTYME ID === > FIN.R/KOVACH
                     NEW ONTYME ID === > NSC.R/KOVACH



         Another example is Dick Gunther's ID.  His new ID, starting 10-3
         will be NSCMS.D/GUNTHER.

                     OLD ONTYME ID === > TYM.D/GUNTHER
                    NEW ONTYME ID === > NSCMS.D/GUNTHER


Thank you for your patience during this transition.
Received: from D35.Tymnet by F29.Tymnet; Wed, 21 Sep 88 14:08:14 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 21 Sep 88 14:00:29 PDT
Return-path: <ACS.L/METOUR@EMSTXS.Ontyme.Tymnet> 
From: ACS.L/METOUR@EMSTXS.Ontyme.Tymnet 
Date: 21 SEP 88 21:53:17 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A49243@Ontyme.Tymnet 
Subject: PLAYING THE 'GUESS MY ONTYME ID' GAME 

                    DO YOU EVER PLAY THE GAME
                      "GUESS MY ONTYME ID?"
          
           * * * * * * * * * * * * * * * * * * * * * *
           *            ____________________         *
           *           /___________________/\        *
           *          /          12        \ \       *
           *         /  11       ^       1  \ \      *
           *        /            |           \ \     *
           *       / 10          |         2  \ \    *
           *      /              |             \ \   *
           *     /  9            O ----->    3  \/   *
           *     \                              /    *
           *      \   8                     4  /     *
           *       \                          /      *
           *        \   7                 5  /       *
           *         \           6          /        *
           *          \--------------------/         *
           *                                         *
           *                                         *
           *    How long does it take you to win?    *
           *        And do you PHONE to win?         *
           *                                         *
           * * * * * * * * * * * * * * * * * * * * * *
 
              PLAY NO LONGER.  TELEPHONE NO LONGER.
 
     Use the MDC OnTyme User Directory to locate OnTyme IDs!
 
 
The MDC OnTyme User Directory consolidates account directories
each OnTyme Account Supervisor maintains.  To simplify look up,
you no longer have to know the user's account!
 
 
   To look up an employee's OnTyme ID, when accessing OnTyme 
   (Choose Manual Access if you are using ISGMail), merely type
 
                  :EXEC *** DIRECTORY [RETURN]
 
   Wait for the prompts and you are then asked to identify 
   the person.  Whenever you use the Directory, you have 
   three times to request OnTyme IDs.  After this, you are
   logged out of the Directory and back into OnTyme.  If 
   you are unable to locate a person's ID, let them know.
   It is possible the Supervisor* needs to add the person to
   his or her directory.
 
 
We think you will find the MDC OnTyme User Directory a valuable 
tool, especially useful during the OnTyme restructuring transition 
taking place during the next few weeks.  

*Note:  For a current list of internal OnTyme Account Supervisors,
type :READ *** DIR.SUPERVISORS
Received: from D35.Tymnet by F29.Tymnet; Wed, 21 Sep 88 14:08:23 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 21 Sep 88 14:00:36 PDT
Return-path: <ACS.L/METOUR@EMSTXS.Ontyme.Tymnet> 
From: ACS.L/METOUR@EMSTXS.Ontyme.Tymnet 
Date: 21 SEP 88 21:55:45 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A49244@Ontyme.Tymnet 
Subject: PLEASE DISTRIBUTE MSG # A49243 

DEAR ACCOUNT SUPERVISOR:

PLEASE DISTRIBUTE MSG # A49243 TO YOUR ACCOUNT USERS.

MANY THANKS!

LES METOUR
Received: from D35.Tymnet by F29.Tymnet; Thu, 22 Sep 88 14:06:06 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Thu, 22 Sep 88 14:00:28 PDT
Return-path: <ACS.L/METOUR@EMSTXS.Ontyme.Tymnet> 
From: ACS.L/METOUR@EMSTXS.Ontyme.Tymnet 
Date: 21 SEP 88 22:26:42 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A49270@Ontyme.Tymnet 
Subject: DIVERSIFIED RESTRUCTURE 

                       OnTyme Account Restructuring


    This is to advise you that the ISGFM account will be phased out.
    There are some new Diversified accounts available, beginning Monday,
    9-26.  They are as follows :

         RSC        Remote Services Center
                    [Includes Mr. Calvert]

         MPD        Manufacturing, Permac & Distribution

         ISE        Information Systems Engineering


The restructure only affects the account name.  For instance, Bill McKay's
OnTyme ID is currently ISGFM.B/MCKAY.  Starting Monday, his new ID will be
RSC.B/MCKAY.  In the same way, Kathy Waddell's OnTyme ID is currently
IPC.K/WADDELL.  Her new ID will be ISE.K/WADDELL.


    In addition, the entire account, MDCSS, will be renamed to the new
    account, MDCIS.  On Monday, you must send your OnTyme's using the new
    account.


    For instance, Paul Scholten's current ID is MDCSS.P/SCHOLTEN.  His new
    ID will be MDCIS.P/SCHOLTEN.


        ** WE THANK YOU FOR YOUR PATIENCE DURING THIS TRANSITION **
 