Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Mon, 13 Aug 90 3:29:26
	PDT
From: SUPS.VAL@EMSTXS.Ontyme.Tymnet 
Date: 13 AUG 90 11:22:23 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: ACS.REQUESTS@Ontyme.Tymnet, ACS.ONTYME@Ontyme.Tymnet,
	ACS.SUP@Ontyme.Tymnet, BTE.SUP@Ontyme.Tymnet, BTUK.SUP@Ontyme.Tymnet,
	INTL.SUP@Ontyme.Tymnet, IPS.SUP@Ontyme.Tymnet, MDEMS.SUP@Ontyme.Tymnet,
	NIS.SUP@Ontyme.Tymnet, NISOSA.SUP@Ontyme.Tymnet, NSC.SUP@Ontyme.Tymnet,
	NSCMS.SUP@Ontyme.Tymnet, NTS.SUP@Ontyme.Tymnet,
	OPERA.SUP@Ontyme.Tymnet, PMTS.SUP@Ontyme.Tymnet, TXS.SUP@Ontyme.Tymnet 
Message-id: S47512@Ontyme.Tymnet 
Subject: UPDATE FILE DIRECT.BTE 

            A C S   CUSTOMER SERVICE CENTER
          REQUEST FOR NEW/UPDATED PUBLIC FILE
          ***********************************


Requestor's Name:AGNES DAL PIAZ

Message number of file sent:S47511

File Stored as (include * or **) >** DIRECT.BTE

ID where above file is stored >BTE.A/DALPIAZ

--------------------------------------------------------------------
EXISTING public filename  *** DIRECT.BTE
--------------------------------------------------------------------

>UPDATING FILE *** DIRECT.BTE
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Tue, 10 Jul 90 14:02:26
	PDT
From: ACS.N/SMITH@EMSTXS.Ontyme.Tymnet 
Date: 10 JUL 90 21:32:35 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A39506@Ontyme.Tymnet 
Subject: Update of username directory 

Dear account supervisor,

As you may know, OnTyme support maintains an online directory of all BT Tymnet
usernames.  This directory is maintained for use by BT Tymnet personnel who
need assistance in determining a fellow employee's OnTyme name.

While updating the directory recently, I noticed that the directory file for
your account (*** DIRECT.acctname) has not been updated recently and may not
be completely current.

We would appreciate it if you would take a few minutes to review the directory
file for your account and update it if necessary.  If you are not sure how to
do this, please read *** ACCTSUP.GUIDE or contact me directly.

Thank you for your assistance.

Norman Smith
OnTyme Support
ACS.N/SMITH, (408) 922-6376

[PC OnTyme Plus 1a:n/smith                  :PCO100216:22295]
Dear account supervisor,

As you may know, OnTyme support maintains an online directory of all BT Tymnet
usernames.  This directory is maintained for use by BT Tymnet personnel who
need assistance in determining a fellow employee's OnTyme name.

While updating the directory recently, I noticed that the directory file for
your account (*** DIRECT.acctname) has not been updated recently and may not
be completely current.

We would appreciate it if you would take a few minutes to review the directory
file for your account and update it if necessary.  If you are not sure how to
do this, please read *** ACCTSUP.GUIDE or contact me directly.

Thank you for your assistance.

Norman Smith
OnTyme Support
ACS.N/SMITH, (408) 922-6376

[PC OnTyme Plus 1a:n/smith                  :PCO100216:22295]
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Tue, 10 Jul 90 18:29:10
	PDT
From: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Date: 11 JUL 90 02:10:07 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: ACS.REQUESTS@Ontyme.Tymnet, TXS.SUP@Ontyme.Tymnet 
Message-id: A39562@Ontyme.Tymnet 
Subject: *** directory update 

                 ONTYME ELECTRONIC MAIL SYSTEM
REQUEST TO INCLUDE NEW/UPDATED DIRECTORY FILE IN ONLINE DIRECTORY
            *****************************************
Requestor's Name > Joe Smith

Enter Message Number of file just sent: 39560

Enter existing filename, including * or ** >** direct.txs

Enter userid where above file is stored > txs.sup
Received: from EMSTXS.Ontyme.Tymnet by F74.Tymnet.COM; Wed, 11 Jul 90 9:19:29
	PDT
From: ACS.N/SMITH@EMSTXS.Ontyme.Tymnet 
Date: 11 JUL 90 16:54:49 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A39789@Ontyme.Tymnet 
Subject: Thanks for the update 

Joe,

Thanks for the prompt update of your directory file.  It will included in the
next update of the online username directory (within a day or two).

Norman

[PC OnTyme Plus 1a:n/smith                  :PCO100216:43735]
