Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 20 Jan 89 14:01:53 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 19 Jan 89 14:11:24 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 19 Jan 89 14:05:31 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 19 Jan 89 14:05:06 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 19 JAN 89 09:26:34 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J92986@Ontyme.Tymnet 
Subject: Trip to CA 
TriptoCalifornia: 

                             MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      19 JAN 89  11:22

TO>        Carl Baltrunas

COPIES>    

FROM>      Debbie Shutt


SUBJECT>   Trip to California


-----------------------------------------------------------------------


Carl, it looks as though Jim O'Connel will not be coming with me to
San Jose.  How does the week of February 6th look for you.  I was
thinking about flying out on the 8th, spending the day with you on the
9th and coming home on the 10th.  Let me know if you think we need more
time or if this is not good for you.  Also can you recommend a hotel
that is close.

Thanks,
Debbie
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 20 Jan 89 14:02:01 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 19 Jan 89 14:13:55 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 19 Jan 89 14:05:36 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 19 Jan 89 14:05:13 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 19 JAN 89 12:09:07 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J93068@Ontyme.Tymnet 
Subject: Cancel EASOP Usernames 
CancelEASOPUsernames: 

                             MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      19 JAN 89  14:02

TO>        Carl Baltrunas

COPIES>    

FROM>      Debbie Shutt


SUBJECT>   Cancel EASOP Usernames


-----------------------------------------------------------------------


Carl, please cancel the following EASOP usernames from the KL-10 system.
I received these from Ted Atkinson today.  When I come out, you can
show me how to do this.

NE2311TC   NE2541TC

If you have any questions, please call.  Thanks for your help...


Debbie
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 27 Jan 89 14:02:14 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 26 Jan 89 14:05:46 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 26 Jan 89 14:05:21 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 26 Jan 89 14:05:01 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 26 JAN 89 12:05:52 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J95256@Ontyme.Tymnet 
Subject: Request from Ted Atkinson 
RequestfromTed: 

TO:    Carl

From:  Debbie Shutt

Date:  January 26, 1989

RE:    Request from Ted

===================================================

Carl, Ted Atkinson called this afternoon.  He needs a program called
CSORT (executable) loaded to his id on system 74 (WE9915X).  They are
having problems with their phones and we can't call in.  Can you send
him a mail message?

Thanks,
Debbie
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 28 Jan 89 14:02:03 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Fri, 27 Jan 89 14:39:53 PST
Received: from D35.Tymnet by F74.Tymnet; Fri, 27 Jan 89 14:05:59 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Fri, 27 Jan 89 14:05:38 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 27 JAN 89 13:59:40 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J95653@Ontyme.Tymnet 
Subject: Important KL-10 
KL-10Billing: 

To:     Carl

From:   Debbie

Date:   January 27, 1989

Re:     KL-10 Billing

++++=======================================================

Carl, after much discussion it looks as though we need to pass
the username to CPIP.  It needs to go into the field that the PPN is
presently occupying.PIP doesn't need the PPN for billing,
the MCN is important to them.  AT&T needs the username with study
type on the end for their billing.  Bob Brown is not going to use the
data that we have sent them so far because we will need to rerun it with
the username put in.  You will need to give him a call and he will discuss
with you how best to give him the new data.  Please give me a call on
Monday and let me know how long it is going to take you to modify your
program.  If you have any questions, please give me a call.  Thanks,
Debbie
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Tue, 7 Feb 89 14:02:00 PST
Received: from F74.Tymnet.COM by EMSTUMS.Ontyme.Tymnet; Mon, 6 Feb 89 21:47:10
	PST
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Mon, 6 Feb 89 14:31:48 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Mon, 6 Feb 89 14:03:27 PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 06 FEB 89 12:00:48 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J98394@Ontyme.Tymnet 
Subject: KL-10 Conference Call 
KL-10BillingCall: 

M E M O

To:   Carl

From: Debbie

Date: February 6, 1989

RE:   KL-10 Billing Call

==============================================================

Carl, Will you be available for a conference call with Jim O'Connell,
Bob Brown, Bob Tucker, and myself on Tuesday afternoon?  Jim wants to 
discuss some outstanding issues with us.  Please send me an ONTYME and
let me know when you are available.  Thanks,

Debbie
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet.COM; Thu, 9 Feb 89 14:01:43
	PST
Received: from F74.Tymnet.COM by EMSTUMS.Ontyme.Tymnet; Wed, 8 Feb 89 14:05:20
	PST
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Wed, 8 Feb 89 14:04:54 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet.COM; Wed, 8 Feb 89 14:04:37
	PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 08 FEB 89 06:45:49 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J99036@Ontyme.Tymnet 
Subject: California Trip 
CaliforniaTrip: 

Memo


To:    Carl

From:  Debbie

Date:  February 8, 1989

Re:    California Trip

==============================================================

Carl, is it okay with you if we postpone my trip to the following week?
That would be March 1 and 2.  I need to be here in St. Louis to make sure
all accounting gets in before the cycle ends on the 24th.  Let me know.
Thanks,
Debbie
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Tue, 7 Mar 89 14:07:14 PST
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet.COM; Tue, 7 Mar 89 14:02:14
	PST
Return-path: <MDCIS.J/O'CONNELL@EMSTXS.Ontyme.Tymnet> 
From: MDCIS.J/O'CONNELL@EMSTXS.Ontyme.Tymnet 
Date: 07 MAR 89 07:55:42 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Message-id: J07651@Ontyme.Tymnet 
Subject: Requesition No. and Study types. 

Carl, please give me a call today.  I talked to Ted Atkinson about the issues
we discussed yesterday.  Thanks, Jim......

[PC OnTyme Plus 1a:mdcis.j/o'connell        :pop10c044:35305]
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Wed, 8 Mar 89 14:04:11 PST
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet.COM; Wed, 8 Mar 89 14:01:45
	PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Tue, 7 Mar 89 14:11:50 PST
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Tue, 7 Mar 89 14:07:15 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet.COM; Tue, 7 Mar 89 14:06:41
	PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 07 MAR 89 12:10:55 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J07836@Ontyme.Tymnet 
Subject: New KL-10 User 
NewKL-10User: 

To:    Carl

From:  Debbie Shutt

Date:  March 7, 1989

Re:    New KL-10 User

-----------------------------------------------------

Carl, I have a new KL-10 user that needs to be set-up on the machine.

Here is the information:

C & P Telephone of West Virginia
P.O. Box 730
1135 6th Ave.
Huntington, West Virginia  25711-0730

Mr. Backus - User
MCN - 1609100
Req. #04-02-90366

This is an AIRPAP user.  Give me a call when you get in and you can
help me get this on the system.

Thanks,
Debbie
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Wed, 15 Mar 89 16:36:34 PST
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet.COM; Wed, 15 Mar 89 16:34:45
	PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Wed, 15 Mar 89 14:04:51 PST
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Wed, 15 Mar 89 14:04:24 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet.COM; Wed, 15 Mar 89 14:04:05
	PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 14 MAR 89 14:28:44 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J10436@Ontyme.Tymnet 
Subject: kl-10 
KL-10Question: 

                             MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      14 MAR 89  16:17

TO>        Carl

COPIES>    

FROM>      Debbie


SUBJECT>   KL-10 Question


-----------------------------------------------------------------------


carl, jim is very concerned that the disk storage for kl-10 users is not
being charges
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 11 Jan 89 13:04:33 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet> 
Subject: TYMNET checking out the engine 

Debbie,
  An additional thought...  Ken mentioned that they were dialing into the
engine that you get using the local number (314) {I presume} 731-8002.  I
suggest that TYMNET also check out that node if at all possible.

  Thanks.

/Carl
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Wed, 11 Jan 89 13:17:04 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet> 
Subject: TYMNET problem? 

Debbie,
  Both Ken and Earl are having the problem that things don't work at
1200 baud any more.  They used to work.

  They are able to get things to work if they drop the line speed down
to 300 baud.

  I feel that this is significant, and may help TYMNET isolate the problem.
I will pursue the issue here with people I know in TYMNET as far as known
problems with new (if any) releases of network code.

/Carl
 PS.  Please pass this info on to whomever comes in to look at the engines.
From: Carl A Baltrunas <Carl@F74.Tymnet.COM> 
Date: Sun, 26 Feb 89 4:06:25 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet.COM> 
Subject: KL-10 Accounting 

Debbie,

  I have coordinated with Bob Brown the complete 7 weeks of accounting data
and the partial re-reun of week 8 due to the operations error last weenend
with the date-time mess up.  All is well.

  Due to the date mess up, we had two days that said 02-22, but Bob said
he would change the first set to say 02-21 since it was supposed to be data
for last tuesday, processed on wednesday.

  As of Friday, everything looked good....


-------------------------------------------------------------------------

  However, ...
    There was some sort of hardware problem that caused operations to have
the hardware switched from CPU # 1300 to CPU # 1195.  This change caused
the system to come up running a monitor (operating system) from DSKA: on
1195 that did NOT have the tty-characters-count data which we are charging
our customers for...  I believe that all tty-character traffic for the last
day and 1/2 will be 0 (Zero).

  I just wanted you to know about it, because we may have to correct the
data (or throw it away, if it is non-zero) to insure we don't over-charge
for one day of system usage.

-------------------------------------------------------------------------

  I have created a new monitor for 1195 and had operations reload the system
early sunday morning.  If all the activity on system 1195 was on Saturday
and Sunday, we don't really have any problem.  My concern is for Friday.

  Please check with Jim Crews and verify when system 1195 was brought up.
I'll be in the office at my regular time on Monday.  If you call me earlier
please let the secretary know it is not an emergency, otherwise she will
call me at home and possibly wake me up.

/Carl Baltrunas
From: Carl A Baltrunas <Carl@F74.Tymnet.COM> 
Date: Mon, 27 Feb 89 4:49:27 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet.COM> 
Subject: KL-10 Accounting K03, K06 

Debbie,
  As per my previous message... I have determined that there were NO
records sent for the 25th of February with K06 or K03 to CPIPS.  THus,
running the old monitor on system 1195 did NOT cause any problems to
the accounting system.  Apparently, the records were zero, and were
not generated.  [1,2] had some K06 records in the "not-charged" file
but I can assume they were from the period from between midnight and
5:00 am when the system went down.

  So, we lost any tty i/o charges for customers on Saturday 2/25, but
it appears NOT for any otehr time period.

  Just for verification, could you please check with Jim Crews to find
out if system 1195 was up as a replacement CPU at any previous time in
1989.   I believe the answer is NO, but I'd like some verfification so
that I can look through the accounting records to see if there was any
bad data for the days when 1195 might have been running as the primary
system.

  You can send me an Ontyme, or reply by voice mail...  If you want to
call the voice mail directly, the phone number is (408) 922-6550 and
that way you won't get the secretary.

  I'll call you when I get in.

/Carl
From: Carl A Baltrunas <Carl@F74.Tymnet.COM> 
Date: Wed, 15 Mar 89 1:41:14 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet.COM> 
Subject: Disk block days, etc 

Debbie,
  I looked at the output of the accounting data and apparently there are
some records which contain K09 records (disk blocks) and cpu usage/logins
in the same batch:


  However, the data will require more study to determine if we have
somehow lost data.  I will be looking into it in my off-hours this week
to determine what is happenning.

/Carl
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Fri, 3 Feb 89 14:01:52 PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Thu, 2 Feb 89 14:04:42 PST
Received: from D35.Tymnet by F74.Tymnet; Thu, 2 Feb 89 14:04:21 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet; Thu, 2 Feb 89 14:04:01 PST
Return-path: <FSC.K/OKEY@EMSFSC.Ontyme.Tymnet> 
From: FSC.K/OKEY@EMSFSC.Ontyme.Tymnet 
Date: 02 FEB 89 10:09:47 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: P15831@Ontyme.Tymnet 
Subject: STANDBY FOR FEBRUARY 1989 
StandbyforFebruary1989: 

              MCDONNELL DOUGLAS FIELD SERVICE COMPANY
 
 
                            MEMORANDUM
 
 
 
TO:           Distribution

FROM:         Craig Fletcher

DATE:         28 January 1989

SUBJECT:      Standby for February 1989

_________________________________________________________________

Here is the Software Standby Schedule for February:

   Week Beginning:   01/27/89           C. Baltrunas
                     02/06/89           O. Guven
                     02/13/89           J. Smith
                     02/20/89           C. Baltrunas
                     02/27/89           O. Guven

Regards, Craig

cc: C. Baltrunas, O. Guven, J. Smith, J. Shields, R. Rawlins,
Received: from F74.Tymnet.COM by D35.Tymnet; Sun, 5 Feb 89 22:42:55 PST
Return-path: <Postmaster@F74.Tymnet> 
From: Postmaster@F74.Tymnet 
Date: Sun, 5 Feb 89 23:23:19 PST 
To: <Carl@F35.Tymnet> 
Subject: Returned MAIL 

The following message was not delivered because:
The request was rejected by EMSTXS.Ontyme.Tymnet
The response was:
:send NSC.W/BARTLETT NSC.V/Stafford NSC.C/Hoeke IPC.E/Roop IPC.D/Mullen FSC.C/Fletcher
SUBJ: 
NONEXISTENT RECIPIENT
IPC.D/MULLEN
MSG # A94914 SENT AT 05 FEB 89 22:37:57  


----------
RCPT To: <IPC.D/MULLEN.@EMSTXS.Ontyme.Tymnet> 
Received: from F74.Tymnet by EMSTXS.Ontyme.Tymnet; Sun, 5 Feb 89 23:20:34 PST
Received: from D34.Tymnet.COM by F74.Tymnet; Sun, 5 Feb 89 23:20:14 PST
Return-path: <Carl@F35.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Mon, 6 Feb 89 0:01:11 CST 
To: Wayne D Bartlett <NSC.W/BARTLETT@Ontyme.Tymnet>, Vida Stafford
	<NSC.V/Stafford@Ontyme.Tymnet>, Cynthia Hoeke
	<NSC.C/Hoeke@Ontyme.Tymnet>, Ed Roop <IPC.E/Roop@Ontyme.Tymnet>, Debbie
	Mullen <IPC.D/Mullen@Ontyme.Tymnet>, Monitor Group <Carl>, Osman Guven
	<Osman>, Joe Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: SETOP cutover and changes 

This is to inform you that the newest release of SETOP has been installed
on system D34. The changes include:

 o  Opernames with no employee number are written to the password file
    as before, except their license field is 0.  If they try to set their
    license they receive the message "Did not set OP".  In effect they
    are disabled until their ISG/Employee numbers are entered.

 o  The DATES and NODATES commands have been added.  These commands control
    the printing of the password change date information as in the old
    version of SETOP.

 o  SM capability has a new meaning.  SM (Setop Manager) allows the user
    to create and delete oper names and otherwise manage the entire tree.

 o  BM capability (Branch Manager) allows the user to create and delete
    oper names and otherwise manage the current branch including all of
    its sub-branches and leaves.

 o  The IMITATE command now requires SU (Setop Utility) capability in
    order to properly record the "on behalf of" license grant.

 o  SU capability has been removed from all oper names other than ROOT
    and that of the SETOP maintainers.  Albeit this will make it slightly
    more difficult to grant license on behalf of a manager, it is felt
    that anyone that needs to grant license, understand how to do it and
    manage that responsibility themselves.  VALIDATIOLL NOT grant
    the actual license to the individual oper names, and therefore does
    NOT need the ability to grant license "on behalf" of another user.


/Carl Baltrunas, MDFSCO: Network Host Software Engineering group
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Mon, 6 Feb 89 14:01:26 PST
From: SYSTEM.ONTYME@EMSTXS.Ontyme.Tymnet 
Date: 05 FEB 89 23:00:32 
To: <Carl@F35.Tymnet> 
Message-id: A94920@Ontyme.Tymnet 
Subject: UNDELIVERABLE MESSAGE - INVALID RECIPIENTS 

Message #A94914 was not delivered to the following recipient(s):

        NSC.W/BARTLETT.

These recipients do not exist.
Please check the spelling of the recipient(s) listed above.

(undelivered message follows)
------------------------------------------------------------------------
Received: from F74.Tymnet by EMSTXS.Ontyme.Tymnet; Sun, 5 Feb 89 23:20:34 PST
Received: from D34.Tymnet.COM by F74.Tymnet; Sun, 5 Feb 89 23:20:14 PST
Return-path: <Carl@F35.Tymnet> 
From: Carl A Baltrunas <Carl@F35.Tymnet> 
Date: Mon, 6 Feb 89 0:01:11 CST 
To: Wayne D Bartlett <NSC.W/BARTLETT@Ontyme.Tymnet>, Vida Stafford
        <NSC.V/Stafford@Ontyme.Tymnet>, Cynthia Hoeke
        <NSC.C/Hoeke@Ontyme.Tymnet>, Ed Roop <IPC.E/Roop@Ontyme.Tymnet>, Debbie
        Mullen <IPC.D/Mullen@Ontyme.Tymnet>, Monitor Group <Carl>, Osman Guven
        <Osman>, Joe Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: SETOP cutover and changes 

This is to inform you that the newest release of SETOP has been installed
on system D34. The changes include:

 o  Opernames with no employee number are written to the password file
    as before, except their license field is 0.  If they try to set their
    license they receive the message "Did not set OP".  In effect they
    are disabled until their ISG/Employee numbers are entered.

 o  The DATES and NODATES commands have been added.  These commands control
    the printing of the password change date information as in the old
    version of SETOP.

 o  SM capability has a new meaning.  SM (Setop Manager) allows the user
    to create and delete oper names and otherwise manage the entire tree.

 o  BM capability (Branch Manager) allows the user to create and delete
    oper names and otherwise manage the current branch including all of
    its sub-branches and leaves.

 o  The IMITATE command now requires SU (Setop Utility) capability in
    order to properly record the "on behalf of" license grant.

 o  SU capability has been removed from all oper names other than ROOT
    and that of the SETOP maintainers.  Albeit this will make it slightly
    more difficult to grant license on behalf of a manager, it is felt
    that anyone that needs to grant license, understand how to do it and
    manage that responsibility themselves.  VALIDATIONS WILL NOT grant
    the actual license to the individual oper names, and therefore does
    NOT need the ability to grant license "on behalf" of another user.


/Carl Baltrunas, MDFSCO: Network Host Software Engineering group
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Wed, 22 Mar 89 14:05:16 PST
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet.COM; Wed, 22 Mar 89 14:01:37
	PST
Received: from F74.Tymnet by EMSTUMS.Ontyme.Tymnet; Tue, 21 Mar 89 14:06:00 PST
Received: from D35.Tymnet.COM by F74.Tymnet.COM; Tue, 21 Mar 89 14:05:31 PST
Received: from EMSFSC.Ontyme.Tymnet by D35.Tymnet.COM; Tue, 21 Mar 89 14:05:07
	PST
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 21 MAR 89 07:30:12 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J12562@Ontyme.Tymnet 
Subject: KL-10 
KL-10: 

MEMO


To:    Carl

From:  Debbie Shutt

Date:  March 21, 1989

RE:    KL-10 
________________________________________________________________

Carl, could you please give me a call when you get in?  I need to
know the status on the problem we found concerning the disk storage.

Also, the FACT LOG that ran on March 18 contained some rather weird
stuff.  There were several "LOGOUT with no previous entry", "Negative
Elapsed Time", "Large Time Found" and alot of "Bad FACT word:"

I am not sure what this means.  If you can't reach me, please send
me an ONTYME.

Thanks,
Debbie
From: Carl A Baltrunas <Carl@F74.Tymnet.COM> 
Date: Wed, 22 Mar 89 19:54:24 PST 
To: Debbie Shutt <MDCIS.D/Shutt@Ontyme.Tymnet.COM> 
Cc: Joe Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: Disk Storage on KL-10 

Debbie,

     I have located the reason for the un-charged disk usage.  You will be
relieved to know that we do NOT have a bug in any of the accounting programs.

     The disk usage information is created using the SPACE program from DEC,
which is designed to write the usage data to the FACT files.  This was done
on our system by adding the following commands to the daily command file run
from OPER [1,2]:

	.R SPACE
	*SPACE.LST=RDES:/FACT
	.R SPACE
	*SPACE.LST=RDET:/FACT
	.R SPACE
	*SPACE.LST=RDEY:/FACT
	   ...

In order to save space and make the DAILY.CTL batch file more readable by
us humans, I shortened these commands to:

	.R SPACE
	*SPACE.LST=RDES:,RDET:,RDEY:/FACT
	   ...

It so happens that this second form of the command doesn't generate FACT
file entries for RDES or RDET, although it still provides information to
the listing file about disk usage.  THIS IS NOT WHAT I EXPECTED!!!!

This will be fixed tonight... so the accounting for the 21st and 22nd will
contain the space usage information for all disks that we are charging disk
utilization to our users.

/Carl

From: Carl A Baltrunas <Carl@F74.Tymnet.COM> 
Date: Wed, 22 Mar 89 23:20:48 PST 
To: Walter Kass <MDCIS.W/KASS@Ontyme.Tymnet.COM>, Jim O'Connell
	<MDCIS.J/O'Connell@Ontyme.Tymnet.COM>, Debbie Shutt
	<MDCIS.D/Shutt@Ontyme.Tymnet.COM>, Craig Fletcher <fletcherc> 
Subject: Lost disk usage charges 

Here's what has been happening:
  Since the daily batch job has been automated and collecting data the ONLY
disks that we have summarized storage for are: RDEY, CATL and DSKL.  We do
NOT have any record of usage on RDES, RDET, TOPE, TOPF, SEPB, DSKC, DSKD,
DSKF, DSKG, DSKJ or ESOP.  We do have info for TOPH but I don't know how
valuable that is, since there are NO billable customers on TOPH today.

  Anyway, we cannot gain anything by re-running the accounting for any day
prior to March 22, 1989 since we have no stored data.  We may determine an
average disk usage by taking a daily usage for one day (i.e. March 22nd)
and multiply that by the number of days in the month to produce a "total"
disk usage just on those disks mentioned above (RDES...ESOP).  For March,
(4+21) for the number of days since the last monthly cycle multiplied by
the disk usage amount for one day.  For February, (4+24) and for January,
(1+27).

  Walt, the decision on how to recover the costs for theses disks is up to
you and Jim, or whether you want to go through the effort  It would take
me 1 day to provide a dummy summary file which contains *total* monthly
usage per user on these disks.

  I took it upon myself to start gathering this information for March 22
and it will gather it for March 23 by the time you see this memo.  If you
want me to discontinue gathering until month end, so we can treat March
as a full month for these disks, let me know immediately via ONTYME and
via our secretary (408) 922-6224.   I may be out of the office today, but
Karin will be able to locate me to let me know if I need to call you to talk
about this situation in more detail.

   ... otherwise, the problem has been corrected as of the March 22nd daily
run and will gather the correct and complete disk usage data for all billable
disks.

/Carl
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Thu, 13 Apr 89 14:04:43 PDT
Received: from EMSFSC.Ontyme.Tymnet by F26.Tymnet.COM; Thu, 13 Apr 89 14:03:58
	PDT
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 12 APR 89 14:06:47 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J19792@Ontyme.Tymnet 
Subject: Deletion of KL-10 Usernames 
CancellationofPDT2AUsernames: 

To :     Carl Baltrunas

From:    Debbie Shutt

Date:    April 12,1989

Re:      Cancellation of PDT2A Usernames

-------------------------------------------------------------------------

Carl, I have received a request from AT&T to delete some PDT2A userids.
Give me a call when you get a chance and we can talk about what to do
with the disk storage for these usernames.

Thanks,
Debbie
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Mon, 17 Apr 89 14:03:47 PDT
Received: from EMSFSC.Ontyme.Tymnet by F26.Tymnet.COM; Mon, 17 Apr 89 14:03:12
	PDT
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 17 APR 89 08:41:50 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J21105@Ontyme.Tymnet 
Subject: kl-10 users 
CancellatiionofPDT2AUsernames: 

Memorandum

To:    Carl Baltrunas

From:  Debbie Shutt

Date:  April 17, 1989

Re:    Cancellatiion of PDT2A Usernames

------------------------------------------------------------------

Carl, per our conversation here is the list of PDT2A usernames that need
to be deleted so that their disk storage won't appear on the invoices.

EA9990PD  PR9990PD
SB3003PD  SC1005PD
SC2107PD  SC4105PD
SC5109PD  SC5113XO
SO8909PD  SO8922PD
SO8926PD  SO8928PD
SO8955PD  SO9012PD

If you have any questions, please call.  Thanks.
Debbie
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Tue, 25 Apr 89 14:05:38 PDT
Received: from EMSFSC.Ontyme.Tymnet by F26.Tymnet.COM; Tue, 25 Apr 89 14:04:52
	PDT
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 25 APR 89 06:28:28 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J23692@Ontyme.Tymnet 
Subject: KL-10 DISK STORAGE 
KL-10DiskStorage: 

                             MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      25 APR 89  08:15

TO>        Carl Baltrunas

COPIES>    Walt Kass
           Craig Fletcher

FROM>      Debbie Shutt


SUBJECT>   KL-10 Disk Storage


-----------------------------------------------------------------------


Carl,

Beginning with May Services (April 29, 1989), please begin sending the
KL-10 disk storage once a week.  We found some problems in billing of
the disk storage (long story that I will talk to you about).  The best
solution is to send one daily storage total once a week preferably
Friday to Bob Brown.  Sally will then calculate the monthly average from
these 4 or 5 records (depending on the month).

Bob was also thinking on Saturdays and Sundays when there is no usage and
only thing that was being sent was disk storage, not to create a tape
now that storage will come only on Fridays.

Give me a call when you get in, and we can talk about this in detail.

Thanks, 
Debbie
From: Carl A Baltrunas <Carl@F74.Tymnet.COM> 
Date: Tue, 25 Apr 89 15:10:11 PDT 
To: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
Cc: Walter Kass <MDCIS.W/KASS@Ontyme.Tymnet.COM>, Craig Fletcher
	<FSC.C/Fletcher@Ontyme.Tymnet.COM>, Joe Smith
	<TXS.J/Smith@Ontyme.Tymnet.COM> 
Subject: Re: KL-10 DISK STORAGE 
In-reply-to: J23692@Ontyme.Tymnet of 25 APR 89 06:28:28

Date: 25-Apr-89

from: Carl A Baltrunas, MDFSCO

to:   Debbie Shutt, MDCIS

cc:   Walter Kass, MDCIS
      Craig Fletcher, MDFSCO
      Joe Smith, MDFSCO

-----------------------------------------------------------------------

Debbie,

  I received your message regarding disk storage charges for the KL-10.
What you are asking, (only billing for disk storage once a week), would
require some effort to develop such a feature.

  I suggest that -- if this is a requirement, then we ask Bob Brown to
pass the data through a filter which removes disk storage records from
the daily batches except for the one day that he wants to gather that
data.  Bob already has to scan the data and generate header and checksum
records, is should be trivial for him to simply ignore disk storage or
any particular service code records. --

  This method will be most reliable and any changes will be completely
under the control of MDCIS and the MIS departments.


/Carl
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Fri, 19 May 89 17:36:10 PDT
Received: from EMSFSC.Ontyme.Tymnet by F26.Tymnet.COM; Fri, 19 May 89 17:34:15
	PDT
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 19 MAY 89 07:22:23 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Cc: FSC.C/BALTRUNAS@Ontyme.Tymnet, FSC.JM/SMITH@Ontyme.Tymnet,
	FSC.C/FLETCHER@Ontyme.Tymnet, MDCIS.W/KASS@Ontyme.Tymnet 
Message-id: J32184@Ontyme.Tymnet 
Subject: KL-10 Accounting 
KL-10Accounting: 

                             MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      19 MAY 89  09:14

TO>        Carl Baltrunas
           Joe Smith

COPIES>    Craig Fletcher
           Walt Kass

FROM>      Debbie Shutt


SUBJECT>   KL-10 Accounting


-----------------------------------------------------------------------


As you know the accounting on the KL-10 has not run since Friday,
May 5, 1989.  The folks in CPIP are getting anxious since month's end
is Friday, May 26.  I would appreciate anything you can do to get this
expedited.  Thanks for your help...
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Wed, 21 Jun 89 14:02:59 PDT
Received: from EMSFSC.Ontyme.Tymnet by F26.Tymnet.COM; Wed, 21 Jun 89 14:02:38
	PDT
Return-path: <MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet> 
From: MDCIS.D/SHUTT@EMSFSC.Ontyme.Tymnet 
Date: 21 JUN 89 12:47:10 
To: FSC.C/BALTRUNAS@EMSFSC.Ontyme.Tymnet 
Message-id: J42604@Ontyme.Tymnet 
Subject: KL-10 Disk Space 
KL-10DiskSpace: 

                             MCDONNELL DOUGLAS
                   COMMUNICATIONS INDUSTRY SYSTEMS COMPANY

DATE>      21 JUN 89  14:42

TO>        Joe Smith

COPIES>    Craig Fletcher
           Carl Baltrunas

FROM>      Debbie Shutt


SUBJECT>   KL-10 Disk Space


-----------------------------------------------------------------------


Joe,

Glen Kasinger of operations has called me. He was calling to let me
know that disk B on the KL is getting full.  Would you please take care
of deleting files to clear up some space.  If you have any questions,
please call Glen at 314-234-5588 or me.  Thanks for your help...

Debbie
 8 M