Received: from F33.Tymnet by D35.Tymnet; Sun, 22 Jan 89 4:56:38 PST
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Sun, 22 Jan 89 12:56:26 UT 
To: SYS 
Subject: Req #51424 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #51424  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  10-Jan-89 11:45:49
; Actual run: 22-Jan-89 03:56:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  22-Jan-89 04:56:25

Received: from F33.Tymnet by D35.Tymnet; Sun, 22 Jan 89 6:37:15 PST
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Sun, 22 Jan 89 14:37:04 UT 
To: SYS 
Subject: Req #51424 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #51424  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  10-Jan-89 11:45:49
; Actual run: 22-Jan-89 03:56:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  22-Jan-89 06:37:04

Received: from F33.Tymnet by D35.Tymnet; Sun, 29 Jan 89 5:21:17 PST
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Sun, 29 Jan 89 13:21:06 UT 
To: SYS 
Subject: Req #51424 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #51424  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  22-Jan-89 23:56:43
; Actual run: 29-Jan-89 04:20:57
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  29-Jan-89 05:21:04

Received: from X32.Tymnet.COM by F74.Tymnet.COM; Mon, 13 Mar 89 17:30:29 PST
Return-path: <PERPOPER@X32.Tymnet> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Tue, 14 Mar 89 1:30:14 UT 
To: CARL 
Subject: Req #14613 DSK:(CARL)ASH.CTL Abort-Zap (3) 

; Processed:  Req #14613 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  13-Mar-89 16:17:00
; Actual run: 13-Mar-89 16:17:01
;
; Options:  Log:Append Mail:Error Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Zap (3)  at  13-Mar-89 17:30:11
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Received: from X32.Tymnet.COM by F74.Tymnet.COM; Wed, 15 Mar 89 17:09:03 PST
Return-path: <PERPOPER@X32.Tymnet> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Thu, 16 Mar 89 1:08:53 UT 
To: CARL 
Subject: Req #14643 DSK:(CARL)ASH.CTL Abort-Notice (4) 

; Processed:  Req #14643 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  15-Mar-89 16:17:00
; Actual run: 15-Mar-89 16:17:04
;
; Options:  Log:Append Mail:Error Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (4)  at  15-Mar-89 17:08:50
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Received: from X32.Tymnet.COM by F74.Tymnet.COM; Sat, 18 Mar 89 1:47:27 PST
Return-path: <PERPOPER@X32.Tymnet> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Sat, 18 Mar 89 9:47:16 UT 
To: CARL 
Subject: Req #14651 DSK:(CARL)ASH.CTL Abort-Notice (0) 

; Processed:  Req #14651 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  16-Mar-89 12:17:00
; Actual run: 16-Mar-89 12:17:06
;
; Options:  Log:Append Mail:Error Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  18-Mar-89 01:47:14
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Received: from X32.Tymnet.COM by F74.Tymnet.COM; Sat, 18 Mar 89 1:47:31 PST
Return-path: <PERPOPER@X32.Tymnet> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Sat, 18 Mar 89 9:47:19 UT 
To: CARL 
Subject: Req #14656 DSK:(CARL)ASH.CTL Abort-Notice (0) 

; Processed:  Req #14656 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 17-Mar-89 10:17:09
;
; Options:  Log:Append Mail:Error Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  18-Mar-89 01:47:17
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Received: from X32.Tymnet.COM by F74.Tymnet.COM; Sat, 18 Mar 89 2:00:13 PST
Return-path: <PERPOPER@X32.Tymnet> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Sat, 18 Mar 89 9:47:28 UT 
To: CARL 
Subject: Req #14656 DSK:(CARL)ASH.CTL Abort-Notice (4) 

; Processed:  Req #14656 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 17-Mar-89 22:26:17
;
; Options:  Log:Append Mail:Error Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (4)  at  18-Mar-89 01:47:26
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 8:00:17 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 16:00:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 05:30:05
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 08:00:08

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 9:01:17 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 17:01:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 08:00:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 09:01:08

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 10:02:19 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 18:02:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 09:01:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 10:02:08

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 11:03:22 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 19:03:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 10:02:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 11:03:09

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 12:04:18 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 20:04:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 11:03:10
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 12:04:08

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 13:05:20 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 21:05:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 12:04:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 13:05:08

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 14:06:16 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 22:06:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 13:05:09
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 14:06:09

Received: from D34.Tymnet.COM by F74.Tymnet.COM; Sun, 19 Mar 89 15:07:18 PST
Return-path: <PERPOPER@D34.Tymnet> 
Reply-to: SUBMIT 
From: D34 Job Processor 
Sender: PERPOPER@D34.Tymnet 
Date: Sun, 19 Mar 89 23:07:08 UT 
To: SYS 
Subject: Req #3981 DSK:(SYS)REDSAT.SAV Abort-Time (0) 

; Processed:  Req #3981  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  19-Mar-89 16:15:00
; Actual run: 19-Mar-89 14:06:10
;
; Options:  Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Abort-Time (0)  at  19-Mar-89 15:07:08

Received: from X32.Tymnet by D35.Tymnet; Fri, 6 Jan 89 13:46:54 PST
Return-path: <OSMAN@D35> 
From: Osman Guven <OSMAN@D35> 
Date: Fri, 6 Jan 89 13:44:06 PST 
To: Carl Baltrunas <Carl@D35> 
Subject: Wayne Bartlett .. 

He wants to set up a meeting with you some time next week.

-Osman-

Received: from X32.Tymnet.COM by F74.Tymnet.COM; Mon, 20 Mar 89 15:41:00 PST
Return-path: <PERPOPER@X32.Tymnet> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Mon, 20 Mar 89 23:40:50 UT 
To: CARL 
Subject: Req #14672 DSK:(CARL)ASH.CTL Abort-Notice (4) 

; Processed:  Req #14672 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  20-Mar-89 10:46:35
; Actual run: 20-Mar-89 10:46:40
;
; Options:  Log:Append Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (4)  at  20-Mar-89 15:40:45
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Received: from X32.Tymnet.COM by F74.Tymnet.COM; Tue, 28 Mar 89 23:21:05 PST
Return-path: <PERPOPER@X32.Tymnet> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Wed, 29 Mar 89 7:21:00 UT 
To: CARL 
Subject: Req #14715 DSK:(CARL)ASH.CTL Abort-Notice (4) 

; Processed:  Req #14715 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  28-Mar-89 16:35:00
; Actual run: 28-Mar-89 16:35:05
;
; Options:  Log:Append Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (4)  at  28-Mar-89 23:20:59
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Received: from F33.Tymnet.COM by F74.Tymnet.COM; Thu, 4 May 89 23:37:14 PDT
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Fri, 5 May 89 6:37:05 UT 
To: CARL 
Subject: Req #67585 DSK:(CARL)UNIQ.TYM Abort-Zap (4) 

; Processed:  Req #67585 DSK:(CARL)TYM0.LOG=DSK:(CARL)UNIQ.TYM
; Scheduled:  04-May-89 23:23:15
; Actual run: 04-May-89 23:23:44
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (4)  at  04-May-89 23:37:04
;
; Output recorded in file DSK:(CARL)TYM0.LOG.

Received: from F33.Tymnet.COM by F74.Tymnet.COM; Thu, 4 May 89 23:42:50 PDT
Return-path: <PERPOPER@F33.Tymnet> 
Reply-to: SUBMIT 
From: F33 Job Processor 
Sender: PERPOPER@F33.Tymnet 
Date: Fri, 5 May 89 6:42:44 UT 
To: CARL 
Subject: Req #67586 DSK:(CARL)UNIQ.TY5 Abort-Zap (4) 

; Processed:  Req #67586 DSK:(CARL)TYM5.LOG=DSK:(CARL)UNIQ.TY5
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 04-May-89 23:24:49
;
; Options:  Log:Supersede Mail:Error
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (4)  at  04-May-89 23:42:44
;
; Output recorded in file DSK:(CARL)TYM5.LOG.

   