
MAPFIL	FPARSE		EXTERNAL SIMPLE BOOLEAN (VALUE STRING PARSE!STRING; ...
MAPFIL	MAPFIL		INTERNAL BOOLEAN
DEFSYS	BRKINI		SIMPLE
DEFSYS	FILESPEC	SIMPLE STRING ( Reference string S, Dev;
DEFSYS	TOKEN		simple string  Token (reference string S);
DEFSYS	RANGE		boolean  Range;
DEFSYS	FATAL		simple  Fatal( String Reason );
DEFSYS	ATFILE		recursive string  AtFile( Boolean Typeit (False) );
DEFSYS	PROMPT		string  Prompt( String P );
DEFSYS	CVPRT		integer  CvPrt( String P; Integer D );
DEFSYS	NOTIMP		Simple  NotImp;
DEFSYS	C.READ		Simple  C.Read;
DEFSYS	Simple  C.Write;
DEFSYS	Simple  ChangeList( Boolean Change );
DEFSYS	Simple  C.Change;
DEFSYS	Simple  C.List;
DEFSYS	Simple  C.Help;
DEFSYS	Simple  C.Quit;
DEFSYS	Simple string  Perform!Command;
MONDOC	simple  Ini;
MONDOC	OpenMemFile (string FileName, How);
MONDOC	CloseMemFile;
MONDOC	MapRO (integer Ptr);
MONDOC	MapRW (integer Ptr);
MONDOC	simple integer  ReadWord;
MONDOC	simple string  ReadLine;
MONDOC	simple  WriteLine (string S);
MONDOC	simple  WriteHeading (string S);
MONDOC	simple  ParseMEM;
MONDOC	string  NameMEM;
MONDOC	simple  IniBreak;
MONDOC	simple  MonParse (
SYDISP	external 
SYDISP	simple string  DelStr (integer Cnt);
SYDISP	simple integer  TermIdx (string Term);
SYDISP	forward internal integer  T!GetC;
SYDISP	internal simple  T!GetTermType (boolean AskTheMonitor(true));
SYDISP	internal  T!Init;
SYDISP	internal simple  T!FlshIBuf;
SYDISP	forward internal simple  T!CPos(integer Row, Col);
SYDISP	forward internal simple  T!Flush;
SYDISP	forward simple  T!SBuf (string Str);
SYDISP	internal  T!Fini;
SYDISP	internal  T!RSet;
SYDISP	internal boolean  T!ChrP;
SYDISP	internal integer  T!GetC;
SYDISP	internal simple  T!Flush;
SYDISP	simple  T!SBuf (string Str);
SYDISP	internal simple  T!Buf(integer Char);
SYDISP	simple  T!NBuf (integer N);
SYDISP	simple  Vt100Region (integer Top, Bottom);
SYDISP	internal simple  T!OutC(integer Char);
SYDISP	internal simple  T!Bell;
SYDISP	internal simple  T!ES;
SYDISP	internal simple  T!EL;
SYDISP	internal simple  T!CPos(integer Row, Col);
SYDISP	internal simple  T!IC(integer N);
SYDISP	internal simple  T!DC(integer N);
SYDISP	internal simple  T!IL;
SYDISP	internal simple  T!DL;
SYDISP	internal  R!Init;
SYDISP	simple  R!SetCursor(integer array Buffer);
SYDISP	internal simple  R!Disp (integer array Buffer; boolean PuntIfKeyHit; integer FinalRow, FinalColumn);
DT	simple integer  GetTimFrac;
NEXTIM	simple integer  GetDaOfWeek( integer dis );
NEXTIM	simple integer  YearNumb( integer disp );
NEXTIM	simple integer  MonthNumb( integer disp );
NEXTIM	simple integer  DaOfMonth( integer disp );
NEXTIM	simple integer  typeW( integer ArrAddr; integer baseDT );
NEXTIM	simple integer  typeN( integer ArrAddr; integer baseDT );
NEXTIM	simple integer  TypeT( integer ArrAddr; integer base );
NEXTIM	simple integer  typeS( integer ArrAddr; integer base );
NEXTIM	simple integer  FindModif( integer ArrAddr; integer ConnSought );
NEXTIM	internal simple integer  NexTim( integer ArrAddr, BasDatTim );
DEFOPR	simple  InitMemPointer;
DEFOPR	simple boolean  Ok2See( integer lic, flag );
DEFOPR	simple  Forget;
DEFOPR	simple  C.Verify;
DEFOPR	simple boolean  C.Imitate;
DEFOPR	simple  writeEntry( integer r );
DEFOPR	simple  C.Write;
DEFOPR	simple  C.Quit;
DEFOPR	Simple  C.Exit;
DEFOPR	C.Open;
DEFOPR	printEntry( reference integer r );
DEFOPR	simple  printGrant( integer g, ch );
DEFOPR	simple  ShowEntry( reference integer r );
DEFOPR	simple  EntryStatus( reference integer r );
DEFOPR	printTrace( reference integer r );
DEFOPR	simple  C.List;
DEFOPR	simple  C.Managed;
DEFOPR	simple  E!Transfer( reference integer r );
DEFOPR	simple  C.Transfer;
DEFOPR	simple  E!Grant( reference integer r );
DEFOPR	simple  C.Grant;
DEFOPR	simple  E!Remove( reference integer r );
DEFOPR	simple  C.Remove;
DEFOPR	simple  C.Show;
DEFOPR	simple  E!Hold( reference integer r );
DEFOPR	simple  E!Release( reference integer r );
DEFOPR	simple  C.Hold;
DEFOPR	simple  C.Release;
DEFOPR	simple  E!Password( reference integer r );
DEFOPR	simple  C.Password;
DEFOPR	simple  E!Change( reference integer r );
DEFOPR	simple  C.Change;
DEFOPR	simple  DumpGrant( reference integer g );
DEFOPR	simple  DumpEntry( reference integer r );
DEFOPR	simple  C.Dump;
DEFOPR	simple  E!Cancel( reference integer r );
DEFOPR	simple  C.Cancel;
DEFOPR	simple  E!Add( boolean Mailing );
DEFOPR	simple  C.Add;
DEFOPR	simple  C.Request;
DEFOPR	simple  C.Batch;
DEFOPR	simple  C.Debug;
DEFOPR	simple  C.Who;
DEFOPR	simple  C.Statistic;
DEFOPR	simple  C.Trace;
DEFOPR	simple  C.Index;
DEFOPR	simple  C.XYZZY;
DEFOPR	simple  C.Futz;
DEFOPR	simple  C.Brief;
DEFOPR	simple  C.Verbose;
DEFOPR	simple  C.Unlock;
DEFOPR	simple  C.Help;
DEFOPR	simple  C.HelpMe;
DEFOPR	simple  C.FixupTexts;         ! requires patch VM$Multi in C.Open ;
DEFOPR	Simple string  Perform!Command;
INIBAI	ST		simple  st;usererr(0,1,"BAIL","B");
FPARSE	FPARSE		Internal Simple Boolean  FParse(Value String Parse!string;
PROC	NEXTRECORD	Simple Boolean  NextRecord;
PACK	Simple  InitStuff;
PACK	Simple Integer  GetText( Reference string Line;
PACK	Simple Boolean  VMSpec( String Line );
PACK	boolean  WantFile( Reference Integer Filename, Extension );
PACK	FileProc( Reference Integer Chan, Cnt, Brk, FileEof;
PACK	Simple  Package;
PACK	Simple  UnPack;
CATTOT	BrkIni;
CATTOT	internal simple integer  FndKey( String Key; String Array CMD.Names );
CATTOT	simple string  Prompt( string P );
CATTOT	simple boolean  Numeric( String Str );
CATTOT	string  TOK ( reference string S );
CATTOT	Simple  DoSubtotal;
PCKSUB	simple boolean  agood( integer ext );
PCKSUB	recursive string  chars( integer N, L(1) );
PCKSUB	internal simple string  PCKDAT;
CMDDPY	simple integer  Install( integer BP; string S );
CMDDPY	simple  InitSysDpy;
CMDDPY	DisplayHelp;
CMDDPY	SetupBuffer;
CMDDPY	CommandScan;
CMDDPY	Snooze;
CARD01	simple integer  Install( integer BP; string S );
CARD01	simple  InitDpy;
CARD01	list  Shuffle( list D );
CARD01	DealCards;
CARD01	list  NewDeck( list Suits, EachSuit, Ranks, EachRank );
CARD01	BridgeDeck;
CARD01	ShowHand( list itemvar MyHand; integer R, C );
CARD01	DisplayHand;
CARD01	DisplayHelp;
CARD01	SetupBuffer;
CARD01	CommandScan;
CARD01	Snooze;
RANDOM	RANI		simple
RANDOM	RAN		internal simple integer  RAN( integer Top );
WOMQUE	string  EXIT(Integer Msg(0) );        ! string so it can be "printed" [ugh];
WOMQUE	Simple  IncLic;
WOMQUE	Simple  DecLic;
WOMQUE	Simple Integer  NewLic( Integer UserLic, FileLic(0) );
WOMQUE	simple  LicenseCheck;
WOMQUE	simple  InitUser;
WOMQUE	BrkIni;
WOMQUE	Initialize!switches;         ! Set to initial default (0,-1);
WOMQUE	ParIni
WOMQUE	string  CvNAME( integer AUN );
WOMQUE	internal simple  ABORT(reference integer WHY);
WOMQUE	simple string  DateString(Integer Type);
WOMQUE	simple  Fatal(String Msg);
WOMQUE	simple integer  GetTRU;
WOMQUE	ReadTimer( Reference Integer HH, MM, SS );
WOMQUE	Set!Delimiter( String Character );
WOMQUE	SetTimeLimit( Integer Limit );
WOMQUE	simple  SYNC;
WOMQUE	String  BoolToStr( Boolean T );       ! Boolean to String;
WOMQUE	Boolean  StrToBool( String S );       ! String to Boolean;
WOMQUE	RW!Item( String Itemvar W,R; Reference Boolean B);
WOMQUE	Date$( String Itemvar W, R);
WOMQUE	Day$( String Itemvar W, R);
WOMQUE	Daytime$( String Itemvar W, R);      ! Read-only * Time of day;
WOMQUE	Delimiter$(String Itemvar W, R);
WOMQUE	False$( String Itemvar W, R);
WOMQUE	Hour$( String Itemvar W, R);         ! Read-only * Time of day;
WOMQUE	HH$( String Itemvar W, R);   ! Read-only * Time of day;
WOMQUE	HHMM$( String Itemvar W, R);         ! Read-only * Time of day;
WOMQUE	HHMMSS$( String Itemvar W, R);       ! Read-only * Time of day;
WOMQUE	Logging$( String Itemvar W, R);
WOMQUE	Mail$( String Itemvar W, R);
WOMQUE	Minute$( String Itemvar W, R);       ! Read-only * Time of day;
WOMQUE	MMSS$( String Itemvar W, R);         ! Read-only * Time of day;
WOMQUE	MM$( String Itemvar W, R);
WOMQUE	Mon$( String Itemvar W, R);
WOMQUE	Month$( String Itemvar W, R);
WOMQUE	Numerics$( String Itemvar W, R);
WOMQUE	Second$( String Itemvar W, R);       ! Read-only * Time of day;
WOMQUE	SS$( String Itemvar W, R);           ! Read-only * Time of day;
WOMQUE	Substitution$( String Itemvar W, R);
WOMQUE	TimeLimit$(String Itemvar W, R);
WOMQUE	True$( String Itemvar W, R);
WOMQUE	Trulimit$( String Itemvar W, R);
WOMQUE	Tomorrow$( String Itemvar W, R);
WOMQUE	Weekday$( String Itemvar W, R);
WOMQUE	Yesterday$( String Itemvar W, R);
WOMQUE	Year$( String Itemvar W, R);
WOMQUE	YY$( String Itemvar W, R);
WOMQUE	ItemIni;                     ! Alphabetical;
WOMQUE	simple boolean  Numeric(String Str);
WOMQUE	string  TOK (reference string S);
WOMQUE	simple string  WScan(  Reference String Str; Integer C;
WOMQUE	simple string  GetFil( Reference string Str, Dev;
WOMQUE	MOV ( itemvar DST,SRC );
WOMQUE	String  Substitute(Integer Chan; String Key);
WOMQUE	simple string  Get!Token(Reference string Par!Lst);
WOMQUE	New!Parameter(Integer Chan; String Name, Initial!Value, New!Value);
WOMQUE	simple  Set!Parameter(Reference string Par!Lst);
WOMQUE	Forget!substitutions;
WOMQUE	string  Make!List(String Text!, L!Quote, R!Quote);
WOMQUE	String  parametize(Value String S);
WOMQUE	simple  HELP;
WOMQUE	simple  NEWS;
WOMQUE	simple  Apply!switch!defaults;
WOMQUE	simple string  print!switch(String Nam);
WOMQUE	simple integer  checksw(String Txt, Val);
WOMQUE	boolean  legal!switch(Reference string S);
WOMQUE	DoDETACH;
WOMQUE	simple boolean  Check!Command(String KW);
WOMQUE	simple boolean  Check!Logfile(Reference string Filename);
WOMQUE	FRONT!END;
WOMQUE	REASSIGN (string CMD);
WOMQUE	COM (string CMD);
WOMQUE	ESCAPE;
WOMQUE	GOTO (string CMD);
WOMQUE	LOGFILE (string CMD);
WOMQUE	PARAMETERS(String CMD);
WOMQUE	simple  QUIT;
WOMQUE	SEND (string CMD);
WOMQUE	simple  STOP;
WOMQUE	TIME (string CMD);
WOMQUE	recursive  COMMAND (string CMD);
WOMQUE	Simple  Do!Cleanup;
UNIQUE	boolean  WantFile( Reference Integer Filename, Extension );
UNIQUE	FileProc( Reference Integer Chan, Cnt, Brk, FileEof;
JQUE	simple  SetupBasePage;
JQUE	Simple  GetLock;
JQUE	simple  UnLock;
JQUE	simple integer  MapQuePage;
JQUE	simple boolean  MapRecord( Integer r );
JQUE	simple boolean  ArrCMP(reference integer LOC1, LOC2; integer Count);
JQUE	Simple  Wrap;
JQUE	Simple integer  NextSequence;
JQUE	Internal simple  ClsQue;
JQUE	simple boolean  OpenQueue;
JQUE	Simple boolean  GetArea( Integer Mem, Dsk, Bit, Size(1) );
JQUE	internal simple boolean  OpnQue( integer Bits );
JQUE	simple boolean  FindRecord( integer A );
JQUE	simple boolean  NextRecord( integer A );
JQUE	simple  DeleteRecord;
JQUE	internal simple boolean  GetRec( integer A; integer Force(0) );
JQUE	internal simple boolean  ModRec( integer A, S );
BIONIC	Simple  Text( string s );
BIONIC	Simple  Finish( String Msg );
BIONIC	Simple Integer  FndKey( String Key; String Array CMD.Names );
BIONIC	Simple Integer 
BIONIC	Simple Boolean  VMSpec( String Line );
BIONIC	Simple  NextPage;
BIONIC	Simple  Deposit( Integer Char );
BIONIC	Simple  Wait4YB;
BIONIC	Simple  PrintBuffer;
BIONIC	Simple  RunIt;
REDALL	simple  check( integer chan, size );
REDALL	boolean  WantUfd( Reference Integer Aun );
REDALL	UfdProc( Reference Integer Chan; Integer array LKB );
REDALL	boolean  WantFile( Reference Integer Filename, Extension );
REDALL	FileProc( Reference Integer Chan, Cnt, Brk, FileEof;
CHKLST	 BrkIni;
CHKLST	internal simple integer  FndKey( String Key; String Array CMD.Names );
CHKLST	simple string  Prompt( string P );
CHKLST	simple boolean  Numeric( String Str );
CHKLST	string  TOK ( reference string S );
CHKADD	BrkIni;
CHKADD	internal simple integer  FndKey( String Key; String Array CMD.Names );
CHKADD	simple string  Prompt( string P );
CHKADD	simple boolean  Numeric( String Str );
CHKADD	string  TOK ( reference string S );
PRTTRP	simple  ZAP( Integer Bits );
PRTTRP	Simple  ZAP}&"ZapC"&{;
PRTTRP	simple  LOS;  GetInt( LOS!,LXROCL lor LXRICL );
PRTTRP	simple  ORG;  GetInt( ORG!,LXROBS );  ! check for OBS and return ;
PRTTRP	simple  CHR;  GetInt( CHR!,LXRBRK );  ! check for BRK and return ;
PRTTRP	internal simple  intZap( integer Port );
PRTTRP	internal simple  PrtDis;      ! disable all interrupts ;
PRTTRP	internal simple  intPrt( integer Port );
HSB	internal simple 
HSB	simple  InitStates;
HSB	simple  EachEntry;
LICSUB	internal simple string  LicPrt( integer License );
LICSUB	simple integer  ReadLic( string License; Integer Size );
LICSUB	internal simple integer  LicRd( string License );
LICSUB	internal simple integer  LicEnt( string License );
LICSUB	internal simple integer  LicOr( integer Lic1, Lic2 );
LICSUB	internal simple integer  LicAnd( integer Lic1, Lic2 );
LICSUB	internal simple integer  LicNot( integer Lic1, Lic2 );
LICSUB	internal simple integer  LicVal( integer Lic1, Lic2 );
LICSUB	internal simple boolean  LicChk( integer Have, Want );
SYF	simple string  CVHMS( integer HMS );
SYF	simple string  TMin( Integer Min );
SYF	simple integer  Install( integer BP; string S );
SYF	simple  Section( string Str, Head( NULL ); integer AddCol( 0 ) );
SYF	simple string  ShowInfo( Integer Arg );
SYF	simple  InitSysDpy;
SYF	Simple  CollectJobInfo;
SYF	simple  InstallSystemInfo;
SYF	simple  DisplayJobInfo;
SYF	simple  CrashwithFrmop;
SYF	simple  DisplayDisk;
SYF	simple  DisplayFRECOR;
SYF	simple  DisplayTTYTAB;
SYF	DisplayHelp;
SYF	SetupBuffer;
SYF	CommandScan;
SYF	Snooze;
WOMBAT	string  EXIT(Integer Msg(0) );        ! string so it can be "printed" [ugh];
WOMBAT	Simple  IncLic;
WOMBAT	Simple  DecLic;
WOMBAT	Simple Integer  NewLic( Integer UserLic, FileLic(0) );
WOMBAT	simple  LicenseCheck;
WOMBAT	simple  InitUser;
WOMBAT	simple  SetDetach;
WOMBAT	BrkIni;
WOMBAT	Initialize!switches;         ! Set to initial default (0,-1);
WOMBAT	ParIni;
WOMBAT	string  CvNAME( integer AUN );
WOMBAT	internal simple  ABORT(reference integer WHY);
WOMBAT	simple string  DateString(Integer Type);
WOMBAT	simple  Fatal(String Msg);
WOMBAT	simple integer  GetTRU;
WOMBAT	ReadTimer( Reference Integer HH, MM, SS );
WOMBAT	Set!Delimiter( String Character );
WOMBAT	SetTimeLimit( Integer Limit );
WOMBAT	simple  SYNC;
WOMBAT	simple  OutPtr (integer PORT; string S);
WOMBAT	String  BoolToStr( Boolean T );       ! Boolean to String;
WOMBAT	Boolean  StrToBool( String S );       ! String to Boolean;
WOMBAT	RW!Item( String Itemvar W,R; Reference Boolean B);
WOMBAT	Date$( String Itemvar W, R);
WOMBAT	Day$( String Itemvar W, R);
WOMBAT	Daytime$( String Itemvar W, R);      ! Read-only * Time of day;
WOMBAT	Delimiter$(String Itemvar W, R);
WOMBAT	False$( String Itemvar W, R);
WOMBAT	Hour$( String Itemvar W, R);         ! Read-only * Time of day;
WOMBAT	HH$( String Itemvar W, R);   ! Read-only * Time of day;
WOMBAT	HHMM$( String Itemvar W, R);         ! Read-only * Time of day;
WOMBAT	HHMMSS$( String Itemvar W, R);       ! Read-only * Time of day;
WOMBAT	Logging$( String Itemvar W, R);
WOMBAT	Mail$( String Itemvar W, R);
WOMBAT	Minute$( String Itemvar W, R);       ! Read-only * Time of day;
WOMBAT	MMSS$( String Itemvar W, R);         ! Read-only * Time of day;
WOMBAT	MM$( String Itemvar W, R);
WOMBAT	Mon$( String Itemvar W, R);
WOMBAT	Month$( String Itemvar W, R);
WOMBAT	Numerics$( String Itemvar W, R);
WOMBAT	Second$( String Itemvar W, R);       ! Read-only * Time of day;
WOMBAT	SS$( String Itemvar W, R);           ! Read-only * Time of day;
WOMBAT	Substitution$( String Itemvar W, R);
WOMBAT	TimeLimit$(String Itemvar W, R);
WOMBAT	True$( String Itemvar W, R);
WOMBAT	Trulimit$( String Itemvar W, R);
WOMBAT	Tomorrow$( String Itemvar W, R);
WOMBAT	Weekday$( String Itemvar W, R);
WOMBAT	Yesterday$( String Itemvar W, R);
WOMBAT	Year$( String Itemvar W, R);
WOMBAT	YY$( String Itemvar W, R);
WOMBAT	ItemIni;                     ! Alphabetical;
WOMBAT	simple boolean  Numeric(String Str);
WOMBAT	string  TOK (reference string S);
WOMBAT	simple string  WScan(  Reference String Str; Integer C;
WOMBAT	simple string  GetFil( Reference string Str, Dev;
WOMBAT	MOV ( itemvar DST,SRC );
WOMBAT	String  Substitute(Integer Chan; String Key);
WOMBAT	simple string  Get!Token(Reference string Par!Lst);
WOMBAT	New!Parameter(Integer Chan; String Name, Initial!Value, New!Value);
WOMBAT	simple  Set!Parameter(Reference string Par!Lst);
WOMBAT	Forget!substitutions;
WOMBAT	string  Make!List(String Text!, L!Quote, R!Quote);
WOMBAT	String  parametize(Value String S);
WOMBAT	simple  HELP;
WOMBAT	simple  NEWS;
WOMBAT	simple  Apply!switch!defaults;
WOMBAT	simple string  print!switch(String Nam);
WOMBAT	simple integer  checksw(String Txt, Val);
WOMBAT	boolean  legal!switch(Reference string S);
WOMBAT	integer  Create!Child;
WOMBAT	DoDETACH;
WOMBAT	Logout!Child;
WOMBAT	simple boolean  Check!Command(String KW);
WOMBAT	simple boolean  Check!Logfile(Reference string Filename);
WOMBAT	FRONT!END;
WOMBAT	simple  SPROUT;
WOMBAT	Simple  LOGOUT!Frame;
WOMBAT	REASSIGN (string CMD);
WOMBAT	COM (string CMD);
WOMBAT	ESCAPE;
WOMBAT	GOTO (string CMD);
WOMBAT	LOGFILE (string CMD);
WOMBAT	PARAMETERS(String CMD);
WOMBAT	simple  QUIT;
WOMBAT	SEND (string CMD);
WOMBAT	simple  STOP;
WOMBAT	TIME (string CMD);
WOMBAT	recursive  COMMAND (string CMD);
WOMBAT	Simple  Do!Cleanup;
VMFOO	string  TOK (reference string Str);
VMFOO	simple string  p( string text );
VMFOO	Simple  DoOpen;
VMFOO	Simple  DoClose;
VMFOO	Simple  DoPrint;
VMFOO	Simple  DoMove;
VMFOO	Simple  DoWrite;
VMFOO	simple  doCopy;
VMFOO	Simple  DoMessage;
VMFOO	Simple  HelpMe;
VMFOO	Simple  Status;
VMFOO	Simple  DoSet;
LUDLST	simple  arrPrint;
PCOM	string  EXIT(Integer Msg(0) );        ! string so it can be "printed" [ugh];
PCOM	Simple  IncLic;
PCOM	Simple  DecLic;
PCOM	Simple Integer  NewLic( Integer UserLic, FileLic(0) );
PCOM	simple  LicenseCheck;
PCOM	simple  InitUser;
PCOM	simple  SetDetach;
PCOM	BrkIni;
PCOM	Initialize!switches;         ! Set to initial default (0,-1);
PCOM	ParIni;
PCOM	string  CvNAME( integer AUN );
PCOM	internal simple  ABORT(reference integer WHY);
PCOM	simple string  DateString(Integer Type);
PCOMle  Fatal(String Msg);
PCOM	simple integer  GetTRU;
PCOM	ReadTimer( Reference Integer HH, MM, SS );
PCOM	Set!Delimiter( String Character );
PCOM	SetTimeLimit( Integer Limit );
PCOM	simple  SYNC;
PCOM	simple  OutPtr (integer PORT; string S);
PCOM	String  BoolToStr( Boolean T );       ! Boolean to String;
PCOM	Boolean  StrToBool( String S );       ! String to Boolean;
PCOM	RW!Item( String Itemvar W,R; Reference Boolean B);
PCOM	Date$( String Itemvar W, R);
PCOM	Day$( String Itemvar W, R);
PCOM	Daytime$( String Itemvar W, R);      ! Read-only * Time of day;
PCOM	Delimiter$(String Itemvar W, R);
PCOM	False$( String Itemvar W, R);
PCOM	Hour$( String Itemvar W, R);         ! Read-only * Time of day;
PCOM	HH$( String Itemvar W, R);   ! Read-only * Time of day;
PCOM	HHMM$( String Itemvar W, R);         ! Read-only * Time of day;
PCOM	HHMMSS$( String Itemvar W, R);       ! Read-only * Time of day;
PCOM	Logging$( String Itemvar W, R);
PCOM	Mail$( String Itemvar W, R);
PCOM	Minute$( String Itemvar W, R);       ! Read-only * Time of day;
PCOM	MMSS$( String Itemvar W, R);         ! Read-only * Time of day;
PCOM	MM$( String Itemvar W, R);
PCOM	Mon$( String Itemvar W, R);
PCOM	Month$( String Itemvar W, R);
PCOM	Numerics$( String Itemvar W, R);
PCOM	Second$( String Itemvar W, R);       ! Read-only * Time of day;
PCOM	SS$( String Itemvar W, R);           ! Read-only * Time of day;
PCOM	Substitution$( String Itemvar W, R);
PCOM	TimeLimit$(String Itemvar W, R);
PCOM	True$( String Itemvar W, R);
PCOM	Trulimit$( String Itemvar W, R);
PCOM	Tomorrow$( String Itemvar W, R);
PCOM	Weekday$( String Itemvar W, R);
PCOM	Yesterday$( String Itemvar W, R);
PCOM	Year$( String Itemvar W, R);
PCOM	YY$( String Itemvar W, R);
PCOM	ItemIni;                     ! Alphabetical;
PCOM	simple boolean  Numeric(String Str);
PCOM	string  TOK (reference string S);
PCOM	simple string  WScan(  Reference String Str; Integer C;
PCOM	simple string  GetFil( Reference string Str, Dev;
PCOM	MOV ( itemvar DST,SRC );
PCOM	String  Substitute(Integer Chan; String Key);
PCOM	simple string  Get!Token(Reference string Par!Lst);
PCOM	New!Parameter(Integer Chan; String Name, Initial!Value, New!Value);
PCOM	simple  Set!Parameter(Reference string Par!Lst);
PCOM	Forget!substitutions;
PCOM	string  Make!List(String Text!, L!Quote, R!Quote);
PCOM	String  parametize(Value String S);
PCOM	simple  HELP;
PCOM	simple  NEWS;
PCOM	simple  Apply!switch!defaults;
PCOM	simple string  print!switch(String Nam);
PCOM	simple integer  checksw(String Txt, Val);
PCOM	boolean  legal!switch(Reference string S);
PCOM	integer  Create!Child;
PCOM	DoDETACH;
PCOM	Logout!Child;
PCOM	simple boolean  Check!Command(String KW);
PCOM	simple boolean  Check!Logfile(Reference string Filename);
PCOM	FRONT!END;
PCOM	simple  SPROUT;
PCOM	Simple  LOGOUT!Frame;
PCOM	REASSIGN (string CMD);
PCOM	COM (string CMD);
PCOM	ESCAPE;
PCOM	GOTO (string CMD);
PCOM	LOGFILE (string CMD);
PCOM	PARAMETERS(String CMD);
PCOM	simple  QUIT;
PCOM	SEND (string CMD);
PCOM	simple  STOP;
PCOM	TIME (string CMD);
PCOM	recursive  COMMAND (string CMD);
PCOM	Simple  Do!Cleanup;
SHOVEL	Simple  Text( string s );
SHOVEL	Simple  Finish( String Msg );
SHOVEL	Simple  CheckBuffer;
SHOVEL	Simple  RunIt( Integer InPort, OutPort )
SHOVEL	Simple  C.Debug;
SHOVEL	simple  C.Quit;
SHOVEL	simple  C.Help;
SHOVEL	simple  C.HelpMe;
SHOVEL	Simple  C.Exit;
SHOVEL	Simple string  Perform!Command;
CARDX	simple integer  Install( integer BP; string S );
CARDX	simple boolean  NeedHelp( string text(null) );
CARDX	simple  InitDpy;
CARDX	simple string  Cviss( integer iv; string str( "Unknown" ) );
CARDX	simple string  TextSuit( integer iz );
CARDX	simple  Shuffle( integer array D );
CARDX	Simple  DealCards;
CARDX	BridgeDeck;
CARDX	simple integer  CardCount( integer Card );
CARDX	simple string  TextHand( integer MyHand );
CARDX	simple string  TextBid( integer MyBid );
CARDX	simple integer  PackBid( string BidText );
CARDX	simple  ShowHand( integer H, R, C );
CARDX	DisplayHand;
CARDX	DisplayHelp;
CARDX	SetupBuffer;
CARDX	simple  SetupDummy;
CARDX	simple  FigureBid;
CARDX	boolean  NewHand( string S );
CARDX	simple boolean  OffLine( integer Arg, Cmd );
CARDX	simple  NewDeal( integer Arg( 0 ) );
CARDX	simple integer  BestHand( integer Meld );
CARDX	boolean  FixupBidding;
CARDX	simple boolean  TheBid( integer Arg, Suit );
CARDX	boolean  ThePlay( integer Arg, Suit );
CARDX	CommandScan;
CARDX	Snooze;
ESCTRP	simple  ESC;   ESC!_ true;    ! set ESC flag and return ;
ESCTRP	simple  NTQ;  NTQ!_ true;     ! set NTQ flag and return ;
ESCTRP	simple  TIM;  TIM!_ true;     ! set TIM flag and return ;
ESCTRP	internal simple  EXCINI;
ESCTRP	internal simple  TIMEnb;
ESCTRP	internal simple  NTQEnb;
ESCTRP	internal simple  EscEnb;
ESCTRP	internal simple  EscDis;
ESCTRP	internal simple  TimDis;
ESCTRP	internal simple  NTQDis;
ESCTRP	internal simple  EXCDIS;
ESCTRP	internal simple  SetTim( integer Time, Units( 0 ) );
VMFILE	simple  Set.FN( integer Slot; string Str );
VMFILE	simple string  Get.FN( integer Slot );
VMFILE	Simple  InitVM;
VMFILE	Internal Simple  VMInit( Integer C(-1),P(-1));
VMFILE	Internal Simple Integer  VMPMap( Integer Slot, NewPage, What(1) );
VMFILE	Simple Integer  FindPage( Integer Count(1), Page(-1) );
VMFILE	Internal Simple Integer  VMName( String Name; Integer Mode(-1) );
VMFILE	Integer  VMSlot( Integer Count(1), Page(-1) );
VMFILE	Internal simple integer  VMPtrB( integer Slot, Pos );
VMFILE	Internal simple integer  VMPtrW( integer Slot, Word );
VMFILE	Internal Simple Integer  VMGetB( Integer Slot, Pos(-1) );
VMFILE	Internal Simple Integer  VMSetB( Integer Slot, Char, Pos(-1) );
VMFILE	Internal Simple Integer  VMGetW( Integer Slot, Word(-1) );
VMFILE	Internal Simple Integer  VMSetW( Integer Slot, Data, Word(-1) );
VMFILE	Internal Simple Integer  VMGetC( Integer Slot, Index(VM$Pos) );
VMFILE	Internal Simple Integer  VMSetC( Integer Slot, Position );
VMFILE	Internal Simple Boolean  VMFree( Integer Slot, Bits(0) );
VMFILE	Internal Simple Boolean 
VMFILE	Simple Integer  Dbp( Reference Integer Ptr );
VMFILE	Internal String  VMLine( Integer Slot; Reference Integer More;
VMFILE	Internal Boolean  VMText( Integer Slot; String Text );
VMFILE	Internal Boolean  VMMove( Integer Slot, HowMany(1) );
UNDELE	simple  Endprog;
UNDELE	simple  Errxit(integer Value,Code; string Msg);
UNDELE	simple  Dskopenerr;
UNDELE	simple  Diritinierr;
UNDELE	simple boolean  Endisini;
UNDELE	simple boolean  Slash3;
UNDELE	simple  Supdirini;
UFDINI	simple boolean  WildMatch (string Name, Ename);
UFDINI	simple string  STTIME (integer TIME);
UFDINI	simple integer  Getlch;
UFDINI	Getownr;
UFDINI	Prnerr (integer errwrd);
UFDINI	helpmsg;
UFDINI	strngchk (string !LET,CM);
UFDINI	Getrecent (reference record!pointer(any!class) filptr,endptr;
UFDINI	modechk(reference string STRNGLN;
UFDINI	simple  setupbreaktables;
UFDINI	strngchk(Frstlet,Tempcmd); ! Call  that does actual checking;
DPY	SearchTTY (string Arg(null));
DPY	simple  Seek (integer Y,X(1));
DPY	simple  NewPage;
DPY	simple  ClearEOL;
DPY	simple  Write (string S);
DPY	read (reference string S);
PGCOPY	Internal Simple  PGCErr( Integer ErrorCode );
PGCOPY	Internal simple integer  PGCopy(
FRMTST	simple  ERR;  ERR!_ true;
FRMTST	simple  ECF;  ECF!_ true;
FRMTST	simple  LCF;  LCF!_ true;
FRMTST	simple  FEX;  FEX!_ true;
FRMTST	simple  SIP;  SIP!_ true;
FRMTST	simple  SIC;  SIC!_ true;
FRMTST	simple  SIS;  SIS!_ true;
FRMTST	simple  SIA;  SIA!_ true;
FRMTST	internal simple  FrmDis( integer Frame );
FRMTST	internal simple  FrmEnb( integer Frame );
FRMTST	Simple  KillJob( Integer J );
FRMTST	simple boolean  Create!Child;
FRMTST	simple  FrmXct(Integer Frame; Reference Integer Arg; Integer Funct);
SWITCH	Internal String  SW!INI(String Name(null), Option(null);
SWITCH	String  Get!line;
LOGPKG	Internal Simple  Talk( integer job; string text );
LOGPKG	Internal Simple boolean  CTYLog( String Text; Boolean Date(false) );
LOGPKG	simple 
LOGPKG	internal simple  SetLog( String File; Boolean Critical( false ) );
LOGPKG	internal simple  LogInfo( String Text; Boolean Time(true) );
LOGPKG	internal simple  LogOnly( String Text; Boolean Time(true) );
LOGPKG	simple  LogItAll( String Name; Integer Array Data; Integer Tries(LogTry) );
LOGPKG	internal simple  LogBin( Integer Array Data );
MAPPIN	EXTERNAL SIMPLE BOOLEAN  FPARSE(VALUE STRING PARSE!STRING;
CVDATE	internal simple string  CvDate ( integer Date.In );
MONEDK	simple  Ini;
MONEDK	recursive string  INCR(string S);
MONEDK	OpenMemFile (string FileName);
MONEDK	CloseMemFile;
MONEDK	MapRW (integer Ptr);
MONEDK	simple integer  ReadWord;
MONEDK	simple string  ReadLine;
MONEDK	simple  WriteLine (string S);
MONEDK	simple  WriteHeading (string S);
MONEDK	simple  ParseMEM;
MONEDK	string  NameMEM;
MONEDK	simple  IniBreak;
MONEDK	simple  MonParse (
MONEDK	string  NextSYSID;
MONEDK	simple  P10INI;
MONEDK	string  CnfnVersion( string SysNo );
MONEDK	CnfnUpdate( string SysNo, SName, SDate );
MONEDK	simple  CrlfIni;
MONEDK	MsgUpdate( string SysNo, SName, SDate );
MONEDK	MemUpdate (string S);
MONEDK	simple  BTSMini;
MONEDK	SuperMajor(string S);
INTTRP	Internal simple  IntMak( integer intChan );
CATTAX	simple string  prompt(string msg);
CARDS	simple integer  Install( integer BP; string S );
CARDS	simple boolean  NeedHelp( string text(null) );
CARDS	simple  InitDpy;
CARDS	simple string  Cviss( integer iv; string str( "Unknown" ) );
CARDS	simple string  TextSuit( integer iz );
CARDS	simple  Shuffle( integer array D );
CARDS	Simple  DealCards;
CARDS	BridgeDeck;
CARDS	simple integer  CardCount( integer Card );
CARDS	simple string  TextHand( integer MyHand );
CARDS	simple string  TextBid( integer MyBid );
CARDS	simple integer  PackBid( string BidText );
CARDS	simple  ShowHand( integer H, R, C );
CARDS	DisplayHand;
CARDS	DisplayHelp;
CARDS	SetupBuffer;
CARDS	simple  SetupDummy;
CARDS	simple  FigureBid;
CARDS	boolean  NewHand( string S );
CARDS	simple boolean  OffLine( integer Arg, Cmd );
CARDS	simple  NewDeal( integer Arg( 0 ) );
CARDS	simple integer  BestHand( integer Meld );
CARDS	boolean  FixupBidding;
CARDS	simple boolean  TheBid( integer Arg, Suit );
CARDS	boolean  ThePlay( integer Arg, Suit );
CARDS	CommandScan;
CARDS	Snooze;
OPRPKG	internal simple integer  RadX45( Integer C );
OPRPKG	internal simple string  OprGet;
OPRPKG	internal simple  OprHsh( reference integer L; reference string Name );
OPRPKG	internal simple string  OprTxt( reference integer Name );
OPRPKG	internal simple integer  PasHsh( string PW );
OPRPKG	internal simple string  PasGet( string Text("Password: ") );
FRMRUN	internal integer  FRMRUN(
FRMRUN	Simple  SetupParentFrame;
FRMRUN	Simple Boolean  HSERR;
FRMRUN	Simple Boolean  FOERR;
FRMRUN	Simple Boolean  WaitForHalt;
FRMRUN	Simple Integer  CreateFrame;
FRMRUN	Simple Boolean  SaveFrame;
FRMRUN	Simple Boolean  ClearFrame;
FRMRUN	Simple Boolean  KillFrame;
FRMRUN	Simple  CheckHaltStatus;
FRMRUN	Simple Boolean  GetProgram;
FRMRUN	Simple Boolean  StartProgram;
FRMRUN	Simple Boolean  MoveTTY;
FRMRUN	Simple Boolean  GiveAwayTTY;
FRMRUN	Simple Boolean  RetrieveTTY;
FRMRUN	Simple Boolean  ParseFileName( String FileName; integer array ARG );
FRMRUN	simple boolean  Goodbye( boolean arg );
FRMRUN	Simple Boolean  WriteTempFile( Integer Job );
NEWFIL	simple  Commands( reference integer r );
NEWFIL	simple  C.Change;
SY	string  CVHMS( integer HMS );
SY	InitSysDpy;
SY	Simple Boolean  HowMuch;
SY	integer  Install( integer BP; string S );
SY	ShowLine( String  Header, Text;
SY	InstallSystemInfo;
SY	InstallDiskInfo;
SY	InstallJobInfo;
SY	SetupBuffer;
SY	integer  ScanNumber;
SY	SetSleepTime;
SY	OmitJobs;
SY	IncludeJobs;
SY	CommandParse;
SY	CommandScan;
SY	Snooze;
CMDSCN	Internal Simple String  ReScan;
CMDSCN	simple  Fatal( String Reason );
CMDSCN	Internal simple string  CToken (reference string S);
CMDSCN	internal recursive string  AtLine( Boolean Typeit (False) );
CMDSCN	Internal Integer  FndKey(
CMDSCN	Internal Integer  FndCmd(
CMDSCN	Internal String  CmdLin(
CMDSCN	Internal  CmdScn(
EDIT10	 EDIT10(string File,Cmds);
PCOINT	external simple  abort( Reference Integer Why );
PCOINT	simple  SetupBasePage;
PCOINT	simple  initititit;
PCOINT	simple  logit(integer logelement);
PCOINT	Internal simple  IntCause( integer intChan );
PCOINT	does!call!proc( r!p(Circuit) why; r!p(buffer) what;... Perform );
PCOINT	simple  call!proc( r!p(Circuit) why; r!p(buffer) what;
PCOINT	recursive  noSpace( r!p(Circuit) which );
PCOINT	recursive  bufferFinished( r!p(Circuit) which; 
PCOINT	internal boolean simple  finishTop( r!p(Circuit) it );
PCOINT	simple  setIntMap( integer index; r!p(Circuit) theRec );
PCOINT	internal recursive  addBuffer( r!p(Circuit) which; 
PCOINT	r!p(buffer) recursive  new!buffer( integer chars,
PCOINT	internal r!p(Circuit) recursive  new!circuit(
PCOINT	recursive integer  NewFilePage( r!p(circuit) c );
PCOINT	recursive  one.sample( reference r!p(Circuit) int;
PCOINT	Internal simple  IntZap;
PCOINT	ZAP;
PCOINT	simple  ORG;  ORG! _ true;    ! wake up SYNC;
PCOINT	simple  NTQ;  abort(NTQ!);    ! abort & wake up SYNC;
PCOINT	simple  TIM;  abort(TIM!);    ! abort & wake up SYNC;
PCOINT	XINT (reference integer MC4;  MC2);
PCOINT	MC2;                        ! call int service ;
PCOINT	simple  QINT;
PCOINT	IntPort( Integer  port, cause, interrupt,
PCOINT	Internal integer  IntFin;
PCOINT	internal simple  IntLog( Boolean LogVariable );
PCOINT	Internal simple  INTINI(itemvar INTPRO;
PCOINT	simple  DEFMAP (integer INDEX;  PROC);
FRMTRP	simple  ECF( Integer Bits );
FRMTRP	simple  LCF( Integer Bits );
FRMTRP	Simple  ECF}&"FEXC"&{;
FRMTRP	Simple  LCF}&"FEXC"&{;
FRMTRP	simple  Dummy;        begin end;
FRMTRP	simple  FEX;  FEX!_ true;
FRMTRP	simple  SIP;  SIP!_ true;
FRMTRP	simple  SIC;  SIC!_ true;
FRMTRP	simple  SIS;  SIS!_ true;
FRMTRP	simple  SIA;  SIA!_ true;
FRMTRP	internal simple  FrmDis( integer Frame );
FRMTRP	internal simple  EcfDis( integer Frame );
FRMTRP	internal simple  LcfDis( integer Frame );
FRMTRP	internal simple  FEXDis;  disable( newenb( int!FEX ) );
FRMTRP	internal simple  SIPDis;  disable( newenb( int!SIP ) );
FRMTRP	internal simple  SICDis;  disable( newenb( int!SIC ) );
FRMTRP	internal simple  SISDis;  disable( newenb( int!SIS ) );
FRMTRP	internal simple  SIADis;  disable( newenb( int!SIA ) );
FRMTRP	internal simple  FrmEnb( integer Frame );
FRMTRP	internal simple  EcfEnb( integer Frame );
FRMTRP	internal simple  LcfEnb( integer Frame );
FRMTRP	internal simple  FEXEnb;  enable( newenb( int!FEX ) );
FRMTRP	internal simple  SIPEnb;  enable( newenb( int!SIP ) );
FRMTRP	internal simple  SICEnb;  enable( newenb( int!SIC ) );
FRMTRP	internal simple  SISEnb;  enable( newenb( int!SIS ) );
FRMTRP	internal simple  SIAEnb;  enable( newenb( int!SIA ) );
GETLIC	simple  LevDef;
GETLIC	string  get!line;
GETLIC	internal long real  GetOpr( string Name(null) );
GETLIC	Simple Integer  Radix.45(Integer Ch);
GETLIC	integer  CVHASH(string PW);
GETLIC	internal integer  GetLic( string OPN(null) );
DSKCHK	simple boolean  Compare( integer Buf1, Buf2 );
DSKCHK	simple  MapNext( integer Size(BufferSize) );
DSKCHK	simple  DumpNext( integer Size(BufferSize) );
PASPKG	simple integer  Radix.45( Integer Ch );
PASPKG	simple string  GetNam;
PASPKG	internal  OpHash( reference integer L; reference string Name );
PASPKG	internal string  NamOpr( reference integer Name );
PASPKG	internal simple integer  CvHash( string PW );
PASPKG	simple string  GetPas;
PASPKG	internal simple string  PasErr( integer Code );
PASPKG	internal integer  GetLic( reference integer OperName, Hash );
VMARGP	simple  BreakIni;
VMARGP	simple  InitProgramName;
VMARGP	internal simple  ArgArr( itemvar dst; integer src );
VMARGP	simple  MError( string Msg1, Msg2, Msg3 );
VMARGP	simple  VError( string Msg1; itemvar Msg2; string Msg3 );
VMARGP	AccuParse( itemvar IV; string ST );
VMARGP	internal boolean 
VMARGP	SetOption( reference string S; reference integer B;
VMARGP	internal boolean  ArgParse( itemvar OFs,IFs; set Opts; string Line );
VMARGP	Accu;
CATREC	BrkIni;
CATREC	internal simple integer  FndKey( String Key; String Array CMD.Names );
CATREC	simple string  Prompt( string P );
CATREC	simple boolean  Numeric( String Str );
CATREC	string  TOK ( reference string S );
MONED1	simple  Ini;
MONED1	recursive string  INCR(string S);
MONED1	OpenMemFile (string FileName);
MONED1	CloseMemFile;
MONED1	MapRW (integer Ptr);
MONED1	simple integer  ReadWord;
MONED1	simple string  ReadLine;
MONED1	simple  WriteLine (string S);
MONED1	simple  WriteHeading (string S);
MONED1	simple  ParseMEM;
MONED1	string  NameMEM;
MONED1	simple  IniBreak;
MONED1	simple  MonParse (
MONED1	string  NextSYSID;
MONED1	simple  P10INI;
MONED1	simple boolean  Find( reference string S; string M );
MONED1	string  CnfnVersion( string SysNo );
MONED1	CnfnUpdate( string SysNo, SName, SDate );
MONED1	MsgUpdate( string SysNo, SName, SDate );
MONED1	MemUpdate (string S);
MONED1	simple  BTSMini;
MONED1	SuperMajor(string S);
PCODUL	InitDULStuff;
PCODUL	internal string  CVUser( integer PPN );
INFO	external  $recgc;   ! record garbage collector;
INFO	simple set  ARG!(integer CMD); begin "ARG!"
INFO	simple string  BNF!(integer CMD); begin "BNF!"
INFO	forward simple  PROMPT (string P("{~}"));
INFO	simple  outstr(string X);
INFO	simple  outchr(integer X);
INFO	forward boolean  GET!COMMAND(string P(null));
INFO	simple integer  PEEK; begin "PEEK"
INFO	simple string  SPACE(integer CNT); begin "SPACE"
INFO	simple  PROMPT(string P("{~}")); begin "PROMPT"
INFO	simple  MSG(string M); begin "MSG"
INFO	simple  SET!HEAD(string ID;
INFO	PAGE!BREAK; begin "PAGE!BREAK"
INFO	SEND(string S); begin "SEND"
INFO	forward boolean  LOCATE(string S;
INFO	simple  WHERE; begin "WHERE"
INFO	SET!(string ARG1(null)); begin "SET!"
INFO	force(integer C); begin "force"
INFO	simple  DEF!(set T); begin "DEF!"
INFO	simple  HELP; begin "HELP"
INFO	string  COMMANDS; begin "COMMANDS"
INFO	integer  GET!COMMAND(string P(null)); begin "GET!COMMAND"
INFO	  FLOP(string MESS); begin "FLOP"
INFO	set  PARSE(string ARG; set ARG!); begin "PARSE"
INFO	simple integer  Compare(string A,B);
INFO	BOMB(string M); begin "BOMB"
INFO	kill!temp(string FILE); begin "TD"
INFO	string  read!temp(string NAME;
INFO	boolean  LOCATE(string S;
INFO	 recursive  LOCATOR(record!pointer(NODE) M); begin "LOR"
INFO	simple boolean  SEC!HEAD(string S); begin "SEC!HEAD"
INFO	string  GET!LINE; begin "GET!LINE"
INFO	boolean  OPEN!NODE(record!pointer(NODE)N;
INFO	integer  CRE!DATE;    ! 14-bit date in LH, 11-bit GMT time in RH;
INFO	MENU!SCAN(record!pointer(NODE)N;
INFO	CONTENTS(reference record!pointer(NODE)R); begin "CONTENTS"
INFO	recursive  CONTENTER(record!pointer(NODE)N); begin "CON"
INFO	PUBLISH (
INFO	simple  Heading;
INFO	simple  Footing;
INFO	simple  LineOut (string L);
INFO	simple  Title (string T);
INFO	Insert (record!pointer(node) N);
INFO	recursive  Insert! (
INFO	Titler (record!pointer(node) R);
INFO	recursive  Contenter (record!pointer(node) R);
INFO	recursive  Publisher (record!pointer(node) R);
INFO	simple  Ini2Col;
INFO	simple  Out2Col (string T);
INFO	simple  Flush2Col;
INFO	recursive  Indexer (record!pointer(pub) R);
INFO	EDIT(record!pointer(NODE)N); begin "EDIT"
INFO	forward  MENU(reference record!pointer(NODE)R);
INFO	forward  TEXT(reference record!pointer(NODE)R);
INFO	simple  UP(reference record!pointer(NODE) R);begin "UP"
INFO	GOTO!(reference record!pointer(NODE) R); begin "GOTO!"
INFO	NEXT!(reference record!pointer(NODE) R); begin "NEXT!"
INFO	MENU(reference record!pointer(NODE)R); begin "MENU"
INFO	TEXT(reference record!pointer(NODE)R); begin "TEXT"
INFO	DUMP;
INFO	recursive  DUMPER(record!pointer(NODE)N);
INFO	simple  DUMP!NODE(record!pointer(NODE)N);
INFO	recursive  BUILDER(record!pointer(NODE)N);
INFO	BUILD;
INFO	REBUILD; begin "REBUILD"
INFO	recursive  REBUILDER(record!pointer(NODE)N); begin "REB"
INFO	VERIFY; begin "VERIFY"
INFO	recursive  VERIFIER(record!pointer(NODE)N); begin "VER"
INFO	INIT!TREE;
INFO	INIT; begin "INIT"
INFO	EXIT; begin "EXIT"
OPRPAS	internal simple string  PasErr( integer Code );
VMSWIT	Internal String  SW!INI(String Name(null), Option(null);
VMSWIT	Simple string  Get!Line;
CARDSL	simple integer  Install( integer BP; string S );
CARDSL	simple boolean  NeedHelp( string text(null) );
CARDSL	simple  InitDpy;
CARDSL	simple string  Cviss( itemvar iv; string str( "Unknown" ) );
CARDSL	boolean  CycleHands( integer count );
CARDSL	list  Shuffle( list D );
CARDSL	DealCards;
CARDSL	list  NewDeck( list Suits, Ranks );
CARDSL	BridgeDeck;
CARDSL	ShowHand( list itemvar MyHand; integer R, C );
CARDSL	DisplayHand;
CARDSL	DisplayHelp;
CARDSL	SetupBuffer;
CARDSL	simple  SetupDummy;
CARDSL	simple  FigureBid;
CARDSL	string  TextHand( list itemvar MyHand );
CARDSL	boolean  NewHand( string S );
CARDSL	simple boolean  OffLine( integer Arg, Cmd );
CARDSL	simple  NewDeal( integer Arg( 0 ) );
CARDSL	integer itemvar  BestHand;
CARDSL	boolean  ThePlay( integer Arg, Suit );
CARDSL	boolean  FixupBidding;
CARDSL	boolean  TheBid( integer Arg, Suit );
CARDSL	CommandScan;
CARDSL	Snooze;
SYR	simple string  CVHMS( integer HMS );
SYR	simple string  TMin( Integer Min );
SYR	simple integer  Install( integer BP; string S );
SYR	simple  Section( string Str, Head( NULL ); integer AddCol( 0 ) );
SYR	simple  InitSysDpy;
SYR	Simple  CollectJobInfo;
SYR	simple  InstallSystemInfo;
SYR	simple  DisplayJobInfo;
SYR	DisplayHelp;
SYR	SetupBuffer;
SYR	CommandScan;
SYR	Snooze;
FRMPKG	simple  SetDetach;
FRMPKG	internal simple boolean  CChild( integer Cradle );
FRMPKG	internal simple 
FRMPKG	internal simple boolean  RunSlf;
FRMPKG	internal simple string  CvNAME( integer AUN );
VMSPEC	Simple Integer  GetText( Reference string Line;
VMSPEC	Internal Simple Boolean  VMSpec(String L; Integer array Spec );
VMFILB	simple  Set.FN( integer Slot; string Str );
VMFILB	simple string  Get.FN( integer Slot );
VMFILB	Simple  InitVM;
VMFILB	Internal Simple  VMInit( Integer C(-1),P(-1));
VMFILB	Internal Simple Integer  VMPMap( Integer Slot, NewPage, What(1) );
VMFILB	Simple Integer  FindPage( Integer Count(1), Page(-1) );
VMFILB	Internal Simple Integer  VMName( String Name; Integer Mode(-1) );
VMFILB	Integer  VMSlot( Integer Count(1), Page(-1) );
VMFILB	Internal simple integer  VMPtrB( integer Slot, Pos );
VMFILB	Internal simple integer  VMPtrW( integer Slot, Word );
VMFILB	Internal Simple Integer  VMGetB( Integer Slot, Pos(-1) );
VMFILB	Internal Simple Integer  VMSetB( Integer Slot, Char, Pos(-1) );
VMFILB	Internal Simple Integer  VMGetW( Integer Slot, Word(-1) );
VMFILB	Internal Simple Integer  VMSetW( Integer Slot, Data, Word(-1) );
VMFILB	Internal Simple Integer  VMGetC( Integer Slot, Index(VM$Pos) );
VMFILB	Internal Simple Integer  VMSetC( Integer Slot, Position );
VMFILB	Internal Simple Boolean  VMFree( Integer Slot, Bits(0) );
VMFILB	Internal Simple Boolean 
VMFILB	Simple Integer  Dbp( Reference Integer Ptr );
VMFILB	Internal String  VMLine( Integer Slot; Reference Integer More;
VMFILB	Internal Boolean  VMText( Integer Slot; String Text );
VMFILB	Internal Boolean  VMMove( Integer Slot, HowMany(1) );
COPY	Init.Brk.Tbls;
COPY	integer  Scan.RPG.Time (string Str);
COPY	Scan.RPG.Date (string Str;
COPY	string  Process.Date.Switch (string Str);
COPY	Parse.Input.Str (string Str;
COPY	simple integer  Frmopr (
COPY	simple integer  FrmopI (integer Fd, Arg, Fn, S(false));
COPY	 simple integer  Frmop (integer Fd, Arg, Fn, S(false));
COPY	integer  CvPpn (string User);
COPY	integer  CreFrm (string User(null));
COPY	RunFrm (integer Fd; string Arg; integer Start.Inc(0));
COPY	simple  Complain (string Text);
COPY	simple string  System.Number;
COPY	simple  Do.Telecopy;
COPY	simple string  XXX;
COPY	simple string  My.Name;
COPY	simple  Call.Dirit (string Com.Str);
COPY	string  Foo (string Fox);
COPY	string  Def.Sys.List;
PQUE	simple  SetupBasePage;
PQUE	internal simple boolean  UseQue( String File(QueueFile) );
PQUE	Simple  GetLock;
PQUE	simple  UnLock;
PQUE	simple integer  MapQuePage;
PQUE	simple boolean  MapDataPage( Integer NewPage );
PQUE	simple boolean  EmptyEntry;
PQUE	simple boolean  MapRecord( Integer r );
PQUE	simple boolean  ArrCMP(reference integer LOC1, LOC2; integer Count);
PQUE	Simple  Wrap;
PQUE	Simple integer  NextRequest;
PQUE	Internal simple  ClsQue;
PQUE	simple boolean  CreateQueue;
PQUE	simple boolean  OpenQueue;
PQUE	Simple boolean  GetArea( Integer Mem, Dsk, Bit, Size(1) );
PQUE	internal simple boolean  OpnQue( integer Bits(0) );
PQUE	simple boolean  FindRecord( integer A );
PQUE	simple boolean  Verify( integer A, B );
PQUE	simple boolean  ActRecord( integer A );
PQUE	simple boolean  NextRecord( integer A );
PQUE	simple  DeleteRecord;
PQUE	internal simple boolean  ActRec( integer A );
PQUE	simple  Transform( integer A );
PQUE	internal simple boolean  GetRec( integer A );
PQUE	simple  MarkChange;
PQUE	internal simple boolean  ModRec( integer A, S );
OPRPSW	internal simple string  PasErr( integer Code );
OPRPSW	internal integer  OprLic( reference integer OperName, Hash );
SETOPR	NoG( reference R!P (G) S );
SETOPR	NoO( reference R!P (O) S );
SETOPR	R!P (G)  NewG;
SETOPR	R!P (O)  NewO;
STXLIB	internal simple boolean  Slt( integer A, B );
STXLIB	internal simple string  NoSp( string S );
STXLIB	internal simple string  SxO( integer Mem );
STXLIB	internal simple string  Sxt( integer Mem );
DAYTIM	Simple String  CV( Integer Val, Wid(0), Typ(0) );
DAYTIM	simple integer  CvFraction( Integer Time );
DAYTIM	internal simple integer  GetUDT;
DAYTIM	internal simple integer  GetTDT;
DAYTIM	internal simple integer  SysTDT;
DAYTIM	internal simple integer  CvtDTM( integer Time, NewZone, OldZone(0) );
DAYTIM	internal simple integer  CvtUDT( integer Time, UDT(true) );
DAYTIM	internal simple integer  TFract( String Time );
DAYTIM	Internal simple string  CvSDat( Integer Date );
DAYTIM	Internal simple string  CvDDat( Integer Date );
DAYTIM	Internal simple integer  CMonth( String Name );
DAYTIM	Internal simple string  CvSTim( Integer Time );
DAYTIM	Internal simple string  CvSTym( Integer Time );
DAYTIM	Internal simple string  TymDay( Integer TimeOfDay );
DAYTIM	simple boolean  LeapYear( Integer Year );
DAYTIM	Internal simple integer  CvDate( Integer Month, Day, Year );
DAYTIM	Internal simple integer  CvTime( String  Time );
DAYTIM	Internal Simple integer  CvDay( String Daytime );
DAYTIM	Internal Simple string  TheTime;
RDIST	simple  breakIni;
RDIST	Run (
RDIST	string  AllHosts;
RDIST	DefaultUserNames( reference string NAMES; string USER );
RDIST	boolean  Login( string USER; integer HOST );
RDIST	FINDIT( string NAMES;  CALLIT );
RDIST	Copy( string S );
RDIST	Delete( string S );
RDIST	Declare( string S; string Protection );
RDIST	Setlic( string S; integer License );
RDIST	Build( reference string S );
RDIST	BuildDataBase( string USER, NAMES );
RDIST	Update( reference string S );
RDIST	UpdateHost( string USER, HOST, NAMES );
VMARGS	simple  GetFpn;
VMARGS	simple  DoArgs( reference string ARGS );
VMARGS	ArgIni;
VMARGS	simple  ArgIniSimple;
TTR	Simple String  CV( Integer Val, Wid(0), Typ(0) );
TTR	Simple Integer  DecDate( Integer Days, Minutes, Seconds );
TTR	Simple String  TymDay( Integer TimeOfDay );
TTR	Simple  ToOutput;
TTR	Simple  ToTerminal;
TTR	Simple string  TranslateUser( Integer Nam1, Nam2 );
TTR	Boolean  SetupFiles( String CmdLine );
TTR	Simple boolean  FileMatch;
TTR	Simple boolean  UserMatch;
TTR	Simple boolean  NameMatch;
TTR	Simple Integer  RangeByte( Integer BitNumber );
TTR	Simple  AddRange( Integer Here, There );
TTR	Simple Integer  FirstPos;
TTR	Simple Boolean  LegalRange( String Place );
TTR	Simple Boolean  GetRange;
TTR	Simple  OpenTape;
TTR	Simple  RewindTape;
TTR	Simple String  ContinuationBanner;
TTR	Simple  PrintTapeHeader;
TTR	Simple Boolean  SaveSetHeader;
TTR	Simple Boolean  FileHeader;
TTR	Simple Boolean  TapeIn;
TTR	Simple Boolean  InitializeDevice;
TTR	Simple Boolean  MountNextTape;
TTR	Simple Boolean  EachTapeIsSetup;
TTR	Simple  Header.Restore;
TTR	Simple  File.Restore;
TTR	Simple  Data.Restore;
TTR	Simple  Header.Print;
TTR	Simple  File.Print;
TTR	Simple  Data.Print;
TTR	Simple  Skeleton( Simple  Header, File, Data );
TTR	Simple  TapeReader( Integer Function );
TTR	Simple Boolean  All.Legal( Reference Integer Index );
TTR	Cmd.Action(  Reference Integer Command.Index;
TTR	Simple  NotImp;
TTR	Simple  C.Abracadabra;
TTR	Simple  C.Directory;
TTR	Simple  C.Forget;
TTR	Simple  C.Output;
TTR	Simple  C.Restore;
TTR	C.Skip;
TTR	C.Translate;
TTR	Simple  C.Verbosity;
TTR	Simple  C.Zone;
TTR	Simple  C.Quit;               !  "QUIT" - "EXIT" ;
TTR	Simple  C.Unload;
TTR	Simple  C.Help;
TTYTAB	Simple Boolean  SetupPointers;
TTYTAB	Simple  ShowInfo( Integer Arg );
SYSDAT	simple  SetZone;              ! set timezone to GMT ;
SYSDAT	simple  SetMyLog;
SYSDAT	simple  InitSystem;
SYSDAT	simple  System;
SYSDAT	simple  Disk;
SYSDAT	simple  DateLine;
SYSDAT	simple string  CtyName;
SYSDAT	simple  CTYMessage( string Text );
SYSDAT	simple  CTYrec;
SYSDAT	simple  MakeEntry;
KLLT	Internal simple boolean  KLLT( String Str1, Str2 );
CK	Simple  DO!CHECKSUM;
VMCHAN	Internal Simple Integer  VMChan;
APPEND	simple  LogAll( String Name, Text; Integer Tries(10) );
SYSMON	simple  SetZone;              ! set timezone to GMT ;
SYSMON	internal simple  SetLog;
SYSMON	simple  WriteFile;
SYSMON	simple string  CVHMS( integer HMS );
SYSMON	simple string  TMin( Integer Min );
SYSMON	simple integer  Install( integer BP; string S );
SYSMON	simple  Section( string Str, Head( NULL ); integer AddCol( 0 ) );
SYSMON	simple  InitSystem;
SYSMON	Simple  CollectJobInfo;
SYSMON	simple  InstallSystemInfo;
SYSMON	simple  DisplayData;
SYSMON	simple  DisplayDisk;
SYSMON	SetupBuffer;
SYSMON	CommandScan;
SYSMON	Snooze;
SENDMA	Simple Integer  SendMail( String Type, Text );
BRKINI	Internal simple  BrkIni;
OPRSUB	internal simple integer  Fnd4wd;
OPRSUB	internal simple integer  FndGwd;
OPRSUB	internal simple integer  FndEwd;
OPRSUB	internal simple  BinLock;
OPRSUB	internal simple  BinUnlock;
OPRSUB	internal simple  BinWait;
OPRSUB	internal simple  TxtLock;
OPRSUB	internal simple  TxtUnlock;
OPRSUB	internal simple  TxtWait;
OPRSUB	internal simple integer  Traverse( integer r );
OPRSUB	internal recursive boolean  LCheck( integer r, f, lic );
OPRSUB	internal simple integer  AllLic( integer r, except(0), miss(0) );
OPRSUB	internal simple  Audit( integer M, r; string Text );
OPRSUB	internal recursive  LTake( integer f, r, l );
OPRSUB	internal simple string  Token (reference string S);
OPRSUB	internal simple string  TokNam(reference string S);
OPRSUB	internal simple string  Prompt( String P );
OPRSUB	internal simple integer  CvPrt( String P; Integer D );
OPRSUB	internal simple boolean  SendMail( String Address, Type, Text );
OPRSUB	internal simple  Subordinate( integer r, M );
OPRSUB	internal simple integer  FndName( string s; integer r );
OPRSUB	internal simple  itemize( integer req, slf, who;  what; string p,q );
OPRSUB	internal simple  Display(  Dispatch );
SYSSHO	simple string  CVHMS( integer HMS );
SYSSHO	simple string  WhatDay( string datestring );

(SPL)ACCESS	new!entry;
(SPL)ACCESS	readList( string accessFile("ACCESS.LIS") );
(SPL)ACCESS	drop( r!p (entry) target );
(SPL)ACCESS	boolean  nonoctal( string s );
(SPL)ACCESS	r!p (entry)  construct( string spec );
(SPL)ACCESS	printList;
(SPL)ACCESS	setup( string command, comstr );
(SPL)ACCESS	integer  totsiz;
(SPL)ACCESS	writeList( string accessFile("ACCESS.LIS") );
(SPL)MATCHS	Internal integer  ArrMatch( String S; String Array A );
(SPL)MATCHS	Internal simple integer  StrMatch( String A,B );
(SPL)FTP20	simple  EraseString( reference string S );
(SPL)FTP20	item Zap;
(SPL)FTP20	ZapHandler;
(SPL)FTP20	simple  ZapHandlerIni;
(SPL)FTP20	assign(AuxDead_Zap,ZapHandler);
(SPL)FTP20	simple string  GetLine(integer T(0));
(SPL)FTP20	SendLine(string S);
(SPL)FTP20	boolean  !Csync;
(SPL)FTP20	string  psync( integer T );
(SPL)FTP20	simple boolean  Index (string A,B);
(SPL)FTP20	Connect;
(SPL)FTP20	Login;
(SPL)FTP20	simple  Eraser;
(SPL)FTP20	Enable;
(SPL)FTP20	Disable;
(SPL)FTP20	Quit;
(SPL)FTP20	Gateway;
(SPL)FTP20	simple  Eraser;
(SPL)FTP20	directory;
(SPL)FTP20	get;
(SPL)FTP20	send;
(SPL)GETFIL	Brk!Init;
(SPL)GETFIL	Brk!Release;
(SPL)GETFIL	Internal string  GetFil( Reference string Str;
(SPL)FTP20S	Slave.Transmit( string FileName );
(SPL)FTP20S	Slave.Receive( string FileName );
(SPL)NFICHE	string  TOK (reference string S);
(SPL)NFICHE	simple  BumpFicheFrame;
(SPL)NFICHE	simple string  Prompt( string P );
(SPL)NFICHE	simple integer  SP( String P; Integer Def );
(SPL)NFICHE	simple integer  SPO( String P; Integer Def );
(SPL)NFICHE	simple boolean  SPy( String P; Boolean Def );
(SPL)NFICHE	simple string  TypeMatch;
(SPL)NFICHE	simple string  FindType( String Str );
(SPL)NFICHE	simple string  FindPage( String Str );
(SPL)NFICHE	simple string  FindLine( String Str );
(SPL)NFICHE	simple  SymlokChecks;
(SPL)NFICHE	AdvanceFrame;
(SPL)NFICHE	simple  Print!Heading;
(SPL)NFICHE	boolean  Infile( String F );
(SPL)NFICHE	string  get!line;
(SPL)NFICHE	Each!file;
(SPL)NFICHE	Simple  GetSetupMode;
(SPL)TELCHK	simple  exit;
(SPL)TELCHK	simple  setupBreaks;
(SPL)TELCHK	boolean  somewhatEqu( string results, expected );
(SPL)TELCHK	boolean simple  isReply( string reply, expected );
(SPL)TELCHK	boolean  confirm(string msg);
(SPL)TELCHK	integer  setLogChan( string comLine );
(SPL)TELCHK	oneTransfer( string source, dest, results );
(SPL)TELCHK	simple  copyStarting;
(SPL)TELCHK	finish( integer ch, ppn, name, ext );
(SPL)TELCHK	telecom( integer ppn, name, when );
(SPL)TELCHK	boolean  setCom( integer safe array fileData );
(SPL)MARKER	simple integer  GetTab (integer Table);
(SPL)MARKER	Integer  NEWS (string FN);
(SPL)LUK	helper( string program );
(SPL)LUK	boolean  attempt(string file);
(SPL)LUK	simple integer  LookupUfd(integer dskchan, dir );
(SPL)LUK	string simple  showPpn( integer ppn );
(SPL)LUK	string simple  getUname( integer channel, aun );
(SPL)LUK	simple integer  cvdirppn(integer dskchan; string dirname);
(SPL)LUK	SetPPNsearch(integer ufdChan; string gan,uun);
(SPL)LUK	boolean  findPPN(integer ufdChan );
(SPL)LUK	simple  init; setbreak(skipStar_getbreak, "*", null,"IS");
(SPL)LUK	string  genmsk(string name);
(SPL)LUK	string  genMask(string name );
(SPL)LUK	recursive  regen( integer idx; string tail, add );
(SPL)LUK	string  buildName( string maskString );
(SPL)LUK	r!p(searchSpec)  FiddleMasks( r!p(nameList) head );
(SPL)LUK	boolean simple  acceptable( string MaskStrings );
(SPL)LUK	simple  mention!directory;
(SPL)LUK	boolean  findem( integer ufdchan; r!p (searchSpec) chase );
(SPL)LUK	simple boolean  set!file(string filename);
(SPL)LUK	simple  st!db;
(SPL)LUK	simple string  nextname;
(SPL)LUK	simple  tty!names;
(SPL)LUK	simple  set!names;
(SPL)REDSCR	Simple  Print!system!table;
(SPL)FIND	internal boolean  xpnopen(
(SPL)FIND	internal simple  xpnclose; begin
(SPL)FIND	simple integer  newbuffer(integer fpos); begin
(SPL)FIND	simple integer  newrange(integer xpos); begin
(SPL)FIND	internal simple integer  xpnword(integer xpos); begin
(SPL)FIND	internal string simple  cvr50(integer r50); begin
(SPL)FIND	integer simple  r50char(integer c); return(
(SPL)FIND	internal integer simple  r50(string s); begin
(SPL)FIND	internal boolean simple  symlok(
(SPL)FIND	internal  mullok(
(SPL)MEMCHK	Internal Integer 
(SPL)CPY	simple  InitSystem;
(SPL)CPY	internal simple 
(SPL)CPY	internal simple boolean  CChild( integer Cradle );
(SPL)CPY	simple boolean  ADot( string Str );
(SPL)CPY	boolean  WantFile( Reference Integer Filename, Extension );
(SPL)CPY	FileProc( Reference Integer Chan, Cnt, Brk, FileEof;
(SPL)CPY	simple  Package( String Host );
(SPL)SFTP	simple  BlackBall;
(SPL)SFTP	simple  IntIni;
(SPL)SFTP	simple string  INCHWL;
(SPL)SFTP	simple boolean  EBOM;
(SPL)SFTP	simple  BOUT( string S );
(SPL)SFTP	simple  LBOM;
(SPL)SFTP	simple boolean  EBIM;
(SPL)SFTP	simple string  BIN;
(SPL)SFTP	simple  LBIM;
(SPL)SFTP	CheckFSerror( string FileName );
(SPL)SFTP	CheckIOerror( string FileName );
(SPL)SFTP	simple  ReadInit;
(SPL)SFTP	READ( string FileName );
(SPL)SFTP	fout( integer C; string S );
(SPL)SFTP	WRIT( string FileName );
(SPL)TMERGE	simple  setups; 
(SPL)TMERGE	simple string  cvCommand(string s); 
(SPL)TMERGE	simple boolean  cmdequ(string command, toTest);
(SPL)TMERGE	simple string  Hval(integer v);
(SPL)TMERGE	simple string  cvOut( integer x );
(SPL)TMERGE	string simple  pVersion; 
(SPL)TMERGE	simple integer  nextP( integer ptr; reference integer loc );
(SPL)TMERGE	simple string  copies( reference integer curloc, arrDat );
(SPL)TMERGE	simple integer  bytesUp( integer pseudoPointer );
(SPL)TMERGE	integer  getOutput( string prompt,help(""); integer res(-1) ); 
(SPL)TMERGE	OutPages( r!p(map1) src; integer inch, ouch, tableSize(100) );
(SPL)TMERGE	boolean  dMap( integer DiskPageNumber );
(SPL)TMERGE	expandTable;
(SPL)TMERGE	boolean  Position( integer textPage );
(SPL)TMERGE	CopyMultiple( integer first, last );
(SPL)SWITCH	Internal String  SW!INI(String Name(null), Option(null);
(SPL)SWITCH	String  Get!line;
(SPL)ASK	Internal boolean  Ask(String Prompt);
(SPL)TURNUP	SetVariable;
(SPL)TURNUP	boolean  ParseDate;
(SPL)LINKER	simple string  TmpName(String name3);
(SPL)LINKER	boolean  SomeLeft( r!p(tmp) r );
(SPL)LINKER	string  Rdt(integer BreakT; r!p(tmp) r );
(SPL)LINKER	r!p(tmp)  SetInTemp( string name );
(SPL)LINKER	runprog(string name; integer runOffset(0) );
(SPL)LINKER	simple string  defer(string s); 
(SPL)LINKER	OneSet( string FilePart, SwitchPart );
(SPL)RCR	simple  makeBreaks;
(SPL)RCR	simple string  getString;
(SPL)RCR	simple  error(string why);
(SPL)RCR	simple  Pstr( string s );
(SPL)RCR	simple  oldArg;
(SPL)RCR	simple  oneArg(string name);
(SPL)RCR	simple  twoArg(string name, conjunction );
(SPL)RCR	onDel;
(SPL)LEXSUB	Internal Boolean  LLT(String A;  String B);
(SPL)LEXSUB	Internal Boolean  LGE(String A;  String B);
(SPL)LEXSUB	Internal Boolean  LGT(String A;  String B);
(SPL)LEXSUB	Internal Boolean  LLE(String A;  String B);
(SPL)AUXLIB	internal integer  CREAUX (string UNAME);
(SPL)AUXLIB	internal simple  AUXOUT(string S);
(SPL)AUXLIB	internal simple integer  AUXIN (integer TIM(0) );
(SPL)AUXLIB	internal simple  AUXZAP;
(SPL)AUXLIB	internal simple boolean  AuxSync(string CHS; integer TIM(0));
(SPL)FICHE	string  TOK (reference string S);
(SPL)FICHE	simple  BumpFicheFrame;
(SPL)FICHE	simple string  Prompt( string P );
(SPL)FICHE	simple integer  SP( String P; Integer Def );
(SPL)FICHE	simple integer  SPO( String P; Integer Def );
(SPL)FICHE	simple boolean  SPy( String P; Boolean Def );
(SPL)FICHE	simple string  TypeMatch;
(SPL)FICHE	simple string  FindType( String Str );
(SPL)FICHE	simple string  FindPage( String Str );
(SPL)FICHE	simple string  FindLine( String Str );
(SPL)FICHE	simple  SymlokChecks;
(SPL)FICHE	AdvanceFrame;
(SPL)FICHE	simple  Print!Heading;
(SPL)FICHE	boolean  Infile( String F );
(SPL)FICHE	string  get!line;
(SPL)FICHE	Each!file;
(SPL)FICHE	Simple  GetSetupMode;
(SPL)WHO	simple integer  StrMatch( String A,B );
(SPL)WHO	Simple  UserProc(Reference Integer Ppn; Reference String Name );
(SPL)FINDIT	Simple Simple String  CvDate ( integer Date.In );
(SPL)FINDIT	Simple String  CvTime( Integer Time );
(SPL)FINDIT	Simple Integer  Wild( Integer Card );
(SPL)FINDIT	Simple String  WildSpec( Reference String S; Reference Integer B );
(SPL)FINDIT	Simple Integer  EatOct( String S; Reference Integer Mask );
(SPL)FINDIT	Simple Integer  ScanPPN( Reference String S; Reference Integer M );
(SPL)FINDIT	String  GetSpec( Reference String S; Reference Integer P, M, B );
(SPL)FINDIT	Simple Integer  SubsetSpec( Integer F1, E1, F2, E2 );
(SPL)FINDIT	CopyRecord( r!p (file) That; Integer Name, Ext );
(SPL)FINDIT	CreateLinkRecord;
(SPL)FINDIT	boolean  WantUfd( Reference Integer Aun );
(SPL)FINDIT	UfdProc( Reference Integer Chan; Integer Array Lkb );
(SPL)FINDIT	boolean  WantFile( Reference Integer Filename, Extension );
(SPL)FINDIT	boolean  ThisFile( Reference Integer Filename, Extension );
(SPL)FINDIT	FileProc(Reference Integer Chan,Count,Brk,FileEof; Integer Array LKB);
(SPL)FINDIT	ReadFileList;
(SPL)FINDIT	PrintMissingFiles;
(SPL)PRUNE	simple  destroy( r!p(any!class) rp);
(SPL)PRUNE	r!p(fdes)  newf( string name, ext(null), 
(SPL)PRUNE	r!p(fdes)  xrxf( r!p(fdes) old );
(SPL)PRUNE	string  prtf( r!p(fdes) it );
(SPL)PRUNE	integer  compare( r!p(fdes) first, second );
(SPL)PRUNE	r!p(fdes)  merge( r!p(fdes) l1, l2 );
(SPL)PRUNE	r!p(fdes)  sort( r!p(fdes) r );
(SPL)PRUNE	applies(  doit );
(SPL)PRUNE	simple  setupX;
(SPL)PRUNE	setFileCriteria(string filename);
(SPL)PRUNE	EatUser;
(SPL)PRUNE	boolean  ringSearch( reference r!p(fdes) result;
(SPL)PRUNE	r!p(fdes)  find( string name, ext(null), user(null) );
(SPL)PRUNE	rpt( r!p(fdes) ring );
(SPL)PRUNE	boolean  verify( r!p(fdes) ring );
(SPL)PRUNE	r!p(cell)  cons(r!p(any!class) car, cdr );
(SPL)PRUNE	r!p(cell) simple  c} &{a1}&{a2}&{a3}&{a4}& {r(r!p(cell) it);
(SPL)PRUNE	simple  rplc} &{a1}&{a2}&{a3}&{a4}& {(r!p(cell) it,nv);
(SPL)PRUNE	       simple  inpbrks;
(SPL)PRUNE	r!p(fdes)  cvfd(string line);
(SPL)PRUNE	splice(r!p(fdes) a,b);
(SPL)PRUNE	addon;
(SPL)PRUNE	r!p(fdes)  ReadData( string Prunefile );
(SPL)PRUNE	r!p(fdes)  GrabFiles( integer PPN(0); string user(null) );
(SPL)PRUNE	writeData( R!p(fdes) ring; string FileName(null) );
(SPL)PRUNE	C!command( reference r!p(fdes) it );
(SPL)PRUNE	F!command( reference r!p(fdes) it );
(SPL)PRUNE	W!command( reference r!p(fdes) it );
(SPL)PRUNE	R!command( reference r!p(fdes) it );
(SPL)PRUNE	D!command( reference r!p(fdes) it );
(SPL)PRUNE	M!command( reference r!p(fdes) it );
(SPL)PRUNE	U!command( reference r!p(fdes) it );
(SPL)PRUNE	simple  setup!Text!Channel;
(SPL)PRUNE	T!command( reference r!p(fdes) it );
(SPL)PRUNE	 external  bail;
(SPL)PRUNE	simple  raid;
(SPL)PRUNE	boolean  one!command(string text);
(SPL)PRUNE	r!p(fdes)  mergein( r!p(fdes) lis, Blanks );
(SPL)PRUNE	simple  restoreCase; ttyup( baseCase ); cleanup restoreCase;
(SPL)TWOUP	simple  setupBreaks;
(SPL)TWOUP	simple boolean  match( string reply, pattern );
(SPL)TWOUP	simple string  pad( integer columns );
(SPL)TWOUP	simple string  clip( string s; reference integer size );
(SPL)TWOUP	boolean simple  setSwitches( string switchList );
(SPL)TWOUP	integer  getSource( string prompt; 
(SPL)TWOUP	integer  setOutput( string prompt, defaultDevice, defaultFile);
(SPL)TWOUP	boolean simple  breakUp( string source; integer index );
(SPL)TWOUP	simple boolean  setupPage;
(SPL)TWOUP	simple  clearPage;
(SPL)TWOUP	simple integer  getLine;
(SPL)TWOUP	string simple  nextLine;
(SPL)TWOUP	simple r!p(penders)  new!pend;
(SPL)TWOUP	doOnes;
(SPL)TWOUP	doTwos;
(SPL)PAGE	boolean  WantFile( Reference Integer Filename, Extension );
(SPL)PAGE	FileProc( Reference Integer Chan, Cnt, Brk, FileEof; Integer Array LKB );
(SPL)WHEN	integer  CheckJobs( string UserName );
(SPL)WHEN	integer  CheckLogout( string USER );
(SPL)WHEN	string  Expand (integer DATE);
(SPL)WHEN	PrintNames;
(SPL)CRFSYM	ListIni;
(SPL)CRFSYM	InitReserve( String Array A );
(SPL)CRFSYM	ReservedWordIni;
(SPL)CRFSYM	BrkIni;
(SPL)CRFSYM	Initialize!switches;
(SPL)CRFSYM	Boolean  LLT(String A;  String B);
(SPL)CRFSYM	string  TOK (reference string S);
(SPL)CRFSYM	string  EXIT;         ! string so it can be "printed" [ugh];
(SPL)CRFSYM	simple boolean  Numeric(String Str);
(SPL)CRFSYM	simple string  GetFil( Reference string Str, Dev;
(SPL)CRFSYM	simple  Print!Header;
(SPL)CRFSYM	simple  Print!Line(String Num!Tab,Line);
(SPL)CRFSYM	simple  GetLine;
(SPL)CRFSYM	simple string  Multi!Line(Integer Char);
(SPL)CRFSYM	simple string  NextName;
(SPL)CRFSYM	Recursive  New!Symbol(String Name, Type; Integer New!Value);
(SPL)CRFSYM	Print!Sorted!List(Integer Size; List Itemvar LS; Boolean Flag);
(SPL)CRFSYM	Print!Symbols(String Type, Banner; Boolean Flag(True) );
(SPL)CRFSYM	Simple String  TokenType(String Name);
(SPL)CRFSYM	simple  HELP(String Inout);
(SPL)CRFSYM	simple integer  checksw(String Nam, Txt);
(SPL)CRFSYM	boolean  legal!switch(Reference string S; String Inout);
(SPL)CRFSYM	simple string  MyTime( integer D, T );
(SPL)CRFSYM	FRONT!END;

(SUBMIT)U	simple boolean  ValidTimeStr( reference string S );
(SUBMIT)U	simple boolean  ValidDateStr( reference string S );
(SUBMIT)U	simple boolean  ValidNum( string S );
(SUBMIT)U	simple boolean  ValidDOW( string S );
(SUBMIT)U	simple boolean  ValidOrd( reference string S );
(SUBMIT)U	simple boolean  ValidMOY( string S );
(SUBMIT)U	simple boolean  ValidKey( reference  string S );
(SUBMIT)U	simple boolean  ValidMODIFIER( string S );
(SUBMIT)U	simple boolean  ValidOrdNum( reference string S );
(SUBMIT)U	simple integer  Val( string array AR ;
(SUBMIT)U	simple string  ScanStr( string EnglishStr );
(SUBMIT)U	simple string  GetTodDate;
(SUBMIT)U	simple integer  TodaysIntrnDat;
(SUBMIT)U	simple integer  trunc( real n );
(SUBMIT)U	simple integer  ZELLER( integer day,month,year );
(SUBMIT)U	simple integer  Today;
(SUBMIT)U	simple integer  DayToNum( string Day );
(SUBMIT)U	simple integer  MoToNum( string Mon );
(SUBMIT)U	simple string  getDOW( string date );
(SUBMIT)U	simple  GetDateSpec;
(SUBMIT)U	simple integer  HowMany( string S,Target ); 
(SUBMIT)U	simple boolean  ModUsedBefore( string m );
(SUBMIT)U	simple  SetCode( integer a,b,c,d,e );
(SUBMIT)U	simple boolean  UNIT( string S;
(SUBMIT)U	simple integer  CalcTimFrac( string ds );
(SUBMIT)U	simple boolean  ValidExpression( string S;
(SUBMIT)U	boolean  ValidGroup( string S;
(SUBMIT)U	simple boolean  ParsedOK( string S;
(SUBMIT)U	simple  express;
(SUBMIT)U	simple  Display;
(SUBMIT)U	simple  Look;
(SUBMIT)U	simple  Test;
(SUBMIT)U	simple  TrialCode;
(SUBMIT)U	simple string  GetComFrTerm(string PromptLine);
(SUBMIT)U	simple integer  GetCommand( string prompt );
(SUBMIT)U	simple integer  Validate( string array AR ;
(SUBMIT)U	simple  GetOptions;
(SUBMIT)U	simple  HelpRoutine;
(SUBMIT)U	simple  InsertFN( integer array ENtr;
(SUBMIT)U	simple integer  GeChan(string NameForTheNewFile); 
(SUBMIT)U	simple integer  OpChan(string NameOfTheFile);
(SUBMIT)U	simple  MakeHeader( integer DatNextRun,TimNextRun );
(SUBMIT)U	simple  ShowOneRec( integer array QRec );
(SUBMIT)U	integer  GetNDT( integer AfterDate );
(SUBMIT)U	simple  GetNext;
(SUBMIT)U	simple  GetBySeqNum;
(SUBMIT)U	simple  GetByJobName;
(SUBMIT)U	simple  Delete;
(SUBMIT)U	simple boolean  SubList( integer array QRec );
(SUBMIT)U	simple  LISTP( integer array QRec );
(SUBMIT)U	simple  list;
(SUBMIT)U	simple string  GetUserName;
(SUBMIT)U	simple  Insert;
(SUBMIT)U	simple  Modif;
(SUBMIT)U	simple  ShowAll;
(SUBMIT)U	simple  specials;
(SUBMIT)U	simple  menu;
(SUBMIT)NEXTIM	simple integer  GetDaOfWeek( integer dis );
(SUBMIT)NEXTIM	simple integer  YearNumb( integer disp );
(SUBMIT)NEXTIM	simple integer  MonthNumb( integer disp );
(SUBMIT)NEXTIM	simple integer  DaOfMonth( integer disp );
(SUBMIT)NEXTIM	simple integer  typeW( integer ArrAddr; integer baseDT );
(SUBMIT)NEXTIM	simple integer  typeN( integer ArrAddr; integer baseDT );
(SUBMIT)NEXTIM	simple integer  TypeT( integer ArrAddr; integer base );
(SUBMIT)NEXTIM	simple integer  typeS( integer ArrAddr; integer base );
(SUBMIT)NEXTIM	simple integer  FindModif( integer ArrAddr; integer ConnSought );
(SUBMIT)NEXTIM	internal simple integer  NexTim( integer ArrAddr, BasDatTim );
(SUBMIT)SUBMIT	Internal simple  EnaTRP;
(SUBMIT)SUBMIT	Internal simple  DisTRP;
(SUBMIT)SUBMIT	simple  IncLicense;           ! put process license back ;
(SUBMIT)SUBMIT	simple  DecLicense;           ! take process license away ;
(SUBMIT)SUBMIT	simple  LoadFileName( integer array Arr; ! Array in which to insert ;
(SUBMIT)SUBMIT	simple boolean  CheckLog( string FileName ); 
(SUBMIT)SUBMIT	simple boolean  ComIsOK( reference string FileName );
(SUBMIT)SUBMIT	simple integer  RunLocal( integer date );
(SUBMIT)SUBMIT	simple string  LocalRun( integer array QRec );
(SUBMIT)SUBMIT	simple string  RequestInfo( integer array QRec );
(SUBMIT)SUBMIT	simple  DisplayARec( integer array QRec );
(SUBMIT)SUBMIT	simple boolean  GetOptions( boolean CalledFromMODIFY );
(SUBMIT)SUBMIT	simple  OptionsMenu;
(SUBMIT)SUBMIT	simple boolean  NoConflicts;
(SUBMIT)SUBMIT	simple boolean  MakeRecord( integer DatNext );
(SUBMIT)SUBMIT	simple integer 
(SUBMIT)SUBMIT	simple  QueErr( string Msg );
(SUBMIT)SUBMIT	simple  Insert;
(SUBMIT)SUBMIT	simple  Prepare( integer array A, Name ); 
(SUBMIT)SUBMIT	simple  Message( string Vanilla,
(SUBMIT)SUBMIT	simple boolean  RealRec( reference integer rec );
(SUBMIT)SUBMIT	simple boolean  MyDefault( string Msg( null ) );
(SUBMIT)SUBMIT	simple boolean  Delete;
(SUBMIT)SUBMIT	simple boolean  DisplayMyRec;
(SUBMIT)SUBMIT	simple boolean  ModActiveJob;
(SUBMIT)SUBMIT	simple boolean  ModJob;
(SUBMIT)SUBMIT	simple boolean  ReQueue;
(SUBMIT)SUBMIT	simple boolean  ReRun;
(SUBMIT)SUBMIT	simple  ColumnHeadings;
(SUBMIT)SUBMIT	simple boolean  LIST;
(SUBMIT)SUBMIT	simple  MyLoop( simple boolean  MyProc, MyRec );
(SUBMIT)SUBMIT	simple  Select;
(SUBMIT)SUBMIT	simple boolean  UseCheck;
(SUBMIT)SUBMIT	simple  UseFile;
(SUBMIT)SUBMIT	simple  UseMasquerade;
(SUBMIT)SUBMIT	simple  UseGFD;
(SUBMIT)SUBMIT	simple string  ForceReply( string Question );
(SUBMIT)SUBMIT	integer  GetCommand;
(SUBMIT)SUBMIT	SelectHelp;
(SUBMIT)SUBMSC	simple  SetBreaks;
(SUBMIT)SUBMSC	internal simple  OpLine(
(SUBMIT)SUBMSC	internal simple string  CvNAME( integer AUN );
(SUBMIT)SUBMSC	internal simple integer  CvPPN( string Name );
(SUBMIT)SUBMSC	internal simple string  InfNam( Integer Name );
(SUBMIT)SUBMSC	internal simple string  InfJob( Integer Name );
(SUBMIT)SUBMSC	internal simple integer  FndKey( String Key; String Array CMD.Names );
(SUBMIT)SUBMSC	internal simple string  LopWrd( reference string S );
(SUBMIT)SUBMSC	internal simple string  LopTo( reference string OrigS; String Target ); 
(SUBMIT)SUBMSC	internal simple integer  HowMany( string S,Target ); 
(SUBMIT)SUBMSC	internal simple boolean  ValNum( string S );
(SUBMIT)SUBMSC	internal simple boolean  ValOrd( reference string S );
(SUBMIT)SUBMSC	internal simple integer  IntRead( string msg );
(SUBMIT)SUBMSC	internal simple string  upper( string rawstring );
(SUBMIT)SUBMSC	internal simple  AUS( string str(null) );
(SUBMIT)SUBMSC	internal simple string  prompt( string PromptLine, default(null) );
(SUBMIT)SUBMSC	internal simple boolean  CryForHelp( string word );
(SUBMIT)SUBMSC	internal simple integer  ViK(         string array Arr;
(SUBMIT)SUBMSC	internal simple boolean  ValidTimeStr( reference string S );
(SUBMIT)SUBMSC	internal simple boolean  ValDateStr( reference string S );
(SUBMIT)SUBMSC	internal simple boolean  ValidDaOfWk( string S );
(SUBMIT)SUBMSC	internal simple boolean  ValidMOY( string S );
(SUBMIT)SUBMSC	internal simple boolean  ValidKey( reference  string S );
(SUBMIT)SUBMSC	internal simple boolean  ValModifier( string S );
(SUBMIT)SUBMSC	internal simple boolean  ValNmOrd( reference string S );
(SUBMIT)SUBMSC	internal simple  LJust( string S; integer FieldWidth );
(SUBMIT)SUBMSC	internal simple integer  TodaysIntrnDat;
(SUBMIT)SUBMSC	internal simple integer  Today;
(SUBMIT)SUBMSC	internal simple boolean  EqSign( reference string LogF, ComF );
(SUBMIT)SUBMSC	internal simple string  GetUserName;
(SUBMIT)SUBPAR	simple string  ScanStr( string EnglishStr );
(SUBMIT)SUBPAR	simple  GetDateSpec;
(SUBMIT)SUBPAR	simple  SetCode( integer a,b,c,d,e; Integer Array Current );
(SUBMIT)SUBPAR	simple  ClearCode( integer array Current );
(SUBMIT)SUBPAR	simple  Connect( integer Con; integer array Current );
(SUBMIT)SUBPAR	simple boolean  UNIT( string S;
(SUBMIT)SUBPAR	simple boolean  ValidExpression( string S;
(SUBMIT)SUBPAR	boolean  ValidGroup( string OrigStr;
(SUBMIT)SUBPAR	boolean  TooLong;
(SUBMIT)SUBPAR	simple boolean  ParsedOK( string S;
(SUBMIT)SUBPAR	simple boolean  NoDateExpression( integer array Current );
(SUBMIT)SUBPAR	internal simple  express( integer array Current );
(SUBMIT)SUBPAR	internal simple  Display( integer array Current );
(SUBMIT)SUBPAR	internal simple  Look( integer array Current );
(SUBMIT)SUBPAR	internal simple  Test( integer array MyRec );
(SUBMIT)SUBPAR	internal simple  GetExpFromUser( integer array MyRec );

(EXECX)QUEDDT	simple  MapIt;
(EXECX)QUEDDT	simple  WhereIsIt;
(EXECX)QUEDDT	simple  DoInstall;
(EXECX)QUEDDT	simple  NeedHelp;
(EXECX)EXECX	internal simple  EnaTRP;
(EXECX)EXECX	internal simple  DisTRP;
(EXECX)EXECX	Forget!substitutions;
(EXECX)EXECX	simple  ClearFlags;
(EXECX)EXECX	Simple Boolean  ClearFrame;
(EXECX)EXECX	Simple  EXIT( String Msg(Null) );
(EXECX)EXECX	Simple  Deactivate;
(EXECX)EXECX	Simple Boolean  JobExit( Integer Msg(0) );
(EXECX)EXECX	simple  WhoShouldIBe;
(EXECX)EXECX	simple  LicenseCheck;
(EXECX)EXECX	ParIni;
(EXECX)EXECX	simple  MyLog( string Msg );
(EXECX)EXECX	simple  DumpLog( string Msg );
(EXECX)EXECX	simple boolean  Fatal(String Msg);
(EXECX)EXECX	SetTimeLimit( Integer TimeLimit );
(EXECX)EXECX	Set!Delimiter( String Character );
(EXECX)EXECX	simple  SYNC;
(EXECX)EXECX	simple  OutPtr (integer PORT; string S);
(EXECX)EXECX	String  BoolToStr( Boolean T );       ! Boolean to String;
(EXECX)EXECX	Boolean  StrToBool( String S );       ! String to Boolean;
(EXECX)EXECX	RW!Item( String Itemvar W,R; Reference Boolean B);
(EXECX)EXECX	RW!MyItem( String Itemvar W,R; Reference Boolean B);
(EXECX)EXECX	Date$( String Itemvar W, R);
(EXECX)EXECX	Day$( String Itemvar W, R);
(EXECX)EXECX	Daytime$( String Itemvar W, R);      ! Read-only * Time of day;
(EXECX)EXECX	Delimiter$(String Itemvar W, R);
(EXECX)EXECX	Error$( String Itemvar W, R);
(EXECX)EXECX	False$( String Itemvar W, R);
(EXECX)EXECX	Format$( String Itemvar W, R);
(EXECX)EXECX	Hour$( String Itemvar W, R);         ! Read-only * Time of day;
(EXECX)EXECX	HH$( String Itemvar W, R);           ! Read-only * Time of day;
(EXECX)EXECX	HHMM$( String Itemvar W, R);         ! Read-only * Time of day;
(EXECX)EXECX	HHMMSS$( String Itemvar W, R);       ! Read-only * Time of day;
(EXECX)EXECX	Logging$( String Itemvar W, R);
(EXECX)EXECX	Mail$( String Itemvar W, R);
(EXECX)EXECX	Minute$( String Itemvar W, R);       ! Read-only * Time of day;
(EXECX)EXECX	MMSS$( String Itemvar W, R);         ! Read-only * Time of day;
(EXECX)EXECX	MM$( String Itemvar W, R);
(EXECX)EXECX	Mon$( String Itemvar W, R);
(EXECX)EXECX	Month$( String Itemvar W, R);
(EXECX)EXECX	Numerics$( String Itemvar W, R);
(EXECX)EXECX	Second$( String Itemvar W, R);       ! Read-only * Time of day;
(EXECX)EXECX	SS$( String Itemvar W, R);           ! Read-only * Time of day;
(EXECX)EXECX	Substitution$( String Itemvar W, R);
(EXECX)EXECX	TimeLimit$(String Itemvar W, R);
(EXECX)EXECX	True$( String Itemvar W, R);
(EXECX)EXECX	Trulimit$( String Itemvar W, R);
(EXECX)EXECX	Tomorrow$( String Itemvar W, R);
(EXECX)EXECX	Weekday$( String Itemvar W, R);
(EXECX)EXECX	Yesterday$( String Itemvar W, R);
(EXECX)EXECX	Year$( String Itemvar W, R);
(EXECX)EXECX	YY$( String Itemvar W, R);
(EXECX)EXECX	ItemIni;                     ! Alphabetical;
(EXECX)EXECX	MOV ( itemvar DST,SRC );
(EXECX)EXECX	String  Substitute(Integer Chan; String Key);
(EXECX)EXECX	simple string  Get!Token( Reference string Par!Lst );
(EXECX)EXECX	New!Parameter(Integer Chan; String Name, Initial!Value, New!Value);
(EXECX)EXECX	simple  Set!Parameter(Reference string Par!Lst);
(EXECX)EXECX	String  parametize(Value String S);
(EXECX)EXECX	Simple boolean  SPROUT( Boolean NeedPort; Integer Cradle );
(EXECX)EXECX	simple boolean  ChkCommand( String Str );
(EXECX)EXECX	simple boolean  CheckLabel( reference string S );
(EXECX)EXECX	Simple boolean  GOTO (string CMD);
(EXECX)EXECX	Simple  BackTo (string CMD);
(EXECX)EXECX	simple boolean  FrontEnd;
(EXECX)EXECX	REASSIGN (string CMD);
(EXECX)EXECX	simple  CHECKPOINT( string CMD );
(EXECX)EXECX	COM (string CMD);
(EXECX)EXECX	Simple Boolean  CommandMode;
(EXECX)EXECX	ESCAPE;
(EXECX)EXECX	PARAMETERS(String CMD);
(EXECX)EXECX	simple  QUIT;
(EXECX)EXECX	simple  RESTART( string CMD );
(EXECX)EXECX	SEND (string CMD);
(EXECX)EXECX	simple  SETERROR( string CMD; boolean Flag );
(EXECX)EXECX	simple  SILENCE( boolean Flag );
(EXECX)EXECX	simple  STOP;
(EXECX)EXECX	simple  TIME (string CMD);
(EXECX)EXECX	simple  TRULIMIT( string CMD );
(EXECX)EXECX	recursive  COMMAND( string CMD );
(EXECX)EXECX	Simple Integer  SlotsAvailable;
(EXECX)EXECX	Simple String  JobStatus( integer ASlot );
(EXECX)EXECX	Simple  Cleanup;
(EXECX)EXECX	Simple  Do!Cleanup;
(EXECX)EXECX	Simple  FrameCheck;
(EXECX)EXECX	Simple  ClearFile;
(EXECX)EXECX	Simple  PortLine;
(EXECX)EXECX	Simple Boolean  OneLine;
(EXECX)EXECX	Escape;                                 ! Do escape  ;
(EXECX)EXECX	Simple  FileLine;
(EXECX)EXECX	Internal Simple  GetInt( reference integer Flag; integer Why );
(EXECX)EXECX	simple  EveryMinute;
(EXECX)EXECX	simple boolean  WaitForInterlock;
(EXECX)EXECX	simple  SystemStartup;
(EXECX)XEXEC	Internal Simple  GetInt( reference integer Flag; integer Why );
(EXECX)XEXEC	Internal Simple  EnaTRP;
(EXECX)XEXEC	Internal Simple  DisTRP;
(EXECX)XEXEC	SetTimeLimit( Integer TimeLimit );
(EXECX)XEXEC	Simple Boolean  ClearFrame;
(EXECX)XEXEC	Simple  ClearSlot( Integer Address(0) );
(EXECX)XEXEC	Simple  KillJob( Integer J );
(EXECX)XEXEC	Simple  EXIT( String Msg(Null) );
(EXECX)XEXEC	simple  InitVMFileFlag;
(EXECX)XEXEC	simple  WhoShouldIBe;
(EXECX)XEXEC	simple  LicenseCheck;
(EXECX)XEXEC	Simple boolean  FrontEnd( integer Adr );
(EXECX)XEXEC	simple boolean  CommandMode;
(EXECX)XEXEC	simple boolean  ErrorMode;
(EXECX)XEXEC	ESCAPE;
(EXECX)XEXEC	simple  CreateProcessor;
(EXECX)XEXEC	simple  StartProcessor;
(EXECX)XEXEC	r!p (job)  NewRec;
(EXECX)XEXEC	Prune( Integer AReq  );
(EXECX)XEXEC	Prime( Integer AReq  );
(EXECX)XEXEC	Simple Boolean  NextRecord;
(EXECX)XEXEC	SortQueue;
(EXECX)XEXEC	TellAll;
(EXECX)XEXEC	simple  ReBuildQueue( integer Level( JP$Min ) );
(EXECX)XEXEC	Simple Integer  SendMail( Integer Adr, Type );
(EXECX)XEXEC	Simple  ReSchedule( Integer Type( Sys$Run ) );
(EXECX)XEXEC	Simple Boolean  Unique( r!p (job) r; integer type );
(EXECX)XEXEC	Integer  SlotsAvailable;
(EXECX)XEXEC	Simple  ResetJobArea;
(EXECX)XEXEC	Simple  SetupJobTables;
(EXECX)XEXEC	Simple  MonitorRunningJobs;
(EXECX)XEXEC	Simple  MonitorActiveJobs;
(EXECX)XEXEC	simple  EveryMinute;
(EXECX)XEXEC	simple  DebugOptions;
(EXECX)XEXEC	simple  CleanupJobs;
(EXECX)XEXPKG	internal simple  SetLog;
(EXECX)XEXPKG	simple  SetZone;              ! set timezone to GMT ;
(EXECX)XEXPKG	simple  SetDetach;            ! set NOATTACH ;
(EXECX)XEXPKG	Internal Simple  Talk( integer j; string s );
(EXECX)XEXPKG	Internal Simple boolean  CTYLog( String Text; Boolean Date(false) );
(EXECX)XEXPKG	Internal simple string  HaltStatus( Integer array Status );
(EXECX)XEXPKG	internal simple boolean  CChild( integer Cradle );
(EXECX)XEXPKG	simple  LogAll( String Name, Text; Integer Tries(LogTry) );
(EXECX)XEXPKG	internal simple  LogWho( String Who );
(EXECX)XEXPKG	internal simple  LogInfo( String Text );
(EXECX)XEXPKG	internal simple  LogIt( Integer Bits; String Text );
(EXECX)XEXPKG	internal simple boolean  RunSlf;
(EXECX)XEXPKG	internal simple boolean  OnlyMe;
(EXECX)XEXPKG	internal simple 
(EXECX)XEXPKG	internal simple boolean  RunJob( integer Frame, ASlot; string Par );
(EXECX)XEXPKG	internal simple string  CvNAME( integer AUN );
(EXECX)XEXPKG	internal simple string  InfNam( Integer Name );
(EXECX)XEXPKG	internal simple string  InfJob( Integer Name, Status(0) );
(EXECX)XEXPKG	internal simple boolean  ClubJoin( integer Page );
(EXECX)XEXPKG	internal simple boolean  ClubInit( reference integer Page );
(EXECX)XEXPKG	internal simple integer  GetTRU( Integer Child );
(EXECX)JQUE	external simple  EnaTRP;
(EXECX)JQUE	external simple  DisTRP;
(EXECX)JQUE	simple  ContextSwitch( integer Index; string Name );
(EXECX)JQUE	simple  SetupBasePage;
(EXECX)JQUE	internal simple boolean  UseQue( String File(QueueFile) );
(EXECX)JQUE	Simple  GetLock;
(EXECX)JQUE	simple  UnLock;
(EXECX)JQUE	simple integer  MapQuePage;
(EXECX)JQUE	simple boolean  MapDataPage( Integer NewPage );
(EXECX)JQUE	simple boolean  EmptyEntry;
(EXECX)JQUE	simple boolean  MapRecord( Integer r );
(EXECX)JQUE	simple boolean  ArrCMP(reference integer LOC1, LOC2; integer Count);
(EXECX)JQUE	Simple  Wrap;
(EXECX)JQUE	Simple integer  NextRequest;
(EXECX)JQUE	Internal simple  ClsQue;
(EXECX)JQUE	simple boolean  OpenQueue;
(EXECX)JQUE	internal simple boolean  OpnQue( integer Bits(0) );
(EXECX)JQUE	simple boolean  FindRecord( integer A );
(EXECX)JQUE	simple boolean  Verify( integer A, B );
(EXECX)JQUE	simple boolean  ActRecord( integer A );
(EXECX)JQUE	simple boolean  NextRecord( integer A );
(EXECX)JQUE	simple  DeleteRecord;
(EXECX)JQUE	internal simple boolean  ActRec( integer A );
(EXECX)JQUE	simple  Transform( integer A );
(EXECX)JQUE	internal simple boolean  GetRec( integer A );
(EXECX)JQUE	simple  MarkChange;
(EXECX)JQUE	internal simple boolean  ModRec( integer A, S );
(EXECX)XEXFIL	Simple  InitStuff;
(EXECX)XEXFIL	Internal Simple  VMInit( Integer Page, Count );
(EXECX)XEXFIL	Internal Simple Integer  VMMaxS( Integer Count );
(EXECX)XEXFIL	Simple Integer  MapPage( r!p (F) Rec; Integer NewPage );
(EXECX)XEXFIL	Integer  VM!PMap( Integer Slot, NewPage );
(EXECX)XEXFIL	Internal Simple Integer  VMPMap( Integer Slot, NewPage );
(EXECX)XEXFIL	Simple Integer  Dbp( Reference Integer Ptr );
(EXECX)XEXFIL	Simple Integer  GetText( Reference string Line;
(EXECX)XEXFIL	Internal Simple Boolean  VMSpec(String L; Integer array Spec );
(EXECX)XEXFIL	Internal Simple Integer  VMChan;
(EXECX)XEXFIL	R!P (F)  NewRec;
(EXECX)XEXFIL	Simple Integer  VMSlot;
(EXECX)XEXFIL	Internal Simple Integer  VMGetC( Integer Slot, Index(VM$Char) );
(EXECX)XEXFIL	Internal Simple Integer  VMSetC( Integer Slot, Position );
(EXECX)XEXFIL	Internal Simple Boolean  VMFree( Integer Slot, Bits(0) );
(EXECX)XEXFIL	Internal String  VMLine( Integer Slot; Reference Integer More;
(EXECX)XEXFIL	Internal Boolean  VMText( Integer Slot; String Text );
(EXECX)XEXFIL	Internal Boolean  VMMove( Integer Slot, HowMany(1) );
(EXECX)XEXFIL	Internal Simple Boolean  VMFile( String Spec; Integer Mode(VM$Read) );
(EXECX)XEXTIM	Simple String  CV( Integer Val, Wid(0), Typ(0) );
(EXECX)XEXTIM	simple integer  CvFraction( Integer Time );
(EXECX)XEXTIM	Internal simple string  CvSDat( Integer Date );
(EXECX)XEXTIM	Internal simple string  CvSTim( Integer Time );
(EXECX)XEXTIM	Internal simple string  CvSTym( Integer Time );
(EXECX)XEXTIM	Internal simple string  TymDay( Integer TimeOfDay );
(EXECX)XEXTIM	simple boolean  LeapYear( Integer Year );
(EXECX)XEXTIM	Internal simple integer  CvDate( String  Date );
(EXECX)XEXTIM	Internal simple integer  CvTime( String  Time );
(EXECX)XEXSUB	simple  SetDetach;
(EXECX)XEXSUB	BrkIni;
(EXECX)XEXSUB	internal simple integer  FndKey( String Key; String Array CMD.Names );
(EXECX)XEXSUB	internal simple string  DatStr(Integer Type, Zone(0) );
(EXECX)XEXSUB	internal simple  Timer(Reference Integer HH,MM,SS; integer Zone(0));
(EXECX)XEXSUB	internal simple boolean  Numeric(String Str);
(EXECX)XEXSUB	internal simple string  TOK (reference string S);
(EXECX)XEXSUB	internal simple string  GetFil( Reference string Str, Dev;
(EXECX)QUEDPY	internal simple  EnaTRP;
(EXECX)QUEDPY	internal simple  DisTRP;
(EXECX)QUEDPY	internal simple boolean  RunSlf;
(EXECX)QUEDPY	simple string  CVHMS( integer HMS );
(EXECX)QUEDPY	simple string  TMin( Integer Min );
(EXECX)QUEDPY	simple integer  Install( integer BP; string S );
(EXECX)QUEDPY	simple  Section( string Str, Head( NULL ); integer AddCol( 0 ) );
(EXECX)QUEDPY	simple  InitSysDpy;
(EXECX)QUEDPY	simple  InstallSystemInfo;
(EXECX)QUEDPY	simple  DisplayActive;
(EXECX)QUEDPY	simple  DisplayJobInfo;
(EXECX)QUEDPY	simple  DisplayQueueInfo;
(EXECX)QUEDPY	simple string  APage( integer B; string Y("1"), N("0"), M("-") );
(EXECX)QUEDPY	simple  DisplayFiles;
(EXECX)QUEDPY	DisplayHelp;
(EXECX)QUEDPY	SetupBuffer;
(EXECX)QUEDPY	CommandScan;
(EXECX)QUEDPY	Snooze;
(EXECX)XEXCHR	Simple  CHR;
(EXECX)XEXINT	Internal simple  IntMak( integer intChan );
(EXECX)XEXINT	simple  ESC;    ESC!_ true;   ! set ESC flag and return ;
(EXECX)XEXINT	simple  NTQ;    NTQ!_ true;   ! set NTQ flag and return ;
(EXECX)XEXINT	simple  NIC;    NIC!_ true;   ! set NIC flag and return ;
(EXECX)XEXINT	simple  Dummy;        begin end;
(EXECX)XEXINT	simple  ZAP( Integer Bits );
(EXECX)XEXINT	   Simple  ZAP}&"ZapC"&{;
(EXECX)XEXINT	simple  LOS;  GetInt( LOS!,LXROCL lor LXRICL );
(EXECX)XEXINT	simple  CHR;  GetInt( CHR!,LXRBRK );  ! check for BRK and return ;
(EXECX)XEXINT	simple  ORG;
(EXECX)XEXINT	simple  ECF( Integer Bits );    ECF!_ ECF! lor Bits;
(EXECX)XEXINT	simple  LCF( Integer Bits );    LCF!_ LCF! lor Bits;
(EXECX)XEXINT	   Simple  ECF}&"FEXC"&{;    ECF(1 lsh FEXC);
(EXECX)XEXINT	   Simple  LCF}&"FEXC"&{;    LCF(1 lsh FEXC);
(EXECX)XEXINT	simple  FEX;    FEX!_ true;
(EXECX)XEXINT	simple  SIP;    SIP!_ true;
(EXECX)XEXINT	simple  SIC;    SIC!_ true;
(EXECX)XEXINT	simple  SIS;    SIS!_ true;
(EXECX)XEXINT	simple  SIA;    SIA!_ true;
(EXECX)XEXINT	internal simple  EscDis;
(EXECX)XEXINT	internal simple  TimDis;
(EXECX)XEXINT	simple  TIM;
(EXECX)XEXINT	internal simple  NTQDis;
(EXECX)XEXINT	internal simple  PrtDis( integer Port );
(EXECX)XEXINT	internal simple  EcfDis( integer Frame );
(EXECX)XEXINT	internal simple  LcfDis( integer Frame );
(EXECX)XEXINT	internal simple  FEXDis;
(EXECX)XEXINT	internal simple  SIPDis;
(EXECX)XEXINT	internal simple  SICDis;
(EXECX)XEXINT	internal simple  SISDis;
(EXECX)XEXINT	internal simple  SIADis;
(EXECX)XEXINT	internal simple  TimEnb;
(EXECX)XEXINT	internal simple  SetTim( integer Time, Units( 1 ) );
(EXECX)XEXINT	internal simple  NtqEnb;
(EXECX)XEXINT	internal simple  EscEnb;
(EXECX)XEXINT	internal simple  PrtEnb( integer Port );
(EXECX)XEXINT	internal simple  LcfEnb( integer Frame );
(EXECX)XEXINT	internal simple  EcfEnb( integer Frame );
(EXECX)XEXINT	internal simple  FEXEnb;
(EXECX)XEXINT	simple  SIPEnb;
(EXECX)XEXINT	internal simple  SICEnb;
(EXECX)XEXINT	internal simple  SISEnb;
(EXECX)XEXINT	internal simple  SIAEnb;
(EXECX)XEXMAI	Simple  SendIt;
(EXECX)XEXLIC	internal simple string  LicErr( integer Code );
(EXECX)XEXLIC	simple string  get!line;
(EXECX)XEXLIC	internal  GetOpr( reference integer L; reference string Name );
(EXECX)XEXLIC	Simple Integer  Radix.45(Integer Ch);
(EXECX)XEXLIC	integer  CVHASH(string PW);
(EXECX)XEXLIC	internal integer  GetLic( reference integer OperName,
# x_Ø