	SUBROUTINE YESNOZ($,$,$)
	IMPLICIT INTEGER(A-Z)
10	READ(5, 20,END=25,ERR=25)ANSWER
20	FORMAT(A5)
	IF (ANSWER.EQ.'Y' .OR. ANSWER.EQ.'y')RETURN 1
	IF (ANSWER.EQ.'N' .OR. ANSWER.EQ.'n')RETURN 2
	IF (ANSWER.EQ.'0'                   )RETURN 3
25	TYPE 30
30	FORMAT(1X, 'ANSWER Y OR N: '$)
	GO TO 10
	END
