From: <KEN@930.Tymnet>
Date: Mon, 4 Jun 84 16:03:49 PST
To: sppoper
Cc: ken
Subject: transfer to NTD

                                                            Ken Dawson
                                                            6.4.84

    Jon Mosser,
    Manager, Applications and Languages Unit (ALU)
    36-bit stuff dept
    etc
    Tymshare

    Jon,

    Effective June 11th, 1984, I will be working for Michael Stimac,
    Manager of the Network Tools Unit of the Network Technology
    Division of Tymshare, providing support for the runtime package of
    the Concurrent Pascal cross compiler for Tymnet Engines.  I feel
    this is best, as this represents a major career change for me, and
    brings me closer to my beloved languages.

    Yours,

    Ken Dawson


Received: from 39.Tymnet by 930.Tymnet; Mon, 30 Jul 84 15:04:16 PDT
Return-path: <KEN@39.Tymnet>
From: <KEN@39.Tymnet>
Date: Mon, 30 Jul 84 12:29:24 PDT
To: matoka@897
Cc: ken
Subject: virgil

    Although he still does not have the right to come near the place,
    Virgil has asked me to advise you that his new phone number is
    (408)338-4352. Those who know indicate that this information might
    be worth something in 2 weeks or so.

    /ken
Received: from C39.Tymnet by X930.Tymnet; Wed, 17 Jul 85 13:31:56 PDT
Return-path: <KEN@C39.Tymnet> 
From: KEN@C39.Tymnet 
Date: Wed, 17 Jul 85 13:27:18 PDT 
To: wrs 
Subject: hello there 

It seems I'm back, working for Adele again, doing development for Onytme
II.  Today is my first day.  Send reply to ken:39.

Hee hee hee.

---ken
Received: from C39.Tymnet by C36.Tymnet; Mon, 22 Jul 85 17:59:29 PDT
Return-path: <WRS@C39.Tymnet
From: William R. Soley <WRS@C39.Tymnet> 
Date: Mon, 22 Jul 85 17:55:46 PDT 
To: KEN@C36.Tymnet 
Subject: Re: Lunch 
In-reply-to: your message of Mon, 22 Jul 85 17:13:11 PDT

Probably not.  I'm suffering from
  INSANITY!COEFFICIENT = 1/TIME!TO!VACATION
that is, insanity approaches infinity as vacation draws near.  How about when I
get back (sorry).  Schedule follows:

Un 708 27Jul 6:32a Lv:SFO 18A/B
             1:25p Ar:ORD (breakfast)
Un 208       1:55p Lv:ORD 12A/B
             4:15p Ar:BUF
Un 209 19Aug 5:05p Lv:BUF 10A/B
             5:35p Ar:ORD (snack)
Un 135       6:45p Lv:ORD 27H/J
             9:05p Ar:SFO (dinner)

-Bill
From: KEN@C36.Tymnet
Date: Wed, 28 Aug 85 13:13:34 PDT
To: augment.v/champlin@ontyme
Subject: This is a test

    Virgil,

    I'm going to attempt to just send this from my server to your Id.  In
    theory, your server should hand it on to you, right?

    Let me know if you never receive this.

    /ken
From: KEN@C36.Tymnet
Date: Fri, 4 Oct 85 14:07:03 PDT
To: wrs
Subject: voice communication

    Bill,

    Did you know that yuour home phone is attached to some form of
    McDonnell-Douglas voice answering service?  Did you establish this
    shunt as a punishment for people who read phone directories?  Or is
    this a bizarre side effect of the fact that I'm trying to dial out of
    MDC-Land?

    /ken
Received: from C39.Tymnet by C36.Tymnet; Mon, 7 Oct 85 10:11:30 PDT
Return-path: <WRS@C39.Tymnet
From: William R. Soley <WRS@C39.Tymnet> 
Date: Mon, 7 Oct 85 10:05:02 PDT 
To: KEN@C36.Tymnet 
Subject: Re: voice communication 
In-reply-to: your message of Fri, 4 Oct 85 14:07:03 PDT

Oh that was temporary.  I'd gotten about 685,241 too many phone calls that day
so I forwarded my calls to ASPEN.  Try again this afternoon or at the office.
Not sure where I'll be.  -Bill
